### ISSUE TITLE
borg create --stdin troubles with questions

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1065]
In some cases (repo moved, for example), borg asks questions.
With --stdin, it can't get the answer,because the input stream is connected to a data pipe (not to the keyboard).

**Comment by rpodgorny** [comment]
...any progress on this? since update to 1.1, all my scripts are stuck at "Warning: Attempting to access a previously unknown unencrypted repository! Do you want to continue? [yN]" :-(((

**Comment by ThomasWaldmann** [comment]
Use the environment variables to auto-answer the question (once, be careful not override security relevant stuff permanently).

**Comment by rpodgorny** [comment]
thanks!

**Comment by pharaonic-faery** [comment]
Yes. You can also answer the question even if you can't see the prompted question.

But the problem is still here in 1.1.10 version.

I have a similar problem with 
`borg create --list --show-rc repository::backup backuped-file 2> log-file`
The list and the rc are redirected to the error stream instead of the output stream.

**Comment by ThomasWaldmann** [comment]
Closing this. The env vars solve this and are documented.
