### ISSUE TITLE
main command options?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1163]
stuff like --remote-path should be an option of main command, not subcommand, so it can be used like:
```
borg --remote-path=... create
```
Currently, it only works like this:
```
borg create --remote-path=...
```
Thus, it is a bit impractical if one wants to define a abbreviation like:
```
BORG="borg --remote-path=x"
```

**Comment by ThomasWaldmann** [comment]
note: it is more practical to have env vars like BORG_REMOTE_PATH than having to define such abbreviations (see above).

**Comment by enkore** [comment]
I think we can close this. I looked into this and it would be very, very messy with argparse since you can't have the same argument name in both parent and child parsers. So these would have to get all different names and then be fixed up / merged separately; also any double occurence would have to be checked separately.

**Comment by ThomasWaldmann** [comment]
ok.
