### ISSUE TITLE
OS X (beta): test borg on new APFS

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1169]
If there is anything special to be done about APFS (Apple FileSystem, new), we need help by someone who can test borg on it.

First thing would be to install borg and run the unit tests, see development docs.

**Comment by zyradyl** [comment]
It would still be a development preview, but I can take a look at this if you're still looking for input? 

The tests would need to be done over again on the final version, as there is already expectation that some core things will be added (Case sensitivity requirement, Compression, possible user data checksumming), but I would probably be able to retest earlier than most with closed beta access.

**Comment by ThomasWaldmann** [comment]
@zyradyl yes, still looking for input.

The point is just to recognize issues early, so in case something blows up in borg, we can fix it or in case some important feature is missing (new FS metadata?), it maybe can be added.

**Comment by zyradyl** [comment]
Running them now :)

**Comment by ThomasWaldmann** [comment]
@zyradyl if you do a developer install (see docs), you could also run the tests on apfs maybe (likely this would need pointing TMP to a apfs filesystem).

**Comment by zyradyl** [comment]
https://gist.github.com/zyradyl/241b86f86bf17a4d1de19d18a6a81e8a

Everything here was ran on APFS.

The way I went ahead doing that (just to make sure this works) is to create an APFS filesystem, and then I manually followed the setup in the Vagrant file. So my `pyenv` was still based in JHFSX (Case sensitive HFS), as was the `brew` installed tools, but the actual `borg` code was located on, and the commands ran from, an APFS filesystem.

Dunno what's up with fuse, for the record I have been unable to use `borg mount` even with the JHFSX plus stuff due to a library issue, which I remember seeing somewhere you guys are already aware of.

Please do let me know if theres any testing or anything else I can do on OSX. I really like this project and would be thrilled to help, I just don't know a thing about python 👅

**Comment by ThomasWaldmann** [comment]
Had access to a macOS Sierra 10.12.5 machine and did some testing (TMPDIR on APFS), seemed to work normally.
