### ISSUE TITLE
local/cloud hybrid backup mode

### ISSUE THREAD

**Issue by kiuuik** [borgbackup/borg#1181]
I think about using borg for an offsite backup of about 1tb. Uploading to a cloud storage takes too long and is expensive. The other option is a backup-hdd that I store off-site. However this leads to less frequent backups or too much work. So ideally I would make the first backups to an hdd, subsequent daily (incremental) backups should be uploaded to the cloud. Every couple of months I would download and merge the backups to my backup-hdd. 

I have only found this option in a hardlink-based backup software called [storeBackup](http://www.nongnu.org/storebackup/en/node55.html).

Borg seems to be well suited for such a scenario because it offers built-in encryption and much better deduplication. People with slow or metered connections might benefit from such a feature.

I have looked at the docs. I don't think that I can achieve this objective using exclude patterns or something like this. I havent't found a similar suggestions in the issues.

**Comment by RonnyPfannschmidt** [comment]
in order to support this use-case, borg needs support for a new way to replay backups

in the current master there already is a mode to inexpensively redo archives with changes like exclusions, this mode should/will eventually be extended to support copying chunks and archvies from one borg archive to another

with something like that you could update an off-site backup regulary by copying one archvie from the frequent backup storage to the offsite

**Comment by ThomasWaldmann** [comment]
Just use n (n > 1) local disks and rotate them.

So always n-1 are remote, 1 is local (or on-the way to remote location).

**Comment by enkore** [comment]
^-- There are many backup schemes, but rotating local disks has many advantages. It's relatively hassle-free (don't have to pay someone to retain access to my data), very fast (a few minutes for me with some 500 GBish of data in 2 millionish files) and quite safe in many ways: hacking, physical damage, accidental deletion, ...

Also ... disks are cheap. And if you use many you can even use older or used ones, since it doesn't matter if some of them fail...

To the issue at hand, yes I think what @RonnyPfannschmidt said would be ideal for your use case, since that would allow you to retain the full history created by backups even if none/not all of your backup destinations are available.

**Comment by kiuuik** [comment]
thanks for your replies. 

I can see that this feature apparently more niche than I thought. I also think that there are probably more important features to implement. 
But I thought that such a feature might be quite unique and I do think rotating disc backup schemes for home users are either too laborious or don't offer perfect protection. 


I know some people who have an acceptable backup setup and who have more than 1tb of data (i.e. more than you can upload to dropbox or onedrive at the standard rate). They have two different backups. One is off-site by storing a usb-hdd at work. Every couple of weeks (or after major events like holidays or weddings) they bring the hdd home and make a backup. They usually have some kind of backup at their house like an external usb-hdd or a NAS with raid-1 and Zfs/btrfs snapshots. These strategies are perfect against user mistakes or hardware failure but not perfect against burglary or fire: In a worst case they lose all data from a couple of weeks since the last off-site backup.

I already have a multi disc backup strategy but I'd like to protect myself against such a worst case scenario. Rotating hdds daily is too laborious: I don't own a car which could be used for a minimal off-site strategy. I commute by bus or bike and I don't want to take a hdd when I go shopping.

I might be paranoid but I think a burglary is a real possibility. Not only have burglary rates been rising in Germany but I also live in an apartment with a shoddy door ... and moving is not an option because in my city rents have exploded. 

How I tried to backup only the data that has changed since the last backup to my off-site hdd: I started by using duplicity for a cloud backup. At first I only backuped a couple of small folders that frequently change. The problem is that I change data all over my folders. Then I made a script that listed all files changed since the last off-site backup mainly using 'find --newer' and passed this filelist to duplicity with the option --include-filelist. Then I switched to [storeBackup](http://www.nongnu.org/storebackup/en/node55.html). Its isolated mode is much more comfortable and in theory it allows me to have a complete backup history. It doesn't offer encryption and I didn't know how to use ecryptfs to encrypt data in my locally mounted "cloud sync folder". So I used a usb flash drive (encrypted with luks). But I always have to think of putting in and removing the usb drive. So this setup is not ideal. 

This is why I thought that borg with a temporary secondary location would be useful for some people. 

I wonder how other people make daily backups of large data sets (>=1tb) without much effort or without paying too much. 

PS: I know about cost-benefit analysis. Probably the time I "wasted" writing this post is more than the yearly expected loss of the aforementioned imperfect rotating disc solution - but I like sound solutions and I'm quite risk averse.

**Comment by jmiserez** [comment]
Not that I recommend it, but if you have ZFS you can actually also just export snapshots as files. So you'd do your initial backup on a ZFS disk, then mirror that disk and store the mirror offsite. Afterwards, you create a snapshot after every borg backup, and do `zfs send | gzip > mysnapshot001.gz` and upload that file to the cloud. That file will contain all changes to the borg repo since the last ZFS snapshot.

In case of emergency you grab your offsite ZFS disk, and `zfs receive` to receive all snapshots in order. ZFS also has options to do cumulative snapshots, so you can replace your many snapshots with a single one once in a while. You'll have to test if ZFS performance and RAM usage is good enough for you before you commit to this.

Btrfs can do the same: https://btrfs.wiki.kernel.org/index.php/Incremental_Backup

**Comment by enkore** [comment]
The requested feature seems very complex to implement to me and depends on various other features that are far away (#431 #102, replication etc.). Some alternatives were suggested above. Therefore, closing. Feel free to reopen if this assessment is not accurate.
