### ISSUE TITLE
Prune --keep-within time interval does not have all options lowercase

### ISSUE THREAD

**Issue by madonius** [borgbackup/borg#1226]
In terms of usability, having the hour specifier with a capital H is most confusing since the rest of the interval specifiers are lowercase.

Since in the unix ecosystem H is used as a the hour sequence I would propose that prune simply accepts both H and h.

**Comment by enkore** [comment]
`borg [command] -h` means --help already. Which is somewhat lucky if we were to change this since no script will be using that option ;)

**Comment by madonius** [comment]
Would that be an Issue in the {number}{string} that 'borg prune --keep-within' expects?

**Comment by ThomasWaldmann** [comment]
That is the format string for a ISO-like timestamp: '%Y-%m-%d %H:%M:%S'.
You see, they also use uppercase for hour (and minute and seconds).

borg 1.1 will have `--keep-minutely` and `--keep-secondly` (for completeness - and I did not add short letters because I expect them to be used rarely. but if I had added short ones, -M and -S would have been the obvious choices).

-y currently does not comply, but it is a bit strange in the format string also.
