### ISSUE TITLE
deal with damaged files for FUSE somehow

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1302]
currently, FUSE (borg mount) just lets you read the file with the all-zero replacement chunks.

you won't notice that the file has problems.

**Comment by enkore** [comment]
Somewhat mitigated by check--repair being explicit about this, but it should still be reported somehow.

**Comment by enkore** [comment]
Borg Open undiRected Governance process (aka borg process) resulted it:

> EIO on open, and an option to disable it would be my preference.

Rationale over in-band signalling with editing the file name (".damaged"):

- Changed file name can go unnoticed very easily
- Extending file name can violate length limits

Rationale for on open instead of on read:

- Simpler to implement
- Less change of leaving incompletly copied files around (depending on file copier used)

**Comment by ThomasWaldmann** [comment]
fixed by #1303.
