### ISSUE TITLE
use coala?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1366]
coala bot that reviews pull requests.

coala detect code duplication.

complexity metrics.

grammar check for docs.

C checks for similar stuff.

Generic stuff checker tabs etc.

**Comment by enkore** [comment]
http://coala-analyzer.org/

**Comment by enkore** [comment]
If we use it, put it in the flake (?) tox env, if that works?

**Comment by PlasmaPower** [comment]
Shouldn't we create another coala environment instead of grouping it with flake8? I'm assuming coala won't totally replace flake8, right?

**Comment by enkore** [comment]
Technically yes, but creating environments is quite slow on travis (because it's "always" the first time on travis), so having a separate environment would make the build run longer by maybe 5 minutes or so.

**Comment by ThomasWaldmann** [comment]
See PR #1569.

**Comment by sils1297** [comment]
> I'm assuming coala won't totally replace flake8, right?

@PlasmaPower if coala isn't able to totally replace flake8 please tell us what's missing :) There was a Flake8Bear in the works which should ease switching in the future as you'll for sure be able to reuse your existing configuration but the contributor didn't continue working on it. (See https://github.com/coala-analyzer/coala-bears/issues/169 ) If that's of interest to you please tell us or consider helping out :)

**Comment by sils** [comment]
Hi, just got this notification as we were deploying the first stable working versionof gitmate.io - you might find that interesting. Just turn it on and it'll use the coafile you already have :)

**Comment by ThomasWaldmann** [comment]
@sils thanks for the info! gitmate looks interesting, but look what I got when clicking "login with github":

![gitmate-access](https://cloud.githubusercontent.com/assets/356103/26754210/90ed9f4e-4876-11e7-9a1f-b6c856127da9.png)

Write access to code repo -> NOPE NOPE NOPE NEVER. Admin access to settings -> NOPE.

So, can you do it with less intrusive permissions (I know github permission system sucks, but did you try?).

**Comment by sils** [comment]
hey, thanks for that feedback :) we're aware that this is an issue and have
already worked out plans to mitigate that before beginning to code.
However, this is an MVP up since a few hours, getting the functionality was
our priority up until now. We're working on using GitHub integrations which
will allow more fine grained permission management and will ultimately
solve that. However to do that we have a long road ahead of us, the "github
integrations" are still in beta even I think. We're also thinking about
this issue on GitLab where they don't have anything like this. Another
issue is that ideally we want a "gitmate-bot" user to perform the actions,
not the user who logged in.

So well, there's a plethora of problems on that end yet to be resolved, if
you have any experience with that we appreciate any hints.

If it helps you, all code that is running there except the environment
variables is open source at code.gitmate.io but it still doesn't change
that you're putting that key in our db. However, you can selfhost it
yourself for now, we're just writing up documentation on how to self deploy
it, it's fairly easy as we have a docker compose setup.

**Comment by ThomasWaldmann** [comment]
@sils good that you are working on improving security/privacy, I guess we'll just run coala locally until that is ready. I can't help with github permissions, sorry.

**Comment by sils** [comment]
Actually I took a look at the docs and if I'm not mistaken we might be able
to fix it short-term (maybe tomorrow) without having to switch to
integrations. We basically just need to be able to label, comment, read,
set commit status.

**Comment by step21** [comment]
Just FYI, coala-analyzer.org mentioned above is dead, it is now apparently at coala.io
