### ISSUE TITLE
Size of segment can exceed MAX_SEGMENT_SIZE

### ISSUE THREAD

**Issue by PostalBlab** [borgbackup/borg#1443]
Segments can exceed MAX_SEGMENT_SIZE as explained in constants.py but the name is still misleading.

Please rename MAX_SEGMENT_SIZE or make sure a segment can't be bigger than MAX_SEGMENT_SIZE. Maybe it's only necessary to replace 
`def get_write_fd(self, no_new=False, raise_full=False):`
`if not no_new and self.offset and self.offset > self.limit:`

with something like this

`def get_write_fd(self, no_new=False, raise_full=False):`
`if not no_new and self.offset and (self.offset   + len(data) + self.put_header_fmt.size) > self.limit:`

**Comment by bronwynbiro** [comment]
May I work on this?

**Comment by enkore** [comment]
Sure

**Comment by ThomasWaldmann** [comment]
master branch?

**Comment by Kashyap12** [comment]
hi can I take this up? @PostalBlab , new to open source, would  love to help

**Comment by PostalBlab** [comment]
Sure. I'm not working on it.

**Comment by shreab373** [comment]
beginner here, if the PR was merged, why is the issue still open?

**Comment by enkore** [comment]
It wasn't merged, the PR was closed.

**Comment by jazcap53** [comment]
Apologies for the noob question, but:
Running `grep -nr MAX_SEGMENT_SIZE` my borg root directory, I see only instances of DEFAULT_MAX_SEGMENT_SIZE -- none of MAX_SEGMENT_SIZE by itself.
Does this mean the issue has been repaired?

**Comment by enkore** [comment]
The constant ( (DEFAULT_)MAX_SEGMENT_SIZE ) was always only the default value, which is written into the repository config file when a new repository is created. It was always possible to adjust that after the fact by editing the repository config file.

The principal issue hasn't been 'solved' by the rename.

**Comment by jazcap53** [comment]
Thank you enkore for the explanation.

**Comment by willberriss** [comment]
Hi
I'm trying to understand this issue. We have DEFAULT_MAX_SEGMENT_SIZE, but this is a soft limit. What is a segment? Why is it a soft limit? Can we not make it a hard limit?  And for some reason we need to ensure we don't exceed this hard limit when using get_write_fd()? What happens if we exceed the limit here? And how does checking that offset + otherstuff  > limit help?  Any explanations would be much appreciated. I have built and installed it and it all runs, but I am not sure quite what the requirement is. Also, is there a unit test I can run to test this area of the code? Thanks.

**Comment by enkore** [comment]
You should find answers to most of your questions there:
https://borgbackup.readthedocs.io/en/latest/internals/data-structures.html#repository
https://github.com/borgbackup/borg/blob/master/src/borg/repository.py#L41

> And for some reason we need to ensure we don't exceed this hard limit when using get_write_fd()?

We don't need to ensure it.

> What happens if we exceed the limit here?

Nothing

This issue is basically about a variable being called "..._MAX_..." not being an exact limit for something.

**Comment by enkore** [comment]
If no one objects I'm going to close this as wontfix.
