### ISSUE TITLE
add automated benchmarks

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#146]
use pytest-benchmark for it. start with: create, delete, extract.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/25553185-add-automated-benchmarks)

**Comment by anarcat** [comment]
pytest-benchmark looks nice... i have done [some preliminary benchmarks on attic vs bup](http://anarc.at/blog/2014-11-18-bup-vs-attic-silly-benchmark/) about a year ago. i then found it useful to have [resource usage information](https://docs.python.org/3/library/resource.html) (CPU, RAM, I/O, etc) during the benchmarks as well, to see what was going on more clearly. this doesn't seem to be implemented in pytest-benchmark, so i filed a feature request about this in https://github.com/ionelmc/pytest-benchmark/issues/28.

here's a stub benchmark i used to test the software:

```
from ..helpers import Location
from ..remote import RemoteRepository

def test_ssh_cmd(benchmark, tmpdir):
    repo = RemoteRepository(Location('__testsuite__:' + str(tmpdir)), create=True)
    result = benchmark(repo.ssh_cmd, Location('example.com:foo'))
```

here's the result:

```
===================================================================== test session starts =====================================================================
platform linux -- Python 3.4.2, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/anarcat/src/borg, inifile: setup.cfg
plugins: cov-1.8.1, benchmark-2.5.0, pep8-1.0.6
collected 1 items

borg/testsuite/benchmark.py .

 benchmark: 1 tests, min 5 rounds (of min 25.00us), 1.00s max time, timer: time.perf_counter
Name (time in us)         Min      Max     Mean  StdDev  Rounds  Iterations
---------------------------------------------------------------------------
test_ssh_cmd          24.3047  73.0390  24.8964  1.0002    6323           1
---------------------------------------------------------------------------

========================================================= 1 passed, 2 pytest-warnings in 1.39 seconds =========================================================
```

of course, we should disable that in the default unit test suite and only have that run when we explicitely require it, because it would kill the CI server completely.

although the nice thing with this is that we can just wrap existing calls with `benchmark` and get metrics for free. just keep in mind that, by default, every `benchmark` item can be run 5 times, which can have some obvious side-effects in our case. there is some calibration magic going on that can make that run only once (and in fact that is what is happening in my test above, it seems), but still... there's a `benchmark.pendantic` fixture to control better the number of calls per function.

otherwise it looks like we could just start shoving some of that stuff around our test suite, it would be great!

**Comment by anarcat** [comment]
oh and you need to ignore the warning on install, see https://github.com/ionelmc/pytest-benchmark/issues/18

**Comment by anarcat** [comment]
oh and unfortunately, integrating the fixture in our unittest-based class hierarchy would require .. getting rid of the class hierarchy, because it seems [basically impossible to mix fixtures and unittest](https://pytest.org/latest/unittest.html#autouse-fixtures-and-accessing-other-fixtures)... sigh.

**Comment by ThomasWaldmann** [comment]
I think we would need some extra "tests" (in a testsuite/benchmark module) that are specially made for benchmarking, like generating and processing a bit bigger amount of data, not just the usual 10 small files as the archiver tests do - otherwise we might rather measure the overhead than the core performance and ressource usage would be rather low also.

As a start, we could concentrate on the most frequent operations there: create, extract, list, delete.
The code I posted there might come in handy to produce the bigger amount of data in a reproducable way:

https://github.com/borgbackup/backupdata

If course the benchmark data is only meaningful when running on same machine, under same load conditions (and of course we don't run that on Travis CI).

**Comment by anarcat** [comment]
i agree. i was just saying that we are already running some of those benchmarks, just not measuring them. hooking the benchmark fixture in there may produce basic results that would be part of the CI process, where we could see regressions and so on...

**Comment by anarcat** [comment]
as for https://github.com/borgbackup/backupdata, it seems it would need to actually generate original data, not just modify some existing data... especially if we want to automate it. we could use the tool to alter existing data sets in the future, but that doesn't seem as useful as generating new "standard" datasets.

[bup](https://github.com/bup/bup/) has a [random](https://github.com/bup/bup/blob/master/cmd/random-cmd.py) command to generate a stream of N bytes, based on a [c function](https://github.com/bup/bup/blob/master/lib/bup/_helpers.c#L832). they also have a [memtest](https://github.com/bup/bup/blob/master/cmd/memtest-cmd.py) command that seems to report memory usage.

seivot [uses a genbackupdata command](http://git.liw.fi/cgi-bin/cgit/cgit.cgi/seivot/tree/seivot#n483) that is, like seivot, written by the obnam author: http://liw.fi/genbackupdata/ - the tool is fairly simple and generates randomly filled files...

**Comment by ThomasWaldmann** [comment]
random data is easy to produce and wouldn't require including sample data, but otoh, it is rather unnatural data and thus the benchmark results would be also not very practical. so we could just include some freely licensed real data and feed that into my tool.

**Comment by anarcat** [comment]
one of the things that bup does is use the bup source code as part of the test, so we could use the borg source code as one source of text files. then we'd need images, movies, disk images, compressed files... there can be quite a diversity out there, not sure how to generate that reliably...

**Comment by anarcat** [comment]
oh, and genbackupdata can also alter existing datasets and it is deterministic... http://liw.fi/genbackupdata/genbackupdata.1.txt

**Comment by ThomasWaldmann** [comment]
another question here is how we can avoid the influence of multitasking, a potentially changing OS and hardware environment on the performance tests? do we need a piece of hardware and OS that does not change over time and that does nothing else than benchmarking borg or is there a more elegant solution?

**Comment by anarcat** [comment]
On 2015-10-09 06:57:05, TW wrote:
> another question here is how we can avoid the influence of multitasking, a potentially changing OS and hardware environment on the performance tests? do we need a piece of hardware and OS that does not change over time and that does nothing else than benchmarking borg or is there a more elegant solution?

i know that pytest's benchmark plugin does a calibration step that
alleviates the influence of the environment.

but unfortunately, different hardware will lead to different benchmarks
- they will only be relevant if ran on the same machine...

a.

-- 
We will create a civilization of the Mind in Cyberspace. May it be
more humane and fair than the world your governments have made
before.
                         - John Perry Barlow
