### ISSUE TITLE
Alternative fuse mount method on OpenVZ

### ISSUE THREAD

**Issue by pepa65** [borgbackup/borg#1466]
I have an OpenVZ VPS running as a borg repo over ssh. I was trying to borg mount the repo locally on the server, but it got "Killed". As it appears, there is a special setting to allow fuse on OpenVZ. The hoster changed it, and now I can mount things on fuse, but I still can't do "borg mount"... I was wondering whether a way could be found to still mount in this situation.

**Comment by pepa65** [comment]
I just created a new small repo, and was able to borg mount that. So it's probably more an issue of a resource usage spike (memory) that causes the Kill... This VPS has 128M and 64M swap.

I guess there is no way to limit the memory usage for a borg mount..?!

**Comment by ThomasWaldmann** [comment]
Due to the way how borg works, it needs quite some memory, so it might be not suitable for machines with little memory like yours.

How much it needs depends on many factors, like repo size, chunk count, files count, ... (see docs, there are some formulas and explanations).

borg mount loads the complete metadata for all files/dirs in an archive (or, if you mount the repo: in all accessed archives) into memory. so, if you are low on memory, rather use `borg list` and `borg extract`.

**Comment by ThomasWaldmann** [comment]
Note: it is always "space vs. time". If you make the software use less space (memory), it will often need more time (and vice versa). There likely isn't much we can do to make borg use less memory without making it slower (which is obviously not desired).

https://github.com/borgbackup/borg/pull/1429 might make borg use a bit less memory than it is using now, due to a better load factor of the hashtable (maybe 95% vs. 75% now). It also might be faster, due to a better algorithm. But: it is only a slight improvement, if you haven't much memory you will still run out of memory at some time.

So, while we can try to improve borg gradually, we maybe can't make it use *much less* memory.
