### ISSUE TITLE
Enhancement request: Alternate append-only mode

### ISSUE THREAD

**Issue by copart** [borgbackup/borg#1476]
I feel that the append-only mode added to borg recently is awesome.  Thank you!

However, one issue I have is that I would prefer "attic prune" to FAIL with error instead of creating a transaction log and acting like the command worked.  I have already caused this to happen myself without it being a external "hack".  While I do see the great value in the transaction log way of doing things in the case of a security incident, I would not mind having a less "forensic" way of having "append-only".

Thoughts?

**Comment by ThomasWaldmann** [comment]
Prune also "works" in append-only mode - the stuff it deletes is logically deleted (e.g. you won't see a deleted archive any more in the archive listing) - it is just not that the old segments are rewritten and compacted. The logically deleted data will go away next time compaction is run without using append-only.

So an ERROR or WARNING is not quite appropriate here.

What we could do is emit an INFO pointing out that compaction will not run and space will not be reclaimed due to append-only mode.

**Comment by copart** [comment]
Thomas,

I agree that an error is not appropriate if the actual result is logically deleting stuff.

However....

What I am proposing is that any borg commands that currently "logically delete" would NOT do anything other then error out if the repo is set to say -FORCED-APPEND-ONLY mode.  So, if a repo is set to this none existing mode, it would be completely safe to run a compact without using append-only and not have to worry about previous logical deletes becoming permanent.

**Comment by ThomasWaldmann** [comment]
Not sure if that is possible. The whole point of append-only is that the client is not trusted. So any built-in decision in the client sw to just error instead of prune could be removed client-side.

The server does not see which operation exactly the client is doing. It just sees lower-level ops like open(), get(), put(), ...

full repository deletion is an exception, this is implemented server-side as it operations on the full repo, not on objects in the repo.

**Comment by copart** [comment]
Thomas,

Okay, I am following.

In this case, since the client is not trusted.  If I was a bad actor on a client and I replaced Borg with a customized version that ignored append-only, could I then permanently delete/replace objects from a append-only repo (since I will be sending the raw commands to the server)?  

Assuming that the ssh access to the server hosting the borg repo is completely locked down except for access to the borg command.

**Comment by enkore** [comment]
> could I then permanently delete/replace objects from a append-only repo (since I will be sending the raw commands to the server)? 

No, append-only happens only on the server. You have to be able to either

* modify the repository config file
* directly manipulate files on the server
* manipulate/exchange/use your own (on the server) borg executable

**Comment by ThomasWaldmann** [comment]
Guess we can close this.
