### ISSUE TITLE
suspicious AES IV for keyfile/repokey generation

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1579]
The IV is all-zero there, always.

As the key-protection key is generated using the passphrase and a random salt, this is not necessarily problematic.

change-passphrase encrypts the same repo encryption key, same 0 IV - but as passphrase is likely different it will generate a different key-protection key from it. How about the salt in that case?

Better review that stuff.

**Comment by enkore** [comment]
The code as of 1.0.7 is

```py
    def encrypt_key_file(self, data, passphrase):
        salt = os.urandom(32)
        iterations = 100000
        key = passphrase.kdf(salt, iterations, 32)
        hash = HMAC(key, data, sha256).digest()
        cdata = AES(is_encrypt=True, key=key).encrypt(data)
        d = {
            'version': 1,
            'salt': salt,
            'iterations': iterations,
            'algorithm': 'sha256',
            'hash': hash,
            'data': cdata,
        }
        return msgpack.packb(d)
```

The AES key is derived via the KDF (PBKDF2-HMAC-SHA256) from the passphrase and a random 256 bit salt, which is *always* regenerated. Therefore the AES key is different and pseudorandom in each invocation. Since the AES key is never passed on to the outside world, we cannot encrypt another message under the same key. Therefore always using an all zero IV is safe (as would be any other static IV).

What is a bit problematic is that the same key is used for both AES and also for the HMAC. This violates the one-key-one-purpose best practice, but has no implications in this specific construction (to the best of my knowledge).

---

Call tree:

This is always used for saving via `_save` (e.g. change_passphrase uses this, or KeyfileKey/RepoKey.create) - the save() method itself is only there to put the encrypted key in the right place:

```py
    def save(self, target, passphrase):
        key_data = self._save(passphrase)
        ...
```

`_save` itself. This prepares the key data, encrypts it and then encodes the result.

```py
    def _save(self, passphrase):
        key = {
            'version': 1,
            'repository_id': self.repository_id,
            'enc_key': self.enc_key,
            'enc_hmac_key': self.enc_hmac_key,
            'id_key': self.id_key,
            'chunk_seed': self.chunk_seed,
        }
        data = self.encrypt_key_file(msgpack.packb(key), passphrase)
        key_data = '\n'.join(textwrap.wrap(b2a_base64(data).decode('ascii')))
        return key_data
```

**Comment by ThomasWaldmann** [comment]
/me agrees. Maybe we can do the key split if we introduce a new kdf anyway.

**Comment by enkore** [comment]
(#747)

**Comment by textshell** [comment]
Yes, using a random salt should mitigate the same IV because it generates a different key. Also it’s the construction used in openpgp so there should have been done some cryptoanalysis on it in the past. So for now we are good.
If we start mutating the keyblob we need to keep the part that changes the salt on each save. This is a bit slow, but ok, as keyfiles will not be changed often.

I agree that when we add a new kdf options we should split their output but i don‘t think we need to worry about the existing one too much.

Seems this can be closed without code changes.
