### ISSUE TITLE
fadvise should be more cautious, to make sure we don't break read-ahead

### ISSUE THREAD

**Issue by sourcejedi** [borgbackup/borg#158]
Researching `fadvise`, GNU dd suggested a possible problem with running DONTNEED on the entire file during reads:

<pre>
          /* Note we're being careful here to only invalidate what
             we've read, so as not to dump any read ahead cache.  */
#if HAVE_POSIX_FADVISE
            adv_ret = posix_fadvise (fd, input_offset - clen - pending, clen,
                                     POSIX_FADV_DONTNEED);
#else
            errno = ENOTSUP;
#endif
</pre>

http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/dd.c#n1024

**Comment by ThomasWaldmann** [comment]
btw, some simple benchmark @pguth made today showed no difference at all in backup speed with and without respecting readahead (== code before and after the change of today).

but maybe this is because the drive itself might also do readahead in its internal buffer and thus the readahead of the OS doesn't make a big difference in that simple scenario (there was no other I/O load on the disk).
