### ISSUE TITLE
Remote vs local resource usage

### ISSUE THREAD

**Issue by nerbrume** [borgbackup/borg#1583]
Following a question on the mailing list, where I wondered which work is done locally or distantly in case of a backup over ssh (link to the mailing list archive to follow), I think it might be good to have a FAQ entry regarding this point, especially to help people finding the bottlenecks / best settings fore remote backups.
Here's a draft, to be modified ! (some bits taken from Marian's answer, thanks to him)
# What are the local/remote ressources usage in case of a distant backup ?
- `create` : When doing a backup from a local computer to a remote repository, borg is doing the deduplication, compression and encryption on the local side (the one launching the `create` command). The repository/remote end is a simple key-value database. It needs about (chunks_count \* 40-80 bytes) of memory plus some overhead to work.
- `check` : Some stuff is done on the remote end, which can need another chunk_counts \* 40 bytes of memory, but is normally IO bound.
- `mount` : most of the work is done by the machine doing the borg mount command.
- `delete` : [I don't know about this one]
- `prune` : [I don't know about this one]

**Comment by ThomasWaldmann** [comment]
In general:

Most stuff has to be done client-side. This is because we use encryption, thus a lot of stuff can not be done server side as the server usually does not have the key and only sees encrypted metadata and encrypted data. As deduplication and compression must be done before encryption, this is also done clientside.

So, what's left for the server to do is:
- be a key-value store (and maintain a lock and an index for that, do transactions)
- within borg check, the server is able to do a crc-check on the repo objects.
- if you delete a complete repo, this is also done server-side

**Comment by ThomasWaldmann** [comment]
See PR #1882.
