### ISSUE TITLE
repository / rpc api: sequential scan

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1610]
The current `repo.list()` method lists repo objects in repo index order (means: random segment order).
If one just wants the keys, this is no problem, everything is read from the index, which is in memory.

But if you want (all) the values also, this order causes a lot of random access - a real stress test for your disk(s).

If we want to iterate over all repo objects, same-segment offset (1.) and segment (2.) order would be much better. Maybe it could also support just getting the keys and alternatively key/value pairs.

**Comment by ThomasWaldmann** [comment]
Algorithm could be like:
```
for all segment files:
    for all objects in segment file:
        i_pos = index[key]  # seg, offs
        if i_pos == current_pos:
            yield key, data
```

**Comment by enkore** [comment]
I think check is the only op using it anyway. For the reconstruction cache population it doesn't matter how they're ordered, so changing the existing implementation to returning linearly ordered keys makes sense. Since it's purely in-memory it should be plenty fast. Maybe even implement it straight in Cython.

**Comment by ThomasWaldmann** [comment]
borg check and some debug cmd uses it currently.

What I was proposing above is a disk-based algorithm that just checks against the repo index to make sure it is no superseded object, but results in a completely linear ordering for all keys.

So, considering that the repo index itself might already take some hundred MBs .. some GBs of memory, how would your purely-in-memory algorithm look like?

**Comment by enkore** [comment]
Like a nested-loop JOIN, so it'd be ~O(n_segments * n_index), but doesn't do any IO. Hm.

**Comment by ThomasWaldmann** [comment]
OK, so have a low-level op in C / Cython that does a hashtable scan, filtering out all entries for segment N, then sort (much smaller) result by offset.

**Comment by ThomasWaldmann** [comment]
see PR #1607

**Comment by enkore** [comment]
We removed the sequential scan API from #1607 again due to some complications.

What's currently on the table:

- Add new Repository method + RPC call called eg. `scan` or `linear_scan`
- Which returns a number of object IDs (with the usual limit and marker args)
- It works as follows:
  - If `marker`: get (segment, offset) from index
  - Elif not `marker`: segment = first segment, offset = 0
  - iter_objects from (segment, offset) on; ignore everything except PUTs, yield PUTs that are in the index and current
  - Take care not to evict the read segments from the page cache (this bit is important)
  - After yielding `limit` IDs, return.

- This enables
  - Efficient linear scanning
  - No extra disk access when objects are get()ted, assuming the page cache is large enough for the objects contained within `limit`

**Comment by ThomasWaldmann** [comment]
If we make a new rpc call anyway, we could also offer to yield not just keys, but also key/value tuples, if requested.

**Comment by enkore** [comment]
Making that a toggle would make sense, even if not used right now.

**Comment by ThomasWaldmann** [comment]
Implemented by #1682 (Repository.scan()) and used for `borg check --verify-data`. (master branch)

**Comment by enkore** [comment]
This implementation is better than the random access before but still has very poor performance. Average I/O utilization is below 1 %, while the CPU is hit hard.

Possible reaons:

1. https://github.com/borgbackup/borg/blob/master/src/borg/repository.py#L780

  For every scan() call the segment list is walked up to the current segment. Probably no biggie.

2. https://github.com/borgbackup/borg/blob/master/src/borg/repository.py#L783

  For every scan() call the current segment is re-read up to the marker object. I think this is where the poor performance comes from: it reads 100 objects (0-100); processes them. Reads the next 100 objects (100-200), for which the first 100 objects are read and CRC'd again etc. Effectively this squares the cost of this to the number of objects per segment.

  Note: Test was done with 500 MB segments.

**Comment by ThomasWaldmann** [comment]
Thanks for testing this. Yes, for big segments, 2. is likely an issue. If one has relatively small input files, a 500MB segment can hold a lot of them. I'll work on that.

**Comment by ThomasWaldmann** [comment]
PR #1703 fixed both.
