### ISSUE TITLE
have more details on progress option

### ISSUE THREAD

**Issue by mhajim** [borgbackup/borg#1618]
Hi,
It would  be a good feature to have a progress of reading file/directory with % of the whole size. it should be easy to calculate the size of file and directory and put the read file and total size both in progress bar.  user can estimate when the backup task will be finished!

**Comment by ThomasWaldmann** [comment]
That would need `borg create` to do an extra pass just to compute the total size/count, which would take a considerable extra amount of time. Also, if you backup a life system, it would not even be precise as it could change between the 2 passes. That is the reason why we don't do that.

Besides that, prediction of completion time would be still very unreliable even if we did that due to all sorts of other factors influencing progress, see also there:

https://xkcd.com/612/

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann wouldn't it be interesting to use prior backups as a way to do a estimate ? (the number of files and the size is known, and using more than one backup to compare sizes/file numbers i think reasonable estimates are doable?

**Comment by ThomasWaldmann** [comment]
Due to the way borg works: no

A trivial, obvious case is 1st and 2nd backup, but it also applies for any backup as you do not know the amount of change beforehands.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann i mean its clear that sometimes estimates dont fit, - but still explicitly gauging based on 1-2 prior backups seems like a good ux experience when asked for (all my backups are perfectly fine with something like that)

**Comment by mhajim** [comment]
OK. but in my case I have  only one big file! as source backup. any option?!

**Comment by ThomasWaldmann** [comment]
Hmm, IIRC that might be solved in 1.1. We have in-file checkpoints there and IIRC i also changed the progress display to update in-file.

**Comment by enkore** [comment]
The progress display is also updated in-file in 1.0.x. For large files we could give a %% to tell how much of the file was processed, since we have the stat information.

The more complex part (inspect older archive(s) and gauge progress) is IMHO something that is more something for a system built on top of borg (at least for now), because there are different ways and complexities involved with that.

**Comment by enkore** [comment]
^ Thus, closing.
