### ISSUE TITLE
quicker cache resync

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#163]
https://github.com/borgbackup/borg/pull/33 introduced some speedup for cache resync of remote repos, but overall, it is still too slow somehow.

currently it does that:
keep a local compressed bundle of individual indexes of all remote archives in the repo.

if new archives are created in the repo or archives were deleted from the repo, add/remove individual indexes and create a new compressed bundle. decompressing and recompressing already takes considerable amount of time (but good compression is needed for this method otherwise it would take up too much space). 1 cpu core is near 100% during that phase.

merge all individual indexes from the new compressed bundle into the uncompressed master index.

**Comment by ThomasWaldmann** [comment]
A workaround for users having slow cache resync:
- use a smaller chunks index (use a higher than default value for HASH_MASK_BITS, e.g. 20, with --chunker-params).
- keeping less (historical or other) archives in a repo helps.
- using separate repos per machine avoids this issue completely (except if you somehow lose or destroy your cache).

**Comment by ThomasWaldmann** [comment]
I just realized that while the compression of chunks.archive was quite impressive in my experiments, it is maybe not that effective in practice with bigger archives as the individual chunk index files can easily be e.g. 100MB or more in size and the compression algorithm maybe has not that much "window size" to exploit that the next file is very similar to the previous one.

**Comment by level323** [comment]
First of all, congratulations to @ThomasWaldmann for borg (and to @jborg, of course, for the original idea. @ThomasWaldmann, in my opinion this is one of the more exciting backup tools that is showing both great progress and future potential. Bravo. 

I haven't been able to contribute in any way other than a few comments, but maybe down the track (if/when I 'get a life') I will be able to in some small way.

In the meantime, I offer the following (potentially misguided, read at your own risk, eyebleach alert!) comments on this subject:

The central function is backups, yes? Therefore, a key focus area should be on maximising backup speed. Everything else (e.g. restore. repo maintenance) is secondary, yes?

I doubt the above is contentious. Where it might possibly be a little bit more contentious is that my view is that the "holy grail" is to have a central borg repo to which I can backup data from multiple machines - that's where the deduplication power of a system like borg really shines through and is amplified. As @ThomasWaldmann stated, per-machine repos don't suffer from this issue, but although theses are valid use-cases, aren't per-machine repos actually a secondary use case for a deduplicating backup system?

I'm not familiar with the nitty-gritty detail of borg's repo layout, but I know there's a bunch of files representing chunks of data, and each chunk has a hash. 

So, given the above priorities (particularly that backups should be as fast as possible), aren't the individual archive indexes redundant in the case of executing a backup?  In that case, isn't the only *necessary* requirement to execute a backup from a local machine to a remote repo to sync the "master index"?

**Comment by ThomasWaldmann** [comment]
As I said, using a per-machine repo is just a workaround that avoids having to wait rather long for the cache resync.

The "master" chunk index only exists in the local cache, not in the repository. It gets constructed by reading all files' "chunks" metadata for all archives and writing that info into a hash table.

The local chunk index is used to know which chunks are in the repo (also: their refcount, their size), so we do not have to ask the repo all the time when doing a backup or other operations (asking a remote repo can be rather slow).

**Comment by level323** [comment]
Just because I'm paranoid that terminology might be confusing things, I'll cease to use the terms "local" and "remote" because they may be ambiguous. Instead I'll use "backup source machine" and "backup destination machine". 

Perhaps there's a bit of a language barrier here as well, or perhaps I just don't understand borg's architecture sufficiently (or both!). You said (and I did understand) that there is a "master" chunk index kept on the backup source machine so that the backup source machine can avoid transmitting chunks already in the repo, but is it really the case that the backup destination machine does not retain its own index of the chunks in the repo? I assumed it must do so, otherwise it would be unnecessarily I/O and computationally intensive to determine whether or not an inbound chunk already existed or not.

Regardless of how borg is actually doing it right now, in order to facilitate maximally fast backups (without significantly compromising other functionality), would it not be worthwhile to for the backup destination machine to produce/maintain the "master" chunk index, from which the backup source machines can sync with (using rsync/zsync or similar approach) prior to commencing a backup run?

The "chunk index sync" process will be pretty close to maximally efficient as it will only transfer the data concerning index entries added or removed since the last "chunk index sync". To speed things up further, new unique chunks pushed from the backup source machine can be proactively added to the chunk index on the backup source machine as the backup progresses, reducing delta for the "chunk index sync" for the next backup run.

**Comment by ThomasWaldmann** [comment]
In the repo, there is a repo index that maps id -> segment, offset. That is to support efficient operation of the key/value store.

But that does not have the infos present in the chunks index (building that index requires decryption capability which is not present on the destination machine).

Your ideas are interesting, but we need to think more about them. How it fits into key/value store semantics, how it works with encryption, how we can avoid rsync for that, etc..

**Comment by level323** [comment]
Ahh yes... the encryption issue. That does complicate things.

Well, I hope I've helped, at least in some small way, with these ideas. 

Again I'll say: this is a really exciting project.

**Comment by ThomasWaldmann** [comment]
Note: PR #173 might solve this. It would be great if some brave souls could help testing this before I merge it into master. I did some experiments and it seemed to work for me.

**Comment by RonnyPfannschmidt** [comment]
i just ran into this one with around 150 gb of backup, repo size 100 gb restarting from a checkpoint

**Comment by ThomasWaldmann** [comment]
fixed by merging PR #173 into master.

**Comment by ThomasWaldmann** [comment]
See also this changeset, which significantly speeds up index merging (benchmarks of just the merge call show 1000x speed improvement):
https://github.com/borgbackup/borg/commit/610300c1cec8f21dee7bcbba386d81032cdedbac
