### ISSUE TITLE
Go back to providing compression by default?

### ISSUE THREAD

**Issue by sergiocallegari** [borgbackup/borg#174]
Hi,

Borg 0.25 introduced new compression backends which is quite nice.
It also seems to introduce a "do not compress by default" behavior that looks a bit strange to me.

- On one side it complicates compatibility with past versions of borg itself. In fact, from the borg changelog one reads

  *as long as you stay with zlib compression, older borg releases will still be able to read data from a repo/archive made with the new code (note: this is not the case for the default “none” compression, use “zlib,0” if you want a “no compression” mode that can be read by older borg)*

- On the other side, I think that for one using a backup software that is space savvy enough to use deduplication at the file chunk level it is strange to then avoid compression

Hence, I would like to kindly ask to reconsider the compression default, taking "zlib,6"

**Comment by ThomasWaldmann** [comment]
Borg always defaulted to no compression. The reason is that there is no "correct for everybody (or even for most people) compression choice". And if one can't choose good compression method, the natural default is to not compress and leave it to the user to make an educated decision about algorithm and level depending on the use case if he wants to use compression.

As older borg releases always used zlib compression (there was no way to use "none" compression back then), "no compression" meant using zlib level 0. This added zlib protocol overhead and is not needed if all one wants is "no compression". As 0.25 can now differentiate between different algorithms, "none" is possible now as a cheaper "no compression" way (and it has no overhead any more). 

zlib,6 won't come back as default. It slowed down backups significantly if either the cpu was not super fast or the backup target storage was very fast. See also the recent mailing list posts with the benchmarks, you see attic is always slower, just because that hardcoded zlib,6 there.

**Comment by sergiocallegari** [comment]
Thanks for the explanation. Now I see why backups were way bigger than expected based on past experience with other backup software (areca and attic) to the point that we had to split things among multiple repos.

Is it possible to 'rewrite' repo chunks using compression for an already existing repo?

**Comment by ThomasWaldmann** [comment]
There is no option for "rewrite existing chunks unconditionally" (maybe file a feature request, this would be nice for compression and maybe also for encryption changes).

If you can live with it using more space for a while until the uncompressed older backups are pruned, you could run once (for each machine / backup set) with "borg --no-files-cache --chunker-params ... --compression ...".

You need to use DIFFERENT chunker params than until now - a good chance to reconsider the CHUNK_MASK_BITS in case you use the default 16, IMHO a bigger value e.g. 20 makes sense often, see the docs about --chunker-params. Also choose the right compression wisely. If you don't need to compress the hell out of your data, lz4 might be a good choice. If you have a bandwidth issue storing into your backup target storage, zlib or lzma might make sense.

It would chunk (and compress) ALL the current files for the backup it creates (differently as before, according to your new chunker params, except for small files which result in only one chunk anyway). The --no-files-cache is needed to make it really chunk all the files (usually that cache is used to quickly skip over unmodified files, but you don't want that in this case).

After that (slow) backup, remove the --no-files-cache again, but keep the same new --chunker-params ... --compression ... to get it up to the usual speed again.

**Comment by sergiocallegari** [comment]
Thanks for the extended explanation!
