### ISSUE TITLE
should print a warning if file changed during backup

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1750]
GNU tar(1) does this by stat(2)ing before and after reading from the file. If the ctime changed‡, a warning is printed.

From the mailing list thread about annoying stuff in Borg.

‡ this is platform dependent and needs to be handled different on Windows.

**Comment by ThomasWaldmann** [comment]
Hmm, isn't that a bit a questionable / superfluous feature?

Usually one knows whether one backups a changing or a not-changing set of files.

If you know the stuff is changing and you directly back it up without doing a snapshot, such warning would be expected and you know it, so you usually either live with it (if harmless) or you just don't do that, but create a snapshot (fs, lvm, ...) first and backup that.

To implement this feature, we would have to do 2 stat() calls instead of 1. For many small files this might impact performance.

**Comment by enkore** [comment]
If the files cache is used (file_known_and_unchanged and all chunks presents) then this check doesn't make sense, since we never read from the file.

If we read from the file (chunker loop), then we can do it. I suspect the extra cost will be very low due to inode cache locality (stat - read stuff - stat); if it's a big file it's not a big difference either way.

Since we already have an open FD at that time we can stat through the FD - no directory traversal done.

**Comment by ThomasWaldmann** [comment]
Right, it is likely cached, so just 1 OS call overhead + a bit of python.

If we consider it superfluous, that doesn't matter though. ;)

**Comment by ThomasWaldmann** [comment]
As there was no work on this and we are close to RC phase, I am removing this from the milestone.

**Comment by ethchest** [comment]
This would also in many cases add a lot of output if funning with output/progress enabled. In many cases, snapshots are not really necessary but still, if a filesystem continues to be used, file will change, if only cache files. (which you could exclude, but that is also a lot of work. I noticed this already now when backing up /home -  at least each app that has a cache or similar generated errors about files having been deleted.

**Comment by ThomasWaldmann** [comment]
@ethchest in case of dirs with files that do not need to be backed up, it is way better adding them to the exclude list than having a lot of warnings in each backup log and having unnecessary big backups due to backing them up. nowadays a lot of that is in `/home/*/.cache/`.

**Comment by ThomasWaldmann** [comment]
Do this after PR #4043 is merged.

**Comment by christophlehmann** [comment]
It would be very nice if this can go on 👍 In some environments (cloud server for example) we have to backup an active filesystem and sometimes the backup fails because of `stat: [Errno 2] No such file or directory` when the file were deleted during backup

**Comment by ThomasWaldmann** [comment]
@christophlehmann that is a different case.

In your case, the file vanished after borg listed the directory and before borg began processing the file.

So, borg noticed that and gave you a warning (not an error) and continued with the next file(s).

borg later will terminate with rc 1 for warning status (not with rc 2 as when an error occured).

This ticket is rather about a file having been modified after borg started processing it and before borg finished processing it. That means the file is backed up in an inconsistent state (which should raise a warning at least and could be avoided by doing a snapshot with lvm/zfs/...).

**Comment by christophlehmann** [comment]
@ThomasWaldmann Thanks for clarification!

**Comment by ThomasWaldmann** [comment]
See #4434:
- only implemented for regular files, doesn't make sense for other file types
- with `--list` emits file status `C` if a file changed **while** being backed up, so it might be c)orrupt or have c)onsistency issues [this is a new status, previously we had M)odified, A)dded, U)nchanged].
- does not emit a warning yet, but guess it should, also should set rc to 1.
- no win32 version yet. "this is fine" mode on win32.

**Comment by ThomasWaldmann** [comment]
A short note about this comment:
```
# also, we must not memorize a potentially inconsistent/corrupt file that
# changed while we backed it up.
```
As this condition implicates that the ctime of the file is different already from what will be put into the files cache, it means that even without the modified if-condition it is no problem, because the file will be always considered changed because we compare the ctime of file with the one stored in the cache and only use the chunks list if both match. if somebody uses mtime for this comparison, it should be also no problem as far as file contents are concerned, because a change there also updates the mtime.
