### ISSUE TITLE
cache rebuilds if same repo is used by multiple machines

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#18]
if one backups multiple machines to same repo (which is what one tends to do, if the machines share a lot of similar files, like e.g. same operating system), a backup on one machine invalidates the cache on the other and triggers a cache rebuild that analyzes all the archives in the repo - which is quite time consuming.

find out if there is a more efficient way to deal with this.

**Comment by xrat** [comment]
The fact that caches are invalidated and need to be rebuilt is what keeps me from using attic and borg, cf. my comments at https://www.debian-administration.org/articles/712#comment_3 and my ML posting at http://librelist.com/browser//attic/2014/12/27/times-increase-linearly-with-backups-done/

Unfortunately, I am not a programmer. Otherwise, I would have investigated this already myself. I tried to copy the cache and/or use a shared cache of `chunks` but it didn't work. Attic either kept rebuilding it or broke or refused completely (don't remember exactly).

Also note that this is related to https://github.com/jborg/attic/issues/186 - "Allow multiple servers to back up to the same repo at the same time"

**Comment by ThomasWaldmann** [comment]
There's an easy way to avoid the big data transfer that is annoying esp. for remote repos accessed over slow connections: keep a per-archive chunk index in the local cache (currently we only have one, for-all-archives chunk index).

If the (main, single) chunk index needs rebuilding it can use the (already cached, local) per-archive chunk indices and only needs to fetch the data for the (new, not yet cached) archives from the remote.

So, for N-1 old (already cached) archives and 1 new archive, there might be an almost N-times speedup compared to what we have now. If you have 1000 archives this is a lot...

But: this comes at a price: you'ld need about N+1 times the space of the "chunks" file size. If you have 1000 archives, this is also a lot.

**Comment by ThomasWaldmann** [comment]
Another note: the time / space needs for rebuilding the cache are also influenced by the chunk size (which also contributes to the RAM usage).

The smaller the chunk size is, the more chunks are needed and the higher the costs for dealing with them are. attic's target chunk size is 64KB. OTOH, small chunks contribute to better deduplication.

**Comment by ThomasWaldmann** [comment]
I've found an easy way to get the space usage to a much lower value (still somehow linear with N, but with a smaller coefficient than 1): just make a tar.xz archive from the stuff. Patch coming soon. :)

**Comment by ThomasWaldmann** [comment]
see PR #33 - please try it and give feedback.

**Comment by lfam** [comment]
This is great news! Anything to make this use case more efficient. This is where the real strength of the rolling hash deduplicators will be found.
