### ISSUE TITLE
Add BLAKE2b ID hash functions

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1800]
- New key types which use BLAKE2b-256 for ID hash (and MAC?).
- `authenticated`: no encryption
- `repokey|keyfile-blake2`: the usual encryption.

From #1044 

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/38938088-add-blake2b-id-hash-functions)

**Comment by ThomasWaldmann** [comment]
For the encryption=none mode and to avoid having to do big changes in little time, I think we should just use the unauthenticated hash for 1.1 - otherwise we'll need a keyfile/repokey for that mode also (to store the id-mac key).

In general, doing big changes would create lots of conflicts in the crypto-aead pull request, I'ld like to avoid that.

So, is it maybe easier to read the desired hash / mac type from repo config? And just create new repos with configured blake2b hash / mac, while defaulting to sha256 / hmac-sha256?

**Comment by enkore** [comment]
Portable vs native/sse doesn't make that big of a difference:

**Comment by enkore** [comment]
Maybe that's the reason why OpenSSL also only uses the C implementation and not the SSE implementation; little performance difference, but more maintenance: https://github.com/openssl/openssl/tree/master/crypto/blake2

**Comment by ThomasWaldmann** [comment]
Can you do a plot without the tiny msg lengths (they spoil the scaling and we rarely have such tiny msgs)?
Maybe 512B .. 512kB?

**Comment by enkore** [comment]
Beyond ~2 kB it doesn't change any more - the O(n) part takes over the constant setup time.

![image](http://i.imgur.com/O8T5yX7.png)

Note: to get so "smooth" results one has to kill/halt all resource intensive processes (eg. firefox) and run at high priority, otherwise there will be spikes esp. in the longer message length due to scheduling. This is expected.

**Comment by enkore** [comment]
Mostly done. I'll conduct some additional tests and will submit a PR.

But: it definitely improves performance when deduplicating. With repokey I get ~245 MB/s deduplication rate (=chunker + ID hash). With repokey-blake2 it's 325 MB/s, almost one third faster. When writing fresh data the impact will be less, of course (because I/O, encryption, MAC take their share).

To keep the diff minimal I decided to not change the MAC function to B2 as well. #1034 does not apply cleanly, but all conflicts are easy (import lines, and git being cautious about places where both branches added hunks).

**Comment by ThomasWaldmann** [comment]
@enkore claim the bounty.

**Comment by rugk** [comment]
So is there any way to convert existing repos to use blake after updating borg?

**Comment by ThomasWaldmann** [comment]
@rugk no, there is no converter yet and also no co-existance of different id-hashes.

**Comment by rugk** [comment]
Mhh, that's bad. Is there any plan to add it or should I open a new issue for that?

**Comment by ThomasWaldmann** [comment]
not sure we need one. for existing systems and repos of them, the daily backup just deals with the changes since last backup, which is usually not much. blake2b gives some speedup if there is a lot to hash, especially in the first backup or if there are new/changed big files.

in 1.2, we'll add some more flexibility for the crypto stuff, maybe we can deal better with this by then.

**Comment by rugk** [comment]
I think updating to newer crypto is often desired by some people… And if it just improves the speed of future backups a bit…

**Comment by ThomasWaldmann** [comment]
Sure, we moved the blake2b change from 1.2 to 1.1 to make it available earlier than 1.2.
But we need some other stuff that will come in 1.2 for better flexibility...

**Comment by enkore** [comment]
There will be no further crypto changes for 1.1.
