### ISSUE TITLE
Clarify files cache documentation

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#1825]
I have to say that borg backup is very impressive product and already as such ready for most of my needs. However to make it even better I filed this proposal.

Please clarify documentation:

1)
The option "--no-files-cache" is used in several commands. The explanation for that is "do not load/update the file metadata cache used to detect unchanged file".
But what does that mean in practise? How is the unchanged file detection done if that option is used? Based on file content checksum or are all files assumed to be changed or what?
This is not explained in the documentation.

2)
It is also not very clearly stated how the changed files are detected? What attributes are used? 
Obviously last modification time must be used, most likely also file size but what else? File ctime, permissions, owner, group or file checksum? Are these used in any circumstance?
Natural place for this explanation is borg create command because changed file detection is needed during create.

**Comment by enkore** [comment]
The file-unchanged-detection is used to determine whether the file *contents* have changed. The file metadata that goes into the backup is always read fresh from the file system.

If Borg detects that a file is unchanged, it does not have to re-read the file contents. Since Borg is deduplicating there is no difference in repository space usage -- this is solely an optimization that makes it go faster (in most cases) while needing more memory.

Regarding 2.): mtime, inode and size, but inode check can be disabled with the --ignore-inode option.

**Comment by ThomasWaldmann** [comment]
fixed by #1875.
