### ISSUE TITLE
Does borg do crucial modifications in append-only mode?

### ISSUE THREAD

**Issue by the-n3i** [borgbackup/borg#1867]
I'm planning on doing a backup in borg on a server that is configured to `append-only`.
The backup from this server will then be cloned to a second (off-site) server regularly, using rsync with `ignore-existing`. The aim of this is to keep a copy all files, even if they get changed/deleted on the local backup server.

So, in my scenario, any file will only be synced once and all modifications or deletions won't get synced with the remote server. Will this cause any trouble for borg? I understand that the transaction log won't be synced, but I can live with that if it doesn't cause any problems for backup integrity.

**Comment by enkore** [comment]
> Will this cause any trouble for borg?

No. Segments are only written to once. After that they will only be deleted or not modified at all.

>  I understand that the transaction log won't be synced, but I can live with that if it doesn't cause any problems for backup integrity.

From Borgs point of view it's just a text file that is only appended to, never read back.

It might be useful to have it on the replica, too, perhaps there is some rsync option to only copy appended parts or something like that.

**Comment by ThomasWaldmann** [comment]
How should `with-lock` ensure that no uncommitted segments get synced?

If `borg create` gets interrupted, our cleanup code will usually remove the lock, but there will be uncommitted segments.

**Comment by enkore** [comment]
with-lock has that PUT/GET manifest thing going on, which will trigger a transaction on the repository, cleaning leftovers up.

**Comment by ThomasWaldmann** [comment]
hmm, I've seen that rather as a implementation detail caused by compatibility requirements of old servers (IIRC), not as a feature.

**Comment by enkore** [comment]
Actually the PUT and following rollback would mean that the segment created by the PUT is uncommitted and will later contain different data in the next transaction. So we need to repository.commit() in with_lock, not .rollback().

**Comment by the-n3i** [comment]
OK, so on <1.1.0 I just have to trigger the sync manually after the last backup has completed successfully.

So I didn't fully understand the essence of that `with-lock` discussion. Will the upgrade to 1.1.x ensure I can do my rsync thing?

Also, are the segments terminated in a defined way? Then I could use the rsync switch `--append` instead of `--ignore-existing`, which would enable me to sync the updated transaction log without risking corrupted segment files.

**Comment by ThomasWaldmann** [comment]
I'm adding this to 1.0.9rc1 milestone - so we'll look at the proposed with-lock modification until then.

**Comment by enkore** [comment]
iirc with-lock is only in master branch

**Comment by ThomasWaldmann** [comment]
Discussion above is maybe a bit hard to understand, so I'll add a summary here:

Before the fix was applied, borg did:
- rewrite the manifest to start a transaction (get the repo locked)
- do whatever your command was within `borg with-lock <repo> your_command`
- rollback the transaction, so the last committed state of the repo is like before
- dirty: there is a uncommitted segment file now (and this file was there while your_command was running) that will be cleaned up next time the repo is used. this means that the same file number will later get reused for different content, which is obviously incompatible with rsync's `--ignore-existing` because it would not sync the new file then.

After the fix, borg does:
- rewrite the manifest to start a transaction (get the repo locked)
- do whatever your command was within `borg with-lock <repo> your_command`
- commit the transaction (which will not logically change anything, as we have just re-written the same manifest as there was before). in the filesystem, there will be some changes due to the additional commit and also the compact_segments run triggered by the commit (if your repo is not append-only). this avoid that the same segment file number gets reused for different content later.
