### ISSUE TITLE
Can I backup to Amazon Glacier with borg ?

### ISSUE THREAD

**Issue by RandomPlatypus** [borgbackup/borg#1872]
Hi, I would like to make incremental backups to Amazon Glacier with borg. Is that possible ?

Borg seems to need to read some files in a repository before beginning the backup, so I suspect this kind of "backup is cheap but recovery costs money" service would not be usable by borg. But I ask anyway, because Glacier seems very cheap and reliable.

**Comment by ThomasWaldmann** [comment]
No - at least not directly.

borg either needs a filesystem to write to or a remote borg process it can talk to via ssh.

For some "cloudy storage" types there are 3rd party FUSE filesystems, but some of them might be problematic / buggy / unreliable. I am not familiar with these, so google yourself. :)

There is one cloud storage provider offering direct support and has borg installed (and is "known working good"):

http://www.rsync.net/products/attic.html

**Comment by enkore** [comment]
Some people do this indirectly eg.:

- http://zyradyl.github.io/2016/10/02/Collegi-Backup-System/
- https://techblog.realisaatio.fi/backups/rclone-backblaze-b2-0-005gb-storage/

The idea in both cases is to have a bounce buffer of sorts were you have the full repository locally and work with that, then synchronize it to some cloud storage thingy. While this is a bit awkward, it's also a bit of an advantage, since you inherently have another backup locally with no bandwidth / cost restrictions.

**Comment by ThomasWaldmann** [comment]
closing this. solved (and also not really related to borg).

**Comment by nomeata** [comment]
How hard would it be to keep the actual data chunks separate from the meta data, in a way that during normal backup operations, chunks are only written, but never read? This way, they could be efficiently be pushed to Amazon Glacier while the (smaller?) metadata of borg stays on some other system.

**Comment by ThomasWaldmann** [comment]
The storage does not differentiate between different types of data. it is just key / value (hash(data) / data), they key (hash) is 256bit, the value is a piece of data (~2MB).

Theoretically one could split that into separate stores, but it would need quite some changes and add complexity - for yet unknown benefits.

So, the recommended way to deal with the cloud is to use a tool like rclone to sync a local borg repo to the cloud. This has the benefit that you have super fast local access for all non-catastrophic use cases and you only need to fall back to the cloud copy if the local copy is gone. It's also good because borg devs don't have to deal with lots of cloud code and bugs / issues / limitations in there. :)
