### ISSUE TITLE
use vagrant for platform testing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#196]
misc. linuxes, BSDs, darwin, maybe windows.

**Comment by ThomasWaldmann** [comment]
PR #200 was merged into master.

**Comment by level323** [comment]
Just a heads-up that I had what appears to be major problems (kernel panic) using the Vagrantfile. After doing some searching I found that a relatively common issue encountered by people had something to do with running Virtualbox guests with the guest configured to use multiple VCPUs. 

My system is a relatively recent Intel Quad Core unit so I'm not sure why I was experiencing this issue. There appears (from my research) to be a multitude of possible reasons for this to occur and I have not yet been able to definitively identify the cause in my case.

Nevertheless, changing line 232 in `Vagrantfile` from:

`v.cpus = 2`

to

`v.cpus = 1`

seems to have resolved the situation for me. 

To be clear, this issue is not borg-specific. However, I'm wondering whether or not it might be 'safer' to make the Vagrantfile configure the VM to use only 1 VCPU by default in case anyone else hits this issue.

**Comment by ThomasWaldmann** [comment]
sure, if there are too many issues with 2 VCPUs (which I find a bit embarassing in 2015), we'll just use 1.
