### ISSUE TITLE
permission denied error during backup of EFS encyrpted files

### ISSUE THREAD

**Issue by X-Coder** [borgbackup/borg#2001]
Hi,

is it possible to backup EFS encrypted files?
Once there are EFS encrypted files I see this error during progress output:
/mnt/windows_i/.../IMG_2506.jpg: **[Errno 13] Permission denied**

I try to backup the files of a lvm snapshot of a vm containing a windows server.
So I mounted the snapshot to a local folder, and let borg create work on this. Everything worked as expected, except EFS encrypted files, which some of the windows users on the server seems to use.

Host is Debian with XEN, Windows Server 2012R2 as guest vm, filesystem is NTFS.

**Comment by enkore** [comment]
You have a LVM snapshot with some NTFS in it, and the NTFS uses some EFS for some folders. You mount the snapshotted NTFS and then create a backup from it. Correct?

I believe no Linux driver currently supports EFS due to how the keys are stored in the installation and so on. So the Errno 13 probably means that one just can't read that EFS file from Linux.

**Comment by X-Coder** [comment]
Ok I understand, thank you, you did get me right, cp and every other command has same issue.
I will just switch to backup the whole snapshot instead, then I won't have ACL issues too.

**Comment by ThomasWaldmann** [comment]
@X-Coder have a look at `--read-special` for backing up the snapshot.
