### ISSUE TITLE
Timeout option to borg mount

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2012]
Hi,

I've seen that "borg mount" also requires/sets the lock to the repository. Imagine I mount my repository to check some files and forgot for some reason to umount it. Then my scheduled backups wont be performed. I don't know if the lock is required or not, but having some sort of timeout to umount the archive if inactive would be really nice to avoid this sort of problems.

Thanks for the great app!

**Comment by infectormp** [comment]
read more here https://github.com/borgbackup/borg/issues/768

**Comment by alejandro-perez** [comment]
Thanks. I can live without it nonetheless

**Comment by enkore** [comment]
I believe this is cleared up then?

**Comment by alejandro-perez** [comment]
Yes it is. Sorry I didn't know I had to close it myself.

**Comment by dingens** [comment]
Hi. I don't see why this is resolved by or a duplicate of #768. #768 basically says "mount and create at the same time are difficult to implement" while the issue here is "I want to mount to timeout automatically when I forget it". (Isn't it?) In fact, it is rather the other way around: this bug sort-of resolves #768, because implementing the timeout would make a fix for #768 less important for some use cases.

**Comment by archont00** [comment]
Indeed, just came accross the same trouble - forgotten borg mount blocking any other action on repo.  Timeout option to `borg mount` would be helpfull.

**Comment by ThomasWaldmann** [comment]
Some time having passed does not implicate the mount isn't used any more.

mounts of other filesystems also need explicit unmounting and don't *time out*.
