### ISSUE TITLE
Not documented: Support for NTFS

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#2080]
It is not documented whether borg supports NTFS as source or target (=where the repository is) fs.
- Can I take backup from files on NTFS partition (e.g. USB disk)? And of course be able to restore them back to NTFS partition?
- Can I create a repository on NTFS partition (e.g. USB disk)?
- Are there any problems backing/restoring linux fs (e.g. ext4) files and directories to repository on NTFS disk?

My borgs are running in CentOS / Ubuntu boxes all having ntfs-3g.

Please add this information also to user guide.

**Comment by enkore** [comment]
Yes, yes, yes, depends.

NTFS\Win32 is not a POSIX FS, for example, file names containing chars like "\ < > ? :" are invalid and would not be accessible from Windows applications.

Since Borg works on the view provided by ntfs-3g, which performs some mapping functions between Win32-like semantics and POSIX-like semantics, things like ACLs would generally not be archived or restored transparently.

Re. documentation: We generally don't document that, because it generally works with any available FS within the limitations of the FS. Since there are so many, it would be a long and tedious to maintain list, esp. for cloud-ish-FSes which release often and have many bugs / bug fixes.

**Comment by ThomasWaldmann** [comment]
If we didn't already, we could maybe document borg's expectation for the fs that has the repo.

For some backup tools (like e.g. rsync), the requirements are rather high (>= features of the source fs), so it is a plus if we say that we have relatively low requirements (basically just any working fs).

**Comment by wolfpackmars2** [comment]
For ref: this may be a logical place for such documentation.

https://github.com/borgbackup/borg/blob/cdb4df0885ae81529df1491ec3e825b3c019fafe/docs/usage_general.rst.inc#L209
