### ISSUE TITLE
Borg and Boar

### ISSUE THREAD

**Issue by carstenfuchs** [borgbackup/borg#2119]
I'm currently using Boar (https://bitbucket.org/mats_ekberg/boar) to backup my photos.

It is very similar to Borg (even the name!) but has a few key differences:

  - Backups are versioned. I like this a lot, it feels very natural, like Subversion or Git, e.g. `git commit`.
  - It can be used to distribute files to backup clients (i.e. “family members”), e.g. `git pull`.
  - Distributed: Just like Git, every client has everything (or rather, to be more precise, everyone has the latest commit, like with Subersion). For me, this is a very important safety factor in backups, because it eliminates worries about central server loss.
  - Unfortunately, Boar is barely maintained. I submitted a couple of patches, but even trivial ones are not being reviewed.

(Note that I'm using Boar, but am very new to Borg. Please forgive if I got something wrong about Borg.)

Well, I was wondering how Borg relates to Boar. Personally, I think it would be ideal if the best of each was merged.  :smiley: 
Is this something that would be interesting from Borg's perspective?
Are some of Boar's features also on Borg's roadmap?

**Comment by ThomasWaldmann** [comment]
Not sure why "versioned" is a difference. If you make 2 borg archives of same dataset at different times/states, you also have 2 versions. borg is not a dvcs though.

Distribute files to backup clients? You mean make a copy of the backup repository, right? You can also just use rsync to make a copy of a borg repo. You'ld need to use borg extract or borg FUSE mount to access the files. Also, in borg extract case you have the repo and the extracted files taking up space.

Having everything might be nice sometimes and bad other times. If you keep a long history of backups on your backup server, you do not also want them to also take up same space on source machine.

**Comment by CarstenF** [comment]
"Versioned" is interesting due to its metadata, even in an add-only backup system: who changed what, when and why.
If file deletions are permitted: Which old photos were deleted (any why)? E.g. you can backup all new precious photos from a digital camera immediately, review and delete bad ones later. This obviously requires pruning of old backups/archives/commits sooner or later.
(A dvcs is not required, an analog to a simple cvs would be "enough".)

With "distribute to backup clients" I mean the equivalent of `git clone` and `git pull`: Got a new computer, new harddisk, somebody else who wants to see all the photos, ... – that's all you need.

I'm not exactly sure what you mean by "same space on source machine", but having everything (or at least the latest "commit") on every client machine would, afaics, inherently have many features of a good backup system: convenient and easy to use (backups being done frequently), multiple independent copies in physically different locations (no backups of backups needed, easily distributed), easily accessible and recoverable on arbitrary failures.

**Comment by enkore** [comment]
There is #1697 for replicating archives.

Versions -> Quite a big semantic change, seems unlikely to me. Archives can have comments.

The DVCS / everything-stored-everywhere approach works fine for small data sets but isn't useful for larger data sets; if you want to back a couple TB up to somewhere else then it'd  be not very useful if it _also_ needed the couple TB locally as well.

**Comment by RonnyPfannschmidt** [comment]
borg separates repository from working set, having a general model to replicate archives would probably be helpful but thats already in #1697 

if people want to scm-style manage stuff, i beleive git-annex is the more happy tool to use

**Comment by CarstenF** [comment]
Maybe I explained my intention badly. It's not so much "having everything everywhere" as with Git / DVCS, but rather a Subversion / centralized approach: Have a central server that has everything (unless explicitly pruned). The clients would only have the latest revision/commit/snapshot/archive as their working directory (or any past version if that is their explicit choice).

In this point of view, the backup is still "strong", because I assume that each client (usually) has the latest commit and the latest commit is the most important one. So if everything else fails, at least the latest snapshot can still be recovered from any client.

So I think that the "distributed" feature is not so important at all. However, I draw a lot of confidence from the version control part ("what has changed since the last backup?"): What happened to the file that I thought was still there last week? Did I or am I about to backup a file that has changed unnoticed? (unintentionally overwritten? got virus infected? ...)

Maybe the latter is a good example: If some evil software destroys your files and gets away with it for a while unnoticed, you are in danger of backing up destroyed files, unknowingly still feeling safe. Version control that shows changes between backups can help to prevent this.

**Comment by enkore** [comment]
Ah I see. The latter part is something already implemented (beta) through `borg diff`, although it doesn't really compare to the ease of "git log" or "gitk" -- can't just "scroll through" it (on the other hand most git commits are seldom hundreds of GBs or TBs large :)
