### ISSUE TITLE
Any plan to improve hash and compression performance ?

### ISSUE THREAD

**Issue by sinasalek** [borgbackup/borg#2176]
I'm using borg for a while now, for servers with limited data it's great, but dealing with gigabytes of small and big files, it is very very slow (days).
I understand that calculating hashes and the whole chunk/deduplication system plus compression can be very slow, but it seems that borg does not utilizes modern system resources (Same as Duplicity and Areca Backup that i used before). It can only use one thread. Considering cheap multi core CPUs and how fast even the low budget SSDs are, it's a real bottleneck.
There are already opensource hash and compression libraries with multi-thread and GPU support.
Even processing several files simultaneously on different threads can significantly improve performance
Image if we could backup terabytes of millions of files within few hours :)

If you guys come up with a realistic roadmap, i believe many borg users including myself would be more than happy to donate to support the effort :)

http://libbsc.com/
http://www.blosc.org/
http://compression.ca/pbzip2/
LZMA2
https://www.joachim-bauch.de/projects/pylzma/
https://github.com/akashgangil/GPU-Hashsums
https://github.com/arrayfire/arrayfire-rust
http://lz4.github.io/lz4/
https://pypi.python.org/pypi/lz4

**Comment by enkore** [comment]
So far in 1.1:

- Improved repository I/O which helps with writing speed (reduces iowait)
- BLAKE2b-based encryption and authentication modes. The BLAKE2 implementation used currently is very portable but not the fastest, still faster than SHA-2 on x64 CPUs.
- CLMUL-based implementation of the CRC32 checksum used in the repository code, this is about 10-15x faster than the code used previously on Intel CPUs of the last couple years. (It doesn't work/compile on OSX/clang -- if someone could fix it there, it would benefit even more users).
- Minor improvements in the chunker

With these changes Borg manages about 60-80 MB/s real write speed (ie. not deduplicating) from a SSD to a local hard drive for me. Deduplication works around the ~200 MB/s mark for me, less for smaller files of course.

The [1.2 milestone](https://github.com/borgbackup/borg/milestone/17) is focused on two things:

1. Improve crypto with faster primitives and session keys, which allow more efficient use of multi-threading
2. Introduce multi-threading into `borg create`, perhaps others

**Comment by ThomasWaldmann** [comment]
@sinasalek i had used blosc in my experimental branch and already did some experiment with multithreading there. but that experiment was trying to do too much multithreading, so it turned out to be a too big / too complex / too risky (race conditions, crypto implications) change.

thus in 1.2 we will first do a less big / less risky step and implement a simpler form of multithreading.

blosc (or other lib that does own MT) likely won't get used, we'll do MT on our own as we want to control it ourselves. the problem with compression libs doing own MT is that they usually need more input data at once than we can give it (because it divides that into N pieces for N threads internally - but each piece shall not be too small as otherwise compression gets less effective).

for now (borg 1.0 / 1.1), if you want to have it quick, use lz4 - this is so fast, you won't need MT for it.

in 1.1, the stuff mentioned by @enkore will also help quite a bit.

**Comment by sinasalek** [comment]
Thanks a lot for quick complete answer @ThomasWaldmann @enkore
 I should definitely give 1.1 a try then when it released. I'll let you guys know the result in my use case

**Comment by ThomasWaldmann** [comment]
question answered (and also we have other tickets about improving compression/hashing).
