### ISSUE TITLE
Parallel compression

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2262]
Is it possible (or mark as enhancement please) to compress in parallel and utilize desired number of cpu cores? 

For example, `tar` with `pigz` is MUCH faster on multiple cores (and modern Xeon E5 servers have plenty of cores like 48+) compared to usual `gzip`. I'm using `lz4` and fast SSD disks and it will be great to be able to use more CPU cores for speed.

**Comment by knutov** [comment]
#2176 is related.

And, in my case, lz4 on single core is not enough to utilize my SSD disks and 1Gb+ network.

**Comment by ThomasWaldmann** [comment]
borg-internal multithreading is planned for borg 1.2. we'll have to see whether we can use if for parallel compression - I'll rather avoid race conditions than having parallel compression.

using compressor-internal multithreading is likely ineffective because all we can feed at once to it is usually ~2MiB (for default chunker params). if it needs to cut that into pieces to feed internal threads, compression becomes less effective because it does not have enough data to warm up.

that you do not see full utilization of your resource is because in borg 1.0 (and master/1.1) everything is single-threaded. so there are alternating phases of iowait and cpu-intensive parts.

**Comment by ThomasWaldmann** [comment]
hmm, guess #2176 is enough as a reminder for parallel compression?
