### ISSUE TITLE
mount: allow / in archive names

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2263]
Only seems to be forbidden because it would make the `borg mount` code a bit more complex. Parsing is not hard; extra assertion would probably be `posixpath.normpath(archive) == archive` (to rule `../../` & friends out) and it does not start with a /.

Allowing these gives a nicer, more intuitive separation of archives, e.g. `{hostname}/{date...}` is much neater with / as a separator than -_#@ (whichever) for mounting it, but also because / is considered a separator in general.

Btw., currently `.` and `..` are valid archive names; while these don't crash `mount`, they're inaccessible there.

**Comment by ThomasWaldmann** [comment]
Yes, one could do some nice tricks with that.

But it would also make some stuff harder:

Currently, if you mount a repo, you can expect 1 layer of archive names as directories and the archive contents directly inside these dirs.

With that change, you'ld have to first get a list of archive names from `borg list repo` to get the archive names which are now also the path prefixes needed so you know where the archive content starts below the repo mountpoint.

**Comment by enkore** [comment]
> Currently, if you mount a repo, you can expect 1 layer of archive names as directories and the archive contents directly inside these dirs.

Well the point of using / is to explicitly not have just that one layer...

**Comment by ThomasWaldmann** [comment]
nitpick: there is only 1 "layer" in borg list output though...

**Comment by enkore** [comment]
History: Slashes were forbidden in Borg 0.25 due to jborg/attic#180 ("Creating archive with a slash breaks mount option"), previously they were allowed. As noted in #2278 the fix was actually not complete, because the path-like archive names "." and ".." remained allowed and broke it as well (though who does that?). For everything except borg-mount the archive name is just an opaque handle (with a big "don't care" stamped on it).

**Comment by ThomasWaldmann** [comment]
I am a bit torn about this:
- nice hack to allow structuring your archive names
- otoh, it might trigger structure accidentally where it never was intended
- also, it is giving structure/meaning to the archive name, which is also a major change and might be a troublemaker in case we want to get rid of archive names some day and move to hostname/datasetname/tags/comments.

Just as an example, people could have archive names like:
- "backup done on 02/28/2017 before the migration"
- "backup done before mb/tw changed foo"
- "/I had no idea this gets meaningful/"
- "backup of //share/my/path and //othershare/his/path"

**Comment by enkore** [comment]
All of these were invalid until know, though (and the //smb examples would still be).

If one doesn't know about mount, then the mental model is likely archive name ~ file name, so slash and other fancy characters would be considered illegal. Which is btw. another thing to discuss, it probably makes sense to restrict the available characters more, forbidding e.g. <>?|, since these are not compatible with some operating systems.

> also, it is giving structure/meaning to the archive name, which is also a major change and might be a troublemaker in case we want to get rid of archive names some day and move to hostname/datasetname/tags/comments.

I don't think that's likely (at least within 1.x). We might add tags, and we already have comments, but neither would or could replace archive names.

Archive names are almost always structured, just using different characters, and obviously do have a meaning.

**Comment by ThomasWaldmann** [comment]
Well, we already have archive IDs (the hash), so these could be used instead of the name to refer to archives. Not very readable, not great for recreate (ID changes, content is logically same). Also we have the date/time separately. IIRC, restic does not have archive names.

We have one problem already with the archive names, which is prune. Although archive names are not interpreted at all other places (yet), prune expects at least some prefix structure if you backup multiple different data sets into one repo. With dataset name separately, that would be cleaner.

**Comment by enkore** [comment]
Hashes don't work for humans.

Tags and timestamps (without names) only work for a very narrow set of applications.

**Comment by ThomasWaldmann** [comment]
Git users aren't human. :D

**Comment by ThomasWaldmann** [comment]
Tags or different attributes would work in a equivalent way to names. It is just about not mixing things into the archive name (as now), but keeping them separate. To uniquely identify an archive, you'ld either give its ID or enough tags / attribs, so that the matching set size is 1. To identify bigger sets, one would give less tags / attribs, like for prune.

BTW, if we implement this, it would need some rather strong recommendation (with explanation) in the docs, that archive names with "/" will now trigger non-flat fuse archive directories and that having a reasonable hierarchy in the names will matter for that. Suggest fqdn/datasetname/datetime.

**Comment by textshell** [comment]
This looks to me like this would cause more confusion than help. For machines and humans alike.
Borg mount is a major feature and esp. having archive contents mix with starting points of other archives seems and not having a simple way to detect where an archive root is seems confusing.

**Comment by enkore** [comment]
textshell and I discussed this a bit, and I noticed that I didn't really explain well what the intended use (from my PoV) is. Borg is one of very few programs that offer properly implemented, strong checksumming, efficient {encryption, deduplication, compression}, rich FS meta-data preservation and fast mounts. [1]

This makes Borg well-suited not only for pure backup use ("I have a bunch of hosts and datasets and a script makes Borg Archives from those every $time_interval"), but also for "structured archival". Now of course you could use this to give backups more structure when browsed in a mount, undoubtedly. Structured archival is somewhat similar to "just" having files on a FS and textshell pointed out as well that this use is more like "borgfs" (as a concept, not the binary name). However, I see the read-only nature of a Borg mount as an advantage, because modifications to existing archived pictures, movies and documents (or similar) should be the exception, not the rule, which is what Borg is built on. A rw mount would not only be unfeasibly complex to implement, but also make damaging archives by accident much easier; we probably all agree that we don't want to bother with rw-borgfs. The nature of using special Borg commands to manipulate archives thus has the notion of more permanent actions, similar to burning a DVD or carving symbols into rock.

This use is a bit different from the more frequent application as a regular backup tool, but IMHO does not only work very well, esp. with this change, but also shares so much, on a technical level, that it doesn't make sense to have a separate project just for that. The fact is that Borg is largely unopinionated about how one structures the contents of a repository, what one stores in a repository or how to retain data in a repository, in other words, that Borg is mostly a _deduplicating archiver_ and _not_ a backup-specific tool.

[1] btrfs is unsuitable, because it uses weak checksums and is only supported on Linux. ZFS runs on more platforms, but is cumbersome to use on Linux. Other dedupearchivers exist, but I haven't looked at them in enough detail to be sure that their crypto and other implementation is solid enough.

**Comment by ThomasWaldmann** [comment]
how about a practical example of that use case? could maybe also go into docs, if we implement it.

**Comment by enkore** [comment]
You'd make up some level where you want to routinely add stuff. For example, for a picture collection that is normally already sorted into film rolls one might use `Pictures/<Year>/<Filmroll>` for archive names.

**Comment by ThomasWaldmann** [comment]
@textshell: did you change your opinion after the discussion mentioned in https://github.com/borgbackup/borg/issues/2263#issuecomment-285868505 ?

**Comment by textshell** [comment]
Not really. I can see where enkore is coming from, but the use-case is decidedly non backup where i think the focus of borg is. IIRC enkore‘s use-case was more an media archive where sub-archives are 'mounted' into a common tree and thus creating and deleting archives with specially structured names would change the contents of the merged view (e.g. creating an 'photos/vacations/2017/somewhere' archive would sort that into a existing 'photos/vacations' directory in the merged view.
I can see how such a system would be of interest, but i think starting down that road will bring in a lot of future 'just a little somethings' that then need fixing for that 'borg as a filesystem' use-case. Not that that use-case is not an interesting one, or that it indeed would share a vast amount of code with the current borg. But i also seems like a ongoing distraction.

Without the concern about a possible distraction by more 'tweaks' i feel uncomfortable about having the archives to be mixed into a hierarchy on borg mount by default. I assume a lot of scripts will assume that the directory contents of the root directory of a mount contains *exactly* the existing archives. And even more would assume that the directory of an archive only contains that archive and not other differently named archives as well. So for that point of view i think this should not be the default. That of course leaves the question what to do with archives named with a slash. If we want to support windows mounts we will need to come up with an encoding strategy for archives names anyway(windows has lots of filepath disallowed chars). If we encode archives then of course the tendency for scripts to rely on directory listings will increase even more because they don‘t want to re-implement that encoding.

* So if we want to support '/' in archive names i think we should consider encoding it in the default mount mode. 
* If we want to have name based archive view merging, i think it should not be the default. We are not forced to use '/' as the separator

**Comment by ThomasWaldmann** [comment]
How about a "nested" mount option that's not the default, but does what @enkore envisions when used?

For the default mode, we could just transform the slashes in archive names (if any) to something else that has no special meaning.

**Comment by enkore** [comment]
Obviously not wanted.

**Comment by ThomasWaldmann** [comment]
IIRC the outcome of the discussion was "not wanted without changes" not "not wanted".

**Comment by Titanl** [comment]
This subject caught my interest, so I wrote a simple script that structurizes backups with symlinks, if they were created with a special syntax (:: instead of /): https://github.com/Titanl/borg-tree   
Please let me know what you think.

**Comment by gatlex** [comment]
Pity this should be closed.

Contradicting @textshell, I think there _is_ a use case for backing up data: I only backup all the date ("/") occasionally, but when I am working on documents, for example, I backup "~/Documents" quite often to have a recovery point (because it's so much faster and the rest does not change, anyways). Of course, I want to see what I stored when listing/mounting the archives. Currently, I do it as @Titanl suggests, replacing "/" by ":".

Btw, I don't care whether the directory sub-structure is recovered when mounted - for me it would be enough to have a folder "${mount_point}/home/$(whoami)/${timestamp}/Documents"...

**Comment by Titanl** [comment]
You don't need to worry if you backup the same data a second time, borg will deduplicate it. (Not that I would recommend backing up folders like /usr, /tmp and ~/.cache).

What my script does, is: Group backups in pseudo-folders and subfolders, delimited by :: (now \) instead of /. So you can e.g. create backups with names such as computer1\2019\06\19-234512 and later browse them without being flooded by a gazillion backup folders all at once (because the file browser will only show "computer1" etc. in the resulting link forest).
