### ISSUE TITLE
more docs about nonce security

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2266]
People ask via twitter or email about nonce security, it would be nice to extend the new security docs in master about these topics:

- nonce (non-)reuse
- ...when backup process crashes or power fails in the middle 
- ...when evil repo server cheats you (like offering older repo copy)
- ...when client state is lost
- ...when client state is restored to a previous state (e.g. by recovering from a backup)

**Comment by enkore** [comment]
**Scratchpad**

New section or subsection under Security\Crypto\Encryption

The client needs to track which counter values have been used, since encrypting a chunk requires a starting counter value and no two chunks may have overlapping counter ranges (otherwise the bitwise XOR of the overlapping plaintexts is revealed).

The client does not directly track the counter value, because it changes often (with each encrypted chunk), instead it commits a "reservation" to the security database and the repository by taking the current counter value and adding 4 GiB / 16 bytes (the block size) to the counter. Thus the client only needs to commit a new reservation every few gigabytes of encrypted data.

This mechanism also avoids reusing counter values in case the client crashes or the connection to the repository is severed, since any reservation would have been committed to both the security database and the repository before any data is encrypted.

However, this design is not infallible, and requires synchronization between clients, which is handled through the repository. Therefore in a multiple-client scenario a repository can trick a client into reusing counter values by ignoring counter reservations and replaying the manifest (which will fail if the client has seen a more recent manifest or has a more recent nonce reservation). If the repository is untrusted, but a trusted synchronization channel exists between clients, the security database could be synchronized between them over said trusted channel. This is not part of Borgs functionality.

---

This would be about the part where I would add another sidebox rambling on about planned 1.2 session keys which solve that issue and many others, but I know you don't like these.

Also counter value <=> nonce, the latter is shorter / less cumbersome.

**Comment by ThomasWaldmann** [comment]
Maybe also add the simpler stuff already present in 1.0, like detecting cache newer than repo.

**Comment by enkore** [comment]
This is now included here:

> (which will fail _if the client has seen a more recent manifest_ or has a more recent nonce reservation)
