### ISSUE TITLE
Bad memory, memory errors and their consequences

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2281]
"""
The actual error rate found was several orders of magnitude higher than previous small-scale or laboratory studies, with 25,000 to 70,000 errors per billion device hours per megabit (about 2.5–7 × 10^−11 error/bit·h) (i.e. about 5 single bit errors in 8 Gigabytes of RAM per hour using the top-end error rate), and more than 8% of DIMM memory modules affected by errors per year.
"""
Source: https://en.wikipedia.org/wiki/ECC_memory (referring to a study conducted by Google)

Ehrm, that is a bit more than I'ld have expected. O.O

Update:
https://www.cs.virginia.edu/~gurumurthi/papers/asplos15.pdf
See section 7 "Fallacies".

**Comment by ThomasWaldmann** [comment]
To be clear: dealing with not correctly working memory is usually something that is considered "not our problem" by software projects. We could do it the same way (and just recommend ECC, which might lead to long and rather fruitless discussions as they have for ZFS).

OTOH:
- a lot of our users are likely using systems without ECC (thanks primarily to Intel's product/price policy, board manufacturers not giving a sh*t (but rather stick LEDs for color animations on your mobo) and ECC being slightly (not much) more expensive).
- borg is using considerable amounts of memory, creating a big target to be hit by a memory error.
- consequences of bit errors can be significant: wrong refcounts, wrong chunkids

**Comment by ThomasWaldmann** [comment]
So, what can we do about it?
- add some docs (magnitude, how to avoid by buying ECC memory, pointing out that this is not borg specific)
- add some extra byte(s) per hashtable entry that at least allow detection of single bit errors. maybe this can be done rather cheap as when we deal with an entry, we have it in the CPU cache already, so this does not need additionaly memory reads for the data. When we add a new entry or change an entry, it needs to update the check bytes. And we need to check and compute these bytes (effort for this depends a lot on algorithm - just for detecting a bitflip, the algo could be rather simple).

**Comment by ThomasWaldmann** [comment]
Most trivial implementation:
```
check_byte = xor(b for b in entry_bytes)
or
w = xor(w for w in entry_words)  # 32bit words
check_byte = xor(b for b in w)
```
This would already detect all single-bit errors and even a lot of multiple-bit errors.

**Comment by enkore** [comment]
The main repository data structure [is extremely good at detecting errors](http://borgbackup.readthedocs.io/en/latest/internals/security.html#structural-authentication), but the indexing structures are not. To detect storage errors, #1101. But in-memory these are unprotected. A problem we can't efficiently fix, I think, is code corruption, although that _should_ result in more or less obvious malfunction / crashes in many cases (due to the dense coding of x86), but might not always.

Data corruption could be countered with ECC or checksums on a record level, like you suggest above, but that likely has high overhead / low efficiency since our records are small (<<64 bytes). Another problem is that the ECC is *on* the record itself, so localized issues will affect the checksum as well. In a tree data structure this would be easier to solve I'd say, since you can store a checksum in the pointer to a node, so the checksum is stored somewhere else from the node itself. Nodes are usually larger (>512 bytes), so more efficient to deal with.

But maybe that might not a problem in practice.

----

An interesting question would be what can happen when check --repair is run with bad memory.

**Comment by ThomasWaldmann** [comment]
Hmm, I think the updated issue title does not reflect any more that this is a usual problem, according to the linked study. It's not just when you are unlucky and have obviously-bad RAM (like found by memtest86+), but seems so frequent it is the norm for non-ECC memory. Also: it's "its".

**Comment by ThomasWaldmann** [comment]
I was curious if I actually could see one of these many RAM errors like the google study suggested.

I ran the linked script for 12h on my laptop, 0 errors were found. About 12..24 errors were expected.

So I guess issues pointed out in the 2nd paper linked in top post are real and the usual error rate seen is much lower than suggested in the 1st paper.

https://paste.thinkmo.de/QHuo7TcH#memtest.py

The script write to 3GiB of memory once and then keeps reading/checking this memory until interrupted.
So, the memory is busy with read accesses.

Another interesting try would be to write once, then wait for a long time, then check if everything is still ok.
This would test the idle memory case (except the refresh cycles done by the cpu).

**Comment by ThomasWaldmann** [comment]
Guess I am closing this. Trying to fix this in software might be slow, makes code more complex, can't fix the issue completely, ...

So, if you can't take the risk caused by RAM errors, better get ECC memory.

There are a few options for getting cheap ECC capability:
- some lower cost (non-Xeon) Intel CPUs have ECC capability: some i3, some Pentium
- some AMD CPUs and some mainboards have ECC, needs quite some research though because often presence and quality of the ECC implementation is unclear
- you can get used server/workstation grade machines and ECC modules (esp. DDR3) for cheap(er)
