### ISSUE TITLE
Character set of archive names

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2290]
Currently archive names are very permissive, they can even be binary. This is problematic for operating systems who don't like binary file names (e.g. Windows, perhaps OSX to some extent?).

Specifically, Windows does dislike these: `<>:"/\|?*`, applications get easily confused if you have these in a file/dir name (you can try this, since ntfs-3g allows these by default). Control characters (ordinals 1 through 31) are not well received as well. There are certain words that may cause trouble for some applications. See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx for reference.

**Comment by Abogical** [comment]
Related: #1166

**Comment by ThomasWaldmann** [comment]
@enkore are you seeing this as a problem due to a potential windows based FUSE support in the future or what's the problem?

**Comment by enkore** [comment]
Yes. We might also want to look into defining a limit on the length, currently it's likely only limited by env-var size or command line size (OS+ABI dependent, on x64 Linux that's 128K each), which is likely too large for the VFS.

**Comment by ThomasWaldmann** [comment]
https://learn.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#maximum-path-length-limitation

That reads like we should limit archive names to 250 chars, otherwise a path with just the archive name could already be over the limit.

**Comment by ThomasWaldmann** [comment]
Guess we should have:
- a validator, that checks archive names (given on the cmdline or elsewhere)
- archive names should be valid unicode (w/o surrogate escapes) and not require a binary representation (which is troublesome for json)
- borg transfer (1.2 to 2.0) must validate archive names first and reject if there is any invalid name. guess it is better to let the user rename any problematic names instead of automating this.

**Comment by ThomasWaldmann** [comment]
Update: Archive names will be limited to 200 chars and will reject most invalid chars (for linux or windows).

But we can not reject `:` although it is invalid in windows directory names because borg generates iso-8601 timestamps containing this, e.g. when expanding the `{now}` placeholder.

So, if we ever implement `borg mount` for windows and the `:` in archive names is a problem, we will need to map this character to something else (e.g. `.` or `;`) when building the filesystem.
