### ISSUE TITLE
Separate lock file location for borg serve (at least)

### ISSUE THREAD

**Issue by suuchan** [borgbackup/borg#2301]
We provide a service for people to run borg serve over ssh on a shared storage box where each user has a quota. When a user backs up too much then the free disk space reaches 0% and the lock directory can be created any more. Even 'borg prune' will refuse to work because it also locks the repository.

Is there a solution other than adding space temporarily for the cleanup? Our users would need to contact support for that, self-help is always better. I imagine that either having a '--no-lock' option or an option to place the lock file in a different location could help here. The later only makes sense with 'borg serve' where it can be forced (via authorized_keys) to always be the same and a user cannot circumvent locking by specifying a different path.

**Comment by ThomasWaldmann** [comment]
The lock file is not your problem, your problem is that there is no space to do anything.
Many borg operations need space to work, esp. the ones that write to the repo.

In borg 1.1 (still beta) there is code to abort a transaction and free the space used by it before it hits "disk full", thus I am closing this. Until then you've to make sure that your disk does not run full or be able to enlarge the available space when it does.

**Comment by ThomasWaldmann** [comment]
As a workaround, you could have some space-reserve file (1GB or so) that is accessible (and deletable) by the user.
