### ISSUE TITLE
hardlink slave items, add chunk list?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2325]
currently, hardlink slaves link back (via pathname) to the hardlink master (but they do not have an own chunks list).

that has the issue that if the hardlink master is not extracted (because it is a partial extraction that did not include the master), we can not just create the hardlink in the filesystem (`ln mastername slavename`).
so we have some workaround to get at the master's chunklist somehow, because the slave item does not have an own chunklist.

maybe we can consider giving the hardlink slave items their own chunklist, so we do not need that workaround? (we would still need to keep the workaround for old archives though, until we can make sure the old method does not appear any more in old archives)

I've just read some hardlink support code of `restic`, they handle it like that.
Also, they seem to use (inode, device) to link to the master item (not name).

**Comment by ThomasWaldmann** [comment]
tagged "breaking". not because it is breaking, but because we should do it at a time when we need to convert archives anyway (due to other breaking changes), so we can really get rid of the workaround that is needed for old archives then.

**Comment by enkore** [comment]
(dev, ino) backlinking is not necessarily a good idea, since these may change and break metadata dedup. I think the actual attribute used for the backlink is pretty much irrelevant, since Borg can and indeed does ensure the necessary consistency: whether we write `source = item.path` or `source = item.rdev, item.ino` (the latter is not actually part of the item yet) is not important.

**Comment by ThomasWaldmann** [comment]
@enkore right. so we don't change using the pathname for backlinking (that was just a note what I noted restic does differently - the reason / topic for this ticket is including the chunks list into the slave item).

**Comment by enkore** [comment]
Got that ;) I just expanded on that / why it doesn't make a difference.

**Comment by ThomasWaldmann** [comment]
See also #855.

**Comment by ThomasWaldmann** [comment]
BTW, it just came to me that using (dev, inode) instead of name reference has 2 nice properties:

- it completely decouples from the "hardlink master" (so if master is not extracted, we do not need it in any way)
- it is symmetric (all references are same, all refer to inode, not indirectly to a master item) and better reflects fs reality (there is no master/slave, all are equal).

**Comment by enkore** [comment]
If we put the chunks in, then they are already equal.

**Comment by ThomasWaldmann** [comment]
Almost, N-1 slaves will still refer to the 1 master (and the 1 master will not refer to any slave).

But maybe that is a cosmetic problem rather.

**Comment by ThomasWaldmann** [comment]
Currently writing `borg transfer`, so this is on the radar again.

- It is clear that we want the chunk list in every hard linked regular file item.
- HLID: I think we want to have some "identity value" that establishes the relation between all items hardlinking to the same inode. To make it less confusing and maybe even save some memory/storage, this could be `HLID = H(hardlink_master_item.path)` (with H being some hash, e.g. XXH64 - we use same trick for the `files cache` key with the cryptographic id_hash). This not being a path makes it clear that the specific value is irrelevant - it just matters whether values are the same.
- The previous hardlink master item would be "unmastered" and just made to refer to HLID.  
- Previous hardlink slave items hardlinking to same hardlink_master would also refer to this HLID.
- Symmetry: So, in the end, all hardlinked items are of same quality, no master/slave any more. 
- This can be easily produced at `borg transfer` time (using code similar as we have elsewhere for hardlinks_master management).

For `extract` (and likely also `mount`), we still need some hardlinks management code as we otherwise would not know what to hard link to what else.

So, procedure for future extract:
```
hardlinks = {}  # HLID -> fs_path
for item in extraction_candidates:
    path = basedir + item.path
    if item.nlinks > 1:
        if item.hlid not in hardlinks:
            extract_to_fs(path, item.chunks)
            hardlinks[item.hlid] = path
        else:
            hardlink_in_fs(hardlinks[item.hlid], path)
```

**Comment by ThomasWaldmann** [comment]
@enkore @elho ^^^ can you review, please?

**Comment by enkore** [comment]
You can't use XXH64 for HLIDs because if I understand correctly hash collisions would be able to corrupt hardlinks. Why not use a simple counter while it's single-threaded anyway?

**Comment by ThomasWaldmann** [comment]
Hmm, yeah, guess you're right, the likelyhood of a collision is already too high.

Because it is persisted, i don't want to use the (changing) id hash.

So guess we just always throw it into sha256. It's just a few bytes and only for hardlinks, so speed does not matter.

**Comment by enkore** [comment]
We could just use a counter, right? `borg create` would then essentially do something like this:

```
hardlinks = {}  # (dev, ino) -> hlid
current_hlid = 0
for file in files:
  if st_nlink > 1:
    hlid = hardlinks.get((st_dev, st_ino))
    if hlid is None:
      hlid = current_hlid
      current_hlid += 1
      hardlinks[(st_dev, st_ino)] = hlid
     ...
```

**Comment by ThomasWaldmann** [comment]
yes, in borg create that would work.

in borg transfer, it would need to use the path instead of dev/ino (we do not have these in an incoming archive).

ok, guess i'll implement that. faster and less memory needs (and not that much bookkeeping required).

the nice thing about the hash-based method is that it requires no bookkeeping for create or transfer.

**Comment by elho** [comment]
Having some HLID sounds much better than an inode,dev pair that has no meaning to the archive and potentially neither the target filesystem.

Doing away with the arbitrary master selection is good, too. My first thought reading this issue was to maybe do away with its path altogether and generating the HLID as a cryptographic hash of the actual chunk-list.
So, on `create` any file that has a link count > 1 in the source fs gets the HLID attribute in the archive, while having an in memory cretae-time only cache mapping (inode,dev)->HLID to be able to skip chunking after first encounter. `check` would warn about HLIDs only used once, `recreate` with excludes/patterns would do away with the HLID attribute of a lone remaining file. A primitive `extract` could with a similar in-memory cache do the extract-first-encounter of HLID, hardlink further ones thing outlined above. `transfer` could also easily generate the HLID, chunkid changing operations (both `recreate` with different chunker params or `transfer` to new params/ID hash algorithms) would need to recalculate the HLID hash along with updating the chunk list.
A slightly modified approach would be to have a link flag and always calculate the HLID on the fly from the chunklist if that is encountered, with the in-memory caches it should not hamper performance too much (unless someone builds a huge hardlink farm of tiny files :wink:) and stores less redundant information in the archive.

With partial extractions, there few scenarios, one could be extracting only a few (e.g. accitentally deleted files) onto a filesystem that basically has all the other files as in the archive. While technically arguably somewhat naive, user expectation would be being able to restore the state of the filesystem prior to the accidental deletion. However, in case of e.g. 4 hardlinked files, deleting 2 and then extracting only those 2 from a borg archive, the primitive extraction would yield 2 pairs of 2 hard linked files with the same content using up twice the diskspace as before.
Thus, personally, I see room for a more clever extraction, that on a partial extracts still does go through all files in the archive, also adding their paths to the temporary cache if they have a HLID and either prints warnings (e.g. "File 'path1/foo' was a hardlink to 'path2/bar', 'path3/baz' and 'path4/qux' in the archive which have not been extracted and therefore not linked again.") making the user aware of the opportunity to manually re-link to, or even (with some option given) checks for the presence of the not-extracted fellow hardlinks in the target filesystem and links to them, if their content is identical to the extracted fellows.

**Comment by ThomasWaldmann** [comment]
@elho maybe you misunderstood @enkore - he only used (dev, inode) in memory, it does not get into the archive (the hlid there is the counter [his approach, or the hash, my approach]).

**Comment by ThomasWaldmann** [comment]
hlid as H(chunklist) does not work, because although a hardlink implies same hash, same hash does not imply a hardlink.

**Comment by elho** [comment]
> @elho maybe you misunderstood @enkore - he only used (dev, inode) in memory

I did understand enkore, but maybe misunderstood your comments from 2017 that this was menat to refer to. :slightly_smiling_face: 

> hlid as H(chunklist) does not work, because although a hardlink implies same hash, same hash does not imply a hardlink.

Right, this is the opposite use case, someone intentionally having multiple copies of the same file of which at least one has a link count > 1.

So, the counter based unique ID is the best idea, it seems.

**Comment by ThomasWaldmann** [comment]
When trying to adapt import-tar, i ran into a fundamental issue:

Sadly, standard tar formats do not have a `hardlink_master` flag nor do they have the `st_nlinks` in tarinfo.

Thus, at import-tar time, we do not know what could be a hardlink master. Only when a slave (LNK type) tar item links back (via linkname) to a master, then we would know. But in streaming mode, we neither can go back in the tar stream nor process the tar in 2 passes.

The only solution I did come up with was to create a mapping `path -> (hlid, chunklist)` for **all** items.
But that would only solve part of the problem: we also can't go back in the borg metadata stream. So how would we put same hlid onto all the hardlink items linking to same fs object?

With the hash approach, guess there is a weird, but working workaround:

```
hlid = item.hlid if 'hlid' in item else sha256(path)
```

That still requires the memory consuming mapping for all items (could be `hlid -> chunklist` then), but otherwise is at least doable.

With the counter, it could work via a mapping `path -> (counter, chunklist)` for all items (and likely consume even more memory), but a lot of counter values would not be used in the end (cosmetic).

**Comment by ThomasWaldmann** [comment]
And there's another issue:

We mostly cared for the chunkslist and the hardlinking, but what about all the metadata (xattrs, acls, ...)?

**Comment by ThomasWaldmann** [comment]
It always updates the `stat_simple_attrs` and `stat_ext_attrs`.
