### ISSUE TITLE
Change upgrade command to always explicitly specify what to do

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2356]
E.g. `borg upgrade --from-attic ...` and also add some checks that the path looks like an attic repo.

**Comment by ThomasWaldmann** [comment]
What other options except --from-attic would it have?

**Comment by dragetd** [comment]
Just a random idea:
If 'upgrade' was interpreted as 'import' it could be the interface for #176 and other code to import backup-date from something different than a plain filesystem.

**Comment by ThomasWaldmann** [comment]
Side note: the attic upgrade parts were removed in #6516.

**Comment by dragetd** [comment]
Since it fits here:

Out of curiosity: Who is responsible for closing no longer relevant issues, in a FOSS project? Always the issue author? Always one of the maintainers? Or both may do so?

**Comment by ThomasWaldmann** [comment]
Well, guess it doesn't help to discuss responsibilities:
 - most FOSS contributors work voluntarily and for free, so there is no obligation to do anything
 - also, many FOSS projects (including this one) are intended as a community effort, so basically any task can be picked up by anybody who is willing to do it and capable of (correctly) doing it.

That said, original ticket author or project maintainers shall close tickets that are solved or do not apply any more.

Anyone else guess is not capable to do so I guess, because github does not let them. But still anybody can write a comment "Close?" or so if they think it can be closed.

**Comment by ThomasWaldmann** [comment]
upgrade command was removed completely in borg2 branch.
