### ISSUE TITLE
list + info

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2365]
I need to get list of backups, "diff" size for each snapshot (at least for the last N snapshots) plus size of all repo.

I can do it now by `borg list ...` plus `borg info ...` for each line. This is not convenient at all. Are there any better solutions? 

To me looks logical to add columns "Original size", "Deduplicated size" to the output of `borg list` plus column "size of repo" (all lines equal for easy parsing the output by scripts). 

```
# borg -V
borg 1.0.10
```

**Comment by ThomasWaldmann** [comment]
What are you trying to achieve?

**Comment by knutov** [comment]
We are small hosting company and we are writing some scripts and web interface around borg to make it userfriendly to the customers.

So, for each repo I want to have table with this columns:

snapshot name, datetime (with timezone), size, deduplicated ("diff") size
plus the size of all repo. 

It will be much better to get this data in single run of borg. We do now several execs of borg list + borg info to get info for web interface and I think I would want to see described table even if I work in shell.

**Comment by ThomasWaldmann** [comment]
Well, do you realize that the "size of the unique chunks" (what you call diff size) is relative to the repo state (all other archives) and only of quite limited use, especially if it is not fresh, but for old archives?

**Comment by knutov** [comment]
Yes I do.

And I can do some analytics having this data (and I can store historical values outside repo) for example to calculate expected size for the future, order enough servers/disks etc.

**Comment by ThomasWaldmann** [comment]
See #1213, which is closely related.

**Comment by enkore** [comment]
- The new JSON-based API that I hope to stabilize for 1.1 ([docs here](http://borgbackup.readthedocs.io/en/latest/internals/frontends.html)) makes scripting easier. Since this is beta and *not* stable yet, changes can be made, so feedback would be very welcome.

- Also beta: "borg info" can list multiple archives in one go due to consistent --last/--first/--prefix implementation.

**Comment by reitzig** [comment]
Unfortunately, `borg info --first N` is nor very usable in scripting, nor very readable for humans.

Use case: Realized a huge folder was backed up that shouldn't have been, or shouldn't be large; uncertain since when. Want to run `borg list` and see sizes (either of the variants may be relevant) in one glance.
