### ISSUE TITLE
add timezone to datetime display format

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2368]
As for now, dates and times in all places, especially in `borg info` and `borg list` are in the local timezone. But borg can be used remote, and some service/scripts may be around borg, and there is json api in the next version, so it will be good to see time in the full format with the Z sign and timezone, at least as on option to the current behavior.

**Comment by ThomasWaldmann** [comment]
Well, I guess you could just use `TZ=UTC borg list ...`.

We don't display a timezone indication, but timestamps will be UTC then.

**Comment by knutov** [comment]
Yes, I understand I can use this hack and process timezone in my scripts, just thought it must be with timezone out of the box.

(unfortunately I can not write in python, only in perl, may be I will try to learn python later)

**Comment by wolfpackmars2** [comment]
Use PyTZ to implement time stamps?

**Comment by drzraf** [comment]
`--list-format` does not work when listing repos (only for files)
I had a script to check the last date a backup happened.
It relied upon `borg list repo` and failed because my awk+grep of `--short` format failed (format change), but mostly because `--list-format` isn't considered for repo listing, and secondly because it does not output usable timestamps (only formatted date).
I'd be happy to see this fixed one day.
