### ISSUE TITLE
FUSE may show confusing user/group names

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2377]
when a archive is created on host A (using the user/group id -> name mapping of A) and then that archive is FUSE mounted (borg mount) on host B (and B has a different mapping), then "wrong" user and group names show up (e.g. with `ls -l` within the mountpoint).

this is because borg mount just uses the archived uid and gid "as is" for the filesystem it emulates.

we could optionally do the following at `borg mount` time:
- do a archived_username -> uid, archived_groupname -> gid lookup
- if we get a result, use that uid (gid) - the username will then look correct in the mounted fs.
- if we do not get a result, ... (what then?)

**Comment by enkore** [comment]
(This happens with all unix-style file systems as far as I'm aware)

**Comment by dragetd** [comment]
Same issue for example with nfs v3. One sophisticated way would be to allow the user to specify a mapping of uids/gids. Anything unmapped could be mapped to 'nobody'.

Then again, is this really the scope of the backup software?

**Comment by enkore** [comment]
wontfix?

**Comment by ThomasWaldmann** [comment]
I see some correspondence to `borg extract` here, which offers 2 modes:
- `--numeric-owner` just extracts uid/gid as archived
- by default, it tries to map using user2uid and group2gid functions

**Comment by ThomasWaldmann** [comment]
Hmm, guess we need to push this to 1.2:
-`borg mount --numeric-ids` will behave as `borg mount` does currently (just use archived uids/gids)
- `borg mount` (default) will try to map archived usernames/groupnames  to local ids (via local name -> id lookup).

**Comment by martinvonwittich** [comment]
This change caught us badly by surprise today - we had mounted a `borg` backup on a backup server, and then used `rsync --numeric-ids` to copy that backup onto the destination server. The result was that all ownerships were garbled completely, because the backup server of course has different uid/gid mappings in `/etc/passwd` than the backed up filesystem. This used to work fine in `borg` < 1.2, and we hadn't noticed before that this behavior was changed. IMO it would've warranted a much bigger warning than just a notice in the full changelog.

We've already been bitten in the ass lots and lots of times in the past because people tend to forget the `--numeric-ids` option for `rsync` so easily, so I find it disappointing that `borg` followed this IMHO ill-advised default. Now there are two commands where people need to remember that they need `--numeric-ids` to not fuck up the restore completely :(

**Comment by ThomasWaldmann** [comment]
@martinvonwittich I'm sorry that you got into troubles by this.

But the reason this was done that way is to get borg internally consistent (extract vs. mount).
`borg extract` worked since longer like that already, we just now made `borg mount` to behave consistently with that.

For borg2 (which has a lot of changes), I'll keep a section with "incompatible changes" in the latest 2.0.x release changelog.
