### ISSUE TITLE
Possible documentation note

### ISSUE THREAD

**Issue by level323** [borgbackup/borg#2391]
While working on recovering data from a failing server (using borg) I was using borg to backup tarballs (that I created on-the-fly and piped to borg via stdin). I discovered that deduplication rate is MUCH better when compelling tar to ingest files in a repeatable order. It seems that tar's default behaviour does not ingest files in a repeatable order (this is quite clearly implied in the tar manpage). 

So, I just wanted to note that I used the `tar` argument `--sort=name` and achieved much (drastically) better deduplication on (run 2 onwards) for borg backups of tarballs.

So I was just noting this here in case the admins here thought it beneficial to add suggestions about this in the borg documentation.

I'm still neck-deep in the recovery job so create a PR myself at this stage. Could possibly do it once I complete this recovery job though....

**Comment by wolfpackmars2** [comment]
Just a serious question... what's the advantage to storing tarballs versus storing the files directly?

Storing the files directly seems to be the only way to create a fuse mount to browse the repository. Is there a performance or storage gain by storing tarballs?

**Comment by level323** [comment]
Having to sacrifice the benefits of `borg mount` is definitely a disadvantage of 'borging' tarballs. 

In this particular case I was recovering the root partition of a machine. Borg being quite new and under heavy development, I didn't want to take any chances with regard to borg accurately capturing and restoring file metadata (perms, ID's etc). So I 'borged' a tarball of the filesystem (in addition to 'borging' the filesystem directly - so in this case I can still actually `borg mount` if needed). I couldn't afford the time/expense of discovering some quirk or problem using borg to restore the contents of the root partition.

**Comment by wolfpackmars2** [comment]
Makes perfect sense - especially when careers may be on the line ;)

**Comment by ThomasWaldmann** [comment]
Well, guess this is rather something for a tar FAQ than borg FAQ.

Creating first a tar file has the following negative impact:
- file boundaries disappar, identical files are not necessarily creating same chunks, so dedup will be bad (with the mentioned trick, you will get some dedup because the stream will have longer identical parts - but only if the parts are big enough for the target chunk size)
- borg mount will show you tar files, not directly your data set files
- additional processing for taring at archive creation and extraction time
- depending on your tar version, you might lose some metadata borg could have handled

Creating a tar file first has the following positive impact:
- you could compress the tar stream, which might give better compression than borg's chunk compression. but in that case, you totally lose deduplication.
- if everything is one big tar stream, borg will usually cut target chunk size (and not create small chunks for small files), so borg's compression might be better.

So, overall, I do not think that can be recommended, thus we do not need a FAQ entry for it.
