### ISSUE TITLE
borg extract performance

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2407]
I read something from a user who was unhappy with borg extract performance, so I did a measurement myself:

```
# time borg extract ::tux-2017-04-09 mnt/rootfs/usr
Enter passphrase for key '...':

real    12m6.962s
user    0m1.809s
sys     4m40.288s

8.8G    mnt/rootfs/usr
481937 files

Throughput = 8.8GiB / 727s = 13MB/s (663 files/s)
ping n40l: ~3-5ms

HP MicroServer N40L encr. HDD ---> WiFi ---> Sony SVP13 encr. Laptop SSD

borg 1.0.11-pre-rc1
```

So, not super fast, but reasonably fast considering it was lots of small files, wifi connection, slow server, encrypted media, ...

borg is not (yet) multithreaded, so there is some time lost due to I/O wait.

Also, borg extract is maybe not as much optimized as borg create.

**Comment by ThomasWaldmann** [comment]
TODO: measure via WAN (higher latency, lower throughput)

**Comment by ThomasWaldmann** [comment]
https://wiki.linuxfoundation.org/networking/netem

**Comment by ThomasWaldmann** [comment]
I did the same stuff again, now with 100ms latency added and 10MByte/s max throughput and tuned network params:
```
#!/bin/sh

DEV="wlan0"

# increase network buffers for high bw*delay product:   
echo '1' > /proc/sys/net/ipv4/tcp_window_scaling
echo '16777216' > /proc/sys/net/core/rmem_max
echo '16777216' > /proc/sys/net/core/wmem_max
echo '4096 87380 16777216' > /proc/sys/net/ipv4/tcp_rmem
echo '4096 16384 16777216' > /proc/sys/net/ipv4/tcp_wmem

tc qdisc add dev $DEV root netem delay 100ms loss 0% rate 10MBps

# Remove the rate control/delay
#tc qdisc del dev $DEV root

# To see what is configured on an interface, do this
#tc -s qdisc ls dev $DEV
```

```
# time borg extract ::tux-2017-04-09 mnt/rootfs/usr
Enter passphrase for key '...': 
   
real	20m34.955s
user	0m2.253s
sys	5m22.286s
```

So, there is some limited impact of high latency.

**Comment by ThomasWaldmann** [comment]
BTW, I had to tune the network params because otherwise my network stopped working.

**Comment by ThomasWaldmann** [comment]
Now with 300ms latency:
```
# time borg extract ::tux-2017-04-09 mnt/rootfs/usr
Enter passphrase for key '...': 

real	24m24.134s
user	0m2.282s
sys	5m28.953s
```

**Comment by enkore** [comment]
https://github.com/borgbackup/borg/issues/176#issuecomment-282591946 and follow-up

**Comment by Mathiasdm** [comment]
I have a use case for which I noticed borg is currently too slow (I hope I'm correct in commenting on this ticket, let me know if I should move it to another ticket).

Our company has a build system in which a component changes often and needs to be rebuilt often (even though most software developers don't interact with the component). Unfortunately, it takes a lot of time to build this component.

I'd like to be able to, instead of having each user build the component if it changes, build it once and let other users download and extract it. If the user pulls a new version of our source code (with a reference to another version of the component), a new version of the component should be (as part of the build system) downloaded and extracted.

The component consists of ~200 000 files and 5 GB, so there's a speed/size trade-off.
Comparing tar and borg (purely on the same machine so far):

- Using tar results in a much larger backup (every version of the component results in ~5 GB size, while an additional borg archive is at least 10 times smaller).
- Using tar on a machine with a spinning disk takes ~7 minutes (versus ~25 minutes for borg). I still need to do the comparison for an SSD.

I know borg does more (for example the deduplication), but I think it would be interesting to have an option that does not run 'delete and recreate' on every file. For example, one useful possibility could be to check if timestamps have changed since the previous extraction (and only consider those files + the files that are different between the previous and the current extraction as relevant).

I think this matches partially with performance (mentioned in this issue) and with issue #1986. If you prefer, I can also open a new issue.

**Comment by enkore** [comment]
Try 1.1.0rc1, for spinning disks it is usually _much_ faster with small files than 1.0.

Apart from this, it sounds more like a use case for [casync](https://github.com/systemd/casync) which is meant to distribute deduplicated snapshots of things.

**Comment by Mathiasdm** [comment]
(Just as an aside, using 'borgbackup mount' instead of 'extract' appears to solve our problem. I also tried out casync, but its performance doesn't seem to be that good yet.)

**Comment by skorokithakis** [comment]
For me, Borg is slow to the point of being broken. I've been waiting for a few files to be extracted for many minutes now, and Borg doesn't seem to be responding. The files are less than 10 MB and I'm on a 60 Mbit connection. I don't know what's wrong, trying to run `ls` in a mount even freezes.

**Comment by ThomasWaldmann** [comment]
@skorokithakis can you give the command sequence you used?

for a mounted repository (with each archive being represented as a sub directory), the first operation that lists some archive directory (or accesses some item in there) causes demand-loading of that archive and building of the respective fuse fs structure in memory. If the archive is big / remote, this can take a while.

**Comment by skorokithakis** [comment]
Ah, I see. Any command I used was super slow, I tried to extract a directory (it finished ten minutes later with "nothing matched"), to list files (it took too long and I killed it), mounting and `ls`ing took for ever.

The extraction command was `borg extract username@host::archive /my/path`.

**Comment by ThomasWaldmann** [comment]
The problem with your extract command is likely that leading "/". If you do a `borg list repo::archive`, you see that borg removes all leading slashes (similar as tar does).

If you know precisely what you want, borg extract is usually faster (and better, as it can deal with acls/xattrs/bsdflags). Using the FUSE fs is slower as it has more overhead.

**Comment by skorokithakis** [comment]
I think I tried again without the slash, but took a similarly long amount of time. I will try again and see, thank you.

**Comment by ThomasWaldmann** [comment]
"to list files (it took too long and I killed it)"

hmm, that is strange, `borg list` should start with output rather quickly. Are you using 1.0.x and did you forget `-v` maybe?

**Comment by skorokithakis** [comment]
I am using 1.1.6, I added the `-v` now and tried a `borg list`, but it's been six minutes with no output. The remote repo is on rsync.net.

**Comment by ThomasWaldmann** [comment]
@skorokithakis Which borg version on the remote side are you calling? I remember "borg" being 0.x, borg1 being 1.x (not sure how it is right now).

**Comment by skorokithakis** [comment]
rsync.net use borg 0.29.0, which is, admittedly, ancient.

**Comment by ThomasWaldmann** [comment]
try `borg --remote-path=borg1 ...`.

**Comment by skorokithakis** [comment]
Oh, sorry, that's what you meant.  Yes, that seems to work much better, thank you!

**Comment by ThomasWaldmann** [comment]
Maybe also related (for some borg versions?): #5202

**Comment by ThomasWaldmann** [comment]
Quite old / outdated, closing.
