### ISSUE TITLE
support json-lines output for stream-processing of list

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#2439]
http://jsonlines.org/ is a format for streaming json values as lines in a stream,

to me it seems that could be vastly useful to handle list outputs in a streamed manner (given that there are no stream style json parser, but `for value in map(json.loads, fp)` is pretty easy to use/handle

**Comment by enkore** [comment]
There are streaming JSON parsers for most languages available (e.g. yajl, gson, ...).

**Comment by RonnyPfannschmidt** [comment]
@enkore have you surveyed any of those for ease of use, at least the python ones i tried are not something i would want to program with

**Comment by enkore** [comment]
I used yajl in C which is quite alright. For i3pystatus I [rolled my own](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/core/io.py#L146).

I totally see your point about ease of use here and there is also a semantic difference between having a large `{}` with everything in it vs. an explicit stream (in the former case there is the theoretical possibility of keys appearing twice ; probably the reason why the default interface in JSON is serdes, not events/streaming).

`{}` and the standard JSON parsers kind-of suggest loading into memory is okay. An explicit streamed format does not. On the other hand a streamed format means a bit of special-casing due to some additional metadata. I.e. First `{}` is the metadata (repository info etc.), following `{}`s are items.

Ok.

---

**Task:** Make the _file_ listing output of `borg list --json` conform to a JSONlines-style output (and update the docs). The first object should have the metadata that is output now, the following objects are the files.

**Comment by RonnyPfannschmidt** [comment]
@enkore note that i would strongly suggest to keep json output and json-lines output separate including the flags,

one is about getting output that is a json document, the other is a stream of one json document per line

**Comment by enkore** [comment]
I disagree: JSON lines makes sense for large list-documents and while JSON can do the same, the difference is minor semantics and more importantly external support. Providing both for the same output thus has no advantage.

**Comment by RonnyPfannschmidt** [comment]
@enkore you dont have to provide the same, im just opposed to providing the formats under the same name

**Comment by enkore** [comment]
`--json-list`?

**Comment by enkore** [comment]
> **Discuss:** Drop the metadata that is usually output in this case?

Special-casing the first item is kinda ugly. So, don't do it?
