### ISSUE TITLE
Deprecate re: patterns?

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2459]
Since the addition of sh: there isn't really much point in having regexes, most other tools don't support them for similar purposes, either.

Deprecate for 1.1, decide removal later (earliest 1.2)?

**Comment by ThomasWaldmann** [comment]
regex is still way more powerful. also, do we gain much by removing it?

**Comment by enkore** [comment]
Deprecating but not removing something is a clear way of saying "Uhm, sure you want to use *that*? Maybe think again if you can't use the other, *shinier* alternatives?"

**Comment by johnnybubonic** [comment]
either i'm misunderstanding what you're actually requesting or you misunderstand regexes, because:

1. as @ThomasWaldmann hinted at, they are infinitely more powerful. they do things that simply are impossible in normal shell globbing/patterning.
2. what is so hard about clicking on the link directly to the documentation for the re module?
3. regexes are probably "underdocumented" because there documented elsewhere. extensively. the only differences between regex engines is features supported (mentioned in python's re documentation) and syntax (mentioned in pythons re documentation).

as to the speed problems mentioned in #1167 i'd imagine they could be alleviated by searching the file beforehand and pre-compiling all items specifying a regex into a list of [re.compile](https://docs.python.org/3/library/re.html#re-objects) objects.

**Comment by enkore** [comment]
Yes, you do misunderstand.

1.) -> Not the question here. The question is, does that matter? Is context-sensitive matching of paths something needed? Also see the title of this ticket and reply#2. This is about deprecation. Deprecation and removal are two separate things.

2.) -> The "re" docs are not that great.

3.) -> You are correct but again missing the point. _"can't really be replicated using another engine (i.e. something other than sre)"_

> as to the speed problems mentioned in #1167 i'd imagine they could be alleviated by searching the file beforehand and pre-compiling all items specifying a regex into a list of re.compile objects.

This is the current implementation, which produces the expected result (linear w.r.t. number of patterns, o(n*m) for n patterns and m files).

**Comment by enkore** [comment]
Anyhow, I don't care to have another discussion about bikesheds.
