### ISSUE TITLE
follow_symlinks unavailable on this platform

### ISSUE THREAD

**Issue by goerz** [borgbackup/borg#2507]
Restoring any data with (`borg` installed in anaconda via `pip`) results in a crash:

    [...]
    Local Exception.
    Traceback (most recent call last):
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archiver.py", line 2089, in main
        exit_code = archiver.run(args)
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archiver.py", line 2025, in run
        return func(args)
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archiver.py", line 91, in wrapper
        return method(self, args, repository=repository, **kwargs)
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archiver.py", line 101, in wrapper
        return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archiver.py", line 477, in do_extract
        archive.extract_item(item, stdout=stdout, sparse=sparse)
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archive.py", line 452, in extract_item
        raise Exception('Unknown archive item type %r' % item[b'mode'])
    File "/opt/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archive.py", line 79, in backup_io
        yield
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archive.py", line 442, in extract_item
        self.restore_attrs(path, item, symlink=True)
    File "/opt/anaconda/lib/python3.5/site-packages/borg/archive.py", line 489, in restore_attrs
        os.utime(path, None, ns=(atime, mtime), follow_symlinks=False)
    NotImplementedError: utime: follow_symlinks unavailable on this platform

    Platform: Linux webserver 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64
    Linux: debian jessie/sid
    Borg: 1.0.10  Python: CPython 3.5.1
    PID: 4083  CWD: /root/restore
    sys.argv: ['/opt/anaconda/bin/borg', 'extract', 'goerz@backupserver:borg_backup::blub', 'root']
    SSH_ORIGINAL_COMMAND: None

**Comment by goerz** [comment]
It works using the standalone 1.1.0 beta5 binary

**Comment by enkore** [comment]
Probably a missing/incorrect configure flag for the Anaconda build - workaround: Try the distribution's Python.

Also, bug in borg.

**Comment by ThomasWaldmann** [comment]
From python docs:

"""You can check whether or not follow_symlinks is supported on your platform using os.supports_follow_symlinks. If it is unavailable, using it will raise a NotImplementedError."""

**Comment by goerz** [comment]
Interestingly, the system Python 3.5 has the feature for `utime`:

    root@webserver:~> /usr/bin/python3
    Python 3.5.2 (default, Nov 17 2016, 17:05:23)
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.supports_follow_symlinks
    {<built-in function chown>, <built-in function stat>, <built-in function access>, <built-in function link>, <built-in function utime>}

while Anaconda does not:

    root@webserver:~> /opt/anaconda/bin/python
    Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01)
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.supports_follow_symlinks
    {<built-in function access>, <built-in function stat>, <built-in function link>, <built-in function chown>}

Do you think this is something that should be reported to Anaconda as a bug? In any case, `borg` should handle this gracefully, instead of crashing.

**Comment by ThomasWaldmann** [comment]
Checking if this is a python 3.5.1 issue in general...

**Comment by ThomasWaldmann** [comment]
OK, so the situation is that if you have a very old (g)libc (or your python was compiled on/for a system with such old glibc), the calls that implement the follow_symlinks=False variant are not present in the library and thus Python can't support it.

borg usually needs that variant (to get or set attributes on a fs object, even if it is a symlink - we do not want to follow symlinks usually), so we are getting into a situation where correct operation is not directly possible.

Options:
- not handling the exception, documenting we need a non-stoneage python/glibc.
- implementing helpers that wrap all such calls in exception handlers, catch exception, check fs object type (if it is not a symlink we can issue the call again without follow_symlinks=False, otherwise emit warning that correct operation is unsupported and we are doing the best we can considering that)

The latter is quite a bit of effort just to support crappy systems and in case of symlinks, we can't really do the correct thing. So we can either do nothing (set operation) or query the wrong data (get operation, following symlinks to another fs object).

**Comment by enkore** [comment]
The first option seems good to me, given that this is the first report ever mentioning this. For 1.1 we can add it to the self-tests.

**Comment by goerz** [comment]
Maybe a good solution would be to catch the exception at a very high level (in `archiver.py`), and print an error message explaining what might be the problem, and maybe recommending to e.g. use the standalone binary as a workaround.

**Comment by ThomasWaldmann** [comment]
@goerz see #2528 (not really tested yet on such a old system/python).
