### ISSUE TITLE
1.1.0rc1, rc2, rc3, rc4 feedback ticket

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2755]
if you tested a 1.1.0 release candidate and you found some bug or issue, please file a separate issue from this.

if you tested it and everything worked, please write a comment below, stating:
- borg version
- what you tested
- scale of your tests
- fresh repository or existing 1.0 or 1.1 rc repository

**Comment by rugk** [comment]
Except for these two issues:
* https://github.com/borgbackup/borg/issues/2831
* https://github.com/borgbackup/borg/issues/2833

I tested the new version a bit and everything seems to work. You can see what I've tested in the new screencasts I made in https://github.com/borgbackup/borg/pull/2835. So testing was just a side effect here. :smile:

**Comment by lfam** [comment]
I'm using 1.1.0rc1 for the client and server.

Since 1.1.0rc1 was released, I've been using my normal scheduled backup script, which uses LZMA compression, keyfile-based encryption, and custom chunker parameters. I've restored a few times as needed.

The repo is a COW copy of a 1.0.11 repo that is a ~150 gigabytes in size.

**Comment by cwygerde** [comment]
I have tested and found the following issue:

#2923

**Comment by knutov** [comment]
#2963 

can't create new snapshot.

**Comment by jdchristensen** [comment]
I tested the borg 1.1.0rc3 pre-built binary on Ubuntu 16.04.  I used it to do my usual system backups into a repo that has been written to many times with earlier borg versions, most recently 1.1.0b4.  This also involved a cache rebuild.  Now chunks.archive.d is ~40% smaller than it was before, and the rebuild was faster.  I also tested `borg list` and `borg prune`.

**Comment by rugk** [comment]
https://github.com/borgbackup/borg/issues/3050

**Comment by magma1447** [comment]
Just upgraded to rc4 (from b4) and found a new issue with one of my servers.

> Remote: OpenSSL version mismatch. Built against 1000207f, you have 1000114f
> Connection closed by remote host. Is borg working on the server?
> 

I have not yet investigated it further. I will walk through all my other servers first to see that they work.

**Comment by ThomasWaldmann** [comment]
You have rc4 on both sides, client and server?
You use the single-file pyinstaller-made binary?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by magma1447** [comment]
rc4 in both ends, the binary is https://github.com/borgbackup/borg/releases/download/1.1.0rc4/borg-linux64

I am currently upgrading the client server. It's an Amazon AWS instance that I rarely use, running Ubuntu Xenial. It had quite a few packages that were out of date. But since the instance is a "micro", it's taking forever to upgrade it.

SSH from the same server to the target server went without issues.

Been testing ~10 other servers without issues this far. Once I am through with all others I will go back to the amazon instance again to see if I can figure anything out. For example I will try b4<->b4 again, to make sure it's a new issue.

**Comment by ThomasWaldmann** [comment]
Issue looks familiar.

Likely a bad env when creating the ssh subprocess. I recently did a change there...
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by magma1447** [comment]
Downgrading the client to b4 helped, left the server at rc4. I will pause my investigation there.

**Comment by ThomasWaldmann** [comment]
Found the bug, my assumption that the else-branch is only for ancient pyinstaller was wrong, it is also needed for the pyi version we use for the case when LD_LIBRARY_PATH is not in the env. You can work around by setting LD_LIBRARY_PATH=/doesntexist.

**Comment by funkyfuture** [comment]
- upgraded from 1.1.b4 to 1.1.rc4
- using an existing repo (mounted, no ssh involved)
- tested `create`, `prune`, `list`, `mount`

**Comment by ThomasWaldmann** [comment]
PSA: if you have found something not working that should be fixed in 1.1.0, speak up now. :)

**Comment by ThomasWaldmann** [comment]
1.1.0 being released now, closing the rc feedback ticket.

**Comment by ThomasWaldmann** [comment]
Thanks to everybody who helped testing the Betas/RCs!
