### ISSUE TITLE
Borg backup with Cronjob

### ISSUE THREAD

**Issue by HerleX** [borgbackup/borg#2865]
Hey there,

i wrote a small script which is backing up important folders of my server to another server with this command:

`borg create -v --remote-path /usr/local/bin/borg --stats\
    $REPOSITORY::'{now:%Y-%m-%d_%H:%M}'                 \
    /etc/folder                                        \
    /var/folder                                                \
    folder
`

This is perfectly working when starting the script manually as root user.
Unfortunately when adding a cronjob to start the script the remote-borg-command is not found.

> backup.sh: line 40: borg: command not found

What did i miss here?

**Comment by ThomasWaldmann** [comment]
i think it rather means it does not find the local borg, check your PATH.

**Comment by rugk** [comment]
How did you install borg?

**Comment by HerleX** [comment]
I now changed the command from
`borg create`
to
`/usr/local/bin/borg create`

and it is now working...
But still strange. Thanks for your fast reply.

@rugk I installed it on my Debian via 

> apt install borgbackup

**Comment by rugk** [comment]
Strange, I noticed that root often does not read from `/usr/local/bin`, but only `/bin`/`/usr/bin`, but in this case also manually executing it via root should not work.

Are you really sure you used `apt install borgbackup`?

Because I just looked into the AMD64 package of Borg from Debian Stretch and [it uses](https://packages.debian.org/stretch/amd64/borgbackup) (as supposed to be) `/usr/bin` as the path where to install the borg binary.
And this is also the correct path. `/usr/local/bin/` should only be used for unofficial/custom binaries installed by the user and that's why this is also suggested in the borg docs for the static binary.
BTW it is possible to install borg in parallel, one time using the static binary and one time your package manager.

What happens when you execute `which borg` from a non-root and a root shell?

**Comment by HerleX** [comment]
There has been a little brain-mix by me...

I used to install it via `apt install borgbackup`. But i changed it some time ago, because:

I am also using Borg on a Synology Diskstation. To be sure that i am using the same version on both systems, i installed it manually on both systems to `/usr/local/bin`

Nevermind, i will use the full path to borg to use it.
I appreciate your help. Again learned something. Thank you,
