### ISSUE TITLE
drop python 3.4 for 1.2

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2891]
considering 1.2 development will take a while and old distros won't package it anyway, we could consider dropping python 3.4 support and testing.

that would speed up CI (2 tests runs less, one for linux, one for os x) and also local testing (with/without vagrant).

the binaries are currently made with 3.5.x, so no problem for that either.

**Comment by enkore** [comment]
Seems reasonable to me.

**Comment by ThomasWaldmann** [comment]
interesting new stuff in 3.5+, from https://docs.python.org/3/whatsnew/3.5.html

- typing module https://docs.python.org/3/library/typing.html
- os.scandir (we could remove fallback to scandir module)
- better EINTR handling
- *.pyo is gone
- circular imports involving relative imports are now supported
- contextlib.redirect_stderror (and ..._stdout)
- LZMADecompressor.decompress() method now accepts an optional max_length
- os.get_blocking / set_blocking
- os.path.commonpath
- re.error exceptions have new attributes, msg, pattern, pos, lineno, and colno
- subprocess.run
- time.monotonic now always available
- Mock unsafe=False, yay

**Comment by FelixSchwarz** [comment]
The only negative about requiring Python 3.5 for me is that Fedora EPEL 7 (CentOS+RHEL) currently only ships Python 3.4. According to https://docs.python.org/devguide/#status-of-python-branches Python 3.4 has an EOL in 2019 so I guess we will not see an updated Python 3 for EPEL 7 "soon". Anyway probably not too important if borgbackup 1.1 is maintained for some time.

**Comment by ThomasWaldmann** [comment]
Well, I guess borg 1.2 would not get into epel7 anyway, would it?

We have quite big changes there (multithreading+crypto), so that will take a while (1y?) until that reaches release.

Users can always just use the binary we release (which bundles a python).

Yes, 1.1 (and 1.0) will be maintained for a while.

**Comment by FelixSchwarz** [comment]
> Well, I guess borg 1.2 would not get into epel7 anyway, would it?

Theoretically EPEL has pretty strong policy in favor of version stability. In practice volunteers were often unable to match RHEL's 10 year support cycle due to various reasons (including a lack of rigorous vetting before including something in EPEL). So many packages in EPEL get version upgrades (including potentially incompatible ones), e.g. Exim was upgraded to the latest released version in EPEL6+7.

Anyhow if borg 1.1 is maintained for some time after its release I guess this will be fine. We should have RHEL 8 in 1-2 years (I hope)...
