### ISSUE TITLE
OS X: create vagrant VM for borg 1.2 testing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2896]
The current master branch Vagrantfile misses such a VM, see 1.1-maint branch for such a VM:

https://github.com/borgbackup/borg/blob/1.1-maint/Vagrantfile

The VM needs to be updated to work with:
- OpenSSL 1.1
- Python 3.6

Some VMs are used to build a borg binary with pyinstaller: Linux, FreeBSD, OS X.

In the past we used a rather old system to get a old (g)libc, but for borg 1.2 the system should be a recent one that still gets security updates for quite some time. Also: 64bit only. People needing old stuff can just use borg 1.0/1.1 binaries.

**Comment by ThomasWaldmann** [comment]
The VM is there now, but likely still uses openssl 1.0.x.

**Comment by ThomasWaldmann** [comment]
Can some macOS user update me about the OpenSSL versions situation on macOS?

**Comment by Stunner** [comment]
Running `macOS High Sierra 10.13.6 (17G65)`:

```
$ /usr/bin/openssl 
OpenSSL> version
LibreSSL 2.2.7
OpenSSL> 
```
I have installed a newer version of OpenSSL via Homebrew (as `pip install` was misbehaving):
```
$ openssl 
OpenSSL> version
OpenSSL 1.0.2l  25 May 2017
OpenSSL> 
```

I have a VM running a beta version of macOS Mojave that I can check on later (on a different computer). I have older versions of macOS running on other machines that I can investigate if need be.

**Comment by ThomasWaldmann** [comment]
Hah, libressl from 2016...

Can you try whether openssl 1.1.x works for you also?

**Comment by ThomasWaldmann** [comment]
I was mostly wondering about how it is usually dealt with. So, e.g. if you install openssl 1.1 for borg (and borg actually uses that and does not get confused and picks another one) and the python you had installed before already uses openssl 1.0 (or libressl in openssl 1.0 compat mode), does this work or produce interesting conflicts?

**Comment by Stunner** [comment]
Oh interesting. Typically what the vast majority of macOS users do is update openssl via homebrew and then symlink that installation to `/usr/local/bin` as explained [here](https://apple.stackexchange.com/a/126832/50585). Homebrew doesn't currently have the latest stable version so I compiled and installed it manually.

I typically run borg while sshed into an always-on Synology NAS which is a much less forgiving environment than on macOS (uses `ash` instead of `bash` for starters)... But I'll try to test out borg with the latest stable version of openssl.

Anything special I need to do to ensure borg is using a specific version of openssl? I am installing the latest version of openssl to the recommended locations and have added it to the beginning of my PATH to ensure it gets picked up first... but some tips to help validate this, if any, would be appreciated.

**Comment by ThomasWaldmann** [comment]
There are some environment vars that `setup.py` can use to determine the header/lib location. Otherwise it will look at the usual places (and guess it'll the the first acceptable one, which is either openssl 1.0 or 1.1 currently).

If one wants something specific (for master, 1.1 is more interesting), guess it is better to set the env var, see docs.

**Comment by ThomasWaldmann** [comment]
I am experimenting with macOS Sierra (10.12.6):
- I installed openssl@1.1 from brew and set the C(PP)FLAGS/LDFLAGS as recommended.
- pyenv still builds Python with openssl 1.0.2o (not 1.1.1) - why?

**Comment by ThomasWaldmann** [comment]
Got a step further (added the special path for openssl@1.1 to setup.py), but get:
```
ImportError: dlopen(/vagrant/borg/borg/src/borg/crypto/low_level.cpython-36m-darwin.so, 2): Symbol not found: _EVP_aes_256_ocb
```
That's strange because ocb should be there in openssl 1.1.1.

**Comment by ThomasWaldmann** [comment]
https://github.com/pyenv/pyenv/issues/839

**Comment by ThomasWaldmann** [comment]
Above PR is merged, so should work in master.

Not sure if we use master or some release on the vagrant machine...

**Comment by ThomasWaldmann** [comment]
VM now builds python and borg with openssl 1.1. \o/
