### ISSUE TITLE
invalid choice: 'umount'

### ISSUE THREAD

**Issue by reinierkors** [borgbackup/borg#2938]
The documentation (https://borgbackup.readthedocs.io/en/stable/usage.html#borg-umount) says to use `borg umount` to unmount a borg repo.

However when using the command, it doesn't exist:
`
borg: error: argument <command>: invalid choice: 'umount' (choose from 'serve', 'init', 'check', 'change-passphrase', 'migrate-to-repokey', 'create', 'extract', 'rename', 'delete', 'list', 'mount', 'info', 'break-lock', 'prune', 'upgrade', 'help', 'debug-info', 'debug-dump-archive-items', 'debug-dump-repo-objs', 'debug-get-obj', 'debug-put-obj', 'debug-delete-obj')
`

Instead, I could use `umount repo`.

**Comment by ThomasWaldmann** [comment]
borg umount is a rather recent addition, it is not there if you use an older borg 1.0.x release.

at the docs site, there is a version selector at the bottom left.
if you do not use latest stable, select your version there to get matching docs.

use `fusermount -u mountpoint` if you are on linux, otherwise `umount mountpoint`.
