### ISSUE TITLE
Backport security dir to 1.0?

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2954]
Perhaps after 1.1.0?

**Comment by ThomasWaldmann** [comment]
Not sure if it is worth the effort, long term this will be solved by users upgrading to 1.1.

But due to stable / LTS dists, this will take a while. OTOH, depending on the maintainer / dist policy, stable / LTS dists might not take a newer version with added features anyway.

@enkore if you think it should be done nevertheless: would a bounty help here?

**Comment by ThomasWaldmann** [comment]
As nobody stepped up actually doing this and 1.1.x is stable since quite long, this can be solved by people just upgrading to 1.1.x.
