### ISSUE TITLE
Change timestamp for existing archive

### ISSUE THREAD

**Issue by MK-42** [borgbackup/borg#2961]
I imported some old rsnapshot-backups into borg using borg-import (what worked really well - only with minor tweaks to the script due to my requirements on naming the resulting archives).
Because I moved the snapshot-dir to a different location earlier in time they had a wrong mtime, that is not reflecting the actual backup time. The resulting borg-archives now have wrong timestamps set due to that.

Is there a possibility to change the timestamp of an archive in 1.0.11? I saw recreate in master, but that is not availiable for me atm.
I think I cloud also import the archives again and modify borg-import to get the timestamp elsewhere - but would like to save those hours.

**Comment by ThomasWaldmann** [comment]
We have no quick/easy way yet to change the archive metadata (and esp. the timestamps).

Updating the start time in the manifest would be easy, but it also needs updating in the archive itself (plus the end time, so the duration stays correct).

**Comment by MK-42** [comment]
Thats sad. But I just figured out that the mtimes of those archives are scrambled anyway, so i have no reliable way to determine when those snapshots were taken in the original place, so i will stick with those stamps for now.
Thanks for this insane tool, keep up the good work!

**Comment by kosli** [comment]
@ThomasWaldmann I found that issue here as I am looking into the same option -> I would migrate some old backups from an unencrypted borg repo and would like to keep the timestamp of the archive -> Because I wanna apply the prune function to the archives. 
I assume your answer from above is still the same? ;-) No easy way to change the metadata. What would be the easiest way to achieve that, e.g. by using some "borg library functions" to modify the metadata of an existing archive in an encrypted repo?

**Comment by ThomasWaldmann** [comment]
@kosli in your case, just use `borg create --timestamp=... repo::archive`.

**Comment by kosli** [comment]
@ThomasWaldmann  OMG, thank you!! I've never seen that parameter. Life can be so easy ;-)

**Comment by jensb** [comment]
I'd love to have an `borg edit-timestamp <archive_name>` option of some sorts. I just imported three years of old Time Machine backups into my Borg repo, and of course did not (in time) learn about --timestamp, and now the archive timestamps are only encoded in the archive names.

**Comment by ThomasWaldmann** [comment]
@jensb I see what you mean (but that doesn't exist yet).

But there's an alternative way for you: just reimport the stuff and do **not** delete the current archives before having finished.

Either rename the current archives (to move them "out of the way") or use slightly different new archive names.

Due to deduplication that might work much faster than your first run.

**Comment by jensb** [comment]
@ThomasWaldmann thanks. I tried (a), but despite having the same folders, mountpoints and files, it is rehashing the first archive completely now. Also there are ~40 archives to be re-backed up, each taking ~15-20minutes, so I had hoped to avoid this ... :-)
Regarding (b), does this need Borg 1.2.7 on the server or just on the client? I am using a docker image on a Synology NAS, and I cannot find a borgserver image on Docker which has 1.2.7, the best I could find is 1.2.6.

**Comment by ThomasWaldmann** [comment]
a) guess the ctime or inode number will trigger the rehash.

b) the warning is because careless use could lead to that. so be careful, use `--dry-run --list` at first and check if it does what you want. Then run it on one archive and check if the resulting archive contains what you want.

The bug fix i had in mind is on the client.

1.2.6 would be good enough and "nice to have" on the server, but not strictly required.

**Comment by ThomasWaldmann** [comment]
So, the first run would be:
```
borg recreate -v --dry-run --list --timestamp yyyy-mm-ddThh:mm:ss REPO::ARCHIVE
```

The timestamp needs to be in UTC timezone.
