### ISSUE TITLE
Restore a pruned archive from an append-only repo

### ISSUE THREAD

**Issue by pierreozoux** [borgbackup/borg#3000]
[Here](https://borgbackup.readthedocs.io/en/stable/usage.html#drawbacks) you can read:
```
As data is only appended, and nothing removed, commands like prune or delete won’t free disk space, they merely tag data as deleted in a new transaction.
```
So I know my data is stil there.
But how to restore it? :)
I searched everywhere without any luck.

Thanks for the help!

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/latest/usage/notes.html?highlight=transaction#append-only-mode

did you already read / try that?

**Comment by dimejo** [comment]
Sorry, but for me this link isn't very clear in that regard. Does that mean if I delete `hints.N` and `index.N` of that specific transaction I basically undo the prune command?

**Comment by pierreozoux** [comment]
I didn't read that, and actually, after reading I'm still a bit confused.
Could you detail a bit how to exactly undo one transaction in the middle of the transactions?
Is it possible, or should I undo all transactions, until the one I want?

Say I have this list of backups:

```
friday-0100
friday-0200
friday-0300
..
sunday-0100
sunday-0200
```

then I guess I have a transaction for each new backup.
And also a transaction for each prune.

so in term of transaction, I guess, something like that:
```
transaction 100 add saturday-0100
transaction 101 add saturday-0200
transaction 102 prune friday-0200
transaction 103 add saturday-0300
transaction 104 prune friday-0300
...
```

So the question would be how to get access to `friday-0200` without loosing `saturday-0300`. Is it possible? And if yes, how?

From what I read, it is not possible, and I'd have to do:
```
rm hints.104 (just one hints, is it normal?)
rm index.104 (same for index)
rm data/**/{102..104}
```

Is it correct?

And actually, one more question, how do I know which one is the `prune friday-0200`? From what I see, there are just UTC time.
(I think before playing, I'd make a backup of the backup, the proper command is `cp -al` from the document above.)

Thanks a lot for your precious help!
(I restored an earlier backup at the end, but still would like to understand for next time, and update the doc for other people like me :) )

**Comment by ThomasWaldmann** [comment]
It does not document how to remove one transaction in the middle and this is no supported scenario.

In an attack scenario (and this is what append-only was meant for), removing transactions in the middle does not make sense anyway - what you want then is rollback-to-pre-compromised state (== kill all transactions after compromise).

Removing 1 transaction in the middle is not easily possible. Even if the to-be-removed transaction would consist only of deleletes, a manifest write and a commit (and you know for sure that there was no data chunk added), the problem is that the following transactions still do not contain a manifest containing the archive you wanted back. Maybe you could completely kill the manifest and run borg check --repair to reconstruct it from all archives it discovers in the repo. But this is way beyond what we can support.

**Comment by pierreozoux** [comment]
Thanks a lot for the detailed answer!

**Comment by attapolk** [comment]
> Thanks a lot for the detailed answer!

Can you share how to restore it? :)
How to get those transactions log?
can you share example command? 
Thanks a lot!
