### ISSUE TITLE
use pipenv?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3055]
https://pipenv.readthedocs.io/en/latest/

**Comment by newtonne** [comment]
Not sure what this issue is referring to exactly, but thought I'd mention that I'm using pipenv in combination with borg, and it's working really well. The version locking allows for a consistent version of borg and its dependencies across my machines, while pipenv will also automatically read .env files, and allow you to define scripts in the Pipfile which can then be executed as:
```
pipenv run my_awesome_script
```
