### ISSUE TITLE
cygwin remote repos working now?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3174]
from irc user capi:

just tried doing backup from cygwin via ssh to a remote linux. this works fine now. website still says, that this is known to be not working.

**Comment by ThomasWaldmann** [comment]
iirc: the problems were in the tests and not all tests failed all the time - it was spurious failure.

**Comment by ThomasWaldmann** [comment]
I ran the tests 4 times, always only the issue as filed in #1340.
#2637 was first found on cygwin, but later has been seen elsewhere also - and that is fixed now.

So, guess we need just one more confirmation from somebody successfully practically using cygwin borg to a ssh: repo for a while.

**Comment by theChaosCoder** [comment]
I just tried borg via ssh and cygwin for the first time. It seems to work but only if I set the remote path for borg bin
`borg list --remote-path /usr/local/bin/borg  ssh://user@synology:22/volume1/Backups/BackupBorg`

Without it I get the same _Exception: FD exception occurred_ as in #2621

I noticed it only because in WSL (Windows Subsystem for Linux) I get this (correct) warning:

```
Remote: sh: borg: command not found
Connection closed by remote host. Is borg working on the server?
```
Could be a PATH issue on my nas via ssh...

Maybe this Info is helpfull for others

**Comment by ThomasWaldmann** [comment]
That's quite for sure a PATH issue. If you do not give --remote-path, it just invoked `borg` and if that can be found in the PATH, that'll work.
