### ISSUE TITLE
Cross-platform GUI for Borg Backup

### ISSUE THREAD

**Issue by EthraZa** [borgbackup/borg#3242]
Hi.

I'm just starting a personal project to create a full blow GUI Desktop App for Borg Backup, so we all can replace that think called Deja Dup, and I would love to know what you guys have to say about it.

Besides to learning more about Borg Backup, this project is also my very first project with Vue.js, something I'm expecting to learn for some time already, to replace my use of ExtJs in the future. So if you find some dumb mistake here, please be welcome to point it out and I'll gladly take a look at to improve it.

I expect to have something to show of in one or two months from now, It will depends more on the Vue.js learning curve. I'll at least commit the Changelog, with the task list, to let anyone interested to know how the project is doing.

Here is the repo with more information (and a very basic mockup):
[Borg Data Node](https://github.com/EthraZa/Borg-Data-Node)

**Comment by Abogical** [comment]
I think you should post this to borgbackup/community .

**Comment by theChaosCoder** [comment]
I had a similar idea (not started yet, also my first js-app) but with angularjs. The main focus in my gui is "just" browsing files and see what changed since the last backup (fancy diff).

Also all snapshots/repos lists are kept in cache so what you can browse all files without asking borg first.
And a calendar view similar to this http://www.bootstrap-year-calendar.com/ or this  https://stackoverflow.com/questions/15874716/d3-js-calendar-view-colours-custom-date for a better overview of my backups.

**Comment by rugk** [comment]
Note that there is already some work in https://github.com/borgbackup/borgweb.

**Comment by EthraZa** [comment]
Borg Web looks promising but it is a web admin tool. I'm going for a desktop application. 

It's taking shape already and right now I'm able see it listing my local repositories and the backups inside it. As soon as it become more usable, I'll release the first beta.

Anyways, it seems like 2018 will be a good year for Borg Backup.

**Comment by ThomasWaldmann** [comment]
There's vorta now, see link there: https://github.com/borgbackup/community
