### ISSUE TITLE
borg create: clarify duration

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#3301]
I found recently difference between duration reported by borg and linux utility `time`.

I run `time borg create --compression lz4 -svpx --show-rc `

and it shows:
```
Duration: 25.90 seconds
...
real    0m32.331s
user    0m18.926s
sys     0m2.254s
```

Another exmple:

```
Duration: 15.37 seconds
...
real    0m20.451s
user    0m10.623s
sys     0m1.566s
```

The difference is pretty big. Why it is so? 

Does borg count duration correct?

**Comment by ThomasWaldmann** [comment]
The problem is that Archive.save() (which writes start and end time to the archive metadata) has to commit the repo and the cache after doing that.

The repo commit also calls compact_segments internally, which might take quite a while. We have a ticket about separating compact_segments, which would also help for this.

The create stats output uses the same timing values, so at least borg info and borg create --stats should be consistent.

If you like, you could do a PR for the FAQ section to document why we see that difference.
