### ISSUE TITLE
Borg offsite replication

### ISSUE THREAD

**Issue by domacikolaci** [borgbackup/borg#3349]
Hi,

Im trying to wrap my head around using Borg with offsite replication. Ive currently got over 5TB worth of backups which are currently being copied over to a portable HDD for replication purposes, but as the servers are at a different site to me, i would ideally like all new incrementals done via the internet. How would i go about doing this? We have 4 repos currently. Do i just use rsync to copy/paste to a mounted location or is there an option directly in Borg itself?

Thanks!

**Comment by ThomasWaldmann** [comment]
http://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

**Comment by domacikolaci** [comment]
@ThomasWaldmann thanks for the response! I saw that artical earlier, but in that artical you are recommending i stop my backups for the replication, or create a new repo for my offsite? Is there no "replication" in Borg? Can i just an automated rsync of /destionation to /replicationDestination ?

Thanks!

**Comment by level323** [comment]
If you're considering running the remote repo as an independent repo (as per the second option mentioned in the link posted by @ThomasWaldmann above) and you want to pre-seed your remote repo (to avoid massive internet bandwidth consumption of initial runs directly to a fresh/empty remote repo), there is one very important point to keep in mind:

If your source repo is encrypted (that is, was created via `borg init` with a `-e` option specifying encryption) you cannot simply copy/clone the source repo filesystem onto the remote filesystem and expect to spin it up as your pre-seeded remote repo. This is not possible (and even dangerous) because the repo ID (which was determined at `init` time of the source repo) is used by borg to locate it's caches.  Therefore, if you access both the source and remote repos from any given machine borg will not be able to correctly manage local caches because both the source and remote repos have the same repo ID. Thankfully, borg includes some checks which will usually prevent this from corrupting data and prevent you from proceeding to try to use two repos with the same repo ID.

If your repos are unencrypted then this issue is easily resolved by manually changing the repo ID for the remote repo before first use. In contrast, this can't be done with encrypted repos because the repo ID is tied up in the repo encryption and there presently is no facility for changing it.

So if you are running encrypted repos a very important early step is to create the pre-seeded remote repo locally by:

- `borg init -e {encryption_type} /path/to/borg/repo/on/portable/hdd` a new (encrypted) repo - this will be your future remote repo
- Use `borg mount ...` to mount the source repo and `borg create ..` to re-create the archives on the new/future remote repo on the portable HDD, reading from the filesystem created by `borg mount`
- Take the portable HDD to your remote location
- Copy the repo file tree over onto the remote disks.
- From that point on, you can use `borg create ssh://remote.machine/path/to/remote/repo::my-new-archive my-files`

**Comment by domacikolaci** [comment]
@level323 thanks for that, so, my question now then would be, should i just simply then create a new repo for the offsite replication? Really was hoping to avoide all of this as I have 

A - Never used Borg before
B - Didnt do the original setup, ive just taken over this client and am making do with what ive got

Also, stupid question but ive been able to mount the repos without needing a password, i take it this means the previous guys didnt use encryption?

**Comment by level323** [comment]
@domacikolaci  Sounds like there is no encryption.

If you don't mind the bandwidth required by the first backup run to the new remote repo, then you're free to go that route and avoid the pre-seeding steps. Pre-seeding merely saves you the cost that would be incurred for internet traffic during the first backup run.

**Comment by domacikolaci** [comment]
@level323 Think ill go pre seeding, does it matter if the pre seed is a few days out? Borg will catch up correct?

**Comment by level323** [comment]
@domacikolaci Depends what you mean by "catch up".

The remote repository you create will be entirely independent of your local repository (or any others for that matter).

After getting your pre-seed repo setup and in place, your next `borg create` run will work as advertised - it will backup whatever you tell it to, but will naturally skip transferring chunks that already exist in the repo (to save you bandwidth) because that would be pointless.

**Comment by domacikolaci** [comment]
@level323 right, so i can just copy/paste all these repos to my "offsite" location, then create a connection, and then make a "new" `borg create` job to goto that location, and it will catchup from there? Sorry for all the questions, just never used Borg before :)

**Comment by level323** [comment]
@domacikolaci Yes, assuming you are able to make contact with and read/write the remote repo via a method that is supported by borg (most commonly, via `ssh`), then yes. The physical location of the hardware containing the repo is not an issue, as long as you can connect to it over a network.

**Comment by ThomasWaldmann** [comment]
Seems this is answered, closing.
