### ISSUE TITLE
osx: permissionerror in hardlink fuse mount tests

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3389]
```
    darwin64:     def test_mount_hardlinks(self):
    darwin64:         self._extract_hardlinks_setup()
    darwin64:         mountpoint = os.path.join(self.tmpdir, 'mountpoint')
    darwin64:         with self.fuse_mount(self.repository_location + '::test', mountpoint, '--strip-components=2'), \
    darwin64:              changedir(mountpoint):
    darwin64:             assert os.stat('hardlink').st_nlink == 2
    darwin64: >           assert os.stat('subdir/hardlink').st_nlink == 2
    darwin64: E           PermissionError: [Errno 13] Permission denied: 'subdir/hardlink'
    darwin64: .tox/py34/lib/python3.4/site-packages/borg/testsuite/archiver.py:787: PermissionError
```

**Comment by ThomasWaldmann** [comment]
likely related to fakeroot, could not reproduce without.

**Comment by mmerzba** [comment]
The initally reported error could be reproduced using following config:

- OS X 10.11.6
- FUSE for macOS 3.8.2
- python==3.6.3
- borgbackup==1.2.0


**Observations**
Running _fakeroot -u tox -e py36 -- -s borg.testsuite.archiver::ArchiverTestCase_
raises the PermissionError for _test_mount_hardlinks_ if other test cases of this class (ArchiverTestCase) are run before.

In this case the PermissionError is caused by the fact that 'subdir' is owned by root (permissions: "rwx"); groups and others have no permissions.

It seemed that calling _self.cmd_ in a previous test case influences the result of _test_mount_hardlinks_ 

**Note**
Running _tox -e py36 -- -s borg.testsuite.archiver::ArchiverTestCase_ was fine without any errors.

**Comment by ThomasWaldmann** [comment]
as these failures now also showed up on linux, after adding "default_permissions" to the enforced mount options, it became clear how to work around these issues caused by fakeroot: by ignoring permissions.

**Comment by ThomasWaldmann** [comment]
fixed.
