### ISSUE TITLE
borg mount path via fstab

### ISSUE THREAD

**Issue by MrEgenius** [borgbackup/borg#3402]
Hi!

In last borg version 1.1.3 mount path feauture was added.
How can I use this feauture in fstab config or how I can mount repo to use it with samba ?
I can access mount point via samba when I mount repo with fstab options "user", but when I mount it from console I can't get access to share in samba.

Thank you.

**Comment by mgrachten** [comment]
Mounting through `/etc/fstab` is described in the [documentation](http://borgbackup.readthedocs.io/en/stable/usage/mount.html), but for me mounting as a regular user with the `user` mount option does not work due to a permission error. See [issue 3395](https://github.com/borgbackup/borg/issues/3395).

**Comment by ThomasWaldmann** [comment]
@MrEgenius guess there is no way to give parameters (like exclusion options or path args) via fstab.

If you can describe a popular use case for this, open an issue describing it. I somehow thought exclusion options and paths would be rather used dynamically/interactively, not in a rather static way by putting such stuff into fstab.

About the other issue, see the one @mgrachten linked or open a separate one if that does not match.

(only one issue per ticket, don't mix different topics into 1 ticket)

**Comment by MrEgenius** [comment]
I just whant to give access to backups to other users via samba.
How can I do it ?

**Comment by ThomasWaldmann** [comment]
Didn't try that yet, but sounds like a nice way to give users access to their backed up files (if it works).

Just be careful that user and group name-to-id mapping on the system that does the mount and also in samba corresponds to the uids/gids in the backups. Otherwise there will be permission and security issues.
