### ISSUE TITLE
borg crashes with two differente users for the same repo

### ISSUE THREAD

**Issue by mahikeulbody** [borgbackup/borg#3403]
I create archives named {hostname}-{user}-home-{date} into a repo R as user michel.

By mistake, I created (with the same parameters) an archive into R **as user root**. Then, when I tried to create into R as user michel again, Borg crashed (please to see log file attached). I understand it is a permission problem but may be Borg should to handle the error.

Thanks for this great software !

(sorry for my poor english)
[use-case.log](https://github.com/borgbackup/borg/files/1521851/use-case.log)

**Comment by ThomasWaldmann** [comment]
That is the usual permission mixup you get when you work on same data with different users.

This is not specific to borg and one of the usual issues system administrators have to work around / avoid somehow.

E.g. by always using the same user to access the borg repo. When working remotely, this comes quite naturally because you always use same (ssh) user to log in to the borg server. You can also work locally using that method, like borguser@localhost.

Likely you also need a `chown -R borguser.borggroup repo_dir` now.

**Comment by mahikeulbody** [comment]
I though that borg could check it is the same user as `borg init `'user in order to exit more "cleanly".

> Likely you also need a chown -R borguser.borggroup repo_dir now.

Indeed  !

Thanks for the suggestions.

**Comment by ThomasWaldmann** [comment]
It would have to check if it can open/read ALL the segment files (if admins switch the user id they use for borg runs, some files could be ok, some not) - this is expensive, thus won't get implemented.
