### ISSUE TITLE
use better defaults

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#343]
some default values are less than great:

- chunker-params currently default to 64kiB chunks (like attic) and thus creates vast amounts of chunks, huge index files, huge memory needs, quite some time for transaction processing. should be 19,23,21,4095 to create 2MiB chunks.

**Comment by level323** [comment]
I agree with changing the default chunker params as you described.

**Comment by rumpelsepp** [comment]
> should be 19,23,21,4095 to create 2MiB chunks.

Is that a breaking change?

**Comment by ThomasWaldmann** [comment]
@rumpelsepp no, it doesn't break existing repos.

But: it won't be very effective with deduplication. If a file is touched (e.g. just timestamp) and considered by borg for chunking and deduplication, the now bigger chunks will never match any of the smaller chunks that are already in the repo, so all chunks will be stored again. Depending on your prune policy, it can take a long time until all old archives with references to the smaller chunks are gone.

**Comment by ThomasWaldmann** [comment]
another thing we could consider is switching to encrypted-by-default (with repokey method and unencrypted or other key method as an option). this is mostly to have a secure / privacy-enabled storage by default and not to default to less secure unencrypted mode.

**Comment by level323** [comment]
What is the rationale for defaulting to per-archive chunking settings? To
be honest I could never quite work out why this is the case.

Wouldn't it make more sense to specify the default chunker params at repo
init time (which all new archive runs will use, unless overridden)?

The only possible use-case for the current arrangement would be for cases
where one repo is used to create archives of very big files (e.g. machine
disk images) as well as creating archives of large numbers of small files.
However, this seems like a rather odd use case (at least to me) - I use
borg to backup both types of files but it makes more sense (at least to me)
to use separate repos because the retention periods are different for each
and keeping them in separate repos makes pruning straightforward (and using
a single repo but with different chunker params won't save much space
anyway for reasons @TW already outlined).

So I propose:

1. Provide an option at borg `init` time to specify the default chunker
params that will be used for all created archives in this repo
2. Retain the `chunker-params`an option at borg `create` time to change the
chunker params for the archive currently being created (for those that want
per-archive chunker flexibility)
3. Changing the system-wide default chunker-params along the lines
indicated in your first post. However, I'd tweak your suggested system-wide
default to 17,23,20,4095 but now I'm getting pedantic - if there is the
ability to specify a per-repo default then I don't care (and I think it
would be a great feature)!

**Comment by ThomasWaldmann** [comment]
If you like, you can backup a lot different stuff into 1 repo. Depending on the stuff, different chunking or compression might give better results. And you can still use the same settings for everything, if you like, so this is also about flexibility.

If that parameters were fixed at repo init time (and not at archive creation time), there would be no way to change to other parameters except by starting from scratch in a new repo.

For compression, the benefits of "per archive" are easier to show: I used that myself, I backup 1 machine over a very slow DSL upstream (for these archives i want lzma compression) while for another machine that gets backed up into same repo, I have a LAN connection and use lz4 connection. If compression was fixed at init time, I could not do it that way.

**Comment by level323** [comment]
I agree that per-archive compression settings is a feature. I'm prepared to
accept that per-archive chunker settings is also a feature, albeit of
lesser value and with some side-effects of less efficient dedupe.

I think maybe I didn't explain myself clearly about what I was proposing.

Trying again.

1. Currently there is a application default chunker settings of
10,23,16,4095 (i.e. 1kiB min, 64kiB avg). I think we both agree this is too
small as a "best guess" application default. My pick for application
default chunker settings is 17,23,20,4095 (i.e. 128kiB min, 1MiB avg).
2. I would appreciate/suggest addition of an `init` argument to specify a
default `chunker params` for all archives created in a particular repo.
This would NOT enforce chunker params for all archives, merely specify a
default for the repo unless overridden via `--chunker-params` argument in
`create`.

By way of explanation, I my present use case is as follows. I have two main
borg repos:

1. One backs up "almost everything" and updates at most a few times per day
- documents, VM images, you name it. All my home network computers backup
"almost everything" to this one giant repo. The repo is located on my file
server on my LAN. I also mirror the repo (via rsync/whatever) to a
different geographical location - constantly trickling in the background,
rate limited and QoS'ed to a fraction of my DSL bandwidth. For this repo,
therefore, it is essential to have bigger chunks than the present default -
say 18,23,21,4096

2. Another repo only backs up documents and application settings on my
daily driver (my laptop) only. It backs up quite frequently (say, once
every 15 minutes) to a repo on the same machine (because I may not have
network connectivity to reach a remote borg repo). That repo gets synced
(via rsync) to offsite storage regularly. For this repo, therefore, it
makes sense to have smaller chunks - even the present borg default of
10,23,16,4096 works well.

I have other repos as well, but the above explanation is to give background
that should make it clear that, at least for my use case, having the
ability to specify default chunker params on a per-repo basis would be
useful.

At present I work around this by just scripting `chunker-params` arguments
into all my `create`s.... So I don't *need* per-repo chunker param
defaults, but it strikes me as, perhaps, a usual feature for common use
cases and as a general nicety to save users having to specify chunker
params on each invocation of `create`.

Cheers

**Comment by ThomasWaldmann** [comment]
OK, I see what you mean. This ticket is about the builtin ("last resort") defaults, which is separate from the "read defaults from repo" feature that you want (please open a ticket for that and copy whatever you need from above text to there).
