### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by vomout** [borgbackup/borg#3471]
It takes a long time for borg to just start up. This doesn't seem correct, and I don't think it was like this when I first installed the program.

$ time borg --version
borg 1.1.3

real	0m5.243s
user	0m0.193s
sys	0m0.040s

A little bit of further research indicates that the problem is in 'from borg.archiver import main' in the main script. Simply running python3.6 (which takes almost no time) and then typing 'import borg.archiver' similarly takes several seconds.

System: OSX 10.13.1. Borg installed with pip.

**Comment by ThomasWaldmann** [comment]
Sounds like a name resolving / DNS problem.

Make sure local names and IPs resolve correctly, in both directions.

I.E. make sure /etc/hosts has the usual stuff for localhost and your host name.

**Comment by ThomasWaldmann** [comment]
Another thing to note is that borg does some self-test at startup.
But on a usual 4y old laptop with ssd, this is still sub-second, even if you use the fat binary that first uncompresses itself into /tmp.

**Comment by vomout** [comment]
Everything resolves correctly. Only borg has problems / is slow to start.

**Comment by ThomasWaldmann** [comment]
OK, then do an strace to find out what it is. But I'm quite sure it is a local problem.

**Comment by vomout** [comment]
After some debugging I’ve traced the hang to borg/platform/__init__.py:

The very weird part is that if I comment out the entire if-elif-elif-block at the end, ‘import borg.platform' it does not hang. But if I comment out only the darwin part (I’m on OSX so sys.platform==‘darwin’), it still hangs.

**Comment by vomout** [comment]
To be precise, I have to comment out everything that loads the darwin or posix modules for borg/platform/__init__.py to not hang.

**Comment by vomout** [comment]
It appears socket.getfqdn() is broken and should not be used

https://bugs.python.org/issue5004 <https://bugs.python.org/issue5004>

**Comment by ThomasWaldmann** [comment]
wtf.

I believed somehow that having own hostname in /etc/hosts is best practice, to avoid issue when dns malfunctions and also to speed up things.

But looks like it is also needed to work around such breakage. And they are "discussing" since 2009.

**Comment by ThomasWaldmann** [comment]
@enkore ^

**Comment by ThomasWaldmann** [comment]
@vomout my impression is that python ticket is about hostname (short) vs. fqdn (long/full). For the purpose of creating a hopefully unique lock filename, borg wants the fqdn, but can also live with the short hostname (if unique).

Also, that's not quite your problem, your problem is slowness. And that slowness likely comes from DNS not working correctly and you system needing to do a DNS lookup as it can't be resolved otherwise. You have to check forward and reverse lookups.

**Comment by vomout** [comment]
No, the problem is that fqdn expects /etc/hosts to contain information that should not need to contain, and does not contain by default (I have never touched it, and should not have to touch it). Moreover, somehow getfqdn is very slow when it doesn’t find that information. Just doing the same lookup with ‘host’ on the command line is not slow.

**Comment by vomout** [comment]
Also, I don’t understand why borg would need a unique hostname? A laptop almost by definition doesn’t have a fixed hostname.
After some playing around with /etc/hosts such that borg won't hang:

>>> import socket
>>> socket.getfqdn()
'1.0.0.127.in-addr.arpa’

That’s not a very useful ‘unique’ hostname.

**Comment by ThomasWaldmann** [comment]
I could reproduce the slowness by removing the (usually present) entry from /etc/hosts:
```
127.0.1.1 tux.mydomain.org tux
```
Instead, I added it to DNS so that short hostname from /etc/hostname + "." + domain from /etc/resolv.conf gets resolved.

After that, I had slowness with `socket.getfqdn()` while socket.getaddrinfo(host_short, None, 0, SOCK_DGRAM, 0, AI_CANONNAME) worked quickly, as proposed in the patch in the python issue tracker: https://bugs.python.org/file29919/python2.7-socket-getfqdn.patch

Issue: https://bugs.python.org/issue5004

**Comment by callegar** [comment]
I do not know if it is appropriate to write here, since I see the same issue (a slow start) but for reasons that are likely to be unrelated.

    time borg --help
    ...
    real    0m7,709s

Borg version give a similar long time, almost 8 s.  This is on a raspberry thing with borg 1.1.4.  Now, I understand that it is a seriously underpowered thing, however, it should be more than enough to run as a borg server. The problem is that taking almost 10 s jut to read the docs, check the version or start the server is a bit discouraging.

**Comment by ThomasWaldmann** [comment]
There are some things to consider / know about this:

- if you use the standalone binary (one single executable as offer from the releases page on github), startup is expensive as it first has to unpack itself into TEMP dir. That includes all the borg code, the python interpreter plus standard library, additional libraries borg uses - so that is quite a lot. If the TEMP dir is not a ramdisk, but on e.g. SDcard, it will slow down a lot. But you maybe don't want to waste precious RAM for TEMP dir on the rpi either, borg needs the RAM for more important stuff.

- any recent borg version does a quick self-test after startup and before executing any commands. these are a few unit tests which are quite quick on usual hardware (sub-second), but might be slower on slower cores.

- the raspi is a bit slow (cpu core speed as well as I/O speed, like sdcard or usb2 connected mass storage or network) compared to current intel/amd or other desktop/notebook/server hardware, so a bit of slowness here is expected. borg can't exploit multiple cores yet, so it does not help that the rpi3 has 4 cores.

**Comment by callegar** [comment]
Thanks for the clarification!

I'm not using the standalone binary, rather install with pip in a virtualenv.

The quick self test looks indeed a safe thing to do for a backup program.

However, I would like to suggest that it may not be really needed before invoking with --help or --version, since getting usage hints or checking a version is usually expected to be fast.  I also wonder if /all/ the tests are needed also for the server, since - to the best of my understanding - the server functionality is rather limited and usage of borg on restricted hardware is typically in server mode.

In fact, I think that having a split borgserver with minimal deps would be very useful for installing on NAS or even on openwrt/lede.

I have also done some quick profiling. Looks like a huge amount of time is used by importlib even for the simple borg --help

**Comment by jdchristensen** [comment]
@callegar Why do you think the issue isn't about FQDN lookup?

**Comment by callegar** [comment]
Isn't that patched in 1.1.4?

**Comment by callegar** [comment]
@ThomasWaldmann A big raspi limit is access time on sdcard, which indeed makes python a pain on it (not just in borg: pip3 --help also takes ages, in fact longer than borg). So feel free to suggest to turn my comment into a mere wish: bypass as many imports as possible for just giving --help, --version and starting the server.

**Comment by ThomasWaldmann** [comment]
The fqdn slow startup issue is fixed in 1.1.4, this is why this ticket is closed.

I guess @jdchristensen was just wondering about why you add an unrelated issue to an already closed ticket.

**Comment by callegar** [comment]
Had the same doubt, in fact my note started with "I do not know if it is appropriate to write here, since I see the same issue (a slow start) but for reasons that are likely to be unrelated."

In fact, my doubt was on whether it was more confusing to add to an existing closed bug or to open a new one with the same name.

Thanks to the discussion here, I know see, that I should open something in the lines of "Enhancement request: skip slow startup steps for borg serve, borg --help and borg --version".

Hence, I apologize for the noise, but the exchange was in fact useful to me.

**Comment by gamb** [comment]
First time user here. I'm getting a very slow startup time via a Brew install.

```
gamble@Adams-MacBook-Pro-2 ~/d/borg> time borg --version
borg 1.1.7
        5.91 real         0.61 user         0.20 sys
```

Running on reasonable hardware:

> MacBook Pro (Retina, 13-inch, Early 2015). Intel Core i15. 8GB RAM. 500GB SSD.

**Comment by ThomasWaldmann** [comment]
@gamb did you read the comments above? can you try to find out what exactly is slow?

Also, try 1.1.8 (but i don't remember fixing startup speed issues).

**Comment by enkore** [comment]
strace
