### ISSUE TITLE
Take into account names defined in .ssh/config when using remote ssh 

### ISSUE THREAD

**Issue by arthurlogilab** [borgbackup/borg#3472]
```
$ borg list ssh://backup@example-name:/var/backups/borg/
Remote: ssh: Could not resolve hostname example-name: Name or service not known
Connection closed by remote host. Is borg working on the server?
$ cat .ssh/config
Host example-name
  Hostname IP
```

The workaround for this is to 

```
$ borg list ssh://backup@IP:/var/backups/borg/
```

This would be useful in particular when using ProxyJump directives in the .ssh/config, I haven't found a workaround for that :

```
$ cat .ssh/config
Host bastion
  Host IP 
Hostname example-name
  Host OTHERIP
  ProxyJump bastion
  User backup
```

**Comment by EthraZa** [comment]
I guess what you need is to set a host name.

Like in:
`echo "192.168.0.10   example-name" >> /etc/hosts`

**Comment by ThomasWaldmann** [comment]
@arthurlogilab IIRC, borg is just giving username@hostname to ssh, so if it doesn't work, it is a ssh (not borg) issue.
```
Remote: ssh: Could not resolve hostname example-name: Name or service not known
```
The "Remote: " here just means that borg has seen this on stderr of the local ssh process, where usually also stderr output from remote is emitted. But in this case it is from the local ssh client.

**Comment by sainaen** [comment]
I have a very similar setup and everything works great (without `borg-backup` being resolvable domain name):
```
Host borg-backup
  HostName backup.example.com
  User backup
  IdentityFile ~/.ssh/backup.id_rsa
```
I've checked with an ip in the `HostName` directive and it still works. I'm on Debian Sid with borg v1.1.3.

> borg list ssh://backup@example-name:/var/backups/borg/

Don't you have to give it a port with this syntax? For me it's either `ssh://backup@example-name/var/backups/borg/`, `ssh://backup@example-name:22/var/backups/borg/ `, or `backup@example-name:/var/backups/borg/`, otherwise I get an `Invalid location format` error.

**Comment by ThomasWaldmann** [comment]
it seems there is no action needed for borg, as this stuff is just passed through to the ssh client, so any issues with it not working are likely ssh issues.

if you find it is really a borg issue, please re-open this ticket.

**Comment by miguno** [comment]
Let me add some tips here as this is the only relevant GH ticket that turned up when I ran into the same error message. Perhaps it helps others that try to google the error.

```
Remote: ssh: Could not resolve hostname example-name: Name or service not known
Connection closed by remote host. Is borg working on the server?
```

Tip 1: You can use `BORG_RSH` to force the use of specific SSH parameters (`BORG_RSH` defaults to `'ssh'`).  For example, you can tell borg to use a specific SSH key via `BORG_RSH='ssh -i ~/.ssh/id_rsa'`.  See http://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables.

Tip 2: If your server's (Open)SSH version is older than 7.2, you should NOT use the `restrict` directive in the server-side `~/.ssh/authorized_keys` to force the locked-down `borg serve` command.  Instead, replace `restrict` with `no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc`.  This is AFAICT the same issue as https://github.com/borgbackup/borg/issues/3741.  In my case, I ran into this problem because my remote server was a Synology NAS running DSM 6.1 with OpenSSH 6.8 (`ssh -V` on the NAS gives `OpenSSH_6.8p1-hpn14v6, OpenSSL 1.0.2n-fips  7 Dec 2017`).
