### ISSUE TITLE
Add files to an already existing archive path

### ISSUE THREAD

**Issue by tomschr** [borgbackup/borg#353]
(Disclaimer: I've looked through the issue tracker and the documentation, but I couldn't find anything that relates to my use case. Maybe I miss something.)

Let's assume I've created a repository `repo` for the `config` archive with all the configuration files under `~/.config/`:

```
$ borg create --stats --progress --compression lz4 repo::config ~/.config
```

So far, so good. Now, I realize, I forgot to add additional files to the `config` path which should also be stored under the `config` archive. So I've tried this:

```
$ borg create --stats --progress repo::config ~/.alias ~/.bash* ~/.bazaar/
```

This gives me:

```
initializing cache
Archive config already exists
```

It seems, borg doesn't allow me to add additional files to an already existing archive. Maybe add an `--add`, `--extend`, or something similar? The above message could be extended like:

```
initializing cache
Archive config already exists.
Do you want to add additional files to your already existing config archive?
Use the --extend option.
```

**Comment by ThomasWaldmann** [comment]
Archives are designed to be immutable, so doing what you want works a bit differently:

You always create new archives (not add to existing ones) with new archive names.

So this would solve what you wanted to do:
```
$ borg create --stats --progress --compression lz4 repo::config2 ~/.config ~/.alias ~/.bash* ~/.bazaar/
```
It is efficient, because it will recognize the files and their chunks you already wrote into the repository when creating the "config" archive and reuse them - it only writes content chunks for the additional stuff.

Afterwards, if you like, you can:
- delete the "config" archive. It won't free up much space in the repo though, because the chunks are now used by the config2 archive, so it's rather for cleanup.
- rename the config2 archive to config

Usually one includes a timestamp in the archive name (like config-2015-11-01-17:54:00) and does use prune with some appropriate pruning rules, so one does never need to do these "afterwards" steps, but just fixes the "create" command line so it backs up whatever needed (and does not backup what's not needed). Everything else will then fix by itself over time.

**Comment by StoicDeveloper** [comment]
This solution, IIRC, will cause the new archive to not contain any files which have been deleted after the first archive was created. Is there a way for an archive to "inherit" from another archive? For my use-case, I would like to have the most up-to-date archive contain all data that has ever been in the backed-up directories, such that a file can be added, backed up, and later deleted, without that file ever being absent from newly created archives. One such method I could imaging would be to mount the most recent archive, and include its directory as a path for the new archive, but perhaps there is a more obvious method?

**Comment by ThomasWaldmann** [comment]
@StoicDeveloper there is no relationship (and no inheriting) between archives, they are independent of each other. That's a feature, because it makes deleting / pruning archives very simple.
