### ISSUE TITLE
Deduplication ratio on about 750 GB for the first backup

### ISSUE THREAD

**Issue by jeremyfritzen** [borgbackup/borg#3582]
Hi,

I plan to use Borg to backup my NAS through a NFS mount.
The "Backup server" is a Debian VM with borg installed and has access to the NAS through the NFS mount point.

In order to backup a videos directory with 750GB, I made a first backup on the new repo with the following commands:
`borg init --encryption=none /data/NAS`
`borg create --info --stats --progress /data/NAS::28-01-2018 /data/NAS/Videos`

The result was very surprising: **the deduplicated size was exactly the same as the original size!**
As I didn't use `--compression` option, it's normal that the compressed size is the same but I can't understand the deduplicated size.
I can't believe that in 750 GB, there is nothing to deduplicate.

Is it normal?
What do you think about this result?

Thank you all!

**Comment by ThomasWaldmann** [comment]
Not sure what have expected. Borg deduplication has a ~ 2MiB granularity by default, so if you videos do not have duplicate chunks of that size, you won't get "in data set" dedup.

If you just run the backup again, you will get "historical" dedup, close to 100% as most of your data did not change.

Likely, video's won't compress because they are already compressed, but you still could use lz4 compression in case you also have compressible data. It won't slow down your backup even if data is already compressed.

**Comment by jeremyfritzen** [comment]
Thank you for your answer.
I am not sure to understand what you're explaining. Each video file is pretty big: about 700MiB for the smallest and more that 2 or 3 GiB for the biggest.

Is it normal to have no deduplication for this king of file?

**Comment by ThomasWaldmann** [comment]
In a normal video (or audio) file it is rather unlikely to find duplicate chunks.

It's different for big virtual machine files, there are often large, duplicate sparse/all-zero ranges.
