### ISSUE TITLE
Backing up files owned by root

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#3587]
I use [timeshift](https://github.com/teejee2008/timeshift) to create snapshots backups of my Linux system. Timeshift makes these snapshots locally by default, and then I want to use `borg` to add those files into my backup pipeline.

The problem is that since timeshift backups the system files, some of these files are owned by `root:root` and I just noticed that borg fails to backup some of those (check the `E` below, with a `permission denied` error above it):

```
A /timeshift/snapshots/2018-01-30_18-00-01/localhost/bin/znew
s /timeshift/snapshots/2018-01-30_18-00-01/localhost/bin/rzsh
s /timeshift/snapshots/2018-01-30_18-00-01/localhost/bin/zsh
A /timeshift/snapshots/2018-01-30_18-00-01/localhost/bin/zsh518-01-30_18-00-01/localhost/bin/zsh5                                                                                             
d /timeshift/snapshots/2018-01-30_18-00-01/localhost/bin
/timeshift/snapshots/2018-01-30_18-00-01/localhost/boot/System.map-4.13.0-32-generic: open: [Errno 13] Permission denied: '/timeshift/snapshots/2018-01-30_18-00-01/localhost/boot/System.map-4.13.0-32-generic'
E /timeshift/snapshots/2018-01-30_18-00-01/localhost/boot/System.map-4.13.0-32-generic
```

 How would I go about solving this? I tried running `borg` as root using `sudo` but that created more problems in the end, and I don't think it's a good practice to do. Any hints appreciated.

Thanks in advance!

**Comment by ThomasWaldmann** [comment]
Borg needs at least permission to discover (x on the directory path) and read (r on the file).

If you backup other users' file (e.g. root, other users), you usually want to be root to not run into permission issues for the input files.

You need to be also careful not to cause permission issues in the repo itself. E.g. creating / updating a repo as root and use it also as non-root will lead to troubles due to the mixup of users and permissions.

For remote (ssh://user@host...) repos the latter usually is no problem as you always use the same user.

For local repos it is a problem and you can work around by using ssh://user@localhost...

**Comment by fullofcaffeine** [comment]
Thank you.

**Comment by andrewufrank** [comment]
I have backed up files owned by root with sudo and find that the repository is now readable only with sudo because the data files which were added are owned by root. Is there a danger to change the ownershop of all files in the repo to me (including the index and hints files)?

**Comment by ThomasWaldmann** [comment]
@andrewufrank there is no problem for borg with doing that. borg just needs to be able to r/w all files.

You can work around that problem by using borg with `user@localhost:/path/to/repo` as repo (in that scenario, borg client can run as root and borg serve would run as user.

**Comment by andrewufrank** [comment]
thank you - i will try this!
