### ISSUE TITLE
skip slow startup steps for borg serve, --help, --version

### ISSUE THREAD

**Issue by callegar** [borgbackup/borg#3609]
Borg has a very large startup time on some platforms. E.g., ~8s on warm start just to get the borg version string on some ARM SOCs and systems relying on SD cards as root storage.  This is not really specific to borg, rather due to the quite poor performance of CPython on platforms which are both not very powerful and characterized by slow storage media.

Notwithstanding, hardware limitations, small ARM systems are often used as NAS or backup systems, so that running the borg server there (borg serve) can make sense.

Some rearrangement of borg code, allowing borg serve to skip most of the python imports and some sanity tests which may be unneeded in the limited `borg serve` operation may help a lot here, saving the impression of staring at a frozen system.  Similarly, factoring things to delay some imports after checking if one merely wants to see the borg help or version could be precious.

**Comment by ThomasWaldmann** [comment]
This needs someone checking whether this is possible without making a mess in the code, just for the sake of slow platforms. I think we should do what can be easily and cleanly done, but not more. Backups should mostly run unattended, the docs/help can be also read online, so there are already workarounds for the most common use cases.

Running borg on small/slow platforms has also other, more severe issues (like you can run out of memory for bigger repos and, in case of the rpi and some other SBCs and NAS devices, you can not expand memory, because RAM is soldered and there is no DIMM socket). Also, if you run the borg client with the cache directory on SD card, that might be also a performance problem. SDcards are just slow, that is not borg's fault.

**Comment by bulletmark** [comment]
I've been evaluating borg and noticed also that it takes a long time to start. The reason is `python-setuptools` bug https://github.com/pypa/setuptools/issues/510 which is well described by https://coldfix.de/2017/02/25/slow-entrypoints/. Instead of using `entry_points` I just include a small stub to import and run my own python apps and that reduces the start time enormously, particularly on small boxes like the Raspberry Pi where I first discovered this problem.

**Comment by callegar** [comment]
@bulletmark thanks for providing the link to the setuptools bug. That was an interesting read. Bad to see that once more the python support for libraries and plugins is in a bit of a sad state and that there is still no sign of a definitive solution on the radar after a long time that bug was first reported.

@ThomasWaldmann I totally agree no-one should want to run the borg client on an embedded platform, but things may be different just for the server. In fact, I mentioned borg serve and --help and --version only in the report. I wonder if it may be possible to use some of the workaround mentioned in the setuptools bug report at least for them.

**Comment by cpitclaudel** [comment]
@callegar Thanks for documenting this issue.  @ThomasWaldmann thanks for your excellent work and dedication.  Can you clarify whether the caveat against running on a raspberry pi only applies to the client? Or is it also bad to run a server there? Additionally, is there documentation somewhere about what is gained by using `borg serve` rather than sshfs? (I tried experimenting, but the tests were not particularly conclusive)

**Comment by ThomasWaldmann** [comment]
@cpitclaudel it applies:
- very much to borg in non-client/server mode (with a repo in a locally mounted directory, not ssh:)
- less to borg client (client/server mode, ssh: repo) because the memory needed for the repo index is allocated on the server side
- less to borg serve(r) (client/server mode, ssh: repo) because the memory needed for files cache and chunks index is alloced on the client side

Using client/server is preferable over sshfs because you then have an agent on the server side which can do some actions without going over the network (e.g. loading/saving the repo index or doing a repo check).

**Comment by cpitclaudel** [comment]
Thanks a lot! :)

**Comment by m3nu** [comment]
This is partly implemented with `BORG_SELFTEST=disabled` by now: https://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables

We still want further changes here?
