### ISSUE TITLE
Deduplication efficiency or correct application

### ISSUE THREAD

**Issue by DumbTomatoesPolitelyQuestion** [borgbackup/borg#3610]
Quick question about the deduplication in my specific use case:
Backing up pictures. --> Editing some tags. --> Backing up the same pictures again.

I was under the impression that deduplication should catch that only parts of the file have changed and the repo size should not increase much. Sadly in my example this is not the case. I have built a minimal example to reproduce. There is some deduplication going on but I was hoping for more. In particular I refer to the following quote from the manual: 

> 
> -  file/directory names staying the same: So you can move your stuff around without killing the deduplication, even between machines sharing a repo.
> - The absolute position of a data chunk inside a file: Stuff may get shifted and will still be found by the deduplication algorithm.

Deeply apologize if I have missed something. Thanks for a great piece of software.

```
# Freely licenced pictures Source: https://www.flickr.com/photos/kalamazoopubliclibrary/albums/72157647979698021
wget https://downloadr.flickr.com/dl/4f269e83004d1e8a58f53bf608df1d593e3fba8c

ubuntu@ubuntu:~/Downloads$ unzip -d out 4f269e83004d1e8a58f53bf608df1d593e3fba8c
Archive:  4f269e83004d1e8a58f53bf608df1d593e3fba8c
 extracting: out/img_1281_15158298977_o.jpg  
 extracting: out/img_1282_15344523382_o.jpg  
 extracting: out/img_1285_15344829755_o.jpg  
 extracting: out/img_1291_15344522742_o.jpg  
 extracting: out/img_1295_15158297487_o.jpg  
 extracting: out/img_1297_15158062149_o.jpg  
 extracting: out/img_1300_15321799136_o.jpg  
 extracting: out/img_1302_15341650171_o.jpg  
 extracting: out/img_1307_15341649881_o.jpg  
 extracting: out/img_1308_15158061249_o.jpg  
 extracting: out/img_1310_15344520942_o.jpg  
 extracting: out/img_1312_15158124320_o.jpg  
 extracting: out/img_1313_15344520192_o.jpg  
 extracting: out/img_1316_15158294707_o.jpg  
 extracting: out/img_1319_15344519202_o.jpg  
 extracting: out/img_1323_15158249508_o.jpg  
 extracting: out/img_1324_15158058669_o.jpg  
 extracting: out/img_1327_15321795396_o.jpg  
 extracting: out/img_1328_15344824705_o.jpg  
 extracting: out/img_7633_15158057289_o.jpg  
 extracting: out/img_7634_15158055659_o.jpg  
 extracting: out/img_7637_15158054919_o.jpg  
 extracting: out/img_7640_15344514732_o.jpg  
 extracting: out/img_7642_15341642771_o.jpg  
 extracting: out/img_7645_15344820595_o.jpg  
 extracting: out/img_7647_15158116940_o.jpg  
 extracting: out/img_7653_15321789766_o.jpg  
 extracting: out/img_7654_15158116120_o.jpg  
 extracting: out/img_7655_15344511342_o.jpg  
 extracting: out/img_7660_15344817815_o.jpg  
 extracting: out/img_7662_15344509692_o.jpg  
 extracting: out/img_7668_15158239938_o.jpg  
 extracting: out/img_7669_15341637551_o.jpg  
 extracting: out/img_7674_15158111520_o.jpg  
 extracting: out/img_7675_15321783886_o.jpg  
 extracting: out/img_7677_15158045399_o.jpg  
 extracting: out/img_7681_15158234798_o.jpg  
 extracting: out/img_7683_15158042809_o.jpg  
 extracting: out/img_7684_15158105480_o.jpg  
 extracting: out/img_7685_15158275267_o.jpg  
 extracting: out/img_7687_15158038659_o.jpg  
 extracting: out/img_7689_15158037369_o.jpg  
 extracting: out/img_7690_15158271467_o.jpg  
 extracting: out/img_7691_15158270117_o.jpg  
 extracting: out/img_7692_15158033879_o.jpg  
 extracting: out/img_7694_15158267017_o.jpg  
 extracting: out/img_7695_15158094080_o.jpg  
 extracting: out/img_7697_15341617591_o.jpg  
 extracting: out/img_7703_15341616081_o.jpg

ubuntu@ubuntu:~/Downloads$ du -hs out
194M	out


ubuntu@ubuntu:~/Downloads$ borg init --encryption=repokey ~/borg
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: y
Your passphrase (between double-quotes): "test"
Make sure the passphrase displayed above is exactly what you wanted.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /home/ubuntu/borg

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.


ubuntu@ubuntu:~/Downloads$ borg create ~/borg::One out
Enter passphrase for key /home/ubuntu/borg: 

ubuntu@ubuntu:~/Downloads$ du -hs ~/borg
194M	/home/ubuntu/borg

#import the pictures into shotwell and edit tags (with the setting "write tags to file" enabled)

ubuntu@ubuntu:~/Downloads$ du -hs ~/Bilder/
194M	/home/ubuntu/Bilder/

ubuntu@ubuntu:~/Downloads$ borg create --stats ~/borg::two ~/Bilder
Enter passphrase for key /home/ubuntu/borg: 
------------------------------------------------------------------------------
Archive name: two
Archive fingerprint: 94c88de1ec1c5ebfe2b1f61b7378e6103a4f334df68eb7c3fc7e3ce1b9ce105c
Time (start): Mon, 2018-02-12 15:23:37
Time (end):   Mon, 2018-02-12 15:23:39
Duration: 1.81 seconds
Number of files: 49
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              202.40 MB            202.70 MB             94.87 MB
All archives:              404.98 MB            405.41 MB            297.57 MB

                       Unique chunks         Total chunks
Chunk index:                     180                  258
------------------------------------------------------------------------------
ubuntu@ubuntu:~/Downloads$ du -hs ~/borg
284M	/home/ubuntu/borg
```

**Comment by ThomasWaldmann** [comment]
Well, it did deduplicate, but less than you expected (only 107MB reduction, not ~200MB).

Assuming that the byte stream representing the image inside the jpeg file stayed the same and only the tag changed, this is very likely due to the rather coarse default chunking. borg targets ~2MiB (2^21) chunk size by default.

Pro big chunks:
- little management overhead and resource consumption. every (not duplicate) chunk borg cuts needs to be stored into the repo, needs to be in repo index and chunks cache. the more chunks you have, the more memory (RAM) you will need for these indexes/caches.
- good for deduping large files, like VMs, disk images. dedup also works for small files, if they are identical.

Contra big chunks:
- as you noticed, they don't do fine grained deduplication and thus, for relatively small files and small changes, deduplicate less than you expected.

You can change this, see `borg create --chunker-params=...` in the docs, but keep resource consumption in mind.

**Comment by mahikeulbody** [comment]
I have the same "problem" (i.e. backing up pictures. --> editing some tags. --> backing up the same pictures again) and the best values I found (at least for me) are :👍 
CREATE_CHUNKER_PARAMS="11,23,17,4095"

_PS. My desktop has 8 GB of memory._

**Comment by DumbTomatoesPolitelyQuestion** [comment]
Thanks for the hint! Just did that and got a reduction of ~95% instead of the ~54% with the default parameters.
```
ubuntu@ubuntu:~$ du -hs ~/borg
204M	/home/ubuntu/borg
```

**Comment by ThomasWaldmann** [comment]
TODO: check the chunker-params help, whether this is already documented or still need to be added.

**Comment by DumbTomatoesPolitelyQuestion** [comment]
http://borgbackup.readthedocs.io/en/stable/usage/notes.html?highlight=chunker says something about this.

The manpage for create has the following in the Examples section:
          

>     # Make a big effort in fine granular deduplication (big chunk management
>     # overhead, needs a lot of RAM and disk space, see formula in internals
>     # docs - same parameters as borg < 1.0 or attic):
>     $ borg create --chunker-params 10,23,16,4095 /path/to/repo::small /smallstuff

**Comment by anhofmann** [comment]
I'm sorry to revive such an old ticket. My backup scenario consists mainly of regularly backing up large SQL dumps and VM images. With the default chunker params Borg Backup offers hardly any advantages over other backup programs for me and I use " --chunker-params=10,23,16,4095" everywhere. For example: One of my archives with 14 days of data is 384 GB with the default settings and 37.2 GB with the chunker params mentioned above (the original data is 2.2 TB). The description in the documentation is deterrent and I still don't understand what "needs a lot of disk space" means. I would suggest to change the documentation to make it clear that deduplication has massive advantages in some scenarios and to delete the misleading "needs a lot of disk space". 
I have been testing different backup programs for years and nothing comes close to Borg Backup with " --chunker-params=10,23,16,4095" in terms of disk space efficiency. Therefore I do not understand why this is formulated so negatively in the documentation and I would be happy if this were changed.

If this should be done, I would have a further suggestion for the chunk documentation: Since Borg actually gets very slow when you have many millions of chunks, my scripts create a new archive every month.

Translated with www.DeepL.com/Translator

**Comment by ThomasWaldmann** [comment]
attic and early borg used to use smaller chunks and people ran out of memory due to the large in-memory hashtables (indexes) caused by this. using 64K chunks you produce potentially 32x as many chunks as when using 2M chunks and all of them need to be kept in these indexes.

if you have enough memory (or not that much data) and it gives you much better dedup, feel free to use small chunks, but smaller chunks are not good as default and also using small chunks without being aware of the potential issues is not advisable (it might work at the beginning, but over time produce too much resource usage).

The "lots of disk space" refers to the size of the chunks index mostly. If you backup multiple clients to same repo, borg keeps a local cache of per-archive chunks indexes. If each of them is huge, the whole cache is N times as huge.

Your last comment seems that you have already seen one of the effects of too many chunks.

**Comment by anhofmann** [comment]
What I want to propose is that the text in the documentation be formulated in a less repugnant way. For example, it could be expanded to include an explanation of what is meant by more storage space usage. And get a hint that the old chunking mode can be extremely useful for some applications, especially for VM images or SQL dumps. At the moment the documentation sounds as if the old chunking mode was mainly bad and outdated and it took me weeks of trying to find out that smaller chunks make by far the biggest difference with my backup data. I test this by creating cron jobs that save daily with different parameters. Other compression, other chunking parameters etc. After a few weeks I will check which archive "won" and so far zstd=14 and chunking params 10,23,16,4095 is in any case the best combination.

As for the chunk parameters for VM data: my example in the first post is the archive with VM images. These are basically only 5 very large files that are perfectly processed by Borg with the small chunk parameters.

**Comment by anhofmann** [comment]
> Your last comment seems that you have already seen one of the effects of too many chunks.
Not sure what very slow means precisely, but it could be due to running out of physical memory (start swapping to disk) or needing lots of time to load / sync / save indexes.

Just have a look at this:
/usr/bin/time -v borg info ./Archive201805::2018-05-15
[..]
Duration: 28 minutes 54.39 seconds
Number of files: 266
Command line: /usr/bin/borg create --list --chunker-params 10,23,16,4095 --stats -C lzma,6 '/var/mnt/backup/borg/Archive201805::{now:%Y-%m-%d}' ./
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               70.32 GB              6.73 GB            172.39 MB
All archives:                2.77 TB            292.43 GB             18.84 GB

                       Unique chunks         Total chunks
Chunk index:                 2383348             41048765
        Command being timed: "borg info Archive201805::2018-05-15"
        [..]
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:09.97
        [..]
        Maximum resident set size (kbytes): 489168

So it takes almost 10 seconds to execute "borg info" on this archive. This is what I meant with "slow". But the benefits are obvious: 30 days of SQL dumps, logfiles etc. compressed and deduplicated to a tiny amount of 18.84 GB. The 10 Second load time is no problem for anyone. And regarding the "high disk space use": the cache dir for this archive has a size of 222 MB, so not really big. Memory usage is also acceptable with 477 MB. 

I think that the current documentation simply does not do justice to the old chunker params. Instead, it should point out that small chunks can get results (in terms of space usage) that may not be achievable with any other backup program.

**Comment by ThomasWaldmann** [comment]
Just make a PR with a docs update?
