### ISSUE TITLE
borg list exposes some info without authenticating

### ISSUE THREAD

**Issue by thet** [borgbackup/borg#3629]
Querying an inexistent repository with a command like the following:
```
$ borg list ssh://USER@SERVER:23/./PATH/REPO
```
fails with:
```
Repository ssh://USER@SERVER:23/./PATH/REPO does not exist.
```
without any authentication.

IMO and security wise no hints about the borg repository should be exposed without authenticating.

Borg version:
```
$ borg --version
borg 1.0.11
```

**Comment by ThomasWaldmann** [comment]
```
tw@tux:~$ borg list ssh://USER@SERVER:23/./PATH/REPO
Remote: ssh: Could not resolve hostname server: Name or service not known
Connection closed by remote host. Is borg working on the server?
```

**Comment by ThomasWaldmann** [comment]
In case you meant giving valid data for USER, SERVER, PORT (and maybe even the PATH, depending on how restrictive your authorized_keys restrictions are):

you need to be authenticated via ssh (key or manual login), otherwise your local borg won't be able to communicate with the remotely installed borg.

**Comment by thet** [comment]
ah, makes sense.
and yes, i meant to provide valid data for USER, SERRVER, PATH and REPO.
so, if I need to be authenticated via SSH first, then this might not be an issue.
closing...
