### ISSUE TITLE
"restrict" option in authorized_keys makes borg 1.0.11 fail

### ISSUE THREAD

**Issue by yvesle** [borgbackup/borg#3741]
Hi

I set up borg with a passwordless private key. When following the [documentation ](http://borgbackup.readthedocs.io/en/stable/usage/serve.html?highlight=restrict), the example  is `command="borg serve --restrict-to-path /path/to/repo",restrict ssh-rsa AAAAB3[...]`. 

However the "restrict" option makes the authentication fail. When I remove it, the script works as expected.

There is a [way ](https://manpages.debian.org/stretch/openssh-server/authorized_keys.5.en.html) in authorized_keys to lift selectively certain restricted capability, for instance : `command="borg ..." ,restrict,X11-forwarding ssh-rsa AAAAB3[...]` permits X11 forwarding previously disabled by the restrict option.

So it's down to finding out what capability borg needs on the server end and update the documentation accordingly. Can you help ?

borg version (client and server): 1.0.11

Regards
Yves

**Comment by ThomasWaldmann** [comment]
If you use 1.0.11, please read the matching docs, see the version selector.
For "restrict" to work, you need a rather recent openssh.

**Comment by yvesle** [comment]
Thank you for the quick tip ! The openssh server version on the server side is 6.8 (synology DSM 6.1.6-15266 latest). The "restrict" option was indeed introduced in [OpenSSH 7.2](http://www.openssh.com/txt/release-7.2) in 2016...

Using the correct version of the doc (http://borgbackup.readthedocs.io/en/1.0.11/usage.html#borg-serve ) it does mention `command="borg serve --restrict-to-path /path/to/repo",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc ssh-rsa...` 

Thank you again !

**Comment by miguno** [comment]
FWIW, here is the SSH forced command that works on a **Synology NAS with DSM 6.1**.

```shell
$ cat /volume1/homes/borg-user/.ssh/authorized_keys
command="borg serve --remote-path /usr/local/bin/borg --restrict-to-path /var/services/homes/borg-user/my-repository --restrict-to-path /volume1/homes/borg-user/my-repository",no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc ssh-rsa ABNza...
```

Notes:
- The `borg` executable was the `borg-linux64` downloaded from https://github.com/borgbackup/borg/releases, placed under `/usr/local/bin/borg` on the NAS (you might need a different one depending on the architecture of your NAS). You must set `--remote-path` to configure the exact location of `borg` executable unless you place it in the *default* PATH on the NAS (like `/bin/borg`).
- In the example below, the NAS user for ssh'ing is `borg-user`. The home directory is, by default, `/var/services/homes/<username>` in DSM 6.1. On the NAS, `/var/services/homes` is a symlink pointing to the Shared Folder `/volume1/homes`.
- Make sure the login shell for `borg-user` in `/etc/passwd` is `/bin/ash` (and not `/sbin/nologin`).
- Because DSM 6.1 uses the older OpenSSH version 6.8 instead of 7.2 (the latter supports `restrict`), the forced SSH command in `.ssh/authorized_keys` must say `no-pty,no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-user-rc` instead of `restrict`. See tip at bottom of http://borgbackup.readthedocs.io/en/stable/usage/serve.html#examples and https://github.com/borgbackup/borg/issues/3741.

Example to run a backup on the client to match the SSH config above:

```shell
$ borg init --encryption=repokey borg-user@nas:~/my-repository
```

**Comment by ThomasWaldmann** [comment]
@miguno `--remote-path` (as the name says) is intended to be used on the client to specify the ssh path to be invoked on the remote (borg server) system. IIRC, it is not useful on the `borg serve` side, so maybe double check that. If you do not have borg in your path on that side, you rather want to use a forced command like that:
```
command="/usr/local/bin/borg serve ...", ...
```

**Comment by miguno** [comment]
Thanks, @ThomasWaldmann.

I actually did double-check this.  Oddly enough, my setup now works no matter where and what I set `--remote-path` to.  That is, all permutations of the below work.

Server (NAS):
- `borg` binary installed to `/usr/local/bin/borg`.
- `.ssh/authorized_keys` set to:
    1. `command="borg serve ...`
    2. `command="borg serve --remote-path /usr/local/bin/borg  ...`
    3. `command="borg serve --remote-path /does/not/exist  ...`

Client (Mac):
1. `borg list <repo>`
2. `borg --remote-path /usr/local/bin/borg list <repo>` (as suggested by you)
3. `borg --remote-path /does/not/exist list <repo>` (even this works)

At least the client variant (3) should fail, no?
