### ISSUE TITLE
Borg hangs if repo lock is acquired but cache lock cannot be acquired

### ISSUE THREAD

**Issue by shaotongwang** [borgbackup/borg#3766]
Normally if borg cannot acquire the repo lock it will timeout and terminate shortly. However, if repo lock is acquired but cache is already locked by another process, borg will hang until the other process releases the cache lock.

To repoduce:
```
borg init -e none repo1
cp -r repo1 repo2
borg create repo1::archive path
```
then before borg create finishes do
```
borg create repo2::archive path
```
The second borg create will hang until the first borg create finishes before giving the error about cache is newer than repo.

**Comment by ThomasWaldmann** [comment]
This is not a supported nor a secure way to use borg.

If you just make a 1:1 copy of a repo, it will have the same repo id (and the same (repo)key).

Thus, both copies will ("accidentally") use the same cache, although they could have a different state.
Also they will use the same AES encryption key, which is not safe if you update the repos independently due to counter value reusage.

So, just don't do that.
