### ISSUE TITLE
Question about worst case scenario

### ISSUE THREAD

**Issue by Catscrash** [borgbackup/borg#3782]
Hi,

If a server is backed up to a borg repository on its own harddrive and this repository is cloned to backblaze / S3 / sth. via rclone. What would happen if the server crashes and completely dies during the rclone operation in a worst case scenario?

Is it possible that the off-site location is so messed up by the ongoing filetransfer, that its not useable anymore? Or would in worst case only the last backup be unusable?

**Comment by ThomasWaldmann** [comment]
Might depend a bit on whether append-only mode is used for borg or not.

In append-only mode, new data is always appended at the end (new segment files with higher numbers), while old files are not touched in any way (they won't get compacted, they won't get removed due to compaction).

In normal (not append-only) mode, new data is also always appended at the end, but after committing the new data, borg will also compact segments. That means deleted or superceded chunks in old segment files are removed by reading the old segment files, writing all the still-needed data to new segment files, dropping all the deleted/superceded chunks and afterwards deleting the old segment files.

How good that works with rclone I can't say, I neither use it nor know how it precisely works.

But I'ld suggest not to rely on such implementation details but rather make sure a usable state by other means. Maybe you could just make a snapshot of the target fs after a successful sync. If some sync is not successful and leaves the target in a weird state AND your server dies, you still have the valid state in the snapshot.

Also, at the source, I'ld make sure that the repo is in a good state before doing the sync. E.g. run borg check.

**Comment by fsironman** [comment]
What can happen:
Imagine the following segments with an imaginary modification time and size:

```
1 01.01.2018 500M
2 01.01.2018 500M
3 01.01.2018 500M
4 01.01.2018 300M
```

now you do a backup and prune
```
1 01.01.2018 500M
3 02.01.2018 500M
4 02.01.2018 500M
5 02.01.2018 200M
```

Because of the prune segment 2 is gone,segment 3,4 changed and segment 5 is new.

Now you sync with rclone or some other tools. What can happen now in the worst case is that you end up with the following:

```
1 01.01.2018 500M
2 01.01.2018 500M
3 02.01.2018 500M
4 02.01.2018 500M
5 02.01.2018 200M
```

Because of how borgs deduplicacation works in order to make sure you wont compromise the integrity of the whole repository you have to make sure that all the segments "stay" together.

The main problem here is that most sync tools work on files and as long as the one file is consistent it was a success the problem with borg that only all files together ensure a valid repository.

With rsync theres:
```
--delay-updates
          This  option puts the temporary file from each updated file into
          a holding directory until the end of the transfer, at which time
          all  the files are renamed into place in rapid succession.  This
          attempts to make the updating of the files a little more atomic.
          [...]
          See  also the "atomic-rsync" perl script in the "support" subdir
          for an update algorithm  that  is  even  more  atomic  (it  uses
          --link-dest and a parallel hierarchy of files).
```

In your use case B2 retains by default the old versions of a file https://rclone.org/b2/ at paragraph Versions. So in the worst case you would be able to get a consistent repository back.


I think the best practices that were mentioned here would make a nice addition to https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

I made a little draft about what we could add to it:

> Be careful when you use file syncing tool to backup your repository.
> In case the sync from repo1 to repo2 gets interrupted and you lose access to repo1 depending on your way of syncing repo2 might end up in an inconsistent state and data loss can occur.
> 
> To avert that danger follow these best practices when your use case involves syncing:
> - use append-only mode
> - snapshot the target filesystem (and delete it only after a successful sync)
> - rsync with --delay-updates or hardlinks
> - use some kind of versioning on your target filesystem / cloud storage if it supports it

**Comment by ThomasWaldmann** [comment]
borg does not change segment files after it has once written them.

they either stay or they get deleted (after compacting, writing still needed chunks to new segment files).

**Comment by Catscrash** [comment]
great! thank you, that answers my question :-)
