### ISSUE TITLE
use on disk hashindex instead of RAM (reduce RAM usage for large backups)

### ISSUE THREAD

**Issue by quickslyver** [borgbackup/borg#3868]
- I have checked borgbackup docs, FAQ, and open Github issues
- It is a question / feature proposal (not a bug !)

## Context / Use case

1. I have a large backup server where maximum installable RAM is 32GB (Xeon E3-1260v4 ...)
2. I have a large backup (~8TB) containing lot of file to backup (~250M) to an offsite storage using borg backup: high chunk count, high file count => high memory usage

The RAM usage exceeds quickly 32GB (As expected by the borg backup internal documentation )

As a current workaround, I've disabled the filecache: the RAM usage is lower, but still high (test in progress, I will update when finished will precise numbers)

## Proposal

Currently borgbackup store in RAM 3 large hash index tables:
- the repository index
- the chunk cache index
- the file cache index

Having the possibility, with an option, to store these tables on disk instead of RAM with direct disk read/write accesses would permit to use borg backup on servers with small amount of RAM (or large number of small files...)

Of course it will degrade a lot borgbackup performance(disk I/O limited, and re-hashing will take time), but it is preferable to be slow versus crashing due to out of memory. 

It is also possible to use a SSD for the "on-disk" caches to increase the index tables lookup performance (~8K IOPS for single threaded random read)

## Question

Developers, what is your opinion about such feature/option ? AFAIK it mainly "only" requires a secondary implementation of the hashindex.

Linked issues and commit:
* attic memory usage is too high: https://github.com/jborg/attic/issues/302
* attic was using mmap for hashindex: https://github.com/jborg/attic/commit/2f72b9f96001310ca4a81f8336545f2a3dd1de04
* re-evaluate mmaped hashindex: #513

**Comment by ThomasWaldmann** [comment]
Switching off the files cache lowers the memory needs of the borg client (the memory needs of borg serve stay the same).

A high chunk count means a big repo index (borg serve) as well as a slightly bigger chunks cache (borg client).

Are your files usually smaller than borg's default target chunk size (2MiB)? Do you use default chunker params? If not, a bigger (non-default) target chunk size could help (see `--chunker-params`), but only for a new repo.

Yes, Jonas (attic author) made an experiment in 2014 with mmaped hashindex, but it suffered from performance issues, so he removed the code again and just kept the stuff purely in memory.

I am not totally sure we would still have the same performance issue, because of the `fadvise dontneed` we added later (attic did not have that, so the fs/block cache of the OS was likely competing against the mmaped index files memory needs). OTOH, it would be quite some work to re-try it...

When thinking about how much we depend on the lookup performance (== hashtable performance in the current implementation) an important, but easily overlooked case is the one of unchanged files: we have their chunk ids in the files cache, but we must check whether we still have all these chunks in the repo. 

So we don't read the unchanged input files' contents, but we have a lot of chunkids to look up in the typical "most files did not change" case. This mechanism is why borg is so fast for unchanged files. If we had to do a disk access per chunkid lookup, it could slow down this case significantly.

**Comment by ThomasWaldmann** [comment]
What can be done quite easily, is to add swap space (swap partition, LV or swap file). Of course performance won't be great, but at least it won't run into a `MemoryError`.

**Comment by ThomasWaldmann** [comment]
Another workaround, if you only have a few small volume, but very high file count directories is to tar them first and then backup the tar file with borg (and exclude the directories).

**Comment by quickslyver** [comment]
> Currently borgbackup store in RAM 3 large hash index tables:
> * the repository index
> * the chunk cache index
> * the file cache index

I'm digging into the code (and in fact it's also docuemented in the internals, I missed that):

* the repository index and chunk cache index use the `hashindex` cython implementation
* the file cache uses a standard python dictionary

Do you know why the file cache doesn't use the `hashindex` structure ?

**Comment by ThomasWaldmann** [comment]
because the files cache is not a fixed record length thing, the chunks list in a file entry can have arbitrary size.

**Comment by quickslyver** [comment]
humm, ok, so it is not currently possible to have on disk file cache instead of RAM (it needs a more complex storage data structure)

**Comment by ThomasWaldmann** [comment]
well, it is theoretically possible, just not with a simple fixed-record length on-disk data structure.

**Comment by quickslyver** [comment]
Any implementation idea ? use a databse like Berkeley DB ? use an existing btree/b+tree implementation like https://github.com/NicolasLM/bplustree ?  else ?

**Comment by pierrehenrymuller** [comment]
Hi,

I'm facing same problem, a physical server with 32Go ram 8Go swap with a set of 3,5To to backup in a distant NFS server with many files (I can't count). We don't have access to the NFS server, so we need to backup the data on NFS by the mounting point.

Borg get all of the ram and swap space and the backup take 6 hours for the first backup but next backup is on the way since 4 days. But with the saturation of memory and swap the time to backup is too long.

Any idea to solve this or parameters to change to manage the speed and the memory usage?

**Comment by RonnyPfannschmidt** [comment]
an "easy way" to make it a fixed length on disk structure again would be to introduce a indirection where all chunk lists get addressed in the index as a count/position pair that looks up into a different memory mapped file
then there would be one file that just stores the lists in a index able way and a different file that

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt your post seems truncated at the end. but i see what you mean. we could go from python objects to more memory efficient C data structures that way, but have quite more code and memory management to do by ourselves.

@pierrehenrymuller use a recent borg version and try to reduce memory usage:
- BORG_FILES_CACHE_SUFFIX
- BORG_FILES_CACHE_TTL
- use default chunker params (in case you manually specified smaller target chunk size)
- partition data set into multiple ones and use multiple repos

https://borgbackup.readthedocs.io/en/1.1.16/usage/general.html#environment-variables

If possible, adding more RAM could also be a quick solution. More swap would also help, but be slow.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt as your idea does not really fit into here, I created #5756 for it.

**Comment by ThomasWaldmann** [comment]
Guess I am closing this:
- on a lot of systems, there is now more RAM available
- on-disk index is likely too slow and would spoil borg's high backup speed if most files did not change (it needs to do a lot of index lookups in that case to check whether these chunks are still in the repo)
- #5756 might be interesting though and will keep that open
- borg2 will have a split files cache per archive series with lower RAM needs
- borg2 (as of now) does not need a repository index, thus 0 RAM needs for that.
