### ISSUE TITLE
move away from github

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3875]
since microsoft just has acquired github, i guess it is time to think about other options.

i don't want to repeat the hundreds of arguments here about why microsoft is evil / is not evil / is not evil any more. or whether a closed source platform was better under github's control or will be better under microsoft's control. everybody interested in that discussion can find it on the web.

so the topic of this issue is technical / feasibility / consequences of such move and how we could make the best out of it.
 
hosting an own gitlab (community edition) instance seems to be one of the best options to avoid the `$bigplayer-just-acquired-our-platform` issue.

but how will wide-scale collaboration work then? will every developer have to create a lot of accounts in a lot of separate gitlab instances in the future (just to do a small pull request or file a bug)? this didn't work well in the past and was one reason why everybody and his dog jumped on the github or bitbucket train, just to make easy collaboration possible without the pain, to improve visibility, to be more productive.

so, what are the options nowadays, without losing all that?

**Comment by EthraZa** [comment]
Maybe now, with GitHub falling into the dark pit, Bitbucket becomes "the next big thing"!

**Comment by ThomasWaldmann** [comment]
I used bitbucket in the past (not so much recently), but didn't like it much.

Also, bitbucket, sourceforge, the hosted version of gitlab (gitlab.com) do somehow have the same problem as github.com - it is just a matter of time. And besides future acquisitions, we all do not really know what the current owner is already doing behind the scenes.

**Comment by ArchangeGabriel** [comment]
Yes, the problem of decentralization without federation is multiplication of logins to contribute everywhere. Note that GitLab instances might allow you to log using other accounts, like… GitHub. Examples: https://framagit.org/users/sign_in, https://gitlab.gnome.org/users/sign_in.

But generally speaking, self-hosting does not scale indeed. That’s why https://chatons.org/en was born, and maybe you can find some providers that suits your requirements or has your trust.

The UX has evolved, a lot. They are both advantages and disadvantages vs GitHub in my opinion, and in the end if I currently prefer GitHub, it is most likely because I am much more used to it (even if that does not show in my profile — mostly because comments do not appear —, I’m spending a lot of time every day on GitHub). If I had to use GitLab a lot more than currently, maybe that would change. Now note that this might depend on how you use it, and my use case might be quite different than yours.

Note that there is also Gitea (preferable fork of gogs), that might be better suited for small projects like borg (as opposed to colossus like GNOME) in my opinion, when it comes to self-hosting.

**Comment by ArchangeGabriel** [comment]
Well, the real issue is not the git part, it’s all the existing issues/PR.

**Comment by ThomasWaldmann** [comment]
And the community.

**Comment by ThomasWaldmann** [comment]
https://about.teahub.io/ - sounds like "github, done right", but will still take a while.

**Comment by ThomasWaldmann** [comment]
Considering that we now use even more from github (github actions for CI) than we did back then and that it runs quite well, guess we'll stay here for a while.
