### ISSUE TITLE
backing up a non-existing directory succeeds

### ISSUE THREAD

**Issue by pille** [borgbackup/borg#3902]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
BUG

#### Your borg version (borg -V).
1.1.5

## Describe the problem you're observing.

backing up a _non-existing_ directory succeeds (exit status: 1) and creates an archive of 552B data.
an error message is shown (not a warning):
```
/mnt/data: [Errno: 2] No such fle of directory: '/mnt/data'
```

one might argue about the desired behavior and whether this is a bug or a feature, but with respect to backups in my opinion it should avoid giving the impression that data was actually backed up.
it should fail instead in order to communicate that there's an error in the setup and no data was actually backed up.

**Comment by ThomasWaldmann** [comment]
No, it did not "succeed".

If borg exits with status 1, this means WARNING (not SUCCESS, exit status for that is 0), so you have to check the logs to find out what the problem was.

It is intended that if you backup some sources and some of them are not found or are not accessible, that it emits a warning, but still continues and backs up the remaining sources. Same applies if single files or directories within a source fail: it will log a warning, but continue backing up all other stuff.

Admittedly, 1 source out of 1 given failing looks special, but it still follows the rule I have layed out above.

So, take warnings seriously.

**Comment by pille** [comment]
i was expecting a "warning" label like it happens with "permission denied", so this looked like an uncatched error.
i can understand your argument in regard of multiple sources, though.

**Comment by ThomasWaldmann** [comment]
Looks pretty much the same for both cases:
```
$ borg create repo::arch aabb
aabb: [Errno 2] No such file or directory: 'aabb'
$ borg create repo::arch aabb
aabb: open: [Errno 13] Permission denied: 'aabb'
```

**Comment by ThomasWaldmann** [comment]
In case you want the loglevel also logged, guess you need to create and use a logging configuration for borg.
If you don't, it uses the default builtin one, which is relatively simple.

**Comment by ThomasWaldmann** [comment]
in case you want the exit status logged, there is `--show-rc`.
