### ISSUE TITLE
Deduplication not working with data read from stdin?

### ISSUE THREAD

**Issue by elifarley** [borgbackup/borg#3910]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.
Arch Linux, Kernel 4.16.13-2-ARCH

#### Your borg version (borg -V).
1.1.6

#### Operating system (distribution) and version.
Arch Linux, rolling release

#### Hardware / network configuration, and filesystems used.
BTRFS

#### How much data is handled by borg?
100 MB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```BASH
[user@ideapad fstbkp]$ borg init -e keyfile-blake2 /volumes/bkp/borg
# 72K /volumes/bkp/borg

[user@ideapad fstbkp]$ tar --xattrs -p -c -C /var/lib/pacman/local . | borg create -v -p --stats --stdin-name tar /volumes/bkp/borg::pacman-local-'{now}' -
Enter passphrase for key /home/user/.config/borg/keys/volumes_bkp_borg.2:
------------------------------------------------------------------------------
Archive name: pacman-local-2018-06-17T01:49:45
Archive fingerprint: cae5730bb70d16168417033314f01f6a186ee5c00auseraaac050dee201604b64                                                                                   
Time (start): Sun, 2018-06-17 01:49:51
Time (end):   Sun, 2018-06-17 01:49:52
Duration: 1.07 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               49.05 MB             25.05 MB             25.05 MB
All archives:               49.05 MB             25.05 MB             25.05 MB

                       Unique chunks         Total chunks
Chunk index:                      20                   20
------------------------------------------------------------------------------

# 24M /volumes/bkp/borg

# Immediately after the above command completes, I re-issue the same command:

[user@ideapad fstbkp]$ tar --xattrs -p -c -C /var/lib/pacman/local . | borg create -v -p --stats --stdin-name tar /volumes/bkp/borg::pacman-local-'{now}' -              
Enter passphrase for key /home/user/.config/borg/keys/volumes_bkp_borg.2:
------------------------------------------------------------------------------                                                                                           
Archive name: pacman-local-2018-06-17T01:50:15
Archive fingerprint: 33be76cfad2654d2aabbfd3ce992cf10cf1c74e3d091dbb400a0ce2c73ad96eb
Time (start): Sun, 2018-06-17 01:50:18
Time (end):   Sun, 2018-06-17 01:50:18
Duration: 0.79 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               49.05 MB             25.05 MB             25.05 MB
All archives:               98.10 MB             50.11 MB             50.11 MB

                       Unique chunks         Total chunks
Chunk index:                      42                   42
------------------------------------------------------------------------------

# 48M /volumes/bkp/borg

```

## Describe the problem you're observing.
I create a tar file from `/var/lib/pacman/local` and pipe it to borg, which makes the empty borg repo grow from 76K to 24M in size. Immediately after this first command ends, I simply type the up arrow key followed by enter (to repeat the same command). Once it finishes, I check the borg repo size, and it has grown to 48 MB.

I concede that 2 consecutive runs of the tar command above will produce different content, but the difference probably can only be found on the tar header field `mtime` and nothing else.
So, piping 2 almost identical chunks of data uses 2x the expected size.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
This can be easily reproduced by just copying and pasting the commands indicated above.

#### Include any warning/errors/backtraces from the system logs
None

**Comment by RonnyPfannschmidt** [comment]
borg is using a probability based round robin hash to chunk files into chunks that average about 2mb 

if you tar a lot of small files of which some change, then borg is unaware of the structure of that tar and the deduplication suffers due to simly mismatching what could be deduplicated

content aware chucking could help, but isn't implemented as of now,
same goes for a import command that would read the tarball into a actual archive

**Comment by elifarley** [comment]
But the files included in the first tar ball are exactly the same as the second tar ball.
In principle (bar a hacker attack or neutrinos flying through my SSD), they could only have changed if I had invoked `pacman` (Archlinux package manager) before creating the second tar ball, which I haven't.

**Comment by RonnyPfannschmidt** [comment]
@elifarley borg is unaware of what a tarball is, it acts as if the whole tarball is one big file hence not finding duplicate files within

**Comment by RonnyPfannschmidt** [comment]
@elifarley why not just run borg on it directly? without the tar middleman borg will capture all the files and dedulicate all the contents

**Comment by elifarley** [comment]
@RonnyPfannschmidt Well, when not using the `--xattrs` arg, borg is able to take the second tarball with a near-zero increase in repo size, so it works well on that case.

If I let borg archive each file, I won't be able to use `--anchored --exclude-from=my-excluded-files.txt`, which are tar arguments to specify which files should be excluded from archiving, unless borg can understand the same syntax as tar does.

**Comment by elifarley** [comment]
There seems to be a better deduplication algorithm. I fed the same 2 tarballs with `--xattrs` to another tool, bup, and instead of a 100% increase in repo size, it only increased 32%:

```bash
bup init
du -hs ~/.bup/
64K

cat /tmp/pacman-local.tar.A | bup split -n pacman-local -vv
bloom: creating from 1 file (5757 objects).
bup: 48000.00kbytes in 2.53 secs = 18972.68 kbytes/sec

du -hs ~/.bup/
25M

cat /tmp/pacman-local.tar.B | bup split -n pacman-local -vv
bloom: adding 1 file (1734 objects).
bup: 48000.00kbytes in 2.24 secs = 21447.95 kbytes/sec

du -hs ~/.bup/
33M
```

Maybe bup's algorithm could be copied over to borg, as they are both open source. The problem with bup is that it doesn't provide built-in encryption as borg does.

**Comment by jdchristensen** [comment]
Really you should only feed a tar file to borg as a last result.  Getting borg to scan the files directly will be much more space efficient and also much faster, since it will completely skip unchanged files.

About the deduplication algorithm:  see the borg docs, as you can adjust the parameters borg uses.  You will be able to achieve better deduplication, but at the cost of more overhead.

**Comment by elifarley** [comment]
@jdchristensen Your statements don't quite match my tests. When letting **borg** archive the files instead of piping a tarball to it, the repo gets 2 MB bigger than it would be when using a tarball.

See my table below:

**tar-xattrs**: tarball with extended attributes (`--xattr`)
**tar-simple**: tarball without extended attributes
**borg**: no tarball, borg does the archiving on its own

```
----------|---|---------|
   mode   |run|repo size|
----------|---|---------|
tar-xattrs| 1 |     24M |
tar-xattrs| 2 |     48M |
----------|---|---------|
tar-simple| 1 |     22M |
tar-simple| 2 |     22M |
----------|---|---------|
borg      | 1 |     23M |
borg      | 2 |     24M |
----------|---|---------|
```
The command lines were like:
```bash
# tar-simple 1:
cat /tmp/pacman-local.tar.A | borg create -v -p --stats -C auto,zstd,22 --stdin-name tar /volumes/bkp/borg::pacman-local-'{now}' -

# tar-simple 2:
cat /tmp/pacman-local.tar.B | borg create -v -p --stats -C auto,zstd,22 --stdin-name tar /volumes/bkp/borg::pacman-local-'{now}' -

# borg 1:
borg create -v -p --stats -C auto,zstd,22 /volumes/bkp/borg::pacman-local-'{now}' /var/lib/pacman/local

# borg 2:
borg create -v -p --stats -C auto,zstd,22 /volumes/bkp/borg::pacman-local-'{now}' /var/lib/pacman/local

```

**Comment by jdchristensen** [comment]
Using borg without tar will be faster when the files aren't in the filesystem cache, which will be the typical situation.  Try dropping the caches before every test to get realistic numbers.  But with a source directory of only 50MB, the difference won't be large.

Using borg without tar will have smaller backups in the typical case when there are some changes to some files.  The tar file approach does achieve slightly better compression for the first backup, which is expected, but will likely be worse in the long run.  Also, if you use borg to store xattrs directly, rather than with tar, you'll probably see much bigger space savings.

By the way, your command lines above are confusing.  In some of them, you use no compression.  In others, you use a pregenerated tar file, so the time taken by tar isn't taken into account.

**Comment by elifarley** [comment]
Thanks for pointing that out. I've edited my comment to make things clearer, and I have also testes with a bigger folder (/usr/include - 319M)

**Comment by ThomasWaldmann** [comment]
As @jdchristensen already pointed out, the effect originally observed (and also that bup did better dedup) is due to a granularity mismatch.

Borg has relatively coarse grained default chunker granularity (~2MB) and your tar stream had fine grained changes, spoiling the deduplication.

Using `--chunker-params` you could get finer grained chunker granularity, but the reason this is not the default is that it also means much higher resource usage (e.g. RAM needed).

So, my advice would also be to not use tar, use borg's include/exclude patterns and to not change the chunker params.

**Comment by ThomasWaldmann** [comment]
About the observed tar stream differences you maybe want to ask the tar developers about whether this can be improved.

**Comment by ThomasWaldmann** [comment]
I am closing this, deduplication IS working on stdin streams.
