### ISSUE TITLE
Retrieve data after formatting client

### ISSUE THREAD

**Issue by pcmanprogrammeur** [borgbackup/borg#3911]
Hi all,

A client server pushed backups on my backup server.

I formatted my client server and now, when i have to connect borg to backup server, i have a problem :

`borg init --encryption=keyfile borg@[BACKUP_SERVER]:/home/backups/$(hostname)`
=> Repository borg@[BACKUP_SERVER]:/home/backups/$(hostname) already exists.

Normal, so i test to list :
`borg list borg@[BACKUP_SERVER]:/home/backups/$(hostname)`
=> No key file for repository ssh://borg@[BACKUP_SERVER]:/home/backups/$(hostname) found in /root/.config/borg/keys.

How can i retrieve my data please ?

**Comment by RonnyPfannschmidt** [comment]
by passing the same keyfileas you used when creating?

**Comment by pcmanprogrammeur** [comment]
and if my server has been formatted ? is it dead ?

**Comment by ThomasWaldmann** [comment]
If you have an encrypted repo, but you lost the key, you lost access to all data in it.

borg does not use local keyfiles by default, you have to explicitly tell it to do so:
- before borg 1.1, the default was repokey (store the encrypted key in the repo config).
- since borg 1.1, you have to explicitly request the encryption mode after reading the docs about it.

in a repokey mode the key is relatively safe as long as you do not lose files from the repo.
in a keyfile mode, you request to store the key locally and you must back it up separately.

http://borgbackup.readthedocs.io/en/stable/usage/init.html#description says:
"""
But be careful with the key / the passphrase:

If you want “passphrase-only” security, use one of the repokey modes. The key will be stored inside the repository (in its “config” file). In above mentioned attack scenario, the attacker will have the key (but not the passphrase).

If you want “passphrase and having-the-key” security, use one of the keyfile modes. The key will be stored in your home directory (in .config/borg/keys). In the attack scenario, the attacker who has just access to your repo won’t have the key (and also not the passphrase).

Make a backup copy of the key file (keyfile mode) or repo config file (repokey mode) and keep it at a safe place, so you still have the key in case it gets corrupted or lost. Also keep the passphrase at a safe place. The backup that is encrypted with that key won’t help you with that, of course.
"""

**Comment by pcmanprogrammeur** [comment]
Thank you very much for this explanation.
I will store the key now that i losed my backup :(
An another question. In my case, i have a lot of servers. Is it a possible to use the same key for every servers or each server must a his own key, please ?

**Comment by ThomasWaldmann** [comment]
@pcmanprogrammeur sorry that you lost data, we thought that documenting this is enough, but obviously it isn't - therefore I opened #3913.

You have 1 key per repo. You can backup multiple servers into 1 repo, but that will be slower than using 1 repo per server (but maybe use less space due to deduplication). See also the docs / faq about this.

**Comment by pcmanprogrammeur** [comment]
Thank you @ThomasWaldmann.
I think it's a real problem to can't share the same key between many servers when you have more than 100 virtual machines like me. Storing more than 100 keys instead of 1 key shared between every VM is not a good solution.
An other solution when we have many servers is maybe to not use security key :(

**Comment by ThomasWaldmann** [comment]
@pcmanprogrammeur using the same key material for different repositories would not be secure any more, due to AES CTR mode (for the same key, any ctr value must only be used once).
