### ISSUE TITLE
feature request: limit prune on multiple archives per repository 

### ISSUE THREAD

**Issue by pille** [borgbackup/borg#3914]
preface: i'm backing up several servers (same OS) to a shared repository. this yields a huge benefit using the deduplication feature. the downside is that correct pruning is harder. one might use the --prefix feature but that would need hardcoding strings or scripts that pull and group archives automatically, which i dislike when automating deletion.

it's possible to distinguish archives based on their metadata. 
i've tested my backup-dataset and was able to generate stable archive identifiers:
1) archive-dump all archives
2) feed them to ```|jq ._meta.cmdline[-1],._meta.hostname |sha1sum```
this simply hashes the last backup-cmdline argument (source) and hostname.

it would be nice to have such an archive-source-id added to metadata and an option that limits pruning to archives of the same source. kind of an auto-prefix.

**Comment by ThomasWaldmann** [comment]
- there can be multiple source arguments
- would one want the id to change just because of adding a source (e.g. if you back up /pics1 /pics2 and then you add /pics3)?

so i still think that having a prefix and working based on that makes sense, e.g. myhostname-pics- as the prefix.

you don't need to hardcode the hostname and the tag ("pics"), you can use shell variables (or even borg placeholders) for that.

**Comment by pille** [comment]
i wasn't thinking of multiple source arguments, as i don't use them. i'm sure this can be worked out. somehow you need to parse them, anyway.

your second remark is harder to answer. i would want the id to change, if the source changes, but i see the other use-case.
