### ISSUE TITLE
docs/faq: copying a repo?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3933]
check docs and faq whether we have some words about copying a repo (which should NOT be done usually, at least not if the goal is to update the original as well as the copy using borg).

problems:
- aes ctr reuse (crypto not secure any more)
- cache confusion due to duplicate repo id

we need to point out that for encrypted repos always `borg init` must be used.

**Comment by ThomasWaldmann** [comment]
for unencrypted repos, copies can be made, but you need to change the repo id in the repo config after copying to a new unique value.

**Comment by plattrap** [comment]
To clarify for me:
- if I am just making a copy / backup of a repo (move to a new USB drive / server) so long as I only ever write to one of them in the future then all is good. Can read from either.
- If I am making a copy so that I have a seed repo for future backups, and plan to write to both of them then this is bad.

Could we add a `borg reinit` command that can be run on one of the copies which would take the old password, and a new password, then create a new repo id, and re-encrypt all the repo data with a new aes key, encrypted with the new password.

or `borg export-tar  /path/to/repo::Monday - | borg import-tar /path/to/new-repo::Monday -`

**Comment by ThomasWaldmann** [comment]
borg import/export-tar: is half there, needs someone doing the other half.

reinit: if you first copy it 1:1, then decrypt and reencrypt everthing, you have read all your data twice and written all your data twice, plus all the encryption/decryption.
