### ISSUE TITLE
Brief checking mode without reading whole repo data required

### ISSUE THREAD

**Issue by Self-Perfection** [borgbackup/borg#4051]
## Is this a BUG / ISSUE report or a QUESTION?

Feature request

#### Your borg version (borg -V).
Local system performs backups with borg 1.1.6
Backup server runs borg-linux64 1.1.5
#### Operating system (distribution) and version.
Client: Arch linux
Server: Ubuntu 16.04.4 under OpenVZ

#### How much data is handled by borg?
```
                       Original size      Compressed size    Deduplicated size
All archives:                1.57 TB              1.38 TB            177.77 GB
```
#### Borg crud benchmark
```
# time borg --progress --verbose benchmark crud ${BORG_REPO} /tmp/borg_crud_bench
...  [Deleting archives] ... 
C-Z-BIG         151.08 MB/s (10 * 100.00 MB all-zero files: 6.62s) 
R-Z-BIG          27.89 MB/s (10 * 100.00 MB all-zero files: 35.86s)
U-Z-BIG         242.39 MB/s (10 * 100.00 MB all-zero files: 4.13s)
D-Z-BIG         335.41 MB/s (10 * 100.00 MB all-zero files: 2.98s)
...
C-R-BIG          11.36 MB/s (10 * 100.00 MB random files: 88.03s)
R-R-BIG           3.11 MB/s (10 * 100.00 MB random files: 321.70s)
U-R-BIG         247.51 MB/s (10 * 100.00 MB random files: 4.04s)
D-R-BIG           1.40 MB/s (10 * 100.00 MB random files: 712.58s)
...
C-Z-MEDIUM      203.99 MB/s (1000 * 1.00 MB all-zero files: 4.90s)
R-Z-MEDIUM        3.04 MB/s (1000 * 1.00 MB all-zero files: 328.57s)
U-Z-MEDIUM      281.16 MB/s (1000 * 1.00 MB all-zero files: 3.56s)
D-Z-MEDIUM      372.69 MB/s (1000 * 1.00 MB all-zero files: 2.68s)
...
C-R-MEDIUM       11.45 MB/s (1000 * 1.00 MB random files: 87.36s)
R-R-MEDIUM        2.17 MB/s (1000 * 1.00 MB random files: 461.49s)
U-R-MEDIUM      282.77 MB/s (1000 * 1.00 MB random files: 3.54s)
D-R-MEDIUM        1.00 MB/s (1000 * 1.00 MB random files: 999.21s)
...
C-Z-SMALL        22.20 MB/s (10000 * 10.00 kB all-zero files: 4.50s)
R-Z-SMALL         2.11 MB/s (10000 * 10.00 kB all-zero files: 47.43s)
U-Z-SMALL        21.60 MB/s (10000 * 10.00 kB all-zero files: 4.63s)
D-Z-SMALL        27.56 MB/s (10000 * 10.00 kB all-zero files: 3.63s)
...
C-R-SMALL         6.83 MB/s (10000 * 10.00 kB random files: 14.63s)
R-R-SMALL         2.20 MB/s (10000 * 10.00 kB random files: 45.37s)
U-R-SMALL        18.94 MB/s (10000 * 10.00 kB random files: 5.28s)
D-R-SMALL        13.63 MB/s (10000 * 10.00 kB random files: 7.33s)

real    54m45,912s
user    1m41,876s
sys     0m23,762s
```
## Describe the problem you're observing.
Server that I'm using for backup is quite restricted in disk read speed, it is like 1-1.5 MiB/s on average (curiously write speed seems to be unrestricted). I'd like to occasionally check repo consistency for at least limited way, but currently this is impossible for me without missing 1-2 daily backups. Both `borg check --repository-only` and `borg check --archives-only` seems to cause server borg process to read whole repository contents from disk. That would take ages! 180000 MB / 1 MB/s / 24*3600 = 2 days!

I strongly suspect it must be possible to perform consistency checks without reading whole repo data. For instance checking all chunks headers (`cd $REPO_DIR; head -c 8 data/*/* >/dev/null`) takes just 40 seconds.

**Comment by ThomasWaldmann** [comment]
What's the point of checking if the check is insufficient?

**Comment by Self-Perfection** [comment]
Well I believe the first question should be what the point in any checking? For me it is a way to increase my confidence that my data can be recovered in case of disaster. Not 100% sure, as 100% confidence can never be attained. Even if check is complete there is a chance that repo will become corrupted during time span between last checking and disaster.

What good in two days long checking sequence, if already checked data has substantial chance of corruption while check sequence is still running?

I can't afford running full checking sequence. But just checking that all $BORG_REPO_DIR/data/*/* files are present and have expected size is way better than not performing any integrity checks at all.

_Some_ checks is better than _no checks at all_.

**Comment by ThomasWaldmann** [comment]
This is from `borg check --help`, hopefully it explains some things:

The check command verifies the consistency of a repository and the corresponding archives.

First, the underlying repository data files are checked:

- For all segments the segment magic (header) is checked
- For all objects stored in the segments, all metadata (e.g. crc and size) and
  all data is read. The read data is checked by size and CRC. Bit rot and other
  types of accidental damage can be detected this way.
- If we are in repair mode and a integrity error is detected for a segment,
  we try to recover as many objects from the segment as possible.
- In repair mode, it makes sure that the index is consistent with the data
  stored in the segments.
- If you use a remote repo server via ssh:, the repo check is executed on the
  repo server without causing significant network traffic.
- The repository check can be skipped using the --archives-only option.

Second, the consistency and correctness of the archive metadata is verified:

- Is the repo manifest present? If not, it is rebuilt from archive metadata
  chunks (this requires reading and decrypting of all metadata and data).
- Check if archive metadata chunk is present. if not, remove archive from
  manifest.
- For all files (items) in the archive, for all chunks referenced by these
  files, check if chunk is present.
  If a chunk is not present and we are in repair mode, replace it with a same-size
  replacement chunk of zeros.
  If a previously lost chunk reappears (e.g. via a later backup) and we are in
  repair mode, the all-zero replacement chunk will be replaced by the correct chunk.
  This requires reading of archive and file metadata, but not data.
- If we are in repair mode and we checked all the archives: delete orphaned
  chunks from the repo.
- if you use a remote repo server via ssh:, the archive check is executed on
  the client machine (because if encryption is enabled, the checks will require
  decryption and this is always done client-side, because key access will be
  required).
- The archive checks can be time consuming, they can be skipped using the
  --repository-only option.

The --verify-data option will perform a full integrity verification (as opposed to
checking the CRC32 of the segment) of data, which means reading the data from the
repository, decrypting and decompressing it. This is a cryptographic verification,
which will detect (accidental) corruption. For encrypted repositories it is
tamper-resistant as well, unless the attacker has access to the keys.

It is also very slow.

**Comment by ThomasWaldmann** [comment]
So, as you see above, a **repo check** really does read all data from disk, otherwise it could not check the crc32 of the segment entries. It does not transfer the data over the network in client/server mode though, as it runs on the server side.

An **archive check** does not read all data from disk, except if you demand it by `--verify-data`.

What you can do to have a relatively quick check is to use append-only mode (so new stuff is always appended and old stuff not touched in any way) and only verify the latest archive(s) added after your last check.

**Comment by pescepalla** [comment]
I had the same need to quickly check whether a borg archive exists and I ended up with using something along the lines of `borg list <REPO> >/dev/null 2>&1 && echo "exists"`

**Comment by ThomasWaldmann** [comment]
@pescepalla what you describe is correct, but not related to this issue.
