### ISSUE TITLE
implement --log-level

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#426]
minimum log level is currently hard coded to INFO.

with such a commandline switch, it could be changed to WARNING (or DEBUG or ERROR), if one is not using a logging configuration file.

**Comment by anarcat** [comment]
i object to such a change because:

* i can't think of a use case for turning off `ERROR` or `WARNING`... is that something we even want to allow? this could lead to silent errors and impossible bug reports...
* it would be confusing with the existing `--verbosity` flag. if we add a `--log-level` flag, we need to remove or change the semantics of the `--verbosity` flag.

`--verbose` is currently only used in 6 calls in the whole program (or more precisely, it is used only in one place, in `print_info`, and that is called 6 times total):

```
archiver.py:68:        self.print_info("%1s %s", status, remove_surrogates(path))
archiver.py:290:            self.print_info(remove_surrogates(orig_path))
archiver.py:376:            self.print_info("Mounting filesystem")
archiver.py:479:            self.print_info('Keeping archive: %s' % format_archive(archive))
archiver.py:482:                self.print_info('Would prune:     %s' % format_archive(archive))
archiver.py:484:                self.print_info('Pruning archive: %s' % format_archive(archive))
```

The first one is the file listing on `create`. That could be a topical flag. (The second one is the file listing on extract.) Why wouldn't the others  those be `logging.info()` messages?

i believe that, instead of calling this `--log-level`, the solution should be to reuse the basically unused `--verbose` flag by mapping it to `INFO` and adding a `--debug` flag, mapping it to `DEBUG`. the few items that use `verbose` specifically now could be turned into topical flags of their own if the semantics are not appropriate. For example, above, `borg create -v` currently has the side effect (in archiver.py:68) of showing all parsed files, that could be a `--list` or `--changed` topical flag instead of being triggered by `--debug` as i originally suggested.

i would of course be happy to implement such a change and cleanup the `print_*` calls that seem like unnecessary abstraction.

right now, i think the semantics of `--verbose` are confusing: some commands use it, some don't. By mapping it to `info`, we enforce some program-wide semantics that can be easily understood...

re-reading our previous conversation, i found https://github.com/borgbackup/borg/pull/233#issuecomment-144963335 - where you explicitely state a similar position: 

> [...] logging.warning should be only used if it is actually a warning that you're logging, not to make something visible that might not be visible because you reduced output by setting the minimum level to warning.
> There could be an additional "verbosity level" that controls how much informative output one gets (which could be controlled via verbose being an integer created either from -v0..9 or -v, -vv, -vvv - whatever is easiest with the argument parser).
> There could be additional "output options" that control which kinds of informative outputs are emitted.
> E.g. whether to show stats or not, whether to show this or that or not.

I understood this as meaning that we would have:

1. topical flags (`--progress`, `--stats`, etc), that was resolved in #302
2. verbosity levels which i understood as `--verbose`, `--debug` and so on

i understand you disagreed with my previous objections and have a different perspective, but i found it important to manifest it again in a last ditch attempt to preserve POLA (Principle Of Least Astonishment) where most commandline tools have `--verbose` and not `--log-level`. after re-reading our discussions in #233, i still do not understand the reason behind the objection of mapping `-v` with log levels.

also, sorry for the wall of text, but i felt i needed to explain my ideas more clearly and in details.

**Comment by ThomasWaldmann** [comment]
a) it's not our business to decide the logging level the user wants. usually they will want info or warning, in some cases they might want debug or error.
b) no, that's not the case. this tickets topic is as simple as replacing the hardcoded loglevel value with the value given on the commandline. point.

So please do not spoil every ticket with that loglevel vs. verbosity discussion, i won't participate in that discussion any more (repeating the same arguments you seem to not understand or not wanting to understand).

**Comment by anarcat** [comment]
i tried and tried to understand what your point is. i asked for clarification and pointers to previous discussions. i re-read all the comments in #233, even quoting one of them where you seem to agree with what i am proposing.

it is not i do not (want to) understand the arguments you are "repeating": i just don't see which arguments you are referring to. but okay, i've moved the `--verbose` discussion to #427 and will leave this ticket, which seems to be already decided...
