### ISSUE TITLE
reverse --verify-data feature

### ISSUE THREAD

**Issue by AshTex** [borgbackup/borg#4268]
### The problem
No tool exists that will ensure the latest backup does in fact reflect the local files. Essentially something that automates `borg mount` and then `rsync --dry-run --itemize-changes -aSHAX`.

Currently this is *half* implemented. `check --verify-data` compares the remote repo files to the repo's hash table. However the hash-table is never compared to the local files that it is backing up. It is assumed to be accurate despite potentially being edited thousands of times over a huge timespan. This seems like a lot of faith to place on many cumulative actions. 

### Potential solution
A reverse of the `--verify-data` functionality. Something that downloads the latest hash table from a fresh backup and compares all the hashes against the local files, ensuring it is a true representation of the filesystem being backed up. 

This then only requires the download of the hash-table, no decryption or decompression occurs and so will hopefully be less expensive (but still only 'half' of the check). 

### Caveats

This could only be performed directly after creating a backup, as any changes to the local files would mean the check fails as the hashes wouldn't match. This is exactly what the check is for though, as directly after a back up they should be identical to what is present in the remote repository.

**Comment by AshTex** [comment]
Right, and there's been no use-case need to have a meta-data check function? Or some sort of compare-to-local?

**Comment by ThomasWaldmann** [comment]
The id-hash (MAC) is computed directly after reading / chunking the input file, the encryption envelope MAC directly after compressing and encrypting the chunk. So if the borg client hardware works correctly and does not e.g. corrupt data in memory, we can just check repo data against repo MACs to know whether anything got corrupted after the MACs were computed.

This works for any archive, not just for the case where you still have exactly the same data locally.

So your compare-to-local would only be better (due to saved traffic) for that special use case, if:
- one assumes local data did not change (e.g. the same snapshot is still active or data is static)
- one assumes that data might be corrupted while/between reading from disk and computing the MAC
- one assumes that for a subsequent read of same data, the corruption won't be the same, so it would result in a different MAC.

compare-to-local would be worse, as:
- as it does not read the chunk data from the repo, it does not check potential corruption on the server which could occur between receiving the data from the network and computing the crc32. in that case, the computed crc32 would be correct, but the stored data could be wrong. but we only notice that if we read it and verify the MACs clientside.
- it could be confusing as a normal file change would result in a similar check-fail as data corruption.

**Comment by ThomasWaldmann** [comment]
--verify-data is about verifying all **content** data.

to just verify the archive metadata stream, you don't need this option.

**Comment by dsteinkopf** [comment]
I am also looking for the function AshTex asked for initially: I'd describe my requirement / use case like this: Compare the local files to those in the backup archive in order to detect any local changes. Thus: Show a diff. That goal is to see if my long-lasting local files (stored there for years) are still correct and did not get corrupt.

Of course the "diff local to archive" would also display any intended changes to the local files since the latest (or specified) backup.

`borg check --verify-data` verifies the integrity of the remote archive - so in my eyes it would be ideal the have something like "`borg check-local`" that verifies the integrity of my local data (byte by byte).

Any other thoughts?

**Comment by mbunkus** [comment]
I have need for such a tool as well. Use case: I've just had a nasty I/O problem with the underlying storage, and subsequently filesystem errors & a kernel panic. After file system recovery, I'd like to compare what's left on storage to what's in the backup archive.

I would also like to have two modes:

1. A fast mode only comparing the meta data (would be enough to list regularly changed files as well as files having been added or removed),
2. A thorough mode doing block checksum comparison, too (this would be the true verification).

After a recovery like the one I'm currently doing a check with the proposed fast mode would be invaluable to determine if important data was lost. And the thorough mode would be invaluable for when you're dealing with hardware issues leading to silent data corruption.

Please reconsider.

**Comment by ThomasWaldmann** [comment]
@mbunkus maybe that? did not try it myself.

https://borgbackup.readthedocs.io/en/stable/faq.html#how-can-i-compare-contents-of-an-archive-to-my-local-filesystem

**Comment by mbunkus** [comment]
Thanks. That does take care of my second point. But that's the slow option — and if your amount of data is in the region of several TB this really makes a difference.

True, I can still use the combination of `borg mount` and `rsync --dry-run --itemize…` the OP suggested for my first case, but that still runs into the problem of the FUSE mounting not supporting ACLs.

**Comment by ThomasWaldmann** [comment]
Anyway: this is the wrong ticket to discuss the feature you would like.

`--verify-data` is a specific sub-functionality of borg check and (as the rest of borg check) used to verify the integrity of a repository / borg archives (whether checksums are ok, whether MACs are ok == whether the repo and archives look good / consistent / not internally corrupted).

There are other ticket(s) about comparing an archive to the local filesystem.
