### ISSUE TITLE
Explain milestone system

### ISSUE THREAD

**Issue by milkey-mouse** [borgbackup/borg#4385]
This is a pretty minor issue, but at first I didn't understand the milestones in the issues (`hydrogen`, `helium`). Perhaps somewhere in the Development section of the docs we could mention their "meanings" wrt borg versions?

From what I gather `hydrogen` is a milestone for borg 1.2 features, `helium` is borg 1.3, and `lithium` refers to borg 1.4. Is this correct? Is `fluorine` borg 2.0?

**Comment by FabioPedretti** [comment]
I suppose they are in the same order of their atomic number, so your statement should be correct. I also suppose they are used instead of numbers so that eventually, for example, helium could be called 2.0 if needed.

![Periodic table](https://upload.wikimedia.org/wikipedia/commons/2/2e/Simple_Periodic_Table_Chart-en.svg)

**Comment by ThomasWaldmann** [comment]
@milkey-mouse that was the idea, right. but the main reason was to go away from version numbers and still have a way to talk about a milestone, even if we find out that we need to change the version number of that milestone. so name stays, version number changes.

@FabioPedretti because flourine breaks everything (see breaking stuff in 2.0).

**Comment by milkey-mouse** [comment]
I see. I suppose if someone else is confused they will search for "milestone" in issues like I did and find this.
