### ISSUE TITLE
Unable to view folder contents on a different machine/account (permission error)

### ISSUE THREAD

**Issue by jagrg** [borgbackup/borg#4433]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue/question

#### Your borg version (borg -V).
1.1.9
#### Operating system (distribution) and version.
Ubuntu 16.04
#### How much data is handled by borg?
~100 GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg init --encryption=keyfile-blake2 /media/user/mybackups

borg create --verbose --stats --progress --compression lz4 --exclude-caches /media/user/mybackups::$(date +"%Y-%m-%dT%H%M%S") $HOME

borg mount /media/user/mybackups /home/user/mount_point
```
## Describe the problem you're observing.

I use borg to backup my $HOME folder and it works great. However, when mounting the fs using a different user account, nautilus tells me I do not have the permissions necessary to view the contents of the repo (in this case the $HOME folder). In the manual it [says](https://borgbackup.readthedocs.io/en/stable/quickstart.html#important-note-about-permissions) that for a local repository (external HD in my case) I have to always invoke borg as the same user. I'm confused. Is it saying it's not possible to access the repo from a different user?

I tried changing permissions but the fs is read-only. Is there anything else I can do to access that repo?

**Comment by ThomasWaldmann** [comment]
The hint to always use same user to access (read/write to) a borg repo is completely unrelated to your problem because the permission problem avoided by that is about accessing the repository files, not the backed up files stored inside a borg archive.

What you have here can be due to multiple issues:
- fuse permissions handling, read `man fuse` and docs about `allow_other` mount option and fuse configuration.
- `borg mount -o...` mount options (see docs)
- having different numerical user ids for same user name on different machines
- the usual unix permissions checking based on uid/gid/permission bits

**Comment by jagrg** [comment]
Thanks for your help. I added `user_allow_other` to `/etc/fuse.config` and from another account I did:

`borg mount -o allow_other /media/user/mybackups /home/user/mount_point/`

It prompts for the passphrase and mounts ok, however I still cannot access the $HOME folder, so I think the issue may have something to do with your last point. For example, if I do `ls -l` from \home I get:

```
drwx------ 83 user1
drwxr-xr-x 19 user2
```

Do you think I should change permissions for user1?

**Comment by ThomasWaldmann** [comment]
Guess you could get root and then access the already mounted stuff.

**Comment by jagrg** [comment]
That works, yes. Thanks a lot!
