### ISSUE TITLE
What is the bottleneck for an initial backup?

### ISSUE THREAD

**Issue by chrissound** [borgbackup/borg#4486]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Possible bug. I'd hope the backup would be faster, and I'm not sure what is limited the speed? 

#### Your borg version (borg -V).

borg 1.1.9

#### Operating system (distribution) and version.

Linux nixos 4.14.107 #1-NixOS SMP Tue Mar 19 12:13:25 UTC 2019 x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.

Usual spinning disks - no SSDs.

source: 2x 2TB SATA ext4 in raid1
destination: 2TB SATA ext4 (via USB) 

#### How much data is handled by borg?

1.5TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
(I think I ran the below): 
`sudo borg create  --stats --compression lz4  ~/mount/raidBackup::Initial ~/mount/raid18t`

## Describe the problem you're observing.

Backup attempt took ages - close to 10 hours (not sure what % it got to - but I didn't run it to completion), I'm not sure what the bottleneck is however, as CPU usage was low as well as IO according to `iostat`.

#### Include any warning/errors/backtraces from the system logs

benchmark:

```
C-Z-BIG          93.10 MB/s (10 * 100.00 MB all-zero files: 10.74s)
R-Z-BIG         731.64 MB/s (10 * 100.00 MB all-zero files: 1.37s)
U-Z-BIG         352.75 MB/s (10 * 100.00 MB all-zero files: 2.83s)
D-Z-BIG         992.02 MB/s (10 * 100.00 MB all-zero files: 1.01s)
C-R-BIG          83.98 MB/s (10 * 100.00 MB random files: 11.91s)
R-R-BIG         150.93 MB/s (10 * 100.00 MB random files: 6.63s)
U-R-BIG         371.97 MB/s (10 * 100.00 MB random files: 2.69s)
D-R-BIG         103.88 MB/s (10 * 100.00 MB random files: 9.63s)
C-Z-MEDIUM      111.21 MB/s (1000 * 1.00 MB all-zero files: 8.99s)
R-Z-MEDIUM      482.14 MB/s (1000 * 1.00 MB all-zero files: 2.07s)
U-Z-MEDIUM      529.21 MB/s (1000 * 1.00 MB all-zero files: 1.89s)
D-Z-MEDIUM      978.12 MB/s (1000 * 1.00 MB all-zero files: 1.02s)
C-R-MEDIUM      101.55 MB/s (1000 * 1.00 MB random files: 9.85s)
R-R-MEDIUM      154.41 MB/s (1000 * 1.00 MB random files: 6.48s)
U-R-MEDIUM      513.54 MB/s (1000 * 1.00 MB random files: 1.95s)
D-R-MEDIUM       72.54 MB/s (1000 * 1.00 MB random files: 13.79s)
C-Z-SMALL        13.99 MB/s (10000 * 10.00 kB all-zero files: 7.15s)
R-Z-SMALL       106.43 MB/s (10000 * 10.00 kB all-zero files: 0.94s)
U-Z-SMALL        29.46 MB/s (10000 * 10.00 kB all-zero files: 3.39s)
D-Z-SMALL        91.29 MB/s (10000 * 10.00 kB all-zero files: 1.10s)
C-R-SMALL        10.54 MB/s (10000 * 10.00 kB random files: 9.49s)
R-R-SMALL       104.07 MB/s (10000 * 10.00 kB random files: 0.96s)
U-R-SMALL        20.22 MB/s (10000 * 10.00 kB random files: 4.95s)
D-R-SMALL        47.82 MB/s (10000 * 10.00 kB random files: 2.09s)
```

**Comment by ThomasWaldmann** [comment]
The benchmark for your machine looks quite ok.

The reason why borg isn't faster is because it is rather sequential non-pipelined internally and uses only one thread. So it is expected that it takes quite a while for bigger amounts of data. Multithreading is planned for the future (don't hold your breath).

This is no big problem though, because you can interrupt the backup and start another one later again without losing much overall progress. By default, it checkpoints every 30 minutes.

And once you got your initial backup completed, it will be very fast as it will only add new and changed data.

lz4 compression is the fastest (and also the default).

Maybe you want to add `--progress`. You'll see how much you have already, but it won't give you an ETA.
