### ISSUE TITLE
files cache semantic, local disk and memory consumption and performance

### ISSUE THREAD

**Issue by cruftex** [borgbackup/borg#4488]
The behavior around the file-cache seems to me a bit tricky and has a bunch of pitfalls that are performance and/or safety related. Basically I understand the necessity.

As far as I read and understood the documentation borgbackup is using a file-cache. Based on the cache content, it decides whether the file will be investigated in deep and hashed and chunked and actually backed up.

Since the actual backup strategy is not the same on each run, there is a slight margin of failure here. A possible scenario of failure would be:

- default change detection is not reliable, because of OS, filesystem or nature of application
- files get backed up correctly, because the cache content always expires
- cache content does not expire any more, maybe because of archive numbers is reduced
- files do not get backed up reliably and no one notices

To make the behavior consistent, the decision could be based on the archived data and the file-cache only be used to speed things up and reduce the need of data exchange with the borg server.

Probably there are a lot of technical issues while that is not so easy (Maybe no inode number is stored in the archive?).

Another issue is the needed storage space on the backup client. In case there is no sufficient space, it is undesirable that borg is doing chunking/hashing.

**Comment by ThomasWaldmann** [comment]
borg always does full backups, so all files in the backup input files set will be in the created archive.

so there is no "skipping" of files, all files are processed. it is just that it does not read/chunk a file again if the file is considered unchanged, but rather reuses the chunk list from the files cache. it will still read all the metadata from the fs as these are not cached (e.g. acls, xattrs).

ctime/inode/size based change detection should be rather safe. ctime is updated for all changes in file content or metadata of a file and this is enforced by the kernel and not under the user's / userspace processes' control. this is the default in borg since quite a while (1.1.x).

mtime should be normally also ok, but there are some known issues with tools which modify the mtime in unexpected ways (iirc e.g. a picture tool resetting the mtime to the previous value after processing the picture). While these tools might mean well from their PoV, this is of course completely wrong and dangerous from the PoV of change detection by sync or backup tools. This is why we stopped using mtime by default.
 
So, we use something safe by default and there is the option to configure it otherwise if your filesystem does not correctly support ctime / inode / size (which is not borg's problem if you use such a fs and decide to choose less-safe files-cache settings to speed it up on that fs).

There is also the option to switch off the files cache, but that will slow down backups of unchanged files significantly (it would always read, chunk, hash, dedup).

The files cache always expires after N generations (== after N backups), so I don't see an issue here.

Reading a (potentially remote, encrypted, compressed) archive is rather expensive (and only possible in a sequential way) and I don't think we should do that if we can have a local, in-memory, random-access files cache.

The space vs. time thing is a very fundamental issue often found in cs, guess we have to live with that. You can either optimize for one or the other.

So, considering the above, I don't see how we could improve something. Did I miss something?

**Comment by cruftex** [comment]
Hi @ThomasWaldmann, thanks for the elaborate response!

> The space vs. time thing is a very fundamental issue often found in cs, guess we have to live with that. You can either optimize for one or the other.

I didn't say that the cache makes no sense. In fact I am a big fan of caching. I am the author of a Java caching library (cache2k) and I can lecture for hours of the pros and cons of different caching eviction algorithms.

The design of the file cache is great and works well in my context and probably for many most others, too.

Still, what I would like to see:

- The backup strategy is always identical, no matter whether there is a cache
- If there is no space for cache data on the client have a fall back option that is much faster then do chunking which means all data needs to be read from the disk

> Reading a (potentially remote, encrypted, compressed) archive is rather expensive (and only possible in a sequential way) 

Isn't it possible to retrieve the file list and metadata of the last 20 archives in a fast way? That should actually comprise the file cache contents.

Another design decision would be "Where to keep the lookup index?" That can be at the server or the client. I would prefer minimizing the client requirements.

To be clear, I don't see a strong need for this. borgbackup is great! Maybe its worth considering for version 2.

**Comment by ThomasWaldmann** [comment]
Finding the "right" archive(s) in the repo means:
- being able to relate current "borg create" action / data set to past archive names of same action / data set - **not implemented**

Reading an archive means:
- possibly remote data transfer, decryption, decompression, msgunpack

Building a files cache (in memory):
- feeding some of the metadata and the chunks id list into a big dict, msgpack

So, we would need to add `--prefix` (and also via glob etc.) as we have it in `borg prune` to `borg create` also - that way we can match corresponding archives, find the latest one(s), read them and build a in memory files cache.

Quite a bit of an effort to just save some local on-disk storage (with yet unkown performance) - do you want to make a PR about this so we can try it out?

**Comment by ThomasWaldmann** [comment]
As a side note:

if we start identifying datasets by their relation to archive name patterns, we could use this as a key to split the currently all-in-one files-cache into K (number of keys) separate files-caches.

Faster loading times, less memory needs.

**Comment by cruftex** [comment]
> - being able to relate current "borg create" action / data set to past archive names of same action / data set  **not implemented**

As you mentioned in the side note, the files cache has the same problem. With the remote archive it gets worse, because the backup can come from different machines. Or it gets better, because the backup of the same volume is done by different nodes in a cluster, depending what node has capacity.

**Comment by cruftex** [comment]
> if we start identifying datasets by their relation to archive name patterns, we could use this as a key to split the currently all-in-one files-cache into K (number of keys) separate files-caches.
> Faster loading times, less memory needs.

That's quite a cross cutting concern in your code base, I think. The only clean approach would be to introduce a real volume name as a parameter.

Alternatively, the user can use different `BORG_CACHE_DIR` settings for each volume.

With "volume" I mean the data under a specific mount point which usually gets a name, e.g. "root" or "home"

**Comment by cruftex** [comment]
> Quite a bit of an effort to just save some local on-disk storage (with yet unkown performance) - do you want to make a PR about this so we can try it out?

There is an ironic sub tone here, and I feel not comfortably when reading it. The sentence shortens and simplifies the facts to make a point, but actually you spend quite some time to explain details and get facts right. The latter, I appreciate a lot.

> some local on-disk storage

There are "some" problems with "some local on-disk storage":

- "some" is undefined and depends on the amount of files saved. So the backup needs O(n) space on disk and probably also in memory (?). That may lead to additional operational burden, in CS they teach, that you should avoid O(n).
- Maybe there is no local storage, if you want to backup a kubernetes cluster
- In case the backup runs on different nodes each time, local storage does not help you

So let's update the requirements:

- The backup strategy is always identical, no matter whether there is a cache
- If there is no space for cache data on the client, don't degrade dramatically in performance and make it necessary to read all data, e.g. by having a fall back option to retrieve the recent file metadata from the archived backup
- The needed resources for backup should be constant and not rise with the amount of data being backed up

Probably, the more people considering borgbackup, the more it will be used in environments where this becomes more important.

I am totally fine if you close the issue or keep it as idea for the "far future" .

**Comment by ThomasWaldmann** [comment]
There's nothing ironic about my comment. I was just asking whether you want to invest the time needed to do that experimental code change (and make a PR) that would just save some local disk space. The specific performance is unknown yet, but loading it from remote is likely to be slower than loading from local disk.

Keeping data about N files in less than O(N) space -> good luck with that! :-)

Introducing volume-name (mount point related) as backup set identifier -> nope, because backup sets are not required to be single volume. E.g. backing up /etc /home /var /usr/local into 1 archive.

But as I said, we already identify the backup sets / archive names relation for prune, we can just do the same for create and rather re-use an already present concept than adding a new one.

In general i think this ticket should be superseded by smaller scope and more specific tickets:
1. split files cache: using a dataset id for borg create (id == prefix / pattern, like in prune), splitting the files cache by id (this can be done with the current local files cache approach, just use multiple files)
2. rebuild files cache from archive(s): at the beginning of borg create, if there is no local files cache, build it in memory from archive(s) found via the prefix/pattern. at the end of borg create, store it on disk (to save time) or not (to save space). 

With that approach, there are obvious benefits for 1 as well as for 2.

**Comment by ThomasWaldmann** [comment]
Files cache might change in future, see #8385.
