### ISSUE TITLE
Speed test, similar to openssl speed

### ISSUE THREAD

**Issue by cruftex** [borgbackup/borg#4490]
It would be great and possible not much effort to have a command like `borgbackup speed` that writes out the throughput for some basic operations:

- hashing/chunking in bytes per second
- encryption in bytes per second
- read of file status in files or ops per second

**Comment by ThomasWaldmann** [comment]
hashing and encryption speed: see openssl benchmarks. you can either look them up on the web or run them on your machine using openssl. these speeds are usually quite high, AES encryption is accelerated on modern CPUs. For hashing, sha256 is not the greatest, because of this we added the faster blake2b in borg 1.1.

file status: i assume you mean `stat` here? or maybe also directory traversal and files cache lookup? You can see that speed if you back up unchanged data again. borg will be quite fast then.

borg also has `borg benchmark` command already, that does some more practical measurements, creating, reading, updating, deleting data.

**Comment by cruftex** [comment]
Thanks for the answer. Is blake2b identical to blake2b512?

I get here:

openssl speed -evp blake2b512
Doing blake2b512 for 3s on 16 size blocks: 8714317 blake2b512's in 3.00s
Doing blake2b512 for 3s on 64 size blocks: 8775905 blake2b512's in 3.00s
Doing blake2b512 for 3s on 256 size blocks: 5412167 blake2b512's in 2.98s
Doing blake2b512 for 3s on 1024 size blocks: 1816106 blake2b512's in 3.00s
Doing blake2b512 for 3s on 8192 size blocks: 252330 blake2b512's in 3.00s
Doing blake2b512 for 3s on 16384 size blocks: 126849 blake2b512's in 3.00s
OpenSSL 1.1.0g  2 Nov 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(int) aes(partial) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\"" 
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
blake2b512       46476.36k   187219.31k   464937.84k   619897.51k   689029.12k   692764.67k

> file status: i assume you mean stat here?

The amount of work/syscalls borg needs to do to scan a file.

**Comment by ThomasWaldmann** [comment]
We only use 256 bits from blake2b result (otherwise memory needs for the chunks hashtable would almost double).

If you're interested in the syscalls borg is doing, run borg 1.1.x and master branch through strace and you'll see. Or search the issue tracker for some posts with strace logs (did some when switching master to work mostly on FDs instead of filenames).

**Comment by ThomasWaldmann** [comment]
Closing this, I guess we do not need to add benchmarks for the crypto algorithms and we already have some for highlevel stuff.

**Comment by cruftex** [comment]
I still think there is some value here, since I saw a few issues discussing about hardware requirements. "borg speed" can be used to investigate whether the hardware may be a bottleneck. It's not about benchmarking.

Maybe we can leave it open for a while and see what others say?

**Comment by ThomasWaldmann** [comment]
to find out whether it is way too slow on your hw, you can also use `borg benchmark` and it'll give more meaningful numbers.
