### ISSUE TITLE
use a different hash for file_path (files cache)?

### ISSUE THREAD

**Issue by varuzam** [borgbackup/borg#4511]
Changing the line https://github.com/borgbackup/borg/blob/df5641ad2757d44bbd863ab1133309dbecea3a89/src/borg/archive.py#L1202
to
`path_hash = hash(os.path.join(self.cwd, path))`
saves 30 bytes per each element in file cache dict.

**Comment by ThomasWaldmann** [comment]
```
>>> b = b"012345678901234567890012345678901"  # 32 bytes = 256bit = like current id hash
>>> i = hash(b)  # seems to result in a python `int` (signed 64bit range)
>>> sys.getsizeof(i)
36
>>> sys.getsizeof(b)
66
```
So yeah, python's `hash()` is 30bytes less than our `id_hash()`.

So the questions are:
- can we use it?
- what are the consequences?
- compatibility?

**Comment by ThomasWaldmann** [comment]
Problem: `hash(same_value)` (by default) has only the same result for same python interpreter:
```
user@development:~$ python
Python 3.6.0 (default, Dec  2 2018, 22:50:02) 
>>> hash("foobar")
390169116132606473

user@development:~$ python
Python 3.6.0 (default, Dec  2 2018, 22:50:02) 
>>> hash("foobar")
-3756096016081911912
```

**Comment by ThomasWaldmann** [comment]
So let's think about using a truncated `id_hash` that gives a 64bit result:
```
>>> b = b'0' * 32  # 256bit
>>> sys.getsizeof(b)
65
>>> b = b'0' * 8  # 64bit
>>> sys.getsizeof(b)
41
```
So that would save 24 Bytes per entry.

**Comment by ThomasWaldmann** [comment]
Collisions:
- we do **not** store the original value of `file_path` into the files cache dict
- we **only** store `h(file_path)` to save memory and use it as a lookup key
- with a cryptographic quality 256bit hash, collisions are no problem
- with a 64bit hash, collisions are a problem (*)

(*) it could be that we get an entry for a different path than we were looking for. then it would compare some stat values (configurable, usually size, ctime, inode number).

in case of a collision, these will often not match, then there is no problem and no wrong data from the files cache is used.

but we can not completely rule out that the stat values do accidentally match (esp. if user configures to only use size and mtime, because inode numbers are not stable). especially if one has a huge amount of fixed-size files with maybe even same mtime, it could wrongly confuse one file with another and use the wrong cached chunks id list, so the backup would be with wrong content data.

So, AFAICS, we can't do that.

**Comment by varuzam** [comment]
Perhaps it would be nice to implement this as optional  and give choice to
user via command line argument
Borg is awesome but its memory consumption is too high

**Comment by ThomasWaldmann** [comment]
You noticed that there is already an option to switch off the files cache completely?
Saves a lot of memory, but has a big performance impact as it will chunk/hash all files.

About files cache memory consumption:

Not sure if saving 30 bytes per entry would help you long term.

From the docs: `files_cache_usage = total_file_count * 240 + chunk_count * 80`

So, for the best frequent case (file with 1 chunk), it would reduce from 320 to 290 bytes - at the risk of having a collision and with making the cli interface more complex and its docs longer.

**Comment by varuzam** [comment]
Disabling the file cache increases a disk load.

How is this 240 bytes for file entry calculated?

In my test environment with ~2000000 file entries my test python script 
with ONLY file cache uses about 390 MBytes.  it is roughly 204 bytes for 
each (file cache entry + all file's chunk ids). The entries are packed 
by msgpack.


regarding the collisions. I checked  path hashes, hashed by python's 
hash(),  of 120 millions files  on my file server. There was no 
collisions. perhaps, 64bit is enough for most cases? or 128bit?

According to this https://en.wikipedia.org/wiki/Birthday_attack it is 
possible for 64bit hash to get one collision in 2^32 ~ 4 billions 
hashes. hmm. Does someone use the borg for backing up such huge count of 
files?

**Comment by ThomasWaldmann** [comment]
Guess when I made that formula, I just added up the memory needs for all the "item" dict elements and the dict itself. Not sure if I considered the msgpack packing.

In general, the formulas can't be super precise anyway due to all the factors that play a role.

Considering the collisions: guess with 120M you don't need much luck to not have a collision, but as you found, one might be able to reach the point where one gets them.

**Comment by varuzam** [comment]
As far as I know the python dict hashes the key passed to its and uses the key internally for getting/setting data. For me it means that no matter how strong hash alghoritm used for the key, internally it is hashed again by python hash() anyway. 
I suggest to get rid of this double hashing. It saves memory and cpu time
Does that make sense?

**Comment by ThomasWaldmann** [comment]
I didn't look at the dict implementation of cpython yet, but I assume it somehow works like that:

Given: dict d, key k, hash function H, random seed s, hash table HT.

`v = d[k]` would do:
```
h = H(k, s)
start searching the hash table at bucket index h % table_size.
is h == H(stored_key, s)?
- yes: we have found the right entry, iff also k == stored_key (full comparison). return value HT[index],
- no, we had a collision at insert time and need to look at next index. repeat until k found or a free bucket is encountered or hashtable has been traversed completely.
```

You see that for correct operation, it needs to have the key stored in the hashtable to be able to fully compare it to k to make sure it is identical (to detect different values, looking at h / h' is good enough).

In our case that would be the file_path (which can be rather long for deeply nested directories, so would waste a lot of memory). This is why borg uses id_hash(file_path), which is only 32b long **and** can be considered equivalent to file_path (without likely collisions). We only persist the id_hash dict keys to disk and lose knowledge about file pathes.

If you neither store file_path nor id_hash(file_path), how could you be sure enough to avoid the collisions of H and how would you be able to find the for-sure right bucket?
