### ISSUE TITLE
{hostname} have unexpectedly changed to short in v1.1.9

### ISSUE THREAD

**Issue by TobbeJ** [borgbackup/borg#4533]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.9

#### Operating system (distribution) and version.
Fedora 28

#### Hardware / network configuration, and filesystems used.
not relevant

#### How much data is handled by borg?
Many tb

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes

Since v1.1.9 the placeholder {hostname} have changed from fqdn to just hostname.
This change was completely unexpected and have broken my scripts for backup and purging since purge no longer matches properly with the old backups.

So this must be considered a bug since it is unexpected behavior between two releases and hostname from shell doesn't match {hostname} tag used by borgbackup any more which is conuterintuitive.

#### Include any warning/errors/backtraces from the system logs

Not relevant

**Comment by ThomasWaldmann** [comment]
IIRC:

`hostname` placeholder ever has been intended to be short hostname, not long fqdn - that's why there ever has been `fqdn` placeholder additionally.

depending on the system configuration (contents of /etc/hostname, which is a bit badly documented sometimes, but must be the short hostname only), hostname placeholder has been expanded sometimes to short hostname, sometimes to long fqdn though. this was a problem and it was worked around in borg now always resulting the short hostname for the hostname placeholder even if the system isn't configured correctly.

sorry about any inconvenience this change has caused, but it had to be fixed to always yield the intended result.
