### ISSUE TITLE
Difficult to recover from "Cache is newer than repository"

### ISSUE THREAD

**Issue by bjornfor** [borgbackup/borg#4631]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg 1.1.10

## Describe the problem you're observing.
My borg repo somehow got into this "Cache is newer than repository [...]" state and borg would not do any operation on it. I tried to following steps, but neither worked:

* delete ~/.cache/borg directories (locally and remote)
* run ```borg delete --cache only $repo```

What worked in the end was removing (or renaming) ~/.config/borg/security, which was mentioned in https://github.com/borgbackup/borg/issues/3428#issuecomment-380399036.

Perhaps a rewording of the message could help users? Instead of saying "Cache", explicitly say which directories are being used for the timestamp check?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
No, cannot reproduce. Perhaps a hard machine shutdown or aborted borg process caused it.

**Comment by ThomasWaldmann** [comment]
Did you do any unusual operation on your repository?

Like restore it from a backup?

**Comment by bjornfor** [comment]
Oh, right, that is actually what happened (restore from backup). I completely forgot! What happened is that I migrated the backup repos to a new host, but then a bit later reverted back to using the old host, making the clients effectively see the remote repos "go back in time", like in a restore from backup scenario.

So this is more or less a duplicate of https://github.com/borgbackup/borg/issues/3428 then.

**Comment by simonmichael** [comment]
Thanks for borg backup!

Here's how I got into this situation: I was trying to recreate a remote borg repo to rechunk and recompress it. Didn't want to do it in place. --target doesn't let me recreate the whole repo. So I used ssh cp -pr OLDREPO NEWREPO and proceeded to borg recreate NEWREPO in place. It asked me to confirm NEWREPO's new path, which I did. Now I have two repos with the same id, which confuses borg. Like the OP, I found it difficult to recover. I tried every variation of borg delete [--cache-only] [--force [--force]], rm -rf ~/.cache/borg, but had to search the web to find #3428 and ~/.borg/security.

**Comment by gerroon** [comment]
@simonmichael 

How did ypu resolve this issue?

**Comment by simonmichael** [comment]
Sorry I don't remember, but I see some mention on the linked issue of a `.config/borg/security` file.

**Comment by mihalycsaba** [comment]
Tried setting it like a month in the past, a day in the past, setting in the future, nothing helped.

**Comment by tomchiverton** [comment]
Doesn't work

```
falken@wopr:~$ borg delete --cache-only
falken@wopr:~$ borg create --stats --compression auto,zstd \
        $BORG_REPO::{hostname}-{user}-{utcnow} \
        /home/falken/Documents 
Cache is newer than repository - do you have multiple, independently updated repos with same ID?
```

Neither does `touch -t 202001010234 ~/.config/borg/security/*/manifest-timestamp`

**Comment by tomchiverton** [comment]
I had to remove the folders `~/.config/borg/security/*` and `.cache/borg/*` to recover.

I had restored the (SSH based) repo location from backup. 

Borg should offer to do all this for me, or at least link to some documentation about the how and why.

v1.2.4 on Fedora 38

**Comment by ThomasWaldmann** [comment]
@tomchiverton Yeah, guess the UX could be improved there.

BTW, that "touch" was ineffective, that changes the timestamp of that file. Look inside the file, the timestamp is there **as content**.

You can just remove that file.

**Comment by tomchiverton** [comment]
Even better would be for Borg to say that if you expected this eg the server was replaced, press 'f' to continue and recover
-- 
†øღ

**Comment by afaianswq** [comment]
This is quite a design failure to not let operator choose how to handle this situation. A simple "are you sure you want to continue" question would solve most of the problems.

**Comment by ThomasWaldmann** [comment]
That exception is indicating that something is going **fundamentally wrong** or **something rather unusual happened** , so the solution should be to fix the root cause (== not doing it wrong / checking if somebody might be attacking you / ...) rather than making it more comfortable to deal with it.

Potential root causes:
- a repo was lost and the recovered from an older backup by the admin
- admin is trying to use borg with multiple repos with same ID (that is unsupported as it confuses borg)
- a repo-side attacker has rolled back your repo to a previous state trying to trick you into AES-CTR mode nonce reuse

Depending on what precisely happened, this can be an inconvenience, a security risk or a cause of further malfunction.

The good news is that the crypto part of this will be resolved in borg2.

**Comment by afaianswq** [comment]
Nothing fundamentally wrong in an attempt to resume backups into a restored from a snapshot borg repo. That's one of many examples from the top of my head. Another example: moving backups from one storage to another without interrupting regular backups process, and just switching paths when everything is ready. Anyway, I definitely know better whether I'm doing something wrong or not, and it's not for the app to decide on this for me, app must ask if I know what I am doing, not dictate me what to do.

**Comment by afaianswq** [comment]
One more thing, we use borg purely as a backup tool and don't need any encryption and other security measures it offers. They simply not applicable here. Most of them can be disabled via env vars, i.e. BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK and BORG_RELOCATED_REPO_ACCESS_IS_OK, and it would be very nice to have similar vars for the rest of "smart" borg features like this one.

**Comment by AndreasHoffmann2** [comment]
This should definitely be made easier!
I just had to revert a couple of backups to an older state, expecting that borg would just pick up where it left off (just as Veeam and Duplicati both did).
But instead of just working again, borg refused and I am still trying to get it  up and running.

And now, after finding this thread, I am deleting some folders without really knowing what I am deleting and hope that I do not destroy anything else.

If you guys do not want to make too easy for the user, you could make him type something else than "y" before deleting the cache.

**Comment by ThomasWaldmann** [comment]
The "solution" is in our FAQ since quite a while:

https://borgbackup.readthedocs.io/en/stable/faq.html#this-is-either-an-attack-or-unsafe-warning

**Comment by ThomasWaldmann** [comment]
I cleaned up most of the comments above and added a pointer to our docs.
