### ISSUE TITLE
Suggestion: faster startup times using pyinstaller --onedir

### ISSUE THREAD

**Issue by russelldavis** [borgbackup/borg#4641]
On my maxed-out MacBook Pro, the fat-binary version of borg takes 200ms longer to start up than the regular version. That time is all spent unpacking everything to a temp directory.

It's not a huge amount of time, but it's not unnoticable either. Especially because borg is already relatively fast -- that extra 200ms is a 1.66x multiplier on the baseline time of 300ms. (For a long backup job, the difference wouldn't matter, but borg has a lot of options, and running the various `borg help` commands is pretty common.)

If borg provided releases built using `pyinstaller --onedir` (in addition to the current `pyinstaller --onefile` builds), users would get the faster speed, without, as far as I can tell, any downside.

I get the appeal of a single file that doesn't need to be manually unzipped, but for users installing via a package manager, that work is abstracted away anyway. With homebrew, it would be trivial to update the formula (and I'd be happy to do so). I assume other package managers would be similar. Users installing manually would still be able to download the fat binaries.

Thoughts?

**Comment by ThomasWaldmann** [comment]
Did you try just catching whatever the borg binary unpacks to the temp dir? Can that be used?

I'ld rather not like to offer other binary packages:
- it's additional release work
- needs docs
- requires the user to choose one or the other
- (...)

For distribution packages, the general idea is to create a package starting from source and requiring the additional stuff (like libraries) via package requirements rather than using the fat all-in-one binary. See e.g. how it is done for the Debian package.

**Comment by ThomasWaldmann** [comment]
I'm closing this as it is a distribution issue and should be raised at the distributors.
