### ISSUE TITLE
Borg modifies existing files in data folder

### ISSUE THREAD

**Issue by fthdgn** [borgbackup/borg#4676]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## System information. For client/server mode post info for both machines.

borg 1.1.9

#### Operating system (distribution) and version.

Raspbian GNU/Linux 10 (buster)

#### Hardware / network configuration, and filesystems used.

FS: ext4

#### How much data is handled by borg?

~100MB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create repo::archive path

## Describe the problem you're observing.

I am planning to use borg with "rclone sync". However every time borg creates a new archive it renames files inside data folder and modifies contents of them. Thus "rclone sync" uploads everything from start.
Is there any way to tell borg don't modify and rename existing files inside data folder?

Example:
My source includes many small files and a large file.
After first "create", there is a large file on path 0/data/64 with sha256 62694f840e1ff9e24d83333208a21ca2793c6e336019d5fc9abc0d3e8231f25b.

After second create, the large file is moved to 0/data/68 and its sha256 become 
22f68bd891f302149b72e96e40640148c116a3b22329a83b18cfcd6713f10ae8.

**Comment by ThomasWaldmann** [comment]
borg does not modify existing segment files.

but when compacting, it reads the contents of non-compact segment files and writes them into new (compact) segment files, then deletes the superseded non-compact segment files.

borg < 1.2 compacts always when committing the repo (== for all repo-writing ops).
with borg 1.2, compact will be separate, so you can call it as often as you like.

until then, you maybe can optimize your traffic a bit by using a smaller segment file size, see the repo config. maybe try 20MB or 50MB segment file size rather than the default 500MB.
