### ISSUE TITLE
{utcnow} output isn't correct

### ISSUE THREAD

**Issue by JiffB** [borgbackup/borg#4724]
Severity: Minor

#### Your borg version (borg -V).
borg 1.1.10

#### Operating system (distribution) and version.
Debian Stretch (9) + backports

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
ARCH={hostname}-{utcnow}Z
borg create --verbose --exclude-caches --show-rc --filter AME --stats --checkpoint-interval 600 --compression auto,zlib,6 --exclude-from /usr/local/sbin/BORG_EXCLUSIONS.list ::$ARCH 
```

## Describe the problem you're observing.
Using {utcnow} alone doesn't print the final 'Z' char => {utcnow}Z
which from the ISO-8601 standard is abnormal.

## Wish
The regular ISO-8601 UTC string would also be better as a default: YYYYMMDDTHHMMSSZ because it is more compact.

Jean-Yves

**Comment by Arcovion** [comment]
I also noticed this, and agree the trailing `Z` should be added.
I'd personally keep it as `YYYY-MM-DDTHH:MM:SSZ` though.

**Comment by ThomasWaldmann** [comment]
IIRC, borg nowhere stores / outputs the timezone part.

So the timestamp are similar to iso-8601, but not complete.

As you've shown, there is an easy workaround if one likes to add the `Z` (or tz).

**Comment by JiffB** [comment]
There is a glitch though Thomas, we're talking about a UTC timestamp, which mean it _must_ have the ending Z (or a tz set to 00:00) - this is normal, otherwise you don't have any visual clue if you're using a TS with tz or a UTC one.

**Comment by ThomasWaldmann** [comment]
`ARCH={hostname}-{utcnow}Z` there it is, the Z, so you know you were using UTC.

**Comment by JiffB** [comment]
So, this piece of code doesn't conform to the standard so users have to fiddle with it to get it back, strange conception.

**Comment by Arcovion** [comment]
The reason I expect the `Z` is because of the `T`. That is, I've only ever seen:
`2019-08-22 17:57:37` or `2019-08-22T17:57:37Z` or `2019-08-22 17:57:37 UTC`
And never:
`2019-08-22 17:57:37Z` or `2019-08-22T17:57:37` or `2019-08-22T17:57:37+0000`
Even though I'm aware all of those are probably valid and commonly used.
So for me it's just an issue of familiarity; I'd prefer if either the `T` was removed or the `Z` was added.
I know how pedantic I sound btw 😛 Yes, it *is* easily solved by adding `{utcnow}Z` and that's what I currently do.
Maybe there could be an extra option for a simple `{timestamp}` &rarr; `1566496657`, where it's clear you don't care about the timezone and just want a unique identifier?

**Comment by ThomasWaldmann** [comment]
We used to have a blank where the T is now, but that is impractical for selecting, copy&paste and due to the need of quoting as a shell argument.

**Comment by wsw70** [comment]
This is similar to  https://github.com/borgbackup/borg/issues/4832

I honestly do not understand why not having a real timestamp, backed by a standard. It would help usability, especially when someone actually wants to use the dates provided by borg.
