### ISSUE TITLE
How to limit folder size?

### ISSUE THREAD

**Issue by VladimirMikulic** [borgbackup/borg#4760]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, but found nothing.

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## System information. For client/server mode post info for both machines.

OS: KDE Neon 5.16.5

#### Your borg version (borg -V).

1.1.5

#### Hardware / network configuration, and filesystems used.

No special configuration regular backup and rclone to GDrive.
Filesystem ext4.

## My question:
As the title says, I would like borg to ignore folders that are bigger than <number>MB or <number>GBs.

How can I achieve this?

Thanks.

**Comment by infectormp** [comment]
This is not possible

**Comment by VladimirMikulic** [comment]
There must be a way. Can I add an if statement before each file/folder is backed up or hack something in bash?

**Comment by ThomasWaldmann** [comment]
Why do you want to do that?

**Comment by VladimirMikulic** [comment]
@ThomasWaldmann Because I don't want to add --exclude for every folder/file.

**Comment by ThomasWaldmann** [comment]
You can put a tag file into "known unwanted" folders to keep borg from backing them up.

Also, what you ask for is potentially dangerous. Why should folder size be a criteria for not backing up? 

It could be correct (for your needs) when you specify it and suddenly another (important) folder is not backed up any more just because it went above your size limit. And you likely won't notice that until you want to restore these files...

**Comment by VladimirMikulic** [comment]
> Why should folder size be a criteria for not backing up?

If we have limited storage?

**Comment by ThomasWaldmann** [comment]
The reason for backing up files is because they are important and you don't want to lose them.

Not because they are small.

The reason for **not** backing up files / folders is because they are not important and you accept the possibility of losing them (or you can get them again from elsewhere, like download them again from the internet).

Not because they are big.

You need to have appropriate backup space. If you can't do that, you need to limit space at the data source so that users can not create more stuff than you are able to back up. You could still give users some extra space that is known-unsafe (not backed up).

**Comment by VladimirMikulic** [comment]
My use case is different, but I'll figure something out.

**Comment by ThomasWaldmann** [comment]
ok.
