### ISSUE TITLE
SSH backup always hangs on the same file

### ISSUE THREAD

**Issue by a-gn** [borgbackup/borg#4762]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

borg 1.1.10

#### Operating system (distribution) and version.

Ubuntu 18.04 in WSL on Windows 10 1903

#### Hardware / network configuration, and filesystems used.

Remote backup _via_ SSH to rsync.net (they use ZFS and OpenBSD as far as I know). Local filesystem is WSL's one, and some Windows NTFS folders from C: mounted in WSL (in `/mnt/c`).

#### How much data is handled by borg?

~25GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```bash
/usr/bin/python3 /usr/bin/borg --remote-path=borg1 create --progress --stats rsn:borg::important_2019-09-22T13:24:50+00:00 /home/arno/winhome/Documents /home/arno/winhome/Pictures /home/arno/winhome/Desktop /home/arno/winhome/code /home/arno/winhome/.ssh /home/arno/winhome/Apple /home/arno/winhome/.gitconfig /home/arno/winhome/.gitignore /home/arno/winhome/AppData/Local/Google/Chrome/User Data/Default /home/arno/winhome/AppData/Roaming/Code /home/arno /etc/fstab
```

`/home/arno/winhome` is a symlink to my Windows user folder:

```bash
$ file /home/arno/winhome
/home/arno/winhome: symbolic link to /mnt/c/Users/Arno/
```

## Describe the problem you're observing.

On this repository, backups invariably hang when trying to back up the same file (a simple PDF lecture, which I can attach if you ask). borg stops using any CPU/disk/network bandwidth, and keeps the SSH connection open. The progress output stays still with that file's name. There is no more output or warnings.

From that point, borg doesn't respond to Ctrl+C, but it does stop with Ctrl+Z and I can then kill it. I can also `killall -9 borg` from another WSL console, or by closing the WSL window borg is running in. After killing it, the lock stays on the remote repo, and I have to `borg break-lock` it before doing anything else.

`borg check` on that repo ends with code 0 and without any message. I tried `borg check --repair --save-space rsn:borg`, which didn't output any warning besides the confirmation for `--repair`. I can run `borg list` and `borg prune`, and there doesn't seem to be anything off with these commands' behavior.

I have no idea what is happening. Operations on that repo have been interrupted a lot since I created it due to a bad connection, but backups worked fine until these last few days. Do you think my repo is corrupted?

**Comment by ThomasWaldmann** [comment]
Try to simplify the borg command to the minimum needed to reproduce the issue. Like:
- not using rsync.net as target, but a local folder
- removing not needed source roots
- no --stats
- try --list instead of --progress

If you run with --dry-run and --list, you should be able to see the files before and after the file that borg displayed to you as last one. Is there anything special with the files before and after that?

**Comment by bleaktradition** [comment]
Can confirm this issue.
I removed the file it hangs on but it will hang on some other file.
One thing i noticed is that it will always hang on PDFs as far as I could see.

### Borg/OS version
Client: borg 1.1.10 (on Arch Linux 5.3.1-arch1-1-ARCH)
Server: borg 1.1.10 (on Arch Linux 4.19.75-2-ARCH)
### Hardware / network configuration, and filesystems used.
- SSH
- Remote: RaspberryPi with external harddrive (ext4 formated partition)
- Local: Laptop x86_64 with SSD (ext4 formated partitions)
### How much data is handled by borg
~35GB
### Full borg commandline that lead to the problem (leave away excludes and passwords)
Practicaly I adapted the example script to my system
```
borg create                         \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --exclude '/home/*/.cache/*'    \
    --exclude '/var/cache/*'        \
    --exclude '/var/tmp/*'          \
                                    \
    ::'{hostname}-{now}'            \
    /etc                            \
    /home                           \
    /root                           \
    /var                            \
    /boot
```

Well I didn't back up my PC over this system in a while so i am not quite sure since when it's failing, last successful backup was Juli 2019 afaik.

Hope this helps

**Comment by ThomasWaldmann** [comment]
@bleaktradition See my previous comment.

**Comment by bleaktradition** [comment]
Okay had the time to look into it again, the file before that is pretty normal but the file after the last shown before hang up would explain the issue for me with its few GB in size.
If the last printed filepath is the last one finished, the issue is solved for me.
Thank you :)

**Comment by ThomasWaldmann** [comment]
Closing this rather old issue. If it still happens, please file a new issue.
