### ISSUE TITLE
Backups to alternating targets

### ISSUE THREAD

**Issue by wyae** [borgbackup/borg#4776]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes (and that's what this issue is partly about)

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION / ISSUE

## System information. For client/server mode post info for both machines.

Debian 10  (current)

## Describe the problem you're observing.

Current standard backup procedure is to rsync to a (number of USB) disc(s). Only one of them is connected at all times, the others are offline (and possibly offsite), rotating in a multi-generation scheme (daily/weekly/monthly).

As far as I could read from the docs this might be an issue, as when replacing the current backup disc with one from the safe that has not seen updates in a month.  AFAIU the local index (on the client) expects due to the cache that the blocks written in the last month to be on the disc. 

question 1 - potential data loss:
Does Borg automatically update the missing pieces on the older target?

question 2 - loss of snapshot:
If I have to restore a snapshot from 2 weeks ago (but not older) - that would be on the currently offline disc. Or does Borg maintain a local (client-side) copy of the snapshot indices?
Can Borg access snapshot from an old disc after it already worked with the new one?

### possible workaround

I guess one could work around that issue by using the same target mount point but different target names. Or even label the discs differently, so the mount points differ.

**Comment by ThomasWaldmann** [comment]
The local cache is per repository (see `~/.cache/borg/<REPOID>/...`) so as long as you `borg init` for each of your target / repository disks, you'll be fine.

Also, borg does additional checks whether the cache state corresponds to the repo state.

So there is no problem with swapping repos / having multiple repos (as long as they have unique repo ids, so do not clone repos), neither at backup time, nor at restore time.

**Comment by wyae** [comment]
So basically (formulated as FAQ entry) - did I understand that correctly? 
If correct, maybe add something like that to the FAQ?
Thanks!


Backing up to multiple, swapped sets of "the same" backup target.

To protect against data loss against wipers, malware or catastrophes like a burning building you might want to back up to regularily (weekly?) swapped-out backup media like USB discs. Then you place all of the media currently NOT in use offline and some even offsite, safe and unreachable for attackers or local catastrophes. The swapping out can be as simple as swapping two discs weekly, or in more elaborate schemes like the Grandfather-Father-Son ones (see https://en.wikipedia.org/wiki/Backup_rotation_scheme )

If you backup to multiple "identical" targets (e.g. weekly swapped USB disks), please do assign each backup medium/set its own repository (by creating a new one with "borg init" for each rotated medium). Otherwise you might run into problem when trying to restore a snapshot that only does exist in the cache but not on this medium/set.

**Comment by milkey-mouse** [comment]
The last paragraph's warning is [already covered](https://borgbackup.readthedocs.io/en/1.1.11/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location) in the FAQ. I don't know if the docs mention different backup schemes anywhere, or whether that's even in scope (aside from what `borg prune` can do).

**Comment by fantasya-pbem** [comment]
We have already [Can I copy or synchronize my repo to another location?](https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location), which covers redundant repositories.

**Comment by fantasya-pbem** [comment]
@wyae See my comment from 6 Apr 2020 above. Does this FAQ cover your use case? If not, can you explain what we should add?

**Comment by wyae** [comment]
See my comment from 2019-10-05   ;-)
The FAQ covers a repo-of-repo scenario, not the swap-out scenario.

**Comment by fantasya-pbem** [comment]
OK, let's rephrase your comment into something more FAQ-like:

_Can I back up to multiple, swapped backup targets?_

_To protect against data loss against wipers, malware or catastrophes like a burning building I want to back up to weekly swapped-out USB disks. Then I place the media currently not in use offline and/or off-site, safe and unreachable for attackers or local catastrophes. The swapping out can be as simple as swapping two disks regularly, or in more elaborate schemes like Grandfather-Father-Son (see https://en.wikipedia.org/wiki/Backup_rotation_scheme)._

_It is possible to swap your backup disks if each backup medium/set is assigned its own repository by creating a new one with "borg init". Borg needs to keep a local cache containing checksums of all file chunks already stored in the repositories. These caches are stored in subdirectories of ~/.cache/borg/. If Borg detects that a repository has been modified since the local cache was updated, it will rebuild the cache which can be quite time consuming._

OK?
