### ISSUE TITLE
Discussion: use borg as a storage backend

### ISSUE THREAD

**Issue by Barafu** [borgbackup/borg#4847]
Hello!
I want to start writing an opensource application that help collecting service manuals. People usually use Calibre (if anything), and it always turns out to be a disaster. I want to make an app that is more geared towards those kinds of document collections. 

Since the data is heavily duplicated by nature (different versions of the same manual, often the same file with a page replaced), I think I can use borg repository for actual storage.

- Do you think it is a good or bad idea?
- Is there an API I can use, or will I have to call CLI by `subprocess` every time?
- Are there any speed tests beside my own? Collections can be big. For example, my own is 4Tb with I don't know how many (million?) of actual entries. I tested up to 700Gb, then I've run out of space. Calibre becomes very slow adding new files after a 100k entries, because it updates DB indexes after every entry even in batch processing. DB I can handle, but what about borg? Will 4Tb repository take a minute to add a small file?

Thanks for any advise!

**Comment by ThomasWaldmann** [comment]
You need to try whether it really helps you regarding compression and deduplication (you may need to change the chunker params for this, see the docs, as by default it is targetting 2MiB chunk size, which might be too much to help with manuals / ebooks).

There is no stable API, you should use the commandline interface.
Maybe have a look into `vorta`, which is a GUI for `borg` and also calls borg via cli (python with QT).

borg should be able to handle many TB of data, but you might need a lot of RAM if your repo is big or if you have many small files (see docs for a formula to estimate resource usage).

Maybe also have a look at `borg mount`. It's not the fastest way to extract a lot of data, but maybe the easiest way to find / browse / access data.

**Comment by Feuermurmel** [comment]
@Barafu Reading your description of the project you're trying to start, here are some ideas:

- Use a clustered database, which can handle the large volume, and write a middleware to do the deduplication. I've used [Cassandra](http://cassandra.apache.org) and [radosgw](https://docs.ceph.com/docs/master/radosgw/) in the past with great success.

- Place the files in a plain file system and use a database to track the files. If it's a single user application, even [SQLite](https://www.sqlite.org/index.html) may be very well suited because you're probably only dealing with millions of entries. The _Photos_ app on macOS uses exactly that approach, while accomplishing a similar task; storing and cataloging hundreds of thousands of files a few megabytes each. 

Maybe deduplicating whole files will give you the best benefit-to-complexity ratio. PDFs are compressed so deduplicating between similar-but-not-identical files may not yield a lot (I'm not sure, I've never researched this).

**Comment by Barafu** [comment]
I already do decompress PDFs, Epubs and other stuff before adding it to the vault. I simply want data deduplication and don't want to do it myself. Seems hard. :)
Thanks for all the replies!

**Comment by Feuermurmel** [comment]
If you have lot's of RAM, you could also give ZFS with deduplication a try.

**Comment by Barafu** [comment]
I already do decompress PDFs, Epubs and other stuff before adding it to the vault. I simply want data deduplication and don't want to do it myself. Seems hard. :)
Thanks for all the replies!

**Comment by Barafu** [comment]
There is a tool called 'precompressor'. It searches file for ZIP sequences, decompresses them and puts back into the file with metadata required to restore the file bit to bit.

**Comment by ThomasWaldmann** [comment]
@Barafu interesting. we already had the decompress-and-recompress discussion in another ticket, but the main problem was bit-identical reproduction of the original file.

**Comment by Barafu** [comment]
https://github.com/schnaader/precomp-cpp
