### ISSUE TITLE
Limit prune on borg server

### ISSUE THREAD

**Issue by tuxick** [borgbackup/borg#4938]
Given the problems companies are having with ransomware i'd like so see an option to 'borg serve' that limits the amount of backups that can be pruned from client. Something like 
 borg serve  --keep-days=7
so this can be set in authorized_keys

In our case append-only would soon result in storage space issues.

**Comment by ThomasWaldmann** [comment]
How does that help?

Even if that was possible (it is not), you could just invoke prune multiple times and prune as many backups as you want.

It is not possible because borg serve does not know about the high-level operations that the client is doing, it is only seeing low-level PUT, DEL, GET operations for chunks / stored objects.

**Comment by marioli** [comment]
Well ... I know the problem is closed, but since the answer doesn't apply, I'll try to clear it up.
If the "Borg Serve" can restrict cleaning (and this is definitely possible, since "--append-only" forbids cleaning at all), the ransomware would have to encrypt files undetected for 7 days (in the example for a tuxedo) in order to make sure the 1000 day circumcision really does cut the 7 day guarantee. Within the 7 days this can still affect the backup, but imagine the guarantee is higher.
If the backup is performed once a day (regularly) and the cleanup process starts after it is created, the server should have 7 versions of the backup. Even if one night (possibly due to the ransomware) backup cleanup is run 100 times, the server will not remove the last 7 days. Doesn't that make sense?

**Comment by he-leon** [comment]
Hi, 
I just stumbled across this issue as I was thinking about the security implications of automated backups with borg.
Let's say we have an attacker on the client machine which has gained root access. Let's assume the borg backup is automated in a way so that it can remotely execute "borg prune" in the repo on the borg server. 
In this scenario, could the attacker wipe the complete repo?  If yes, what  would be the best way prevent this?

**Comment by ThomasWaldmann** [comment]
You can run the repo in append-only mode. See the docs and also other tickets about this, this has already been discussed a lot.
