### ISSUE TITLE
Prune not working as expected, hourly keeps all archives

### ISSUE THREAD

**Issue by rs-development** [borgbackup/borg#5021]
BUG

I started using --keep-hourly, but it is not working as expected. I assumed it keeps the following. 

- 1 for each hour in a single day.
- 1 for each day in a week
- 1 for each week in 4 weeks
- 1 for each month in 6 months.

But instead, it keeps all archives since I activated the hourly option end of February. See below. I just discovered the kee-within option, which seems to be a better option for many backups over the day and a single in the night or so. But I would like to make sure hourly is working correctly first.

I can only check the version after I am on-site again, or is there an option do check the version remotely? It should be version 1.1.x

    borg prune                          \
        --list                          \
        --prefix '{hostname}-'          \
        --show-rc                       \
        --keep-hourly   24              \
        --keep-daily    7               \
        --keep-weekly   4               \
        --keep-monthly  6              \

Leeds to the following result:

    Keeping archive: ncvps-2020-03-10T02:17:02            Tue, 2020-03-10 02:17:15 [d1ddfdcd73534002902f90884b2177e3526fba42b6073e8d4cbef8ed5afc508c]
    Keeping archive: ncvps-2020-03-09T02:17:02            Mon, 2020-03-09 02:17:14 [15b1a0831459803f9e2a7ee2b07e5259b4ee9db6e76692ee485e7a6320d3d617]
    Keeping archive: ncvps-2020-03-08T02:17:02            Sun, 2020-03-08 02:17:14 [696c9e43e4e7a971b6e38c5ac62206eb784e02549c2b4e6080db3af4bdd55634]
    Keeping archive: ncvps-2020-03-07T02:17:02            Sat, 2020-03-07 02:17:14 [489d72a01ed00d822a6bbb24a53a04a80450d1859f489b317e354fe5aa14e259]
    Keeping archive: ncvps-2020-03-06T02:17:02            Fri, 2020-03-06 02:17:15 [71d5989da353a38e3a393905d6e443930877d1acdd49354ccc9553a24c0acf44]
    Keeping archive: ncvps-2020-03-05T02:17:02            Thu, 2020-03-05 02:17:15 [c8ea1c8b22dd99c3a0c147d1d997ff1c5f56baf9ade4cb6fe7840a388916e4c2]
    Keeping archive: ncvps-2020-03-04T02:17:01            Wed, 2020-03-04 02:17:14 [dc41597ca933925e7b7d275600b36f22265830fd05da5ed733f4d3a5b3dd1c30]
    Keeping archive: ncvps-2020-03-03T16:37:31            Tue, 2020-03-03 16:37:44 [b7667d327931c64dc7f3c3d3d6fbda248acef26a69ba81818a9cbb678a24575d]
    Keeping archive: ncvps-2020-03-03T11:54:25            Tue, 2020-03-03 11:54:28 [11486c0b24ddf94dc2661c96249e0c9f9998d8002363b90243de08576791f463]
    Keeping archive: ncvps-2020-03-02T13:24:06            Mon, 2020-03-02 13:24:09 [024548dca09d2450abf5b2b96d1123377a0edc28f7546d684206bcf196209e54]
    Keeping archive: ncvps-2020-02-29T18:12:06            Sat, 2020-02-29 18:12:09 [527c6c1af9da04a160708f12306a7ee11003834a419d7da10a5a9f1595d4c74f]
    Keeping archive: ncvps-2020-02-28T02:17:01            Fri, 2020-02-28 02:17:05 [922b0970dbbae61a14d07817a7bde09fb7fb8287fd7d2f9e909d22ed69bebf8e]
    Keeping archive: ncvps-2020-02-27T02:17:01            Thu, 2020-02-27 02:17:05 [0d56a852361ca52c418f318f38a339b9cd3f2a5b271266680b3c3ad15506d4c6]
    Keeping archive: ncvps-2020-02-26T02:17:02            Wed, 2020-02-26 02:17:05 [6dfa16ea15f95061fa7c19b4514348fc9c8b3f8c42dcfae8b5a2a1901ff857f4]
    Keeping archive: ncvps-2020-02-25T02:17:01            Tue, 2020-02-25 02:17:06 [629c05d66e1b1dc5e5ffbd66ec40884f8b8e6e8866670b94373d4da34fdcd1db]
    Keeping archive: ncvps-2020-02-24T02:17:02            Mon, 2020-02-24 02:17:06 [676e5c768e9fd37a52da29a08c5b9709fa4ba4acc6be45d2115f5a7a091c9b14]
    Keeping archive: ncvps-2020-02-23T02:17:03            Sun, 2020-02-23 02:17:06 [89787a17699dc269684dc26e5f04c548928499a6d8b7924474e249cc84de4aa6]
    Keeping archive: ncvps-2020-02-16T02:17:01            Sun, 2020-02-16 02:17:06 [d5c49f125038404c250b7df833441e7a537903a50ce41cef284e35ce5568bd6d]
    Keeping archive: ncvps-2020-02-09T02:17:02            Sun, 2020-02-09 02:17:06 [5e69547c5c4e2131e356a48f33770cd073e23949b17a61c88341957c45978cfd]
    Keeping archive: ncvps-2020-02-02T02:17:01            Sun, 2020-02-02 02:17:05 [d0c38b40ef69025d7264ebd1b4f93bb3a31bfd5051c2710ab343545de5e853ac]
    Keeping archive: ncvps-2020-01-31T02:17:01            Fri, 2020-01-31 02:17:05 [a54571279af04fdf7b4ea70720cee03a4c6a6cfdf36fbb8ba54ba514a08c6d8f]
    terminating with success status, rc 0

**Comment by ThomasWaldmann** [comment]
Do not **assume** how it works, but please read the docs about what it actually does.

There is also an example in the `docs/misc` folder which might help with clarification.

Specifically, telling --hourly 24 means to keep 24 hourly backups. I do not see more than 24 in what you posted.

**Comment by rs-development** [comment]
Okay this needs a careful read. Just to make sure: It is now saving the latest backup for each hour. (Max 24). Since those backups are on different days it is recognised as different hours and so would save upto 24days?

**Comment by ThomasWaldmann** [comment]
From the docs:
```
As an example, --keep-daily 7 means to keep the latest backup on each day,
up to 7 most recent days with backups (days without backups do not count). 
```
So, what is unclear about that?

**Comment by ThomasWaldmann** [comment]
(and if you replace "day" by "hour", you have the rule for --keep-hourly)

**Comment by rs-development** [comment]
My think was more like this; There are 24 different hours (0-23), so if I am keeping 10 hourly backups and I am doing one backup a day at hour X, it would only save the most recent backup for hour X. And not 10 backups all done (in my Opinion) the same hour.

Just explaining! I am totally happy with the --keep-within function, since it does resolve some more issues.

**Comment by ThomasWaldmann** [comment]
I still do not see the issue. Please clarify or simplify the data / how to reproduce, so it gets clearer.

Read the docs and mark the specific thing that does not comply to the docs.

**Comment by andyDoucette** [comment]
First off, let me start by saying borg is awesome and I'm never going back to any other backup tool!  Cudos for the great work.

Now, I'd like to chime in about this particular topic as someone who also had the same confusion.  The issue with borg prune is that the way it's programmed does not match what users expect the options to do.  If someone sets --keep-hourly 24, they expect only backups from the past 24 hours to be kept.  If only 2 backups were made in that time, then they expect to keep 2.  The way it's coded is from a very borg-centric perspective instead of a user-centric perspective, because the length of time covered also depends on how many of the scheduled backups actually happend, information that is not available to the user when they are setting up the script.  Let's say someone has a data retention policy that they want to keep things only from the last 3 months and their backup success rate is intermittent (perhaps because their computer is not always on when the cron job runs) .  I don't see a good way to do that right now.  Yes, they could use --keep-within, but then they lose the ability to have the spacing between their backups decrease the further in the past you go.   The other issue is that the help text does not have enough information to tell users what to expect either.  People won't always go to the online documentation or even know that it exists.

**Comment by ThomasWaldmann** [comment]
@andyDoucette Thanks for the feedback.

Yeah, there is often a wrong intuition about how these options work, but that's why we have docs. :-)

Also note the wording: it's not `--keep-hours 24` (for which 24 would refers to the hours), but it is `--keep-hourly 24` (for which 24 refers to the count of hourly backups).

The reason why it is like that is also safety:

Just imagine that you use `--keep-daily 42` and for some reason no backups are created for 6 weeks.

If it would only keep the backups from the last 42 days, it would have delete all your backups! If you noticed that because you needed a backup, that would be really bad.

But as 42 refers to the count, you still have 42 older backups at least, which is not perfect, but at least better than nothing.

**Comment by grinapo** [comment]
I _think_ (even after repeatedly reading the documentation) that it works a pretty weird way. I think it could be explained like:
- the keep process starts walking through the defined periods, starting from seconds
- it _always_ keep the defined amount of backups, _no matter how far apart they are_
- when they are spaced closer than the period, removes the ones between the periods
- when there are more backups than the defined amount, borg takes the next period, and starts again counting

It results that if you defined _hourly=12_ and _daily=7_ and you make backups daily then you will have **19 daily backups**, since there always have to be 12 hourly, and since they are already spaced farther than an hour they will all be kept. 

If you only make monthly backups and you also defined _monthly=12_ then you will have 12+7+12 monthly backups kept.

I agree with @andyDoucette that this is rather counter-intuitive, and I also understand @ThomasWaldmann that it ensures that there are always that amount of backups kept, even if they are spaced far more than their period. 
My other type backups remove dailies if there are no successful backup and I'm left with weeklies and monthlies, and I thought so far that this is normal. Right now the solution was to seriously lower the hourly amount since it became pretty much daily for me.

**Comment by ThomasWaldmann** [comment]
@grinapo it should work as documented.

If you think the docs are wrong or easy to misunderstand, rather file a pull request with incremental improvements, so we can discuss them there.

**Comment by ThomasWaldmann** [comment]
The process would be rather that you read and check the borg docs.

If you find something that is wrong, fix it in your PR.
If you find something that is misunderstandable, rephrase it in your PR.

**Comment by grinapo** [comment]
Ideally one would read what they respond to:
 > even after repeatedly reading the documentation

Anyway, on the sidenote you seem to ignore that writing (and especially _fixing_) documentation actually require one to _know_ what the documented process do and how it does what it does. 
I think I have detailed what I understood from reading the documentation and from experience, and I think I have politely asked whether I understand right and that is how I should, as you sort of kindly requested, PR the docs. Or if you would have said no, then I would have known there is a bug in the code, so I would need to open an issue about it. Right now I cannot do either, since I am guessing about what exactly happens. 

I thank you for your time to respond and I am truly sorry for the lack of answer, and that I can't help because of that.

I only hope that people bitten by this will get to this issue, read my guesses and maybe it could help them to understand what is possibly happening.

**Comment by ThomasWaldmann** [comment]
AFAIK, the prune docs are correct and complete (so you don't need any inside knowledge about the code).

If you think different, please:
- prove it
- do a PR to fix it
