### ISSUE TITLE
dsize and dcsize both 0?

### ISSUE THREAD

**Issue by jucor** [borgbackup/borg#5044]
Is it normal that `dsize` and `dcsize` are listed as `0` for all files in an archive ? 
I looked at the first archive where these files were backed up. I cannot find any other copy of these fields that would have been backed up before [which could have explained a deduplicated size of 0]. The files can be extracted without problem, so the content is there.

I'm baffled, and there is probably something I do not understand about deduplication. Could you help, please?

## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes
## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

- local: 1.1.7
- first remote tested: borg 1.1.11
- second remote tested: borg1+, more details not known, whatever is run by borgbase.com

#### Operating system (distribution) and version.

- Local: Synology  NAs running Linux nas 4.4.59+ #24922 SMP PREEMPT Wed Jul 3 16:38:29 CST 2019 x86_64 GNU/Linux synology_apollolake_218+
- First remote: unknown, server run by rsync.net
- Second remote: unknown, server run by borgbase.com

#### Hardware / network configuration, and filesystems used.

- local: Synology DS218+
- remotes: unknown, whatever is used by rsync.net and by borgbase.com

#### How much data is handled by borg?

12 TB+

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
BORG_CACHE_DIR "/volume1/backups/borg/cache" \
BORG_RSH="ssh -i keys/id_ed25519_borg" \
BORG_PASSCOMMAND="cat config/passphrase" \
borg  list --debug  \
user@server.repo.borgbase.com:repo::nas-2020-03-16T01:01:46  \
"path/to/the/folder" \
--format "{path}{TAB}{size}{TAB}csize:{csize}{TAB}dsize:{dsize}{TAB}dcsize:{dcsize}{TAB}chunks:{num_chunks}/{unique_chunks}{NL}
```

In the output, all the 
```
using builtin fallback logging configuration
35 self tests completed in 0.24 seconds
SSH command line: ['ssh', '-i', 'keys/id_ed25519_borg', 'g778jyvm@g778jyvm.repo.borgbase.com', 'borg', 'serve', '--umask=077', '--debug']

Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.27 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'repo'
Remote: Resolved repository path to '/srv/repos/user/repo'
Remote: Verified integrity of /srv/repos/user/repo/index.6747
TAM-verified manifest
security: read previous location 'ssh://user@server.repo.borgbase.com/./repo'
security: read manifest timestamp '2020-03-17T01:54:41.659439'
security: determined newest manifest timestamp as 2020-03-17T01:54:41.659439
security: repository checks ok, allowing access
Verified integrity of /volume1/backups/borg/cache/1d65dc2b7f3066ee51635dec0b66007d69258dd97e4fe3732e969d1559171c9d/chunks
security: read previous location 'ssh://user@server.repo.borgbase.com/./repo'
security: read manifest timestamp '2020-03-17T01:54:41.659439'
security: determined newest manifest timestamp as 2020-03-17T01:54:41.659439
security: repository checks ok, allowing access

path/to/the/folder/file1 766393917csize:709581131 dsize:0 dcsize:0 chunks:287/0
path/to/the/folder/file2 4363580 csize:4313376 dsize:0  dcsize:0 chunks:2/0
path/to/the/folder/file3 716446049 csize:663533499 dsize:0 dcsize:0 chunks:279/0
(...)
RemoteRepository: 187.92 kB bytes sent, 117.24 MB bytes received, 3554 messages sent 

```                                                                                                               

## Describe the problem you're observing.

All the `dsize` and `dcsize` fields are 0.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Problem reproduced by running the same command on another repository where I backed up the same files.

#### Include any warning/errors/backtraces from the system logs
None

**Comment by ThomasWaldmann** [comment]
Where did you get from that `dsize` and `dcsize` are supported placeholders?

**Comment by ThomasWaldmann** [comment]
OK, can you please reproduce with borg 1.1.11 (and also read the changelog)?

You need to install that version anyway due to important bug fixes.

**Comment by jucor** [comment]
I will try, but since I'm using a Synology I'm a bit limited in terms of cutting-edge version.  
This being said, are the ctime and dctime computed on the server or on the client? If on the server, then that's already using Borg 1.1.11 (only the client is 1.1.7).

**Comment by ThomasWaldmann** [comment]
borg does most stuff on the client side.

you need 1.1.11, see: https://github.com/borgbackup/borg/blob/1.1-maint/docs/changes.rst#pre-1111-potential-index-corruption--data-loss-issue

**Comment by jucor** [comment]
Brilliant. I'm fiddling with the binary you released, see if I can use that. I will update when I get 1.1.11 working.

**Comment by jucor** [comment]
Alright, seeing exact same `0` sizes with 1.1.11 :/  Do you recommend doing delete/repair procedure listed in the changelog? Am I correct in understanding this will download the whole compressed archives?  [570 GB total stroage downloaded on a weak home connection is not an operation I can do lightly ;-) ]

**Comment by jucor** [comment]
`borg check --repair` in progress. Now to being patient, I'll update when it's done.

PS: Thanks for the binary release, by the way, extremely helpful on Synology (where there was no way to update from source easily)

**Comment by jucor** [comment]
Repair done with 1.1.11, no errors found, and `dsize` and `dcsize` still 0. Can you try on one of your own repos, see if you see the same behaviour, please?

**Comment by ThomasWaldmann** [comment]
OK, I'll have a look.

**Comment by jucor** [comment]
Thank you! Happy to run any command / debug log that might help, just let me know :)

**Comment by travisdowns** [comment]
I am also seeing `dcsize` and `dsize` all zero on one of my repositories, but not for another.

**Comment by travisdowns** [comment]
@ThomasWaldmann - maybe `dsize` means "the size of unique blocks only"? 

In that case, for a repository with several backups close in time, I guess it is normal to have zero or nearly zero dsize for most files: a file could only have non-zero `dsize` only it if contained a chunk that wasn't shared with any earlier or _later_ archive in the repo. The _later_ part I guess is where it is unexpected: when you look at the "deduped" stats for a `borg create`, for example, you see any file that has changed since the last backup, or any new file. So many files have non-zero deduped size. However, the next day when you back up those files again, their deduped size (even for yesterday's backup) effectively changes to zero.

So if that's how `list` works it is a bit confusing in that it dedupes forward in time too. If you do two backups close together (no changes), _every_ `dsize` will be zero? The sum of all `dsize` doesn't have a relationship to the sum of "deduplicated size" you see in all the `borg create`.

**Comment by ThomasWaldmann** [comment]
> @ThomasWaldmann - maybe dsize means "the size of unique blocks only"?

Yes. Do the docs say something else?

> In that case, for a repository with several backups close in time,
> I guess it is normal to have zero or nearly zero dsize for most files:

Exactly.

> a file could only have non-zero dsize only it if contained a chunk that
> wasn't shared with any earlier or later archive in the repo.

Yup.

> The later part I guess is where it is unexpected.

Well, maybe you have wrong expectations. :-)

If a block of data is being pointed to by multiple archives, all these pointers are equal.
So why should earlier or later even matter?

**Comment by travisdowns** [comment]
> Well, maybe you have wrong expectations. :-)

Yes, I think I had wrong expectations, and I think I admit as much above.
 
> If a block of data is being pointed to by multiple archives, all these pointers are equal.
> So why should earlier or later even matter?

Because you want this statistic to be useful. Ultimately, you want to know what takes up size in the archive: size is not a reliable indicator because of the possibility of lots of deduplication.

When you do a `borg create` you get useful info: the compressed, deduplicated size (final column). Ultimately, you expect your repo to grow basically as the sum of these sizes across borg create (and this works_. 

Similarly one _might_ expect the dsize/dcsize show in `--list` to be related to this value, but it isn't as soon as you do another compression. There is no stat that when summed reflects the size impact of the archive: size is way too big (in general) and dcsize is way too small (often zero). There is no way to answer "if this file didn't exist (in any archive) how much smaller would the archive be", unless you do the `list` when the archive in question is the last one.

Probably, there is no efficient way to get the stat that I want, though, short of making a temporary copy of the repo and deleting all later archives.
