### ISSUE TITLE
Perfomance issue with small chunk size

### ISSUE THREAD

**Issue by Tokyx** [borgbackup/borg#5063]
Hi,

I try to store VMA proxmox backup file.
This filetype has the particularity of recording the disk datas in disorder. [`details here`](https://git.proxmox.com/?p=pve-qemu.git;a=blob;f=vma_spec.txt)

To have an interesting deduplication ratio with Borg, the --chunker-params must be adapted to reduce the size of chunks. With such parameters (12,20,15,4095), we get a very interesting result (write and dedup perf), but a very large number of chunks.

However, we have big problems with performance in the extraction, whether locally or through SSH. We do not exceed 1-2MB/s, where we usually have speeds of 50MB/s in write (create) and in export (extract) with the default parameters.

Here are some of our tests, with 2 VMA of 65GB pure data. We use Borg 1.1.9 on the client and server side. SSH server is on the same LAN, with 0.2ms latency.

_(1st archive | 2nd archive)_
`--chunker-params 19,23,21,4095 (default)`
> Processing time : 26 min | 24 min
> Archive size after dedup : 52.89GB | 47.14GB
> Unique chunks in repo : 25k | 44k
> Final extraction perf : 40MB/s

`--chunker-params 12,20,15,4095 (our)`
> Processing time : 22 min | 11 min
> Archive size after dedup : 47.38GB | 2.08GB
> Unique chunks in repo : 1,5m | 1,6m
> Final extraction perf : 2MB/s

`--chunker-params 14,20,18,4095`
> Processing time : 28 min | 12 min
> Archive size after dedup : 62.00GB | 16.96GB
> Unique chunks in repo : 217k | 252k
> Final extraction perf : 18MB/s

`--chunker-params 14,20,17,4095`
> Processing time : 24 min | 12 min
> Archive size after dedup : 60.84GB | 9.44GB
> Unique chunks in repo : 399k | 435k
> Final extraction perf : 37MB/s

`--chunker-params 12,20,17,4095`
> Processing time : 25 min | 11 min
> Archive size after dedup : 60.75GB | 9.52GB
> Unique chunks in repo : 425k | 461k
> Final extraction perf : 30MB/s

`--chunker-params 13,21,17,4095`
> Processing time : 27 min | 12 min
> Archive size after dedup : 60.82GB | 9.58GB
> Unique chunks in repo : 416k | 452k
> Final extraction perf : 20MB/s

`--chunker-params 13,20,16,4095`
> Processing time : 26 min | 12 min
> Archive size after dedup : 59.69GB | 5.06GB
> Unique chunks in repo : 778k | 817k
> Final extraction perf : 17MB/s

Do you have any explanations for this loss of performance? Is there a solution ?

Thank you !

**Comment by infectormp** [comment]
Can you repeat this tests with recent version of borg?

**Comment by Tokyx** [comment]
After installing and testing with Borg 1.1.11 and fresh repos, it seems that there is better when doing a local extraction, with --chunker-params 12,20,15,4095 params. 50MB/s !

But when I try with SSH, always the same result. 2-3MB/s. Even when performing an extraction via SSH locally (via 127.0.0.1).. But only on extract. On create, we have 50MB/s with SSH.

**Comment by infectormp** [comment]
Can you perform write operations via local SSH using any other software and check write speed to  make sure this is not an SSH problem.

**Comment by Tokyx** [comment]
I tried an rsync via locally SSH, it up to 50-60MB/s.

When I try a borg create from another server, I up to ~50MB/s too.

`BORG_PASSPHRASE="xxx" borg create --verbose -s --progress --exclude-caches --chunker-params 12,20,15,4095 --compression lz4 borg-backup@BACKUP:borg/test-2::201-2020_03_27-14_29_10 vzdump-qemu-201-2020_03_27-14_29_10.vma'`

IOTOP on borg repo server :
```
TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
2450522 be/4 borg-bac    0.00 B/s   46.94 M/s  0.00 %  0.00 % python3 /usr/local/bin/borg serve --umask=077 --info
```

Same datas on network interface stats.

**Comment by infectormp** [comment]
maybe related to https://github.com/borgbackup/borg/pull/5032

**Comment by callegar** [comment]
I am experiencing the same issue. Extraction seems to be much much slower than backing up.  I am also working with a small chunk size due to the features of some portion of the data that I am backing up.

Yesterday I had to extract an old firefox profile due to an issue with the the latest firefox update. Extracting that 600 MB folder took much longer than backing up my whole 100 GB stuff.

I am on borg 1.15 (both client and server). Server is on a different machine on the same LAN, so that access is via the SSH interface. Server is a machine with rather mediocre performance (but I understand that this should not matter much as most of the work is done by the client) and backup disk is on a non-ssd USB3 disk (so no huge performance even there). A final factor impacting absolute speed is that not just the client but also the server is currently connected via wifi. However, what strikes me is not the absolute slowness, but the speed asymmetry wrt backup. This happens both trying to extract with `borg extract` and trying to mount the backup via fuse and copying.

The aspect that makes me wonder is that the server machine appears to be overwhelmed network-wise during the extraction. Trying to SSH into it shows a limited cpu load and disk activity, but the network looks dead. Pinging around from the server during the extraction gives response up to 10-20 times larger than usual.  In the meantime the client network seems to keep doing relatively fine.

**Comment by ThomasWaldmann** [comment]
Please note:
- small chunks have always higher overhead than bigger ones
- extract is always a full extract, while backup ("create") is only adding to the repo what's not already there yet
- backup is optimized (because very frequently used), extract not that much
- wifi slower / higher latency than LAN
- USB disks sometimes have rather bad performance when lots of I/O is happening, queue up a lot of stuff and bring the system to a crawling state (check whether it is better with or without UAS)
