### ISSUE TITLE
Feature request: suppress warning about files changed while backed up

### ISSUE THREAD

**Issue by gnd** [borgbackup/borg#5075]
Hi, 
this is a feature request, and i'm going to skip most of the reporting template.

We use 1.2.0a8.dev9+g73ab1f1d to backup /var/log. Obviously, as per https://github.com/borgbackup/borg/pull/4434, borg complains about files being changed, which as a warning raises the return code to 1. We can suppress the output by using --error, however the return code is still 1 and that interferes with general error reporting (eg. we want to report anything over return code 0, but not this). 

Is there a chance to add a option to borg to not warn about files that changed ? Thanks !

**Comment by ThomasWaldmann** [comment]
Well, a warning is a warning. not an error.

And a file which has changed while being backed up is definitely warning-worthy, because it will likely be inconsistent internally. If the file does not matter, exclude it. If it matters, the warning is important.

So this rather sounds like you need a different handling of this in your scripts / monitoring.
