### ISSUE TITLE
borgbackup 0.29.0 broken (cannot allocate memory)

### ISSUE THREAD

**Issue by LocutusOfBorg** [borgbackup/borg#509]
as said in Debian bug http://bugs.debian.org/808913

The program output:
```
hashindex: malloc buckets failed(Cannot allocate memory)
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1261, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1215, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 183, in do_create
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 247, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 221, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 535, in process_file
    chunks.append(cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats))
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 359, in add_chunk
    self.chunks[id] = (1, size, csize)
  File "borg/hashindex.pyx", line 174, in borg.hashindex.ChunkIndex.__setitem__ (borg/hashindex.c:3382)
Exception: hashindex_set failed
```

**Comment by ThomasWaldmann** [comment]
Well, that quite obviously means you do not have enough memory.

As a slow workaround, you can add more swap. Faster is having enough real RAM.

In the internals docs, there is a (rough) formula to estimate RAM usage.
To summarize it quickly, RAM usage depends a lot on chunk count (and file count).
So, if you are low on RAM, try to have less chunks, see --chunker-params (or less files, e.g. by dividing your stuff).

BTW, while you can switch to a new chunk size in an existing repo, that does not make all the many existing small chunks go away, so consider starting from scratch.

The explanation why with 0.28.x it still worked for you and with 0.29.0 it stopped working (for same repo, same data) is likely because of the load factor fix that went into 0.29, see https://github.com/borgbackup/borg/pull/452. But if that pushed your borg over the RAM border, a slight increase in your files or chunks count would have done the same.

**Comment by LocutusOfBorg** [comment]
thanks for the full explanation!

I'll close the Debian bug report!

**Comment by No15pecial** [comment]
I started from scratch and I used a  --chunker-params 19,23,21,4095  it still fails

**Comment by ThomasWaldmann** [comment]
@No15pecial Not sure why anybody would want to use a almost 4y old borg version these days.

If you have a problem with a current borg version, don't comment on old tickets but rather create a new one.

**Comment by No15pecial** [comment]
Being a noob and out  if my element I comment the only place I saw the error that I’m am receiving. 

I believe I am on a new version of borg, box is old and under powered. I used defaults when creating LVM so swap space may be small 

Sent from my iPhone

> On Sep 24, 2019, at 4:28 PM, TW <notifications@github.com> wrote:
> 
> @No15pecial Not sure why anybody would want to use a almost 4y old borg version these days.
> 
> If you have a problem with a current borg version, don't comment on old tickets but rather create a new one.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



 
----------------
 HIPAA/Confidential Notice- Please note:
 

 This Email along with all of the information in this e-mail message, including any attachments, is covered by the Electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521. This information is confidential, not for publication, and intended only for the sole use of the individual(s) named above. If you, the reader of this message, are not the intended recipient, you are hereby notified that you should not further disseminate, distribute, or forward this e-mail message. If you have received this e-mail message in error, please destroy all copies of the original message, and notify the sender.  GENERAL DATACOMM
