### ISSUE TITLE
Change key mode

### ISSUE THREAD

**Issue by skruppy** [borgbackup/borg#510]
It would be great to be able to change an existing repo from keyfile to repokey mode (and vice versa).

**Comment by ThomasWaldmann** [comment]
Yes. And also from (deprecated) passphrase to repokey mode, which is already covered in #97.

**Comment by textshell** [comment]
from looking into this because of a question on irc.

Changing the key borg loads from a keyfile to a repokey only needs to move the data over to the repo with save_key and change the type field of the manifest crypto envelope.

But AESKeyBase checks the type of each chunk it decrypts and would bail there. Which leaves rewriting the whole repository or declaring all AES legacy based types to be equivalent. From just thinking about it for a few seconds i don‘t see any real harm from that.

**Comment by varac** [comment]
Also, a command would be helpful to show general info about a repository - i.e. the current encryption type (none, keyfile, repokey).
May there is one already but I didn't find it ?

**Comment by enkore** [comment]
That's scheduled for 1.1.0b3 (27bc73c)

**Comment by ThomasWaldmann** [comment]
no news afaik. if it is just one repo you maybe can do it manually.

test first with some non-production test repos and just look how the repo config / key file looks like (the key data is the same).

**Comment by Mirodin** [comment]
I understood from @textshell explanation that I would have to rewrite the whole repository. Since that is on a rather weak server rewriting 1.2 TB would take at least a week if it does work at all.

So if I understand you correctly I just change keytype from 3 to 0 and copy the key string from my repo config into a keyfile? That should be doable I would say.

**Comment by ThomasWaldmann** [comment]
oh, right, sorry, i did not consider that. yeah, looks like it can't be done manually.

**Comment by fullofcaffeine** [comment]
@Mirodin Thanks for sharing.

Right now, the password I use is quite long, so security-wise, so I guess it doesn't make much difference (estimations for cracking it are infinite time with current processing power, I tested a similar length password here: https://www.betterbuys.com/estimating-password-cracking-times/), unless quantum processors become a thing next week and are able to crack it ;) 

There's a downside even for larger passwords, it's easier to leak them accidentally than key files, I'm extremely careful not to type my unique long password where I'm not supposed to or to leave it in the clipboard (the latter could be a problem for keyfile contents as well).

**Comment by ams-tschoening** [comment]
> Now that my workflow is consolidated, I'm considering moving the key out of the repo, so a way for borg to migrate from one strategy to the another would really be great.

Im considering exactly the opposite approach: Started with `keyfile` and maintaining that additionally to the password in my KeePass is a bit annoying for multiple repos. Especially when I'm thinking of the worst case that my server crashes, I need to access the backups using some other host and first need to setup keyfiles etc. again. Just to remind that both switches would be nice to have repokey -> keyfile and keyfile -> repokey.

Of course I have the same problem with rewriting a whole repo: That is placed on some kind of low end NAS with 2,5 TiB currently. So would really be great if that could be avoided somehow.

**Comment by ThomasWaldmann** [comment]
see also #2153.

**Comment by ThomasWaldmann** [comment]
superseded by #2153.

**Comment by psy-q** [comment]
I realize this is closed, but is there an interface to use this, similar to `borg key migrate-to-repokey`? I don't understand how the linked MRs make htis possible and it seems like a useful feature.
