### ISSUE TITLE
Backup only hidden files and folders of my home directory?

### ISSUE THREAD

**Issue by bobblkabb** [borgbackup/borg#5234]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
1.1.13

#### Operating system (distribution) and version.
openSUSE Tumbleweed

#### Hardware / network configuration, and filesystems used.
Processors: 4 × Intel® Core™ i5-6500T CPU @ 2.50GHz
Memory: 15,5 GiB RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 530 

#### How much data is handled by borg?
< 1GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
START=$(date +"%Y-%m-%d_%H%M")
borg create --compression zlib,9 /HD2/mykderepo/::'myrepo-'$START --patterns-from borginclude.lst

```
borginclude.lst:
```
P sh
R /home/
+ '/home/myhome/.*'
- /home/myhome/.cache
```

## Describe the problem you're observing.
Everything in /home/myhome is saved, except of the .cache folder. Bold one shouldn't be saved.

Borg mount insight extract:

x /home/myhome/.cache/kinfocenter/qmlcache/2ddd0ad42abe0d67a00c89fc9eda5c949ef3c918.qmlc
x /home/myhome/.cache/kinfocenter/qmlcache/7d6f70b15d4b427dc701306a26aea666421f1545.qmlc
x /home/myhome/.cache/kinfocenter/qmlcache/1bb9034f1a64d20cad06a1566a4a0b1551cfba79.qmlc
A /home/myhome/.face
A /home/myhome/.directory
A /home/myhome/.Xauthority
A /home/myhome/.gtkrc-2.0
**A /home/myhome/deldown.sh**
d /home/myhome
d /home

**Comment by ThomasWaldmann** [comment]
If you invoke borg and give one or multiple recursion roots, the default behaviour is to include everything below that. You notice that easily if you do not use any include or exclude patterns at all.

If you do not want that, you need to use an exclusion pattern. In your case, you want to exclude all files.

But, as there is an exception to that rule (hidden files starting with a dot), you need to include these and that pattern needs to come before the all-files-exclusion, because first matching pattern wins.

You do **not** need to quote patterns if you put the stuff into a patterns file. Quoting is for keeping the shell away from doing shell expansion. But the shell does not process the contents in the patterns file.

```
R /home/
+ /home/myhome/.*
- **
```

Related docs (please read them and suggest improvements):

https://borgbackup.readthedocs.io/en/stable/usage/help.html

```
Inclusion patterns are useful to include paths that are contained in an excluded path.
The first matching pattern is used so if an include pattern matches before an
exclude pattern, the file is backed up.
If an exclude-norecurse pattern matches a directory, it won’t recurse into it and
won’t discover any potential matches for include rules below that directory.
```

**Comment by bobblkabb** [comment]
That's it, actually very simple.
Thanks a lot!
