### ISSUE TITLE
"Previously missing file chunk is still missing" message

### ISSUE THREAD

**Issue by olaquetal** [borgbackup/borg#5235]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes
## Is this a BUG / ISSUE report or a QUESTION?
Issue report
#### Your borg version (borg -V).
borg 1.2.0a4
#### Operating system (distribution) and version.
Linux Mageia 5.6.14-desktop-2.mga7
#### Hardware / network configuration, and filesystems used.
fuse on s3 using s3fs V1.86
#### How much data is handled by borg?
43Go
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg check -v --progress  --archives-only repo

## Describe the problem you're observing.
I had a file permission error during a create (I have a quite slow connection, that might generate some problems)
After a check I had errors found, so I ran a check with repair, that ended fine as far as I understood 
When I run a new check, I have a lot of this messages:
```
<filename>: Previously missing file chunk is still missing (Byte 0-37351). It has a all-zero replacement chunk already.
....
Archive consistency check complete, no problems found.
```
There are missing chunks but at the end it states no problems found.
What should I do?
Thanks a lot

**Comment by ThomasWaldmann** [comment]
If borg repairs a repo and there are chunks missing (e.g. because of filesystem issues, deleted segment files, read errors, ...), it will patch the affected files with all-zero replacement chunks of same length.
AND it will remember that it has done this and it will also remember the original chunk id of the (currently missing) correct chunk.

When doing that patching, it will give you some appropriate error log output.

What you see above is kind of a **reminder** that these chunks are still missing. Sometimes a chunk reappears because it is still generated from source data and stored again into the repo. If that has happened and you run a `borg check --repair` afterwards, borg will heal the place that currently has the all-zero replacement chunk and use the correct chunk there again.

So, the logical structure of the repo is ok, but there are still all-zero replacement chunks in use.

If the original chunk is lost and can't be regenerated from source data, there is nothing you can do about that.

**Comment by olaquetal** [comment]
> If the original chunk is lost and can't be regenerated from source data, there is nothing you can do about that.

Thanks for the information.
The original files are still there. 
I did a "borg create " last night with same directories which ended without errors and then a 
borg check -v --archives-only <last-archive-name>
without errors too. I avoid doing a full check if I can because it's too long for my connection.
Then I should not worry, there should be no more missing chunks?
Thanks a lot

**Comment by ThomasWaldmann** [comment]
If borg fixes such an issue, it also tells you via log output.

If you only run a partial check, be careful (as it is only partial), see man page / docs for borg check.

**Comment by olaquetal** [comment]
> If borg fixes such an issue, it also tells you via log output.

Indeed, In ran another check and I had lot of output:
"Healed previously missing file chunk! "
and 
"Completely healed previously damaged file!"
Great ! :+1:
