### ISSUE TITLE
borg mount out of memory

### ISSUE THREAD

**Issue by leagueofsoups** [borgbackup/borg#5244]
Hi! I use borgbackup-1.1.11-3.el7.x86_64, this is last version on epel repos. My server have centos7 operation system and kernel 3.10.0-1127.

I have borg repository with two archive (this is jpeg images). Source directory size about 2Tb.
borg info output:
```
                       Original size      Compressed size    Deduplicated size
All archives:                4.21 TB              4.21 TB              1.41 TB

                       Unique chunks         Total chunks
Chunk index:                 2320978              6795534
```
when I mount my repository like this
```
BORG_RSH='ssh -i /home/borg-ci/.ssh/id_rsa' borg mount ssh://borg-backup-push@n2-bkp:22/TSUM_BACKUP/<repo_dir> /backup
```

and I try:
```
ls /backup # I see two my archive
ls /backup/<archive_name> # console freezes, memory utilization of borg mout process encrese, until oom killer come 
```
no result with -f --debug keys add to borg  mount

problem process strace:
[borg_oom.gz](https://github.com/borgbackup/borg/files/4863304/borg_oom.gz)

my server have 6gb ram

**Comment by infectormp** [comment]
Can you try to reproduce this issue with the latest version of borg?

**Comment by leagueofsoups** [comment]
reproduce on borgbackup-1.1.13-2.el7.x86_64
100% borg mount cpu utilization, until oom killer come

**Comment by ThomasWaldmann** [comment]
There are multiple things to consider here:

- i fixed a memory leak recently (not sure it affects borg mount though), that's why 1.1.13 would be good to try.

- in general, borg mount may use a lot of memory when mounting big repos / archives. you can reduce that by only doing a partial mount (e.g. only 1 archive instead of whole repo or even only a specific directory in one archive, see the docs).

- if you don't get it working with borg mount, you can still use borg list and borg extract to get what you need (the memory leak i mentioned above may also affect borg extract though).

**Comment by leagueofsoups** [comment]
@ThomasWaldmann @infectormp many thanks
borg extract resolve my problem
