### ISSUE TITLE
Any way to extract files from a borg stdin file?

### ISSUE THREAD

**Issue by ChojinDSL** [borgbackup/borg#5257]
Hi, I was trying to move stuff from one repo to another. So I wrote a bash script that does something along the lines of :
borg extract --stdout | borg create --name "blah" -

This resulted in the new archive just containing a single file called "stdin"

Let's assume that I was stupid enough to delete each source archive after "copying" it, so I'm only left with the target repo with archives where each one only contains a single stdin file. 

Is there any way to extract all the backed up files from that stdin file?

**Comment by ThomasWaldmann** [comment]
if you use `borg create repo::archive -` it will just take every byte coming in over stdin and write it to a single file `stdin` in the archive. this is usually used to to save sqldumps or disk images.

to extract such (!) an archive, the counterpart is `borg extract --stdout repo::archive` - it will just pump out every byte it extracts from the archive to stdout (and from there, one usually pipes it to sql db or disk).

your problem is that you extract a multiple file archive and just wrote every content byte of many files to stdout, thus you lost all filenames, metadata and also file boundaries.

so while you still somehow have all content, you can not easily split that into individual files now - you don't have the metadata for that (file names, sizes, ...).

so guess that is a "shit happens" type of event, sorry!

**Comment by ChojinDSL** [comment]
Ah ok, oh well live and learn. :-)
