### ISSUE TITLE
How to deal with `compact` in 1.2

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#5315]
Will there be support to detect if `borg compact –cleanup-commit` ever ran? I'm a bit worried that it will be hard to keep track of such upgrade tasks. Or will there be something like '1.2.0 upgrades done' and a command that does all of them? (Right now I only found this recommended upgrade task.)

Second thing, always running compact is bad because it's slow. That was my takeaway message. Running it after purge however, seems to be a good idea? And after `borg create`? Every few weeks? Will the repo know when the last `compact` was done? If the server does it, a GUI could skip it in this case. Or if multiple clients use the same repo, not all have to do it.

**Comment by ThomasWaldmann** [comment]
Well, you could look into the repo dir - if there are tons of 17 bytes file, you'll want to run the cleanup.

compact makes sense if there is something to compact (== new logical holes in segment files due to chunks being logically deleted).
so that's after delete and prune usually.

you don't need to run it after every prune, just if you expect to actually free up space.
