### ISSUE TITLE
1.1.15b1 testing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5414]
I made a new release 1.1.15b1 for testing, see there:

https://github.com/borgbackup/borg/releases/tag/1.1.15b1

As you see, the borg code is pretty much the same as in 1.1.14, but especially the binary building got some updates. Thus, primarily the binaries should get some testing, to find issues before I make the final 1.1.15 release later this year.

As they were made on debian stretch with libc 2.24, they will require a libc compatible to that.

The binary not working on linux dists with incompatible libc versions is expected.

Note: In 1.1.14 and before, binaries were built on debian jessie with libc 2.19.

This issue is about general feedback, there is also #5402 about performance and resource usage, please give such feedback there.

**Comment by ThomasWaldmann** [comment]
There is #5402 about performance, please give performance feedback there.

**Comment by noplanman** [comment]
We've decided to build the ARM binaries for alpha and beta versions too 👍 

You can find them at https://borg.bauerj.eu/?show-unstable

I'll be updating the build system to also include all 1.2.* alpha builds.

**Comment by mmarinez** [comment]
Hi, I would like to work on this issue. Is there anything else I would need to know before starting the testing?

**Comment by ThomasWaldmann** [comment]
https://github.com/pyinstaller/pyinstaller/issues/2357 see the last comment there, maybe test that, too.

**Comment by ThomasWaldmann** [comment]
@mmarinez well, the biggest change is about how the binary is built / the glibc it is built for / the python version it bundles/uses, so guess testing should address primarily that.

**Comment by m3nu** [comment]
> Guess this might be interesting in the context of vorta calling borg as a subprocess. @m3nu

For macOS I'm currently using the develop branch of PyInstaller due to [this issue](https://github.com/gridsync/gridsync/issues/267#issuecomment-609980411), which needs a bootloader with newer `MACOSX_DEPLOYMENT_TARGET`.

With this setup I didn't see any issue when calling `subprocess` on the Pyinstaller `borg` binary. I also tried building the `borg` binary with the official Pyinstaller version on PyPi. No issue either.

Maybe the linked issue is related to Linux or to single binary Pyinstaller executables. For Vorta and Borg on macOS we only use single directory binaries to get around macOS signing issues.

**Comment by ThomasWaldmann** [comment]
releasing 1.1.15 now, thus closing this issue.
