### ISSUE TITLE
Clarifcation option --keep-daily

### ISSUE THREAD

**Issue by vincenzogianfelice** [borgbackup/borg#5596]
Hi. Today I did some tests with the prune command, and tried to set the `--keep-daily` to **7**. Now, if I try to run the prune command every day, it also deletes my previous backups. The question is: if I have set that every **7** days (therefore every **7** backups) must delete the oldest backups, why if I launch the command it deletes the backups even if the **7** days have not passed?

Thanks

**Comment by ThomasWaldmann** [comment]
Please read the docs about what borg prune does exactly. There is also a detailled example in docs/misc/...

If you still have questions after that, we need all the details, like timestamps of all archives, verbose/list output of prune, borg version etc.

**Comment by vincenzogianfelice** [comment]
in reality it is only a clarification ... it may be that I misunderstood.
I tell you my backup strategy. I backup every day at 00:10 and I would like to have 1 backup every week, 4 backups for 4 weeks, and 1 backup for each month ... I don't know if I made myself clear. Here, I tell you how I would have set the prune command.

`--keep-daily 1 --keep-weekly 1 --kee-monthly 1`

Is correct?

Thanks.

**Comment by ThomasWaldmann** [comment]
No, your spec is not clear.

But I think you could use:
```
--keep-daily 7 --keep-weekly 4 --keep-monthly 12
```
That approximately means what it reads like. What it does exactly is described in our docs.

Note that using very low values for daily (and also, to a lesser degree, for weekly) is a bit pointless, because you do not save much repo storage space by doing that, but you risk not having a backup for what you want to restore, even if you have just lost it a few days before.

Considering that, this is likely better:
```
--keep-daily 14 --keep-weekly 8 --keep-monthly 12
```

If there is a chance that you'ld need a backup older than 12 months, you could also add `--keep-yearly 5` or so.

If you can afford longer `borg check` runtimes, you can also increase the daily and weekly even more.

Additional close-time-distance backups are cheap, storage-wise, but need time within a borg check run.
