### ISSUE TITLE
check why there is substantial repo size growth

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5736]
See there: https://gist.github.com/scy/de5176aef9209cb07e5f8c7b365cfbf1

**Most of the experiment done there yields results as expected**:
- deduplication works
- deduplication has some overhead, depending on chunk size (this will matter at boundaries)

But:

```
# Concatenate all three files that are already in the repo to a new file "c", add that.
$ cat a a1 b > c
$ borgbackup create sizetest::five c
$ du -sh sizetest
280M    sizetest
# Size has increased substantially (because of chunking), but deduplication still shows.
```
**This (+30MB) is a bit more growth than expected**, I'ld expect less than half of that.

Of course, this depends on:
- chunk size (default: 2MiB)
- chunker secret (always random and per repo)
- on input data, so using random input data might make this not precisely reproducible.

TODO:
- use latest borg 1.1.x and give precise version number with test results
- make a test case without using random data that still reproduces this problem
- do not use compression
- do not use `du -sh repo` but rather `du -sh repo/data` (or borg create --stats output)
- use borg debug / dump commands to get more insights

**Comment by ThomasWaldmann** [comment]
Trying to look at this more precisely:
- file a = A0 A1 A2 A3 ... An
- file b = B0 B1 B2 B3 ... Bm
- file a1 = x A0 A1 A2 ... An
- file c = file a + file a1 + file b = A0 ... An  +  x + A0 ... An  +  B0 ... Bm

The block boundaries in a file are defined by the buzhash algorithm, but also by some other conditions:
- we don't want too small blocks, there is a minimum size (see chunker params)
- if a file ends, a block will of course also end (without requiring buzhash indicating a cutting position)

So, when chunking file c, guess this happens:
1. A0 ... will yield duplicate chunks (as file "a") for all chunks except the last chunk
2. the chunk that has An + x + A0... will be a new one (due to buzhash determining chunk end)
3. the next chunk might or might not be a duplicate chunk (depends on size condition and resyncing)
4. some duplicate chunks from file a1 except last chunk
5. the chunk that has An + B0 will be a new one (due to buzhash determining chunk end)
6. the next chunk might or might not be a duplicate chunk (depends on size condition and resyncing)
7. some duplicate chunks from file b including the last chunk

So:
- for sure: 2 new chunks from 2. and 5.
- maybe: 2 new chunks from 3. and 6.

By default, chunks are between 0.5MiB and 8MiB with a target size of 2MiB.
We get 2 to 4 new chunks, so that could be 1MiB up to 32MiB growth.

So the observed +30MiB is at the upper end of that range, but still explainable.

Deduplication efficiency can be improved by using a smaller target chunk size, but that does not come for free, you have to "pay" for that by increased management overhead (bigger hashtable sizes, more RAM and disk consumption for these).

Restic (IIRC) has a default target size of 1MiB, so that might explain why you got a bit better results for restic.
You can have that with borg, too, if you use `--chunker-params`.

**Comment by ThomasWaldmann** [comment]
The above is a purely theoretical estimation. If someone feels like, prove me correct or incorrect. :-)

**Comment by jdchristensen** [comment]
I tested the above with borg 1.1.15.  I started with `alias borgbackup=borg`, and then did exactly the same commands as in the gist.  I got much better results for my sizes:
```
101M # just a
101M # a re-added
201M # b added
202M # a1 added (a with two bytes at start)
207M # c added (a + a1 + b)
```
So I think all is working as expected.  The restic repo ended up with 218M, so borg beats restic in this test, even though the default block size is larger.  Maybe the results depend on the random bytes in the file?  I think the original poster should let us know what version of borg they used, try with a new borg, and try with new random data.

**Comment by scy** [comment]
Hi there, I’m the guy that wrote the Gist. Thanks for looking at it. Please let me start by saying that I wouldn’t have opened an issue about it myself, at least not without additional investigation and a more thorough test setup. @ThomasWaldmann saw my tweet about it and I guess got curious, too ;) Thanks for looking into this.

> Maybe the results depend on the random bytes in the file?

Possible. As far as I can see, nobody of us used `--compression none`, right? That might also have side effects.

> I think the original poster should let us know what version of borg they used, try with a new borg, and try with new random data.

I’ve been using `borgbackup 1.1.15` in the Gist. And I’ve tested again, with new random data:

```sh
borgbackup init -e repokey-blake2 sizetest
du -bsh sizetest/data; du -sh sizetest/data  # 8.6K / 0
borgbackup create sizetest::one a
du -bsh sizetest/data; du -sh sizetest/data  # 101M / 109M
borgbackup create sizetest::two a
du -bsh sizetest/data; du -sh sizetest/data  # 101M / 109M
borgbackup create sizetest::three b
du -bsh sizetest/data; du -sh sizetest/data  # 201M / 222M
cat <(echo x) a > a1
borgbackup create sizetest::four a1
du -bsh sizetest/data; du -sh sizetest/data  # 206M / 227M
cat a a1 b > c
borgbackup create sizetest::five c
du -bsh sizetest/data; du -sh sizetest/data  # 213M / 237M
```

I’ve checked both `du -sh` as well as `du -bsh` in this new test. As you can see, there’s a significant difference between “file size” and “disk usage”, which is of course usually explained by the filesystem’s “block” or “cluster” size. However, `find sizetest -type f | wc -l` shows only 21 files. They shouldn’t add up to 24 MB in overhead.

I’m running these tests on Ubuntu on Windows 10’s WSL1. Checking the directory size on the host machine’s NTFS filesystem (`C:\Users\scy\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\scy\tmp\sizetest`) confirms that Windows considers `sizetest` to contain 212 MB of data and occupying 236 MB of disk real estate. No idea what’s happening here, but I tend to declare Borg to be innocent.

But, since this issue is already open, would one of you care to comment on what I called “initial test setup”, the part at the end of my Gist? In a nutshell, I was checking the following:

* On my volume B, I have a Borg repo that contains a file X. The repo is unencrypted and uses no compression.
* That same file X is also present directly (i.e. outside of the Borg repo) on volume B.
* Were I to create a _second_ Borg repo that includes both the “inner” Borg repo on volume B (and in it the file X) as well as the original file X, how well would the two occurences of X be deduplicated against each other?

I’ve tried to read up on Borg’s internal data structures in order to find out whether the file X could be found pretty much unmodified somewhere in the repo’s `data` directory (and thus might be able to be efficiently deduplicated), but didn’t find the answer. (To be fair, I didn’t invest a lot of time.) When testing, it looked as if file X ended up interspersed with metadata or some other internal datastructure in `data`, cutting it in pieces and therefore basically preventing deduplication completely. Is this what you’d expect, too?

And I know that this is kind of a strange setup. If you’re interested, the reason is this: Basically I have two disks, 2 TB and 14 TB, and I’d like to back up the 2 TB disk onto the 14 TB one, and back up the 14 TB one to another machine. However, sometimes I move some large files from the smaller to the larger disk, and I wouldn’t want it to occupy space twice then (once in the backup of the smaller disk, once in the backup of the larger one). That’s why my idea was to turn off encryption and compression for the 2 TB disk’s repo, hoping that the files could then be deduplicated (at least to a certain degree), no matter on which of the two disks they were stored.

**Comment by ThomasWaldmann** [comment]
Compression: does not influence chunking or dedup (as that is done on not compressed, not encrypted data). Size will vary a bit of course, but if you use pure random, it won't compress anyway, but rather grow a little maybe due to compression overhead.

The effect you've observed in your "initial setup" might be due to the chunker secret: a file is chunked differently depending on the repo (on the per-repo unique random chunker secret). So likely you'ld get a rather bad dedup as the chunks are cut at different places. This is a security feature.

Also, because multiple chunks are put together into segment files, there is a similar effect as in my analysis above: where there was a file end in the original data forcing a chunk end also, there is no file end in the middle of a segment file, so the buzhash will trigger the cutting at another place. Also, the additional metadata in the segment files will change cutting places.

**Comment by ThomasWaldmann** [comment]
reproducer for macOS:
```
#!/bin/bash
head -c 100000000 /dev/urandom > a
head -c 100000000 /dev/urandom > b
borg init -e none sizetest
du -Ash sizetest/data; du -sh sizetest/data  # 2K / 8K
borg create sizetest::one a
du -Ash sizetest/data; du -sh sizetest/data  # 96M / 96M
borg create sizetest::two a
du -Ash sizetest/data; du -sh sizetest/data  # 96M / 96M
borg create sizetest::three b
du -Ash sizetest/data; du -sh sizetest/data  # 191M / 192M
cat <(echo x) a > a1
borg create sizetest::four a1
du -Ash sizetest/data; du -sh sizetest/data  # 194M / 194M
cat a a1 b > c
borg create sizetest::five c
du -Ash sizetest/data; du -sh sizetest/data  # 205M / 205M
BORG_DELETE_I_KNOW_WHAT_I_AM_DOING=YES borg delete sizetest
```

**Comment by ThomasWaldmann** [comment]
If I run that multiple times, the sizes fluctuate a bit. So it really depends on the random data which influences chunk sizes.

But everything is in the expected range, so I am closing this now.
