### ISSUE TITLE
reimplement files cache using hashindex code

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5756]
the files cache uses python dicts currently because cache entries also have variable length lists (the chunks list).
this makes it easy to deal with, but also comes with some memory overhead.

@RonnyPfannschmidt had this idea for a more efficient replacement:
- a hashindex for the fixed size entries (all fixed stuff, including the pointer mentioned below for the chunks list)
- store all the chunk list items into one big array and point into that array via (starting index, length of list)

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt do you want to implement that? we could have a bounty for this.

**Comment by RonnyPfannschmidt** [comment]
Potentially, but not soon, currently I am rather thin stretched

**Comment by ThomasWaldmann** [comment]
Current implementation (borg < 1.2):
```
FileCacheEntry = namedtuple('FileCacheEntry', 'age inode size cmtime chunk_ids')
age: 0 .. max_ttl, int 16bit?
inode: see st_ino, int 64bit?
size: see st_size, int 64bit
cmtime: see st_(c|m)time_ns, currently int 64bit or bigint bytestr, 64bit should be ok!?
chunk_ids: list of chunk hashes, 256bits each
path_hash = key.id_hash(filepath)
files[path_hash] = msgpack.packb(FileCacheEntry())
```

**Comment by ThomasWaldmann** [comment]
New implementation idea:
```
FileCache hashindex entry:
age: 32bit (shared for in-band hashtable management)
inode: 64bit
size: 64bit
cmtime: 64bit
chunk_ids_start: 64bit
chunk_ids_count: 64bit
path_hash: 256bit (key)

chunk_ids array of chunk_id elements, 256bit each
```

**Comment by ThomasWaldmann** [comment]
So, do I estimate correctly, that we'ld usuall save 63 - 16 == 47 bytes?

For people running into memory issues, I guess we can assume they have a lot of relatively small files, so there is only 1 chunk in the chunks_ids list.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt can you check? ^^^

**Comment by RonnyPfannschmidt** [comment]
I'll give it a spin later in the evening, im currently working on details for an memory layout idea that may be of use to sort it differently

**Comment by RonnyPfannschmidt** [comment]
I have a basic idea for a structure which allows to use shareable memory mapped files and potentially 32 bit for most values, going by the assumption that in practice it is very unlikely to observe more than  2**30 chunk items there,


The idea needs to be tested, will try once the toddler sleeps

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann my initial experiment failed, and needs some better planning

i believe i'm able to provide a mmap backed variant of the hash-index 
in order to get that working correctly i need to experiment with understanding the involved data-structures
and get a handle on the bucketing/reading/mapping

**Comment by Gelma** [comment]
Thanks a lot for your effort, guys.

Just for the record: in my case, with ~45.000.000 files, I have Borg using ~11GB of RAM. Also, the startup takes minutes (I guess is the Python unpickling object).

Also I have some swapin/swapon of the process (I guess the data are updated, with all the work of interpreter under the hood).

Anyway, I just kindly ask: using sqlite to store 'em? So, no matter the number of files, the RAM usage is always the same.

Thanks a lot again,
Gelma

**Comment by ThomasWaldmann** [comment]
@Gelma borg accesses these hashtables a lot and my gut feeling about speed is: hashindex (RAM) >> hashindex (mmap) >> sqlite (disk).

Especially for non-first backups of mostly unchanged files, the high speed if the in-memory hashtables makes borg very fast.

So the minutes of startup time and some RAM usage may be well invested when the alternative is hours or days longer runtime due to disk accesses.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt maybe we can split the "save RAM" (by using less RAM) and "use mmap" (only have in RAM what we access) aspects. The first is likely generally useful, the latter only maybe.

Attic author tried to use mmaped hashindex long ago and it was unsuccessful (too slow).
But, back then, there was no fadvise DONTNEED and similar stuff in the code.

**Comment by RonnyPfannschmidt** [comment]
The data structure im proposing will potentially archive both (everything should be able to work without mmap) 

I'll have to demo it

**Comment by MichaelDietzel** [comment]
This inspired me to think of something similar for the chunks cache. I hope this is the right place and I understood everything correctly. I only had a short look at the source code of borg but in case you say this could be interesting I could try to find some time to take a deeper look.
According to [this documentation](https://borgbackup.readthedocs.io/en/1.4.0/internals/data-structures.html#indexes-caches-memory-usage) the chunks cache uses at least 58.7 bytes for each entry, assuming the hash table can be filled up to 75%. When adding even more chunks it has to grow and even more memory is needed for a short time.

So maybe an indirect approach with one hash table just holding indices to an array containing the "real data" could be more memory efficient?
The hash table holding the indices would need to hold a 4 byte index for each chunk (except for really large repositories, is this even possible? But even with 8 bytes for each entry it would still save memory). This would result in 5.3 bytes in case you assume it to be 75% filled.
The array storing the entries, that are stored in the hash table in the current implementation, would need 44 bytes each as before. But it could be 100% filled, assuming you use the Linux equivalent of virtual-alloc on Windows (sorry, I just have experience with virtual-alloc in windows and have never used something similar in linux). The idea is to just reserve a huge amount of memory "adresses" for the array but only request them to be actually backed by memory once they are really needed. The downside is that this only works well easily on 64bit OSes, as there the address space is large enough to be able to waste a lot of adresses. (But you could also just use plain malloc of an array which would be 100% filled once the hash table reaches 75% and could still reduce memory usage. Or one could implement a custom solution that does more or less the same that is done by the MMU when using virtual alloc)

The result would be an average memory consumption of 49.3 bytes for each entry in the chunk cache at a load factor of 75% instead of 58.7 bytes. For a load factor of 50% it would be even better: 52 bytes instead of 88 bytes. And an even bigger improvement could be achieved for cases where the chunk cache needs to grow, only the hash table needs to be reallocated, the array could just stay the same (assuming enough memory adresses were reserved). Maybe the hash table could even be recreated from the array so that there would not be any allocation peak at all?

Removing entries from the hash table would also be possible, assuming that the hash of the chunk is stored in the array as well. Just move the last entry in the array to the index that was deleted and update the hash table accordingly.

Maybe the index could even be used in some other places where currently the whole hash of the chunk needs to be stored to be able to reduce the memory consumption even further? (I didn't check if there are any such places). However this could make removing entries more complicated

I hope I wrote this not to confusingly and it is somewhat clear to understand.

**Comment by ThomasWaldmann** [comment]
@MichaelDietzel yeah, guess we'll do something like that at some time.

Another (easier) idea to get started would be to just optimize the chunkid+size tuple list:
- assume we have a ChunkIndex hashtable that internally uses an array to store chunkid key and size value.
- assume the key/value entries have stable indexes inside the array, nothing moves around, only stuff gets added at the end.
- then we could use the array index to abbreviate the chunkid+size in files cache chunks list entries.

**Comment by MichaelDietzel** [comment]
> @MichaelDietzel quite some of your ideas are implemented by using `borghash` in borg2 beta13.
> 
> In master branch, I am currently working on my idea from previous comment, #8511.
> 
> Maybe @Gelma or somebody else with a huge files count can test it after it is in master or in next beta (b14).

@ThomasWaldmann Thanks a lot, this is awesome! I already had a short look and probably will write some more ideas over at the borghash-repo

**Comment by Gelma** [comment]
> Maybe @Gelma or somebody else with a huge files count can test it after it is in master or in next beta (b14).

Sorry for late reply. Well, I can try. I should have enough storage. It will takes weeks (now we are > 100.000.000 files for ~200TB deduplicated and compressed). In the meanwhile abusing zswap kernel module helped a lot!!!

**Comment by ThomasWaldmann** [comment]
@Gelma No, the way to test borg2 is to have a separate repository for borg2.

If you like to test `borg2 transfer` also, you could start by:
- creating a "related" repository
- transferring your borg1 repo contents to the borg2 repo

(see the borg2 transfer command docs / examples)
