### ISSUE TITLE
Multithreading: Using Rust-based compression libraries for Borg?

### ISSUE THREAD

**Issue by kimono-koans** [borgbackup/borg#5764]
Multithreading seems to be an issue that hasn't been resolved despite efforts to do so: #37, #929 and #3500.  Please correct me if I'm wrong.  My experience has been that, on my laptop, a 'borg create' pins one core at ~100% for almost the length of the update.

Has anyone considered implementing multithreading (compression, encryption, etc.) incrementally by using Rust-based compression libraries?  I don't want to say that Rust makes a complicated thing easy, but I will say I've been very impressed by how easy parallelism has been, using certain libraries (such as the Rayon crate).

More particularly, the zstd crate looks to be high quality.  I whipped up a multithreaded compression shim for Python relatively quickly.  And -- it might even work if archive.py could give me a streaming read(!).  Is any borg Python developer interested in assisting on this, even simply as a proof of concept?  FYI I'm not an expert in Rust or really anything at all.

**Comment by ThomasWaldmann** [comment]
Well, I don't think I want to add a rust dependency a) for this and b) now. Also, I do not want to move the boundary between the low level code (currently C, alternatively Rust) and the Python code, like doing more in the lowlevel part.

I general, I see Rust as a good alternative for our C based code (like _hashindex.c), but considering that stuff works and is rather stable, there is no big hurry in changing anything there. Esp. since we do not just have to support Linux, but also many other platforms.

Considering the usual multithreading support in some compression libs (not sure if yours is made in a similar way): doesn't help much if it just divides the input data into multiple pieces, because each piece (== chunk) for borg isn't that big anyway. Compression would suffer due to smaller size, overhead might be significant.

**Comment by electricboogie** [comment]
Totally understand.

**Comment by electricboogie** [comment]
Can I ask why _hashindex.c (or other code) might be a good candidate/s?  I haven't profiled this code.  Is that a bottleneck?

**Comment by ThomasWaldmann** [comment]
That's our homegrown hashtabe and yes, this is performance critical (speed as well as memory usage).

The idea to have that (and other already existing C code in borg) in Rust at some time in the future rather comes from Rust being more strict and less error prone than C (not because I expect it to be faster or consume less memory in Rust).

**Comment by GeNTooFReaK** [comment]
I'm always using zstd compression with borg and was a bit disappointed that it's only 1 core to compress.

In the changelog of 1.4.7 of zstd stands:
> cli : Set nb of threads with environment variable ZSTD_NBTHREADS, by @senhuang42

But I'm not sure and have not tried yet if zstd triggered by borg will respect that var. And because of the chunking it might not improve the speed at all.

**Comment by ThomasWaldmann** [comment]
@GeNTooFReaK that refers to the zstd commandline tool (`cli`). borg just calls some single-threaded library functions.
