### ISSUE TITLE
pfSense/freebsd: dlopen: /tmp/_MEISSz5ZE/libpython3.7m.so.1.0: Undefined symbol "fstat@FBSD_1.5"

### ISSUE THREAD

**Issue by kosch** [borgbackup/borg#5796]
Environment:
pfSense 2.4.5 based on FreeBSD 11.3

Error:
[84828] Error loading Python lib '/tmp/_MEISSz5ZE/libpython3.7m.so.1.0': dlopen: /tmp/_MEISSz5ZE/libpython3.7m.so.1.0: Undefined symbol "fstat@FBSD_1.5"
When executing 1.1.16 binary for freebsd64

Workaround:
1.1.15 borg-freebsd64 works fine.

**Comment by ThomasWaldmann** [comment]
As documented in the README for the binaries:

- borg 1.1.15 binary was built on freebsd 10.3
- borg 1.1.16 binary was built on freebsd 12.1

IIRC, I had to upgrade the freebsd vagrant box due to new issues appearing on freebsd 10.3.

I try to keep old boxes as long as possible, so the generated binaries also run on old systems,

But if stuff breaks, I have to move to something newer.

**Comment by ThomasWaldmann** [comment]
Note: Keep this open for a while so other people searching for this issue can find it.

**Comment by kosch** [comment]
That was the major intention, just FYI the successor pfsense 2.5 is based on freebsd 12.2.
We're fine with 1.1.15 till we can migrate to newer pfsense.

**Comment by ThomasWaldmann** [comment]
Guess this can be closed considering pfsense 2.6.0 is the current version.
