### ISSUE TITLE
When does Borg read files (chunks caches and files caches) for checksum testing?

### ISSUE THREAD

**Issue by gvkazare** [borgbackup/borg#5864]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

Hi. I have read the **Checksumming data structures** chapter of Borg documenattion, but I have a question about it. I’d appreciate to get an explaination. 

It said "Therefore, Borg calculates checksums when writing these files (chunks caches and files caches) and tests checksums when reading them". 

Does Borg read files (chunks caches and files caches) for checksum testing durring a backup time, and if checksums are wrong Borg interrupts the backup and throws an exception borg.crypto.file_integrity.FileIntegrityError to make me recheck my HDD/SDD and an integrity of my data? Or Borg does read the files for checksum testing when I run `borg check` command after the backup ending only?

**Comment by ThomasWaldmann** [comment]
The files cache and the chunks index files are loaded into memory before `borg create` starts to actually back up files.
While it is loading these, it is checking their integrity against the hash from the cache config.

In case of a corrupted chunks index, it would throw an exception and abort. The fix for that would be to check your hardware and/or run `borg check --repair`.

In case of a corrupted files cache, it will continue without files cache (so it will be rather slow) and rebuild a new files cache.

`borg check --repair`

**Comment by gvkazare** [comment]
Ok, I got it.
Does Borg test the files cache and the chunks index files after the transmission of they over the network to a Borg remote repository? In case of the corrupted files due to network problems, would it throw an exception before writing the corrupted files to the repository?

**Comment by ThomasWaldmann** [comment]
The files cache is local on the client, so it is not transferred over the network (if you use a remote repo).

The chunks index is also available locally. Either it is in sync with the repo, then it is just used. If not, it updates / rebuilds the local chunks index using metadata it gets from the remote repo archives or from cached information in chunks.archive.d. This stuff is also checked via hashes / checksums, so no problem.

**Comment by gvkazare** [comment]
Thank you for answering!
