### ISSUE TITLE
Setting borg-repository to locked until lock is broken

### ISSUE THREAD

**Issue by niklassc7** [borgbackup/borg#6020]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.9

#### Operating system (distribution) and version.

Debian 10.11

## Describe the problem you're observing.

On the server that stores the borg-repos I want to set up the IBM Tivoli Storage Manager to make infrastructure-independent copies of the repos.
While the Tivoli backup runs, nothing should be written to the repos so that they're not corrupted.

Since the TIvoli Storage Manager runs as a service and is scheduled I cannot use `borg with-lock` because I'm not executing the backup directly. It provides an option `PRESCHEDULECMD` and `POSTSCHEDULECMD` where commands can be set that will be run before / after the backup is started, and only if `PRESCHEDULECMD` has exit code 0.

## Question

Is there a way which securely locks a borg repository (only returns exit code 0 if successful) and then terminates with the repo still being locked?

**Comment by ThomasWaldmann** [comment]
I just noticed that with the new borgstore based repo locking system in #8332, only a `borg lock create` and `borg lock remove` script commands would not be sufficient, because the new repo locks now auto-expire if they don't get refreshed by a running process.

So, it would at least need another command `borg lock refresh` command and that would have to be called regularly to keep the lock fresh and avoid having it killed by some other borg process.

**Comment by ThomasWaldmann** [comment]
Guess we have too much issues with that, closing.
