### ISSUE TITLE
Return a different exit code if archive name already exists

### ISSUE THREAD

**Issue by Orbixx** [borgbackup/borg#603]
Use case: I want to run daily backups of my desktop, which is not always on. A reliable way of doing this is having my desktop manager execute borg create at login time. In some cases I will need to restart and log in again.

My script attempts to use "notify-send" to report on the status of the backup to the desktop GUI by interpreting borg exit codes. The archive already existing and borg exiting with no action is expected and desired behaviour, but obviously not deserving of a 0 exit code. It currently exits with code 2, which is the same as some other erroneous conditions which are far more severe in my use case.

Unless somebody can think of a better idea to serve this use case, can this exception exit on a different exit code please?

**Comment by ThomasWaldmann** [comment]
I'll have a look at it.

I never had that issue because my automated scripts just use hostname-YYYY-MM-DD-hh:mm:ss as archive name (with the hostname being the real hostname and the date/time being the current time).

**Comment by Orbixx** [comment]
Yeah that would fix it, kind of. Although I have a prune task that prunes daily/weekly/monthly, would this prune the earlier backup from the same day, or the oldest day backup?

**Comment by ThomasWaldmann** [comment]
Sounds like prune is unrelated to this issue, maybe have a look at #602 and the docs?

**Comment by ThomasWaldmann** [comment]
Hmm, exit code 2 is currently used to mean "suddenly aborted, backup did not start/complete due to some error condition". exit code 1 is currently used as "there was a warning (e.g. a single file could not be backed up), but the backup reached its normal end".

So, according to this, 2 is the correct error code, because the backup you started could not be executed.

**Comment by Orbixx** [comment]
Based on those definitions, of course it is the correct error code. I am not disputing that kind of validity. I am arguing for a different kind of definition and perhaps the establishing of a different, new error code.

The result of a backup not taking place because it already exists with the same name and does not need resuming and needs no change may be a desired output by the user and considered a non-error, which by some perceptions may even warrant the exit code of 0. Surely this is deserving of some distinction between the situations you describe where there is an actual discrepancy of data between the source and the remote host.

**Comment by ThomasWaldmann** [comment]
Well, how do you know it needs no change? It aborts early, so borg does not even come to detecting whether files were changed or not.

We could create a separate error code for specific errors, but in that case I think we should collect all such cases in a more generic ticket, so we can do that in one change. As people may have to adapt their error handling, we shouldn't change that too often (and we just did 0/1 -> 0/1/2).

**Comment by ThomasWaldmann** [comment]
See #61 about the previous discussion about exit codes.

**Comment by Orbixx** [comment]
When I run a "borg create", abort half way through then run it again with the same parameters, how does it know to resume? Because once the backup is totally complete, it then returns "archive exists" error. If it can determine it needs to resume, then surely it can also determine that the archive already exists AND matches the source?

**Comment by ThomasWaldmann** [comment]
Ah, now I get your usecase.

The simplest way to avoid this issue is to include datetime in the name, so you never get a conflict.

If you just use a fixed NAME for the archive, there are 3 cases:
- backup gets interrupted early (< 5 minutes, < the checkpoint interval in general). then there will be just some "invisible" uncommitted segments and borg will roll them back the next time you access the repo.
- backup gets interrupted after a checkpoint, but before completion. then you will find an incomplete archive NAME.checkpoint in the repo. All the chunks referenced by NAME.checkpoint are valid and if you just restart the backup, it will reuse these chunks and not re-transmit them. After the backup gets completed you can manually remove the NAME.checkpoint (or keep it, makes no big difference).
- backup gets completed

**Comment by Orbixx** [comment]
> The simplest way to avoid this issue is to include datetime in the name, so you never get a conflict.

Quite, but this makes me concerned about the pruning process which I earlier mentioned:

> Although I have a prune task that prunes daily/weekly/monthly, would this prune the earlier backup from the same day, or the oldest day backup?

Do you know how this would behave?

**Comment by ThomasWaldmann** [comment]
As I said, pruning has nothing to do with the archive names (it just looks at the archive timestamps, which are stored separately from the name). About pruning, see my comment from above and do not mix different topics in one ticket.

**Comment by jdchristensen** [comment]
I think I understand what @Orbixx means, and will try to explain.

He wants at most one backup done per day.  By using an archive name that includes the date but not the time, borg automatically aborts if his script runs twice.  So this works well for him.  But he'd like to be able to use the exit code to determine whether the backup ran, failed because it had already run, or failed due to an error.

If he instead renames the archive to include the time, then he'll get more than one backup per day, and so he'll need to use pruning to keep only one.  And to answer his question:  the oldest one on each day would be kept.

I think that rather than changing the exit code, @Orbixx should do one of the following:

1) Use /etc/cron.daily or the @daily option in crontab to make the job run once per day, even if the computer isn't on all of the time.

2) Use a script that stores a file like /tmp/YYMMDD, and check for that file before running the backup.

3) Parse the output of borg to see if it failed because the archive exists.

**Comment by ThomasWaldmann** [comment]
@jdchristensen are you sure about the oldest one on each day is kept? I thought it keeps the newest one on each day.

**Comment by Orbixx** [comment]
Perfectly described, thank you Dan. I note the cron daily suggestion as a good alternative.

**Comment by jdchristensen** [comment]
@ThomasWaldmann Sorry, I meant the **latest** one on each day.

**Comment by ThomasWaldmann** [comment]
Close issue?

If we ever expand error codes to be more detailled in general (and there needs to be a detailled plan for that first), we could of course add a code for this case, but currently with the 0, 1, 2 generic return codes, I won't add just one additional one just for this case (esp. since it can be solved differently).
