### ISSUE TITLE
Exclude by true file type (based on file content)

### ISSUE THREAD

**Issue by cyril42e** [borgbackup/borg#6051]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION (SUGGESTION)

## System information. For client/server mode post info for both machines.

N/A

## Describe the problem you're observing.

I'm having some trouble to setup excludes as I wish, and I realized that I would like to exclude some files not only based on their name, or their extension, but on their true type (based on the file content).

Extension is not enough because different file types can share the same extension, thus it can be dangerous to rely only on it.

For instance I would like to exclude:

- all compilation objects (*.o, *.a). But I have a few unrelated ".a" files, and it's easy to imagine .o files in other contexts
- core dumps "core". But I did not file a way to exclude only files with some name, and not folders ("fm:*/core" excludes both, and I have some folders named "core").
- *.raw files: some are generated by LTSpice, and are just some cache data, that can be huge. But it is also a very generic extension, for instance a format of raw camera pictures.

I know that I could restrict these extension excludes to some paths only, but it is really painful, and there is always a risk of error.

So I was thinking that we could define some file types, based on the extension (or more generally a file name pattern) **and** a signature in the content.

For instance it could be provided by a python file for each type, that contains a function that returns the name pattern, and another one that takes the file, reads the beginning and returns a boolean "is it my file type". Some standard definitions could be provided with Borg, and the user would be free to add custom ones.

**Comment by ThomasWaldmann** [comment]
I see / understand what you mean, but I do not think it is a good idea:

To create a backup, borg has to look at all files and determine:
- is it included (not excluded)? (usually super cheap matching operation based on path/filename/extension)
- did the contents change compared to what we already have in the repo (usually just a `stat()` which is usually also cheap)

Looking at the contents of a file (like you suggest) to determine inclusion/exclusion means:
- getting slower or even very slow(*), because every file has to be opened and (partially) read
- getting insecure - parsing file contents potentially can trigger bugs in the parser code which would run at root privilege level

(*) I mean relative performance to what we have now. For a typical backup (== not the first one, not many files have changed), borg looks at a lot of unchanged files and just does a `stat()` and then can process them very quickly without having to actually read them. If you would read all of them to determine file type, that is significantly slower for such a backup.

I personally find it kind of tragic that the "file type / mimetype" has never made it to real and separate, precise metadata and most of the world lives with hacks like file extensions (which are not 1:1 with mimetypes and sometimes not even present).

But hacks like `file` or `magic` which try to work around this are even worse in some respects, see above.

**Comment by cyril42e** [comment]
Actually I did not mean to open every file, that's one of the reasons why I mentioned providing a file name pattern (in addition to making it more robust, at least limiting the risk of false positive).

Once we have the list of file types to be excluded for an archive creation, we can preload all the name patterns of the type exclusions, so that we only open files whose name pattern matches one of the type rules, but also only call the scripts defining the types if the name pattern matches (in order to avoid asking every "type script" if every file matches). Hence there would be overhead only for files to be potentially excluded.

For the typical backups that heavily rely on the cache for speedup, not only it would be only type exclusion candidates too, but why not caching the type of excluded files as well? I guess it would not use that much space if there are no chunks to reference?

About the security, indeed I did not think to that. More code increases the risk of bugs of course (especially user-written), but is it a killer argument? About running as root, I guess that the files should be open as read-only, and if borg is run as root the "type scripts" should be run with the file owner, so that would really limit the risks, isn't it?

Another point that applies to both performance and security angles, is that only using the feature would lead to some drawbacks. If it is not enabled by default, and there is a warning in the documentation, then we could consider it is the responsibility of the user.

**Comment by ThomasWaldmann** [comment]
About extending the files cache: the cache is already huge and is loaded into memory completely (this is one of the reasons why borg needs a significant amount of RAM).

We only have included files in there, so putting infos about excluded files in there also could make it even much bigger.

Running detection scripts as file owner would lower the risk, but it would also mean that borg would need to create other processes for that (and not do that in same process), which makes this much slower and more complicated than just a library call.

Another thing i did not mention yet is that there is no configuration language for included/exclude rules that are **not** based on the file name, but on other attributes, like file type / content / size / xattrs / etc.
