### ISSUE TITLE
test methods in wrong test class

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6168]
check for 1.1-maint and master branch:

it seems that there are some test methods in `RemoteArchiverTestCase` that should be rather in the `ArchiverTestCase` class (which is inherited by `RemoteArchiverTestCase`).

idea:
- most tests should be in the base class `ArchiverTestCase`
- the remote tests class should contain tests that only make sense for remote repos
- the remote tests class might contain some test overrides for tests that do not work remotely, but would normally be inherited from the base class
-

**Comment by ThomasWaldmann** [comment]
@hexagonrecursion can you have a look? you added one there (and maybe there already was a bad one there already).

**Comment by ThomasWaldmann** [comment]
Did a quick experiment, this is how it should look like:

```
$ pytest -vk do_not_mention

src/borg/testsuite/archiver.py::ArchiverTestCase::test_do_not_mention_archive_if_you_can_not_find_repo PASSED                                                                                      [ 33%]
src/borg/testsuite/archiver.py::ArchiverTestCaseBinary::test_do_not_mention_archive_if_you_can_not_find_repo SKIPPED (no borg.exe available)                                                       [ 66%]
src/borg/testsuite/archiver.py::RemoteArchiverTestCase::test_do_not_mention_archive_if_you_can_not_find_repo PASSED     
```

**Comment by hexagonrecursion** [comment]
IIRC I put the test there because the bug it reproduces only affected remote archives. I think I did not understand at the time that regular tests are executed for remote archives too. I'll move test_do_not_mention_archive_if_you_can_not_find_repo to ArchiverTestCase.

* test_remote_repo_restrict_to_path and test_remote_repo_restrict_to_repository are in the right class - restrictions are only supported for remote repos
* test_strip_components_doesnt_leak asserts that this line is not triggered:
    https://github.com/borgbackup/borg/blob/56a75ee691f529374e0aba6c6b1a0db1c689b34b/src/borg/remote.py#L619
    this too only applies to remote repositories

**Comment by ThomasWaldmann** [comment]
ah, need to check the strip test again...
