### ISSUE TITLE
Backing up entire disk

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#6213]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Question

## System information. For client/server mode post info for both machines.
Any

#########################################

Hi All!

I am a beginner (but fascinated) user Borg + Vorta, which is why I'm sorry that this is a stupid question.

I would like to ask for an explanation of what practical difference between these two functions: 

borg create --read-special repo::hostname-disk $DISK
https://borgbackup.readthedocs.io/en/stable/deployment/image-backup.html

or

dd if=/dev/sdx bs=10M | borg create /path/to/repo::my-sdx -
https://borgbackup.readthedocs.io/en/stable/usage/create.html

Here a description of my use: https://github.com/borgbase/vorta/issues/1189

Best Regards!

**Comment by ThomasWaldmann** [comment]
Both lead to same result. The first one is maybe a bit more efficient because you have 1 process less and borg directly reads the device file.

You could just try them both and check if there is a speed or other difference.

That the docs mention both is a good finding, depending on your finding we could fix the docs so that only the better method is mentioned at both places (or we could use a link maybe to reduce duplication in the docs).

**Comment by git70** [comment]
Thanks for the clarification!
I am glad that on the occasion unconsciously and unintentioned I helped to discover a small change in documentation;)

**Comment by ThomasWaldmann** [comment]
I the docs shall be adjusted we need to keep this open.

**Comment by ThomasWaldmann** [comment]
OK, let's close this.
