### ISSUE TITLE
implement borg benchmark cpu

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6233]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

# Describe the problem you're observing

https://borgbackup.readthedocs.io/en/master/usage/init.html says that `repokey-blake2` my be faster than `repokey` on some clients, but slower on others.

Instead of trying to give users hints on which mode might be faster we should show users how to compare the two modes on **their** hardware. Trusting advice given in the docs instead of doing your own experiments is a cargo cult (and we should discourage that!).

It looks like we already have [`borg benchmark crud`](https://borgbackup.readthedocs.io/en/master/usage/benchmark.html) that could be used for this purpose - someone just needs to figure out how and document that.

**Comment by ThomasWaldmann** [comment]
Rather than using a "full stack" benchmark like the "crud" one (which depends on lots of stuff), we could also add a more specific one that shows hashing / MACing / encryption speeds.

Both results can be useful, depending on what you want to know. But the effects of slow / not slow sha256 will be much more visible in the more specific benchmark.

**Comment by BloodBlight** [comment]
Man, if there was a "benchmark all" feature that generated report for all function at all levels would be amazing!

**Comment by ThomasWaldmann** [comment]
While we add some scope creep: msgpack and chunker speeds might be interesting also.

**Comment by ThomasWaldmann** [comment]
https://paste.thinkmo.de/QYYdiPgt#borg-benchmark-cpu.txt < first results (macOS 12, M1)
