### ISSUE TITLE
include backup start time / duration in borg info

### ISSUE THREAD

**Issue by fsironman** [borgbackup/borg#627]
If you use the -s parameter on borg create you get an info when the backup started and how long it took.

It would be useful to also include it for display with borg info.

**Comment by ThomasWaldmann** [comment]
`borg info` is showing infos stored in the archive (at any time later).

`borg create --stats` might show some additional infos available at the time it runs, but that are maybe **not** stored in the archive.

Have to check...

**Comment by ThomasWaldmann** [comment]
This would need changing at least the archive metadata dict (see Archive.save) and maybe increasing the version number for that structure.

The archive metadata item "timestamp" (also duplicated in manifest archive list) currently has the **ending** time of the backup. Maybe it would make more sense to put the backup **starting** time there (which is about the same as the snapshot time if one creates a snapshot before invoking borg create). We could add a duration field to the metadata. As this stuff is a dict, we maybe do not need to change the version number if we just add stuff. Changing the meaning of one field is more critical, but maybe not really because these timestamps are only used by humans anyway!?

BTW, one does not need this if the archive name includes the current (backup start) time.
As the archive metadata dict contains the timestamp of the backup end, you can see how long it took.
Also, if you have log files of your backups, you can also see it there.
