### ISSUE TITLE
FAQ: why borg (esp. 1st backup) is slower than rsync

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6305]
See my post in https://github.com/borgbackup/borg/discussions/6304 .

With a little editing, this could be put into the borg docs, FAQ section.

**Comment by m3nu** [comment]
Just came back to refer to this great answer the second time. There is already a [similar question](https://docs.borgbase.com/faq/#why-is-my-backup-process-so-slow) in BorgBase's FAQ. Nice to have an official answer with more depth.

So what I'd like to do is distill your response in #6304 into a Borg FAQ  and then just link to it instead of repeating it.

Our current FAQ also has a few tips on how to speed backups up (flags, acl, xattr). Would those be worth adding to the same FAQ? Are there others worth mentioning? (some flags in those docs still need updating to 1.2)

**Comment by ThomasWaldmann** [comment]
Yeah, checking the FAQ for similar stuff and updating / extending it would be very good.

**Comment by m3nu** [comment]
Added first draft for the updated FAQ on performance.
