### ISSUE TITLE
Safely synchronizing repo to another location [missing feature]

### ISSUE THREAD

**Issue by varqox** [borgbackup/borg#6344]
I read https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location and have a couple of questions because such repo synchronization is the only thing for me that the  Borg is missing.

Suppose I have some files to back up. I want to back them up to two locations:
- (local) on the same machine where the files are
- on an external drive
Doing the first one can be easily automated to occur daily. I connect the external drive to the computer more or less once a month. What I want is that every time I synchronize backup on the external drive with the local backup, every daily backup is available on the external drive.
From reading the FAQ, there is an option to just copy the local repository to the external drive, but this approach has a drawback: if the local repo becomes corrupted, all my previous backups on the external drive also become corrupted i.e. I lose all backups and it sucks.
Another option to just run borg create when I connect the external drive also sucks because I only get ~monthly backups of my data.
The only sensible option I see is to run borg create of the local backup -- essentially back up the local backup. This seems to work, but creates an unnecessary level of indirection. This would get worse if I would want to synchronize the repo on the external drive with another repo -- I would back up the backup on the external drive, so I would get 2 levels of indirection i.e. backup of backup of backup of my data.

Maybe I don't see a different solution for this, I would be glad if someone showed me a better solution.

For me, it is sad that borg has such a limitation i.e. cannot synchronize more than one backup from one repo to another. Such a feature is important in cases where the backup location is not always available but synchronization of the backups occurs rarely but regularly.

Alternatives such as Duplicacy and Bup provide this functionality but have their own issues (license and speed, respectively).

**Comment by ThomasWaldmann** [comment]
Well, the easiest and best solution to this issue is to connect your external HDD(s) way more frequently and directly backup to them (== have independent repositories on them). A good idea is to have multiple external HDDs and rotate them regularly (so that never the same one is connected for a longer time and you always have some disconnected HDDs with enough and also recent enough backups). When doing it like that, you  maybe don't really need your internal backup.

Copying an archive from one repo to another is not as easy as it sounds:
- each repo has different borg key material (different encryption and signing keys, different chunker secret)
- this requires that all copied data gets authenticated, decrypted, decompressed, re-chunked, re-IDed, recompressed, encrypted, authenticated.

We already have some commands which do a similar job:
- `borg recreate` (but only within same repo)
- `borg export-tar/import-tar` (which are still lossy, but could be extended)

Also, i guess we already have some tickets about this on this issue tracker, maybe you can find them and link to them from here.

**Comment by ThomasWaldmann** [comment]
see updated #5830.
