### ISSUE TITLE
compress.pyx compiler warning

### ISSUE THREAD

**Issue by braewoods** [borgbackup/borg#6365]
I found this compiler warning from the generated code:
```
src/borg/compress.c: In function ‘__pyx_pf_4borg_8compress_4ZSTD_2_decide’:
src/borg/compress.c:6017:31: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
 6017 |   __pyx_t_2 = ((__pyx_v_osize < __pyx_v_isize) != 0);
      |                               ^
```
I was reviewing the source code and I noted that the size integers in the ZSTD section are all over the place, differing not just in signedness but also size. It appears there may be more going on here than just a signedness mismatch. Do you have any preferences for how this is resolved?

**Comment by braewoods** [comment]
I mean, this might become an issue if the code ever handles more than 2-4 GB of data which it likely will at some point.

**Comment by ThomasWaldmann** [comment]
As borg is chunking the data, the chunks (pieces) we need to compress are relatively small.
By default, we target ~2MiB chunk size and the hard limit for a chunk stored into the repo is about 20MiB, feeding bigger pieces in there will lead to an assertion error there.

Besides that, there's another limit on the max segment file size of 4GiB, because we store 32bit offsets for that.

Thus, for the chunks we are well below even the signed 32 bit int limits.

**Comment by braewoods** [comment]
Ok, then a simple fix to silence the warning should suffice. I'll get to work on it soon. Thanks.
