### ISSUE TITLE
Opt-out of "file changed" warnings specifically

### ISSUE THREAD

**Issue by grawity** [borgbackup/borg#6379]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION I SUPPOSE

#### Your borg version (borg -V).

borg 1.2.0

#### Operating system (distribution) and version.

Arch Linux

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg create --exclude-caches --one-file-system --exclude /var/tmp --exclude=/n --exclude=/net --exclude=/var/cache/pacman/pkg ssh://borg@[...]/Backup/Servers/star::star.20220226`

## Describe the problem you're observing.

Borg 1.2.0 in issue #1750 added a "file changed" warning, which results borg to return status 1 ("warnings occured"):

> /var/log/syslog: file changed while we backed it up

This is good to have by default, but I don't particularly care about it in my case -- during nightly backups it's going to happen a lot and it's always going to be something like /var/log/syslog -- and would like to ignore it. But there's no option nor environment variable to suppress just this specific warning.

But just as the manual cautions me in the "Logging" section, if I change my backup script to ignore borg's exit status 1 and only fail on exit status 2 ("errors occured"), then I will miss *more important* warnings, such as this one that I had a few months earlier informing me of sudden filesystem corruption:

> /var/lib/[...]org/[...].list: stat: [Errno 117] Structure needs cleaning: '/var/lib/[...]org'

(I think "failed to stat() for other reasons than a disappeared file" should definitely be reported as an error...)

So I'm looking for a way to allow suppressing specifically just the "file changed during backup" messages (i.e. I'd like another of those `BORG_[...]_IS_OK` environment variables to be added), or otherwise detecting when borg has logged other types of messages.

Should I just redirect borg's output to a file, then `grep -v` the unwanted messages away?

**Comment by grawity** [comment]
> Should I just redirect borg's output to a file, then `grep -v` the unwanted messages away?

I decided I'll just do this for now... (I'll also think about calling `fsfreeze` before the backup.)

**Comment by taladar** [comment]
I think what might make more sense than a global setting would be to have a new include/exclude style option which matches the files where we do not care about this warning, e.g. log files or files where we know changes are probably not going to be an issue for the integrity of the backup.

**Comment by sophie-h** [comment]
A more general solution might be to add [`msgid`](https://borgbackup.readthedocs.io/en/stable/internals/frontends.html#msgid)s to the messages that should be filtered and add a general option to filter message ids. (This one is orthogonal to @taladar s suggestion, though.)

**Comment by taladar** [comment]
Looking at the list of messages it seems most of them are hard errors where simply ignoring the error would still have to lead to an aborted run. Ignoring fatal messages doesn't seem very useful, that seems to be mostly something you might want to do with warning or lower level messages.

**Comment by sophie-h** [comment]
> seems most of them are hard errors

True, with the current set of msgids this would barely make sense.

**Comment by basti79** [comment]
Hi, I would also like to have some kind of flag for ignoring just these (file changed while we backed it up) warnings, for the same reason @grawity stated in the initial post. I was quite lucky with the previous behavior of just ignoring this case and it would be great to get this back by some kind of command line option or environment variables.

**Comment by mitch-geht-ab** [comment]
Same here. I use borg with rear and every "file changed" warning lead to a rc 1 which makes rear think that the backup job had aborted.

**Comment by ThomasWaldmann** [comment]
@mitch-geht-ab this sound like a bug in rear. a warning is a warning and not an error.

**Comment by taladar** [comment]
@ThomasWaldmann 

An exit code of 1 is an error.

**Comment by sebastianopilla** [comment]
@ThomasWaldmann That is indeed the problem, a file changing while being backed up by borg results in borg exiting with a return code of 1. Any script driving borg is then going to report this as an error, even if it's not one.

If borg could exit with a different return code for files changing while being backed up, scripts could be adapted accordingly.

**Comment by taladar** [comment]
A file changing and being backed up in an inconsistent state should be an error too though, at least for certain files (e.g. database files). For other types (e.g. appending to a log file) it is probably fine.

**Comment by aclindsa** [comment]
> A file changing and being backed up in an inconsistent state should be an error too though, at least for certain files (e.g. database files). For other types (e.g. appending to a log file) it is probably fine.

The fact that it can go either way is why I think it makes sense for this behavior to be configurable - for users to be able to determine for themselves whether or not a file being changed while being backed up results in a nonzero exit code.

**Comment by taladar** [comment]
I really don't think that is enough. It should be configurable for which files it does not matter if they change (e.g. log files) and  for which files it does, simply ignoring file changes during backup will just result in backups that don't allow you to restore anything useful.

**Comment by aclindsa** [comment]
> I really don't think that is enough. It should be configurable for which files it does not matter if they change (e.g. log files) and for which files it does, simply ignoring file changes during backup will just result in backups that don't allow you to restore anything useful.

I agree this would be a more robust solution than a global enable/disable.

**Comment by ThomasWaldmann** [comment]
the borg docs define rc == 1 as warning and rc == 2 as error. scripts and tools which invoke borg have to work like that.

and warning means that someone has to look at it, how severe it is, borg can not know that in many cases.

**Comment by grawity** [comment]
> the borg docs define rc == 1 as warning and rc == 2 as error. scripts and tools which invoke borg have to work like that.
> 
> and warning means that someone has to look at it, how severe it is, borg can not know that in many cases.

Yeah, but this thread is about teaching borg how severe the issue is.

Most other warnings that occur at rc==1 level are either rare (file disappeared, permission error) or actually kinda critical (I/O error that should be looked at ASAP), whereas this one is a daily occurrence.

My point is, if I have my backup jobs alert me for rc==1, then I will get emails about "file changed" every night, and after a while I will end up just deleting those and eventually overlooking the serious warnings. But if I _don't_ have my backup jobs alert me for rc==1, then I will definitely miss the serious warnings.

So if borg doesn't know how severe the issue is, why shouldn't I be able to tell it that?

**Comment by maethor** [comment]
Hi,

I am the maintainer of the borg handler in [backupninja](https://0xacab.org/liberate/backupninja). Backupninja is configured to send an email only if there is something useful to report. So no email when everything is OK.

> the borg docs define rc == 1 as warning and rc == 2 as error. scripts and tools which invoke borg have to work like that.
> 
> and warning means that someone has to look at it, how severe it is, borg can not know that in many cases.

I am using borg daily on 500 servers. Every day, changes happens in some log file during borg backup, which makes email notifications completely useless because nobody will be able to follow them.

I can `grep -v` to filter out the unwanted lines (`No such file or directory` and `file changed while we backed it up`), but then, what should I do with the rest of the output? How will I know if there is another important warning to report? Borg may have been returning 1 for other reason.

That's why it would be very useful to allow the user to tell borg to ignore some warnings (`file changed while we backed it up`, but also `No such file or directory` and maybe the warning at first backup).

I see another way, which could be easier to implement in borg. Could you prepend the output with the type of log, INFO, WARNING, ERROR (at least for non-INFO lines)…? Then, in backupninja (and other scripts), we would be able to filter out unwanted warning lines, and still know if we have something to report.


Thank you for all the work, borg is awesome.

**Comment by ThomasWaldmann** [comment]
borg's logging format is configurable, see the docs. So you can have the log level and other stuff.

i don't see a good solution for the fundamental problem yet.

borg just can't know what's a problematic file change and what not. nor can it know whether "no such file..." is problematic. that's why there is rc == 1 meaning that someone/something else has to decide that.

the best solution is of course when your fs is stable, so nothing changes (snapshotted or inactive fs).

a workaround is to exclude problematic, but unimportant files.

completely switching off a warning of a specific type would be dangerous, because that would silence also such issues in important files.

**Comment by maethor** [comment]
About "no such file..." errors, I believe that's not up to the backup tool to notify missing files. If the file was important, then something is broken and you should see it by any other mean, tests, monitoring… But, ok, if you make a typo… maybe borg should warn you that `/homes` does not exit… Maybe.

About "file changed while we backed it up", I agree this is debatable.
- I believe the users should know that they must not depend on borg to backup `/var/lib/mysql`. And if they do, they may end up with corrupted backup even if the file has not changed during backup. The job of borg is not to teach that to the users.
- But with log files or highly active file servers, this is just so annoying. Excluding problematic files is absolutely not a solution. Even if the file has changed during backup, the file has still been backup. I don't care that it has been modified. That's fine, it will be backed-up again tomorrow.

**Comment by mphilipps** [comment]
I would prefer an exclude list for files/directories that I want included in the backup, but that may change during the backup run without the need to trigger a warning.

**Comment by jdchristensen** [comment]
I think the best solution would be to make the "file changed" warnings happen less frequently.

- Can we get borg to read ahead into a file, so that in more cases it will finish reading a file before any changes happen?
- Does borg check whether the file has changed as soon as it hits EOF, or does it only do that after further processing (compression, dedup, writing to repo) has happened?  The former would be much better.
- Can anything else about the speed of reading be improved?
- Add retry support, so when a file has changed, it will retry N times.  If one attempt succeeds, then a message is logged, but no warning is raised.

The above overlaps with what is in #6457, but with more detail.

**Comment by maethor** [comment]
> Even if the file has changed during backup, the file has still been backup. I don't care that it has been modified…

Hm. Just to be clear, what is the meaning and implication of "File change while we backed it up" (Status C)? Does it mean borg could have backed up half of the old file and half of the new file?

**Comment by ThomasWaldmann** [comment]
@jdchristensen in same order:
- difficult, all data goes through chunker's buffer management (buzhash chunker is Cython/C code). it does some read-ahead already, but only as big as its buffer size (few MBs, IIRC). otoh, we do not want to load huge amounts of file data into memory anyway.
- as processing is per chunk, is it after EOF **and** after processing content data.
- the `fixed` size chunker chunks faster, but the non-chunking parts of processing are the same, likely not a big difference in practice.
- retrying is an option, but would not always help. if a retry is successful, i do not think there should be any message.

**Comment by ThomasWaldmann** [comment]
@maethor borg 1.2:
- opens a file to get a fd (file descriptor, open file handle)
- does a fstat on that fd to get stats like ctime, mtime, etc.
- then it reads blocks from that file. at some point, it reaches end of the file.
- does another fstat on that fd to get the stats again.
- compares stats to check whether the file has changed while we read it.

different stats can mean that the file data we read are not consistent. borg does not know HOW the file was changed, guess if it was changed in a strict "append only" way, it's no problem at all. in other cases, the backup can be inconsistent (having file contents that never existed like that on disk).

**Comment by jdchristensen** [comment]
@ThomasWaldmann 
- A readahead of 8MB would probably be enough to avoid the problem for many frequently changing log files.  Even 32MB would be a minor price to pay.  Couldn't a python function feed the data to the chunker?  (This could also help with future plans to parallelize some of the code.)
- Can it be changed to check the stat as soon as EOF is reached?  This seems like it would help avoid the problem.  I'm always surprised by how often borg says that a file is changing, when it should only take a few ms to read the file, and the file doesn't change *that* often.
- No further comment.
- Even if retrying helps only 90% of the time, it would really cut down on the logs one has to read.

**Comment by rspier** [comment]
Have we given up on the `--dont-warn-on-changed-or-deleted-files-even-though-this-might-lead-to-inconsistent-backups` flag solution?

**Comment by ThomasWaldmann** [comment]
@jdchristensen 
- no, because the default buzhash chunker already uses a 8MiB (2^23B) buffer now.
- needs checking in the code, but as soon as a file has multiple chunks, it would not make a big difference.
- N/A
- yes, but i guess we first need a failure rollback - because after we started processing a file, we have put chunks into the repo. if we then do not write the item to the archive, we potentially have orphaned chunks.

that failure / giving up rollback is also needed for e.g. IO error in the middle of a file, we have a ticket about that IIRC.

for the retry mode, it would make sense to:
- not decref / delete chunks while retrying (because propability for same chunks is rather high and also it works faster in the 2nd+ retry, with better chances to not have yet another change in the file while processing it)
- after N retries, give up and decref / delete chunks as needed to not create orphans.

**Comment by jdchristensen** [comment]
@ThomasWaldmann It's really the combination of the first two items that I think would help, and if the chunker already reads ahead 8MB, then one could consider the first item done (except that one might ask for a slightly larger buffer).  But the first item is only a benefit if the second item is done, namely if you check (or at least save) the stat info right when you reach EOF.

I agree that the fourth item is likely tricky to implement and get right, so I understand your hesitancy.

**Comment by maethor** [comment]
Thanks for you answer @ThomasWaldmann 

Now I agree that disabling the warning globally would be a bad idea, and borg don't need to give that option.

But I am also starting to realize that this change makes borg 1.2 kind of unusable for us, and more generally to backup `/` on servers. Even after ignoring warnings on log files, in 3 days I received 200 emails… prometheus wals, fail2ban sqlite, atop files, rrd files, mailboxes, user uploads, etc. There is a lot of active files on a server.

Do you confirm that Borg 1.1 does not have this problem?
And Borg 2 will carry the same behavior than 1.2?

**Comment by ThomasWaldmann** [comment]
It's not like the problem would not be there if you used borg 1.1.x, just it would not check and therefore would not warn you about this issue. So you might find out at restore time that some files are not internally consistent.

So guess it boils down to: "are these files important?"
- y: you need to get a consistent state of them (e.g. fs snapshot)
- n: do not back them up

borg2 / master branch currently behaves like 1.2.x.

**Comment by ThomasWaldmann** [comment]
BTW, besides the consistency within a specific file there is also the potential consistency issue between different files (that somehow belong together, like db files).

Even if borg tried hard to get in-file consistency (by doing retries until there is no change while it backed up the file), it could never know about inter-file consistency requirements and thus it could not achieve anything in that regard.

Thus, I guess we don't get rid of this fundamental problem from within borg. Users need to use snapshots.

BTW, tar does a quite similar thing as borg: it warns if a file changed during backup.

**Comment by maethor** [comment]
I know about consistency issues between multiple files. I known that I need to backup mysql with mysqldump and not copying /var/lib/mysql. I will never count on borg to backup complex databases (mongo, postgres, mysql, couch, elastic, etc.). They obviously need to be dumped with proper tools.

~~But for SQLite for instance, copying the sqlite file is a completely fine way to backing it up, because to my understanding `cp` ensures that the copy is consistent, even if the database is active during backup. I never saw any consistency problem in a borg backup, so I was believing that borg was working like cp.~~

Ok… so it seems there is the same problem with `cp`… I was sure that `cp` was ensuring consistency, but it's not according to https://unix.stackexchange.com/questions/6924/what-happens-if-a-file-is-modified-while-youre-copying-it It seems we never stop to learn even basic stuff…

So I guess it really comes back to #6457 and some of the propositions in this thread to reduce the volume of warnings. Most of the time files only changes in an ""append only" way.

**Comment by aclindsa** [comment]
@ThomasWaldmann I am struggling with what I feel may be some inconsistency in our discussion of _backup consistency_ here. I am making some assumptions below about your goals/motivations as I try to sort out that inconsistency - please correct me if/when I get something wrong; my goal is solely to understand and resolve this issue, not to criticize.

I understand (again, please correct me if I'm wrong) your opinion is that it should be an error (both with verbose output and a nonzero exit code) when borg detects a file has changed during the process of backing it up. And I believe you prefer not to add an option disabling or softening this warning (i.e. allowing borg to still return rc=0) because it could result in inconsistent backups and you want to protect the user against being unaware of this potential inconsistency. Additionally, we recognize this check is insufficient to ensure backup consistency (individual file's contents, even if internally consistent, may not be consistent with each other).

To summarize: **Borg desires to protect the user against inconsistency with these checks/warnings, but ultimately cannot. It _must_ remain the user's responsibility to ensure the filesystem is in a known-good/stable state if they want to ensure consistency.**

Also, a comment about human behavior: I have frequently found that people will find a way to do what they want regardless of your best intentions as the maintainer of a piece of software. In this case, I fear that by not allowing for disabling this one warning, many people will take the path of least resistance: ignoring borg exit codes entirely. Then they will miss _all_ warnings/errors. Obviously it would be preferable for them to solve the problem in another way, but sometimes that is difficult, or it is OK with them if the changing files are sometimes inconsistent (i.e. log files).

**Comment by aclindsa** [comment]
> BTW, tar does a quite similar thing as borg: it warns if a file changed during backup.

In my reading of the `tar` man pages, I see the 'file-changed' warning, but was unable to tell if enabling this warning caused tar to return a nonzero exit code. Do you know if it does?

**Comment by ThomasWaldmann** [comment]
My opinion is that an inconsistent file backup should trigger a warning (rc 1).
By borg's definition of RCs, warning is between 0 OK and 2 ERROR and needs checking.

This is to inform the user about (not protect them from) potential issues / data loss. If they choose to ignore the warnings, it is at least **expected** data loss (but not borg's fault then).

And yes, this check is not sufficient for inter-file consistency (but the latter check can not be done and not be expected from a file backup tool, while the in-file consistency check can be done easily).

If see how this can be annoying, but guess this is just the uncomfortable truth then.

BTW, there's another ticket about more fine grained return codes, but guess dealing with warnings via rc (there can be many different warnings) is even harder than with errors (usually there is 1 error and that leads to a fatal exit).

No, I don't know the tar rc for that case.

**Comment by magma1447** [comment]
I just upgraded from borg 1.0 to 1.1 and started seeing this issue. I am well aware that it's a good thing that it tells about the inconsistencies, which in some cases of mine actually is an issue. Cases that I had missed.

But I find it quite ironic that two of my servers has a 50% fail rate due to backing up root, where borg stores some data.

    /root/.config/borg/security/73b11...3debf/nonce: file changed while we backed it up

The file is 16 bytes.

Not sure why it's happening on just those servers though, I don't find them special in any way.

**Comment by ThomasWaldmann** [comment]
Not helping your right now, but the nonce problem will go away with borg 2, which does not need to long-term manage the aes counter any more due to usage of session keys.

**Comment by GermanCoding** [comment]
This is also a major pain point for me with borg 1.2. I have alerts that tell me if borg exits with a non-zero code, which previously only happened when something problematic happened (could not get a lock file, connection crashed, files suddenly went away). Now it's a daily occurence since there's always some file (borg's own nonce, some memory mapped files, DB-style files that periodically get rewritten with same content) that borg alerts me about. This has made the warning state completly useless to me, because I don't want to get alerted for something that I can't really influence: I cannot make this behaviour stop, that's just the way some files behave on my rootfs.

I could ignore some of these files, but many of these are still files I want backed up anyway. Even if they're not in a 100% consistent state, they are still useful to me as there's a high chance they are still restoreable (due to append-only behaviour, file content not actually being different etc).

I would probably have to migrate the root filesystems from ext4 to btrfs, just to get snapshot support, and then tell borg to backup the snapshots. That's a lot of work and risk for a warning that is only noise in my case. Yes, there's a chance that a file wasn't correctly backed up but there's also a very real chance that everything is fine. So borg needs some more granular handling about this: More exit codes, more fine-grained logging switches, whatever - just a way to tune this.

**Comment by ThomasWaldmann** [comment]
Can we close this in favour of #7346?

**Comment by ThomasWaldmann** [comment]
Superseded by #7346.
