### ISSUE TITLE
Slow speed through SMB

### ISSUE THREAD

**Issue by Carpe-Diem-Postero** [borgbackup/borg#6385]
I'm testing Borg performance for LAN backups through SMB.

I've been using two devices, both with 1Gbe NIC, one (Ryzen 7 3700x) is using a repository located on a mounted directory in the second device (using SMB) and it's transferring 500GB (in 15-2GB files), but transfer speed never goes over 50MB/s. It's not a network bottleneck, as Rsync can easily saturate the 1Gbe. Borg version is 1.1.17.

Odly enough, if I use borg crud aa benchmark, I get theorical speeds of more than double the ones Im getting.

Of couse, local backup is much faster than that.

Any insight about how can I achieve faster speed?

**Comment by ThomasWaldmann** [comment]
Is it only slow for first or also for 2nd+ backup?

**Comment by braewoods** [comment]
Could the SMB protocol itself be a bottleneck? rsync uses a different protocol and all.

**Comment by Carpe-Diem-Postero** [comment]
> Could the SMB protocol itself be a bottleneck? rsync uses a different protocol and all.

But why should SMB bottleneck backups? 50MB/s is really low. I also tried with 10GBe NICs and the transfer speed is the same (around 50MB/s)

**Comment by braewoods** [comment]
I've seen file transfer protocols become a bottleneck, especially when encryption is involved. The ones used with SSH come to mind but I don't usually use SMB so it was just a thought.

**Comment by ThomasWaldmann** [comment]
In general, you can't compare borg to rsync, borg does way more than rsync (and thus is usually slower for 1st backup) - there is a new FAQ entry pending for that. Also, borg is not internally pipelined or multithreaded, so one can't expect maximum speed (like a saturated fast LAN connection) here.

Network latencies might add their part and also, when using borg client/server, the ssh tunnel also costs some CPU and maybe throughput.

While that is maybe slower for first backup than expected, it is usually a one-time issue, because for the daily backups after that, there is not so much data changing and borg can process unchanged files extremely fast. Big files with small changes can also get processed rather fast as only some changed chunks need to be processed.

Also note that you can run multiple borg in parallel and backup to multiple repos at the same time.

**Comment by santiagobiali** [comment]
Been there, SMB speeds and IOps are horrible compared to direct storage calls, but it's a SMB thing, not borg's.
Try installing borg in the server with the 500GB files and use ssh as transfer path (ssh://myborgserver//mystorageRepo).

Take a look at both of your server's load average, this way you will use waaaay less resources (CPU basically).

**Comment by Carpe-Diem-Postero** [comment]
> Been there, SMB speeds and IOps are horrible compared to direct storage calls, but it's a SMB thing, not borg's.
> Try installing borg in the server with the 500GB files and use ssh as transfer path (ssh://myborgserver//mystorageRepo).
> 
> Take a look at both of your server's load average, this way you will use waaaay less resources (CPU basically).

I'll give SSH a try, although CPU is not bottleneck with SMB (max usage 30%, not a single core is used beyond 50%). Even with single threading, my CPU should have more than enough punch for this work.

I assume you are right about IOPS and SMB then.

**Comment by ThomasWaldmann** [comment]
Guess we can close this?
