### ISSUE TITLE
Prune not freeing up disk space

### ISSUE THREAD

**Issue by NotCharmingAtAll** [borgbackup/borg#6585]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.
Proxmox 7.1-12 Backing up to BorgBackup running on Debian 11 (inside another Proxmox Server)via SSH

#### Your borg version (borg -V).
1.1.16

#### Operating system (distribution) and version.
Debian 11

#### How much data is handled by borg?
100GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
export BORG_REPO=matthias@192.168.178.225:/home/matthias/backup
export BORG_PASSPHRASE='XXXXX'
 
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup unterbrochen >&2; exit 2' INT TERM
 
info "Start backup"
 
borg create                         \
    --stats                         \
    --compression lz4               \
    ::'{hostname}-{now}'            \
    /etc/pve                        \
    /etc/network/                   \
    /mnt/pve/ironwolf/dump/
 
backup_exit=$?
 
info "Loeschen von alten Backups"

borg prune                          \
    --prefix '{hostname}-'          \
    --keep-daily    1               \
    --keep-weekly   1               \
    --keep-monthly  1
 
prune_exit=$?
 
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
 
if [ ${global_exit} -eq 0 ]; then
    info "Backup and Prune finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup and/or Prune finished with warnings"
else
    info "Backup and/or Prune finished with errors"
fi
 
exit ${global_exit
```

## Describe the problem you're observing.
Borg is backing up Proxmox VM backup files to a Debian 11 running in another Proxmox server.
Prune does not free ob disk space and fills up space in Debian 11 HDD continuously until system halts.
I thought Prune will take care of space management since 1.1.16 does not provide the Compact command.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes

**Comment by ThomasWaldmann** [comment]
Correct, for 1.1.16 you do not need the `borg compact` command (you do not have it anyway).

Check if the repo is in `append-ony` mode:
- `repo_dir/config`
- `.ssh/authorized_keys`

**Comment by NotCharmingAtAll** [comment]
Hi Thomas,
thank you for your reply but since I am new to to Borg, I would like to ask you to elaborate a little bit more on this.
Thanks.

**Comment by ThomasWaldmann** [comment]
You can search the docs for append-only, it's explained there in detail.

This is not the default, so whoever set up this would know whether it is in append-only mode - but this is the easiest explanation of prune not reducing space usage.

This can be enforced by either the "config" file in the repository directory or by sshd configuration IF you use borg via ssh.

**Comment by ThomasWaldmann** [comment]
@NotCharmingAtAll were you able to solve the issue?

**Comment by NotCharmingAtAll** [comment]
Hi Thomas,
thanks for asking. After receiving my new raid enclosure I have set up everything from scratch.
It is running fine so far and I should see the first prune activity tomorrow. (retaining a full week)
Will let you know about the behavior.

**Comment by ThomasWaldmann** [comment]
OK, so I'll close this for now. If somebody finds this problem again and can provide more information, please reopen.

**Comment by ThomasWaldmann** [comment]
@nowwireless-andy borg < 1.1.11 (except patched versions, like 1.1.9 in Debian) has severe bugs and must not be used any more (see the notes above the changelog).

The easiest explanation of what the graph shows is that the repo was switched to append-only mode in April, 
see there: https://github.com/borgbackup/borg/issues/6585#issuecomment-1097807107 .

After checking this and confirming it is **not** in append-only mode, check the logs about the `borg prune` output and maybe run the prune command interactively to see what happens.

**Comment by nowwireless-andy** [comment]
@ThomasWaldmann Thank you so much for the very quick reply!

I had already seen the comment above about append only mode and can confirm that `append_only = 0` is set in the config file of all my repos, and none of the authorized_keys lines have any variables set in them.

I've tried running `prune --debug ...` from one of my clients and it's taking a very long time (several hours). It identified four archives to prune. The first two happened quite quickly but the third and fourth (oldest ones) took around an hour each. It then printed a line about `Remote: check_free_space...`, which is still going without any further output. I'll leave it going for now.

I understand there's very likely to be bugs in old software and am very happy to upgrade. Do you suggest I upgrade server and clients to 1.2.1 and then run the procedure from the top of the changelog?

**Comment by ThomasWaldmann** [comment]
Well, considering there are unclear issues still, I'ld recommend first upgrading to a more recent 1.1.x release (these are very stable) and then run that for a while.

If it runs for a while and everything is behaving normally, you can still go to 1.2.1 (or whatever is the current release at that time).

If your distribution does not offer newer 1.1.x releases, you can also consider using the pyinstaller-made binary from our github releases page (check the README there).

**Comment by ThomasWaldmann** [comment]
If you did not prune for a while, some deletions / prunes (and especially the compact segments it runs automatically after the deletion) can take longer... - it might shuffle around quite a lot of data then.

**Comment by ThomasWaldmann** [comment]
If you ran an unpatched version < 1.1.11, you should follow the notes in the 1.1.11 section at the top of the changelog to ensure your repository index is ok.

**Comment by bwurst** [comment]
Having the same issue with borg-1.2.1 on a Hetzner storage box.

I issued a prune manually to clean more old archives and free space, which should have worked according to borg's output:
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:             -353.36 GB           -259.03 GB            -11.15 GB
All archives:              636.30 GB            465.66 GB             31.22 GB
```

But the storage box stays full. It contains no other data than borg's storage.
```
> df -h
Filesystem         Size    Used   Avail Capacity  Mounted on
u143466            100G     95G    4.9G    95%    /home
```
```
> cat config
[repository]
version = 1
segments_per_dir = 10000
max_segment_size = 5242880
append_only = 0
```

As borg's total storage should be 31.22 GB and really is 95 GB, this issue seems to be there for while.

Have you an idea how to debug further?

**Comment by bwurst** [comment]
Well, after sending this, I realized that we never did the upgrade to 1.2 in a clean way. So I'll study the upgrade docs and do that stuff first.

**Comment by noplanman** [comment]
Hi all, I'm facing this issue too that storage isn't being released.

I've followed the upgrade guide and all checks look ok. Repos aren't in append_only mode, so that shouldn't be the problem.

Is there some other way, apart from `borg info` to get the size the repo is actually taking up on the file system, as opposed to how much it _should_ be using?

**Comment by ThomasWaldmann** [comment]
Please be aware that `borg compact` (without `--cleanup-commits`) is part of **regular repo maintenance** (not just a one time upgrade thing).

One does **not** necessarily need to run it after each delete/prune command, but it needs to be run on a regular basis to free up disk space.

**Comment by noplanman** [comment]
Hi @ThomasWaldmann, yes, I'm aware of that, thanks.

I have a management server that does the compacting separately periodically. Unfortunately the space still isn't being freed and I don't know why.

I feel like I must be missing something but can't put my finger on it.
Is there a way of finding out why the storage isn't being freed?

According to the prune and compact outputs, the repo should be "clean", but the disk says otherwise :confused:

**Comment by ThomasWaldmann** [comment]
@noplanman do you use snapshots on the fs or the logical volume that keep referencing the previously used blocks?

**Comment by noplanman** [comment]
@ThomasWaldmann I wouldn't think so, but I'm using rsync.net, so can't imagine that their storage quota isn't "true" when it says how much is being used.

Shall I get in touch with them to ask if that could be the case?

**Comment by ThomasWaldmann** [comment]
I don't know internals of them, but if you have the cheaper "borg" plan, you usually do not get the snapshots feature, IIRC. You could try running a "df" via ssh. If nothing else helps, sure, ask them.

**Comment by noplanman** [comment]
Unfortunately their support was very unhelpful, so I'm stuck with this now :confused: 

`df`, `du`, their own `quota` command, as well as their support, all say the indicated storage is what is effectively being used.

Just to clarify, does `--cleanup-commits` have to be executed with the latest 1.1 binary, or should it work the same with 1.2?

At the moment, it sounds to me like the only solution is discard all historic backups and start fresh, but that's really a "last resort".

**Comment by ThomasWaldmann** [comment]
--cleanup-commits was new in borg 1.2 and needs to get run only once after upgrading.

One thing one needs to be aware of is that deleting some specific archive might not free a lot of space (due to deduplication and other archives still referencing the same data). So, basically if N archives reference mostly the same date, you need to delete all of them to really free a lot of space. As long as one reference is left, the space is not freed because the data is still needed.

Besides what I wrote above in this ticket, some more ideas:
- run prune in a way that it deletes only a few archives (and tweak params step by step until you end up with the desired prune settings - the idea is to have a lower amount of deletions per prune run). if you already finished with the pruning/deletion of archives (and they do not show up any more in borg list / borg prune --list --dry-run), you can skip this step.
- run compact --threshold=90 lower it step-by-step until 10 (the idea is to have a lower amount of segments to be compacted per compaction run).
- run check --repair if nothing else helps.

**Comment by noplanman** [comment]
Thanks for your detailed reply, I'll be doing this for all my repos and see if that has the desired effect. :crossed_fingers:

**Comment by noplanman** [comment]
Oh my, I've just realised I missed a repo that still had append_only set :see_no_evil: 

I've set the threshold on the compact command to 95 and it looks like it will take a while.

So sorry about this, no idea how this one slipped through...

**Comment by ThomasWaldmann** [comment]
Solved.
