### ISSUE TITLE
How to restore an entire block device.

### ISSUE THREAD

**Issue by steabert** [borgbackup/borg#671]
In #118 it was explained how to backup an entire block device.
I couldn't find anywhere in the documentation how to extract an archive that was created by using:
`dd if=/dev/xxx | borg create repo::mydisk -`
The extract command man page mentions that something is always extracted to the current directory.
I expected something akin to `borg extract repo::mydisk - | dd of=/dev/bla` being possible, but it seems it is not.
Is it possible to restore an entire block device?

**Comment by ThomasWaldmann** [comment]
Yes, seems like a raw device restore example is missing. You can still discover this in `borg extract --help`.

Should be something like `borg extract --stdout repo::archive stdin | dd of=/dev/sdxx`.
This assumes that the file stored in the archive is named "stdin".

Keeping this open as a documentation issue.

**Comment by steabert** [comment]
Oh yes, mea culpa, I totally missed that option. I read the bold text "Note: currently, extract always writes into the current working directory (".")" at the bottom of the extract documentation, and took that as an absolute.

**Comment by fr34k8** [comment]
@steabert did you test restoring from already made backup? 

#NOTLIKE 
`dd if=/dev/sdx bs=10M | borg create /path/to/repo::my-sdx -`

**Comment by devZer0** [comment]
@ThomasWaldmann , i found this feature/information extremely useful. thanks.

since borg extract to stdout simply dumps the whole blockdevice contents back to the target/blockdevice, i wondered how you can save unnecessary writes to that, e.g. if you do restore of harddisk image on regular interval like lab/workshop PCs. that would wear out ssd unnecessarily and performance is better if unnecessary writes getting skipped.

i found blocksync.py from https://github.com/theraser/blocksync or https://github.com/shodanshok/blocksync very useful for that, the advantage of using this is that only changed blocks getting written, which will drastically save ssd lifetime (it's working like rsync by comparing src and destination and only writes to destination if there is a difference)

don't know if it would be easily possible or make sense to have such functionality in borg extract, as this would avoid using borg mount for accessing the source file

I'm creating image like this:

dd if=/dev/sda bs=1024k | borg create --progress -v -C zstd --chunker-params=fixed,4194304 /mnt/repo1::sda_07_10_2022 -

and restore like this:

/root/blocksync.py /mnt/repo1/sda_07_10_2022/stdin localhost /dev/devicename

**Comment by jdchristensen** [comment]
@devZer0 I think it would be best to adapt blocksync.py to allow it to read from stdin.  It currently seeks in the input, so it doesn't work on stdin.  The adapted version wouldn't be able to check the lengths ahead of time, but that would be a reasonable compromise, I think.

**Comment by ThomasWaldmann** [comment]
This somehow goes into the direction of "update a locally already existing file" (we have a ticket for that, as this is currently not supported by `borg extract`).

If one wanted to use borg for that (and not just blocksync.py), one would first backup the block device to a borg repo and then restore to another machine. If borg would then support efficiently updating an already present file, one would have something similar to the blocksync functionality.

The chunker for such a use case would be the fixed chunker usually, the block hashes would be the chunk ids borg stores inside an archive anyway.

Even better would be if borg could know unused blocks on the blockdevice level (similar to a sparse file on the file level) and could optimize these, we also have a ticket for that.

**Comment by devZer0** [comment]
blocksync.py from shodanshock now has support for stdin:

https://github.com/shodanshok/blocksync/issues/2

and it works fine!

```
# borg extract --stdout /mnt/repo2::sda_07_10_2022_8 |blocksync.py - localhost /dev/sdc

Dry run     : False
Local       : True
Block size  : 128.0 KB
Skipped     : 0 blocks
Hash alg    : sha512
Crypto alg  : aes128-cbc
Compression : False
Read cache  : True
SRC command : /usr/local/bin/blocksync.py - localhost /dev/sdc
DST command : blocksync.py server /dev/sdc -a sha512 -b 131072 -k 0

Synching...
skipped: 0, same: 261761, diff: 383, 262144/0, 192.3 MB/s

Completed in 170 seconds

**Comment by devZer0** [comment]
btw, by using mbuffer for feeding borg output to blocksync.py i'm getting noticeable speed improvement

```
# borg extract --stdout /mnt/repo2::sda_07_10_2022_8 | blocksync.py - localhost /dev/sdc

Dry run     : False
Local       : True
Block size  : 128.0 KB
Skipped     : 0 blocks
Hash alg    : sha512
Crypto alg  : aes128-cbc
Compression : False
Read cache  : True
SRC command : /usr/local/bin/blocksync.py - localhost /dev/sdc
DST command : blocksync.py server /dev/sdc -a sha512 -b 131072 -k 0

Synching...
skipped: 0, same: 262144, diff: 0, 262144/0, 189.1 MB/s

Completed in 173 seconds




# borg extract --stdout /mnt/repo2::sda_07_10_2022_8 | mbuffer | blocksync.py - localhost /dev/sdc

Dry run     : False
Local       : True
Block size  : 128.0 KB
Skipped     : 0 blocks
Hash alg    : sha512
Crypto alg  : aes128-cbc
Compression : False
Read cache  : True
SRC command : /usr/local/bin/blocksync.py - localhost /dev/sdc
DST command : blocksync.py server /dev/sdc -a sha512 -b 131072 -k 0

Synching...
skipped: 0, same: 262144, diff: 0, 262144/0, 260.6 MB/s r   0% full


Completed in 125 seconds
summary: 32.0 GiByte in  2min 05.9sec - average of  260 MiB/s
