### ISSUE TITLE
interesting backup progress synchronisation effect

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6759]
I am just doing 2 backups:
- of the same data
- in parallel
- to 2 different remote repositories (via ssh:) on the same remote host on different hdds
- running 2x `borg create --list` in parallel
- in screen, so i can switch between the output of the 2 borg

Interesting:

After a while, the screen output looks exactly the same when switching between the 2 screens, meaning that both borg are processing the same files at (approx.) the same time.

**Comment by FabioPedretti** [comment]
It looks like borgs may behave like metronomes?
https://youtu.be/Aaxw4zbULMs
😆

**Comment by jdchristensen** [comment]
Here's my theory:  If the two backups are not in sync, the one that is ahead will be slower, since the one that is behind can make use of the filesystem data getting cached in RAM.  So they eventually get in sync.  An argument against this theory is that I seem to recall that borg advises the kernel to *not* cache read files in RAM.  Still, probably the metadata is cached, which might be enough to cause this?

**Comment by ThomasWaldmann** [comment]
@jdchristensen yes, borg uses "fadvise dontneed" to avoid using lots of memory for stuff it only reads once.
