### ISSUE TITLE
borg check causes corruption in hardlinked config file

### ISSUE THREAD

**Issue by jdchristensen** [borgbackup/borg#6768]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.2.0

#### Operating system (distribution) and version.

Tested on Ubuntu 20.04 and 21.10.

#### Hardware / network configuration, and filesystems used.

ext4

#### How much data is handled by borg?

Doesn't matter.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
mkdir /tmp/borgtest
cd /tmp/borgtest
borg init -e none test.repo
cp -al test.repo copy.repo
borg check -v test.repo
cat copy.repo/config  [binary data]
```

## Describe the problem you're observing.

After making a hardlink copy of a repo, running check on the original causes corruption of the config file in the copy.  It happens with archives in the repo too, but I omitted this to make the script as short as possible.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Reproducible using the steps above.

#### Include any warning/errors/backtraces from the system logs

None.

**Comment by ThomasWaldmann** [comment]
I can reproduce the issue with 1.2.1.

**Comment by ThomasWaldmann** [comment]
Maybe `save_config` should get a `secure_erase=False` argument.

`Repository.save_key` could then call it giving `secure_erase=True`.

That would avoid this collateral damage in all cases except when saving a repokey (e.g. when changing the passphrase).

**Comment by jdchristensen** [comment]
Oh, I see.  One option would be to not do the secure erase iff the config file has a link count > 1.

**Comment by ThomasWaldmann** [comment]
Yeah, I just had the same idea. :-)

**Comment by ThomasWaldmann** [comment]
@jdchristensen see #6769.

**Comment by ThomasWaldmann** [comment]
Besides using `cp -al`, there is also another failure scenario:

In Borg < 1.2.2, there is a narrow but real crash/restart scenario in which the repository `config` file can get corrupted. This was fixed in 1.2.2 by introducing `secure_erase(..., avoid_collateral_damage=True)`.

### What goes wrong in < 1.2.2
`Repository.save_config` follows this pattern:
1) If `config.old` exists, securely erase it.
2) Create a hard link from `config` to `config.old` (so the previous contents can be scrubbed later).
3) Write a new config to a temp file and atomically `os.replace` it over `config`.
4) Securely erase `config.old` (now the old inode).

In 1.2.0, the secure erase call did not have the safeguard to avoid scrubbing a file that still has multiple hard links. If a crash happens after step 2 but before step 3, then on the next Borg run step 1 will securely erase `config.old`. But at that moment, `config.old` and `config` are two names for the same inode. Overwriting the blocks through `config.old` also overwrites the live `config` content, corrupting it.

### Conditions required for corruption
- Filesystem supports hard links (most POSIX local filesystems do; some network FS might not).
- A crash or abrupt termination occurs between:
  - after `os.link(config, config.old)` succeeds, and
  - before the `os.replace(tmp, config)` happens (or succeeds).
- On the next run, Borg sees `config.old` and performs secure erase that actually overwrites the file contents (as in 1.2.0/1.2.1), not merely unlinking.

If any of these are not true, corruption does not occur:
- If the crash happens after the `os.replace`, the live `config` is a different inode; scrubbing `config.old` is safe.
- If the filesystem doesn’t support hard links (link creation fails), Borg logs a warning and doesn’t create `config.old`; thus there’s nothing to scrub.
- If there’s no crash (normal operation), the sequence is safe even in 1.2.0.

### How this was fixed
- The safeguard `avoid_collateral_damage=True` was added to `secure_erase` on 2022‑06‑13 (commit `afcebf32f7ed7436ce420684088276d33161bbf7`, subject: `secure_erase: avoid collateral damage, fixes #6768`).
- Releases including the fix: 1.2.2 and all later releases (e.g., 1.4.x).
- With this flag, if `config.old` still shares its inode with `config` (link count > 1), the code refuses to scrub and avoids overwriting shared blocks, preventing collateral damage to `config`.

### Symptoms if hit on 1.2.0/1.2.1
- `REPO/config` turns into zeros or seemingly random bytes (depending on the scrub pattern), or partial garbage.
- Subsequent Borg operations may fail to open the repository due to malformed config; if using repokey-in-repo mode, the embedded key in `config` may be lost.

### How to check the risky state (before running Borg after a crash)
- Inspect whether `config` and `config.old` point to the same inode:
  ```bash
  ls -li REPO/config REPO/config.old
  # Same inode number → dangerous to scrub in 1.2.0/1.2.1
  ```
- Or check link count of `config`:
  ```bash
  stat REPO/config
  # If st_nlink > 1 and REPO/config.old exists, they likely reference the same inode
  ```

### Mitigations and recommendations
- Best fix: upgrade to Borg ≥ 1.2.2 (or any newer series, e.g., 1.4.x). This fully addresses the issue.
- If you must stay on 1.2.0/1.2.1 temporarily and you suspect a crash occurred between steps 2 and 3:
  - Manually remove `REPO/config.old` before running another Borg command:
    ```bash
    rm -f REPO/config.old
    ```
    This prevents the next run from scrubbing through a hard link.
  - Optionally, make a backup copy of `REPO/config` first:
    ```bash
    cp -a REPO/config REPO/config.backup
    ```
- Prefer running Borg on filesystems with reliable POSIX semantics. But note the bug is independent of FS correctness; it’s a logic gap in 1.2.0/1.2.1 when a crash occurs in the small window.

### Recovery if already corrupted
- Restore `REPO/config` from a known-good backup or snapshot.
- If using keyfile mode (key stored outside the repo), you can often reconstruct a minimal `config` (repository `id`, format options).
- If using repokey mode (key embedded in `config`), corruption may make the repo inaccessible unless you have the key exported elsewhere (`borg key export`) or another copy of the config.

### Conclusion
- In Borg 1.2.0 and 1.2.1, there is a plausible corruption path for the repository `config` due to `secure_erase` not avoiding collateral damage when `config.old` is still hard-linked to `config` after a crash.
- The issue was fixed in 1.2.2 by adding `avoid_collateral_damage=True`. Upgrading eliminates this risk.

**Comment by ThomasWaldmann** [comment]
If upgrading is not possible / desired, applying the fix from #6769 would also fix the issue.

@LocutusOfBorg @FelixSchwarz The circumstances as described in previous post might be rare, but if they trigger and users use encryption in repokey mode (without a key backup), access to the data backed up in the repository will be lost.

**Comment by LocutusOfBorg** [comment]
Hello, are we just speaking about Ubuntu jammy?

<img width="1365" height="179" alt="Image" src="https://github.com/user-attachments/assets/869af63d-1403-4b0b-aa79-0c6fa0c5d421" />

<img width="1249" height="222" alt="Image" src="https://github.com/user-attachments/assets/988db20a-ffe1-48b3-a417-85a83455dc86" />

**Comment by LocutusOfBorg** [comment]
https://bugs.launchpad.net/ubuntu/+source/borgbackup/+bug/2125904

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg yes, yammy (and older, but guess these are out of support).

The new insight was that it not only affects hardlinked copies, but that borg can also produce the conditions by itself, when a crash occurs at an unfortunate time.

**Comment by LocutusOfBorg** [comment]
Older releases have 1.1 and 1.0, I was wondering if they were not affected?

**Comment by ThomasWaldmann** [comment]
That code is rather old, introduced back then:
```
commit 21178617381302abb30ee4afcef72039bdca166d
Author: Milkey Mouse <milkeymouse@meme.institute>
Date:   Wed Mar 8 22:38:37 2017 -0800
```

**Comment by ThomasWaldmann** [comment]
Releases containing problematic code 21178617381302abb30ee4afcef72039bdca166d : borg >= 1.1.0

1.1-maint backported fix commit: 53b6d14cb497945a315f92baf636a7502896c7ae (that was after the final 1.1.18 release)

**Comment by LocutusOfBorg** [comment]
So focal and bionic are affected...

**Comment by FelixSchwarz** [comment]
> [@FelixSchwarz](https://github.com/FelixSchwarz) The circumstances as described in previous post might be rare, but if they trigger and users use encryption in repokey mode (without a key backup), access to the data backed up in the repository will be lost.

Thank you for the heads up.

- Fedora EPEL 8 ships borgbackup 1.1.18 but I already added a lot of patches from the 1.1-maint branch and the backported fix is already present there.
- borgbackup 1.2.x is only used in EPEL 9 but that is already at 1.2.7 so I guess EPEL is fine here.
- All supported versions of Fedora ship borgbackup 1.4.1.

**Comment by LocutusOfBorg** [comment]
Ubuntu focal and bionic were rejected due to EOL.
