### ISSUE TITLE
I interrupted "borg delete" using Ctrl-C, then did successful "borg create", then all commands failed because of locking problems

### ISSUE THREAD

**Issue by safinaskar** [borgbackup/borg#6782]
Hi. Let me report my bad borg experience.

I use borg 1.1.9 on my local laptop (hereafter I will call this host LAPTOP). Remote server is rsync.net (hereafter RSYNC.NET), its borg version is 1.1.17. I set up systemd service, which do backups using `borg create --remote-path=borg1 ... ssh://zhXXXX@zhXXXX.rsync.net/...` every 5 hours. Starting from 2022-05-29 to this day I accumulated a lot of archives, size of storage occupied on server is nearly 1 TiB.

Yesterday (2022-06-20) I decided to delete some archives: I typed command on LAPTOP `borg delete --remote-path=borg1 ssh://zhXXXX@zhXXXX.rsync.net/... --glob-archives ...`. The command surprisingly took too long. I am sure that background `borg create` was not active at the moment (otherwise `borg delete` immediately would say that it cannot get a lock). (Why deleting archives is such long operation?). After waiting nearly hour I terminated the command using Ctrl-C. (Is this okay?)

Then I suspended LAPTOP. Next day the computer (LAPTOP) woke up. I decided to check the repo, so I logged into another host located at digitalocean (hereafter DIGITALOCEAN) and typed command `ssh zhXXXX@zhXXXX.rsync.net 'borg1 check ...'`. The command said that it failed to get lock, because (according to logs) systemd service running at LAPTOP successfully created another archive using `borg create` at the same time.

Then I typed command `ssh zhXXXX@zhXXXX.rsync.net 'borg1 check --lock-wait=3600 ...'` at DIGITALOCEAN. And the command failed (after one hour) with same error: cannot get lock. But this time it should not fail, because that systemd backuper already created backup!

Then I tried to run various other borg commands on this repo from DIGITALOCEAN and LAPTOP. All they failed with message "cannot get lock". But that systemd job was not running (I checked this several times).

So, I have a question: why I got this stale lock? Is it because I interrupted `borg delete` using Ctrl-C? But if this it true, why systemd job succeed today?

Yes, I know this is bad bug report, because bug reports should be reproducible. But this is more like experience report, not bug report. But I decided to share it anyway, I hope it will be useful.

## Is this a BUG / ISSUE report or a QUESTION?

Experience report

#### Your borg version (borg -V).

See above.

#### Operating system (distribution) and version.

LAPTOP: old debian stretch. RSYNC.NET: seems to be FreeBSD.

#### Hardware / network configuration, and filesystems used.

LAPTOP: ext4. RSYNC.NET: seems to be zfs

#### How much data is handled by borg?

See above

**Comment by ThomasWaldmann** [comment]
Well, you should not accumulate tons of archives over a long time, but regularly run prune to keep the amount of archives in bounds (it also helps with keeping space usage in bounds).

If you never deleted something and then you try to delete hundreds or thousands of archives at once, that is expected to take long (and depending on the stability of your systems / your network connection, it might be advisable to split the mass deletion to multiple borg invocations, e.g. by slowly adjusting prune parameters).

The delete by itself is medium expensive:
- starts transaction
- goes through all selected archives and appends `DEL <chunkid>` entries to the repo + decrements the reference counter of each referenced chunk
- commits
- now all selected archives are logically deleted, but the `PUT <chunkid> <chunkdata>` are still present in the old segment files. as they are superseded by `DEL <chunkid>`, they are kind of unused "holes" in the segment files but they still occupy disk space.

To really free disk space and compact away these holes, borg 1.1.x implicitly runs "compact_segments" at the end of each repo writing command and that can be very expensive if there is a lot of segment files to compact:
- go over all segment files with holes
- if the amount of holes is lower than X percent: not worth it, skip to next segment file.
- otherwise: read all entries in the segment file that are still used (not the holes) and write them to a new compact segment file, commit, then delete the old segment file.

If you deleted a lot of stuff, it is likely it needs to compact a lot of segment files, causing a lot of I/O on the repo server.

As you noted, there is no conflict, because borg locks the repo, so only one borg is working in the repo at the same time.

Usually it is ok to cancel a borg operation with Ctrl-C, but you might lose some or all progress it has made up to that time. Usually the next borg operation will then roll back all uncommitted changes to get back into a valid state.

Usually borg should not leave behind a locked repo, there are exception handlers that remove the lock even when borg exits abnormally. But, there are some circumstances when that might not be possible: the most common ones are power failures, hard crashes, kill -9 and similar stuff. Also, there could be yet unknown bugs, of course.

If you have a stale lock and you run borg again from the same machine, the new borg can usually determine if a lock is stale and will automatically remove it. But if you run borg from another machine, that machine can not know whether another machine's lock is stale or not.

You can use `borg break-lock REPO` to remove a lock after making sure no borg process is accessing that repo.
