### ISSUE TITLE
Exception ignored in: <function Repository.__del__ at 0x7f185dfa3eb0> 

### ISSUE THREAD

**Issue by techwanker** [borgbackup/borg#6789]
Bug

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
Linux atx2 5.15.0-39-generic #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.
local backup, DELL XPS17 64 GB RAM 16 Core *9 2 TB nvme
#### How much data is handled by borg?
1 TB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create --exclude-from ./borg.exclude --list /disk/borg::$HOSTNAME_$TIMESTAMP /

i upgraded my OS since my prior run and did an apt-get install borg and then borg complained about the msgpack.
I did a pip install msgpack
then when I ran borg
it complained again

**Using a pure-python msgpack! This will result in lower performance.**

Since it crashed I cannot acquire a lock on the repository.

#
[crash.txt](https://github.com/borgbackup/borg/files/8971170/crash.txt)

**Comment by ThomasWaldmann** [comment]
If you are sure no borg is accessing the repo, you can use `borg break-lock` to unlock it.

pure-python msgpack is usually an issue with compiling the C-based msgpack code.

Maybe try again with the current borg and msgpack version (1.0.4).

If you get a traceback, I need the full traceback.

**Comment by ThomasWaldmann** [comment]
And if you get both borg and msgpack from apt source, they usually should fit. If they don't, contact the maintainer.

**Comment by ThomasWaldmann** [comment]
I had a look at crash.txt, it seems weird.

The assertion error should never happen (it should have that exclusive lock).
The KeyError is also locking related.

Later it also complains about not having "open", which is a builtin function of python.

Can you try reinstalling borg 1.2.2 and also a not broken, recent msgpack?

**Comment by ThomasWaldmann** [comment]
Guess this is solved?

**Comment by Jonny007-MKD** [comment]
Sorry for responding to this old thread, but I found this issue by searching for this specific error message and want to leave a trace what the reason for the error was:
Some files in the borg repository were owned by the wrong user because I executed `borg compact` as root and not as the owner of the repo. Doing a `chown` solved this issue.

**Comment by ThomasWaldmann** [comment]
@Jonny007-MKD The error msg "Exception ignored in: <function Repository.__del__ at ...>" happens in a lot of circumstances and is usually a secondary effect after the primary exception (which usually points to the root cause) happened.

So one usually needs to read the traceback to find the primary exception / root cause.
