### ISSUE TITLE
vagrant: openbsd box broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6796]
due to an incompatible change in package format, the openbsd 7.1-current box is broken.

**Comment by ThomasWaldmann** [comment]
@bket is there an easier fix than just reinstalling?

**Comment by bket** [comment]
I guess userland and ports are not in sync. I'm not sure reinstalling is going to help (unless the Vagrant OpenBSD current box is being maintained).

It was needed to use OpenBSD current because of libdeflate, which was imported at around OpenBSD-7.1. Instead of using current I would suggest to use OpenBSD-7.1.

**Comment by ThomasWaldmann** [comment]
I used the 7.1 iso and did an upgrade of the "broken" system (was just curious whether that will fix it). It seems it did, openbsd vagrant-based tests working again.

After the iso-based upgrade, I booted and ran `syspatch` a few times and `pkg_add -u`.
