### ISSUE TITLE
borg rename should reject invalid destinations

### ISSUE THREAD

**Issue by glandium** [borgbackup/borg#680]
With a bad copy/paste, I ended up doing something like:
```
borg rename /path/to/repo::archive /path/to/repo::renamed-archive
```

And now, `borg list` shows `/path/to/repo::renamed-archive` as the archive name, and commands like `rename`, `delete`, `info` fail saying that `/path/to/repo::/path/to/repo::renamed-archive` is an invalid location format.

**Comment by glandium** [comment]
Thanks. Now, I'm still left with an archive I can't do anything with. Would lifting those checks on a local build allow me to rename it to a valid name without screwing up my repo?

**Comment by ThomasWaldmann** [comment]
Yes, that would likely work. The "no backslash" restriction is just because it breaks the fuse mount.

https://github.com/borgbackup/borg/blob/master/borg/helpers.py#L656

`(?P<archive>[^/]+)` is what matches the archive name and the `[^/]+` part means some arbitrary characters, but no `/` allowed. If you replace that part by `.+`, it will accept any characters.
