### ISSUE TITLE
borg binary's glibc requirement excludes RHEL 6.x

### ISSUE THREAD

**Issue by maltefiala** [borgbackup/borg#681]
RHEL 6.x ships with glibc 2.12. If requirement could be lowered to 2.12, "installation" on RHEL 6.x would be easy. General EOL of RHEL 6.x is 2020.

Building of python3.4 is a possible workaround, of course.

**Comment by ThomasWaldmann** [comment]
I am not aware that we have a "gcc requirement". Can you please add more details to your first post?

**Comment by maltefiala** [comment]
Sorry, my bad. I meant glibc.

**Comment by ThomasWaldmann** [comment]
ok, so fix you first post and also add what the actual problem in practice is. if you don't provide enough details, this has to be closed due to lack of details and clarity.

if you are talking about the binaries (you did not say that), someone told me that the binary built on debian 7 also works on centos 6. Did you try it?

also, your reference to python3.4 is unclear. How is it related?

**Comment by maltefiala** [comment]
Yes, it's about the binary.

I did not try as the [requirements](https://borgbackup.readthedocs.org/en/stable/installation.html#standalone-binary) are depicted as follows:
> Linux: glibc >= 2.13 (ok for most supported Linux releases)

If it is working on Centos6, the requirements are  >= 2.12. I'll let you know when I had time to try.

**Comment by ThomasWaldmann** [comment]
See also: https://github.com/borgbackup/borg/issues/491

**Comment by ThomasWaldmann** [comment]
I'm closing this for now, reopen and provide more details if needed.
