### ISSUE TITLE
Unable to solve - "Cache, or information obtained from the security directory is newer than repository."

### ISSUE THREAD

**Issue by casper** [borgbackup/borg#6900]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

BUG (maybe?) Or perhaps a usability issue, which prevents tool usage due to incomprihensible error message and no route leading to solution.

#### Your borg version (borg -V).
borg 1.1.15 (latest available from the Ubuntu 18.04 repository)

#### Operating system (distribution) and version.
Ubuntu 18.04

#### Hardware / network configuration, and filesystems used.
Hetzner Cloud VPS, repository accessed through SSH

#### How much data is handled by borg?
20 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Not quite sure as the initial error is an hour of troubleshooting ago, but I think mixing `sudo` access with non-sudo access caused it:

```
borg create ... repo
sudo borg create ... repo
```
After a mixed use of `sudo` and non-sudo, it broke.

## Describe the problem you're observing.

```
sudo rm -rf ~/.config/borg ~root/.config/borg
casper@zoid ~/cron $ sudo borg list $BORG_REPO
Enter passphrase for key ssh://borg/./Backup/Borg:
Cache, or information obtained from the security directory is newer than repository - this is either an attack or unsafe (multiple repos with same ID)
```

However this works. Don't know why, but it doesn't help as I need to run my backups as root:

```
sudo rm -rf ~/.config/borg ~root/.config/borg
casper@zoid ~/cron $ borg list $BORG_REPO
... works fine ... normal repo list output ...
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I read the FAQ and tried the commands from there, but no help.

```
borg config repo id   # shows the REPO_ID
rm ~/.config/borg/security/REPO_ID/manifest-timestamp
borg delete --cache-only REPO
```

Borg somehow got confused because I have to run my full system backup as root, but I happened to be browsing the repo accidentally as non-root before. As a result both root and non-root was writing into the same `.config/borg` folder, and I think it broke because of that.

How can I get access back to the repo now? Will I have to delete all my backups and start from scratch?

**It would really help if there was a `--force` switch on borg to get past this error.** I know it's not an attack, I just want to run my backup normally. Thank you.

**Comment by casper** [comment]
Commenting out the following code in `cache.py` and it all starts working. This is the only solution I found so far.

            # else:
            #    raise Cache.RepositoryReplay()

However it is not a permanent solution, because if I enable those lines again, the error persists.

**Comment by casper** [comment]
Ok..finally figured it out:

```
sudo rm -rf ~casper/.config/borg ~root/.config/borg ~/.cache/borg ~root/.cache/borg
```
It would be nice if the error message told the user this, or provided a `--force` switch or similar to resolve this in an easier manner. Anyway. It works now, but was a mostly frustrating exercise :-/

**Comment by ThomasWaldmann** [comment]
Yeah, I can feel the pain.

In borg2, we won't need the aes-ctr mode related precautions any more, so a lot of checks will just get removed.

But, please learn from this:

You shot yourself in the foot here by mixing up file system permissions.

This is **not** borg specific, but you can cause issues by doing such stuff for a lot of programs that work with files in the file system. If you create files as root, you are usually not able to read them as normal user (and that can lead to all sorts of issues). Or in general: if you create as user1, you usually can't read as user2. This assumes the usual `umask`, which takes away (at least) `other` permissions.

Only exception is root, root can read/write everything.

Instead of `rm`, the usual first attempt to fix such a mixup is to:
- always use the same user/group to run
- chown -R user.group affected_files

In a lot of cases (but not all), this will fix the permissions mixup and thus make stuff work again.

Our docs also recommend to always use the same user to run borg / to access a borg repo.

**Comment by casper** [comment]
Thanks @ThomasWaldmann . I will. Good points to keep in mind. I was also mixing `sudo` with running `borg` as `root` from the root prompt, which I now realize is also different because `HOME` is not the same in both scenarios on Ubuntu. Fun adventures in the Unix shell. Will not forget :)
