### ISSUE TITLE
Feature request: ability to estimate size of backup without actually creating one

### ISSUE THREAD

**Issue by SeanDS** [borgbackup/borg#7050]
## Have you hecked borgbackup docs, FAQ, and open Github issues?

Kind of, via googling

## Is this a BUG / ISSUE report or a QUESTION?

Question / feature request

## Describe the problem you're observing.

I want to upload a large amount of data to rsync.net with borg and need to figure out how much storage to buy there. Since borg storage is billed up front yearly, I'd rather not buy more than I need. I looked for a way to estimate the size of borg's final backup, but couldn't. The best I could do was with `du -sh /path1 /path2 --exclude-from=/path/to/borg/excludes`, but this doesn't consider borg's deduplication.

I guess `borg create --dry-run` can't compute this since it doesn't appear to actually look at the specified paths. Maybe there could be a `borg create --dry-run-full` (better name needed) that does everything a real run would do except the data transfer, then report the size at the end?

I guess it could be argued it's potentially a little bit misleading to use `borg create` for this, since the final size of the backup also depends on what's in the repo already. So maybe a separate `borg estimate` command might be better?

Sorry if this feature is in borg already and I've missed it.

**Comment by ThomasWaldmann** [comment]
There are 2 things that can not be cheaply predicted:
- how good your data deduplicated
- how good your deduplicated data compresses

Thus, it is hardly possible to compute the size of a backup without doing most actions as in a backup.

`borg create --dry-run` was made mostly to optimise/check includes/excludes, but does not read / dedup / compress all file content (because that would take much longer).

You could just do a local backup (e.g. to an external hdd or some local server) to estimate the storage size you need to buy.

One also needs to consider that daily backups will add a bit to that first-backup size and that some borg operations need some additional space in the repository, so you shouldn't make it too tight.

**Running out of space is something you should avoid by all means, because borg temporarily needs additional space even to delete archives.**

**Comment by SeanDS** [comment]
Fair enough, thanks for the explanation. I'll back up to an external hard drive to figure out the size I need to purchase.

**Comment by Atemu** [comment]
> it is hardly possible to compute the size of a backup without doing most actions as in a backup.

I wouldn't mind doing that in some cases. I treat my borg backups as append-only and therefore want to minimise the amount of data I add to the store with each backup; adding directories I don't care about to the exclude list each run. In order to do that, it's critical to know which directories would significantly bloat the backup. I currently need to create a backup first and roll back if it happens to include something I didn't actually want to include.

Another useful metric you could calculate is an upper bound on additional storage required using just the file changed heuristic; counting the whole file as changed if borg would have to examine its content. Many (if not most) files won't be changed between backups, so this is a relatively good indicator already and not very expensive to compute. This would also help reduce feedback cycles for trying out different files-cache modes.
