### ISSUE TITLE
discuss: remove "auto" compression mode in borg2?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7054]
## About "auto"

The "auto" compression mode was added to avoid that bad compressors cause a lot of cpu load when trying to compress incompressible data, like:

```
borg create --compression auto,lzma,6 ...
```

This would first use the super-fast lz4 as a predictor whether a chunk is compressible.

If the chunk compresses to less than 97%, the expensive compressor will be invoked.

Otherwise the chunk is considered incompressible and borg will either store lz4-compressed or uncompressed data, whatever is shorter.

## Arguments for keeping it

- evidence that it is actually useful, did somebody measure it / can we have some numbers?
- compatibility to borg 1, no script change needed

## Arguments for removing it

- evidence that it is not useful, did somebody measure it / can we have some numbers?
- adds complexity / one more layer to the compression code (the "Auto" class wrapping the expensive compressor), makes some other code (e.g. rcompress, recreate) more complicated
- adds complexity to the tests
- adds magic behaviour / makes borg's behaviour more difficult to predict / stats output more difficult to understand
- anything else? @elho

**Comment by ThomasWaldmann** [comment]
Related: `DecidingCompressor` base class of the compressors.

When compressing, this either returns the data-compressed-with-desired-compressor or the data-compressed-with-CNONE-compressor, whatever is shorter.

This saves some compression overhead for very short data. Is it worth it?

**Comment by elho** [comment]
- compatibility to borg 1.x scripts is no argument, as borg2 AIUI already is incompatible in its command line interface, so any script needs at least a review.
- Numbers from my old and non-scientific (each compression algorithm had a new repo initialized thus with different chunker hash seed and different resulting chunks) test that still show a clear tendency can be found here: http://www.elho.net/dev/borg/#compression
- The practical reasons why auto is not of much use as it is right now IMO are:
  - Just because a given chunk does not compress well with LZ4 and thus trigger the auto logic of not compressing it, does not mean it would not compress fairly good with the strong compressor.
  - Similarly, a given chunk needs to compress relatively well with just LZ4 for the other compressor even benig considsidered to be tried.
  - ZSTD has both low levels that are relatively fast as well as lots of levels to fine tune it nicely and compressing all data once with a fast(ish) good(ish) results compressor once typically is faster than compressing it all with a very fast not-too-good results compressor plus some another time with a slow but very good results one.
  - Previous items summarized, auto,fastalgorithm makes the penalty of compressing twice not worthwhile, auto,slowalgorithm makes the penalty of not making use of the better compression in many corner cases not worthwhile.
  - Backing up to remote locations (ie. practical use vs. compression benchmark to local NVMe), attainable network bandwidth (which is severely limited by the round-trip delay of the SSH connection in borg's for now synchronous design) is the limiting factor that does (or at lesat would) allow for a fairly slow compression algorithm compared to LZ4, so over optimizing the compression part for speed may be popular among users, but not helping overall backup duration all too much.
- Not storing data that turned out larger after compression (ie. purpose of the `DecidingCompressor` base class) does make sense IMO. Typically it may just be a few bytes, but it making no senste to wsate both space and decompression cycles in that case, depending on the compression algorithm, there may exist specially crafted data that makes the result more than just a few bytes larger, so it also is a question of being robust against that.

**Comment by ThomasWaldmann** [comment]
1. yes, borg2 breaks compatibility. but having more or less to change is still a difference in the amount of work and the amount of potential pitfalls if you forget to change something.
2. looking at these results and comparing the `auto,X` results to the `X` results gives: not worth for the space saved (maybe 1%?), but there are significant timing differences (see `zstd,22`- maybe needs checking, could also come from other influences maybe?)
3. a.+b. not sure about this. could it be that this usually is the case, but maybe not always? we do not check that it "compresses well with LZ4", we check if it compresses better than factor 0.97 == "compresses at least a little bit".
3. c. not sure what the point is here. agreed that zstd has a lot of levels. lz4 is super fast.
3. d. agreed, `auto,fastalgo` does not make much sense (but that never was intended usage, although technically possible). you mean you'ld rather use `slowalgo` than `auto,slowalgo` because investing the additional time is usually worth it? your `auto,zstd,22` run took about 1h (~15%) less than your `zstd,22` run and did only compress 1% better.
3. e. i agree that if one has a somehow slow connection, one would prefer high compression.
4. yes, it makes sense somehow, but if you look at the `borg rcompress` i just implemented, you'll see that it will recompress chunks that are not yet having the **desired** compression. "none" is usually not the desired compression, so it will process these (again and again, because the likely outcome of the DecidingCompressor will again be not the desired one, but again "none"). at least i optimized away that it would re-write such none->none processed chunks, but it still reads and compresses them. maybe i need to make some size stats here, if the savings are only a few bytes, simpler code and less re-re-re-processing might be preferable.

**Comment by ThomasWaldmann** [comment]
What we did not consider at all yet is power consumption (but we do not have any numbers). But guess we can safely assume that high compression levels eat quite more energy because of their much longer high-cpu compression runtime.

**Comment by awgcooper** [comment]
I use 'auto,lzma'. CPU overhead and compression time are not an issue for me. I just want to use as little disk space as possible. If there's a chance, as per elho, 3a, above, that 'auto' compromises the efficacy of the strongest algorithms, then that negates any benefits for me. I appreciate though that my use case - max CPU overhead etc - may not be very representative.

**Comment by awgcooper** [comment]
This isn't an exhaustive analysis, quite the reverse, but it's compelling regarding one of my use cases. I just tried 'lzma,6' without 'auto' on a dataset I regularly backup. There's a mixture of highly compressible data and already compressed such as movies and photos. Before today I never tried it without 'auto': it's slowed down to a few MB/s and, roughly projecting, I reckon it will take approximately 15-20x longer than with 'auto' enabled. I guess tons of CPU cycles are being wasted on the already compressed material. As intended, it appears 'auto' allows me to mix data with different types of compressibility without slowing to a crawl - the aforementioned dataset of 0.5TB takes ~ 3 hours for the first backup. Losing it would - at least for my specific purposes - be a backward step.

I'd vote to keep it, assuming it's not too much of a problem for the codebase.

**Comment by snsmac** [comment]
Another option would be to keep auto but extend it so that it uses some heuristic to determine if a file is compressible or not. This heuristic could be based on the file type, some entropy calculations, or the check with a fast compression algorithm as it is done right now. 
BTRFS for example does some relative fast entropy and content analysis to determine if a file should be compressed or not:
https://github.com/torvalds/linux/blob/master/fs/btrfs/compression.c#L1650

**Comment by awgcooper** [comment]
I just completed the backup that I was referring to in my post just above. It seems - at least for my data mix - that the heuristic works very well as per the following stats (please note, the backed up size figure I quote is obtained by running 'du -sk _local_repo_location_' and I create a new repo for each test; the pre-backed up size is ~ 600GB):

**auto,lzma,6**
- backup time: 3h59m20s
- backed up size (dedup + compr): 485.73GB

**lzma,6**
- backup time: 35h11m47s
- backed up size (dedup + compr): 483.72GB

An extra ~31 hours for 2GB of extra compression when not using auto! The overall compression ratio is, I think, what one would expect given the bias towards uncompressible data. If I have the time I'll run some comparisons with different zstd levels and report back.

**Comment by ThomasWaldmann** [comment]
@awgcooper oh, wow, saved 90% of the time (and likely also power consumption) and did cost only 0.5% of space.

could you try to find the `zstd` level that gives same compression as `lzma,6` and compare that `zstd,L` to `auto,zstd,L`? just to check if it is the same problem with zstd.

**Comment by ThomasWaldmann** [comment]
@snsmac we had it based on file extension before `auto` and decided to rather not cause that configuration load for the users.

**Comment by awgcooper** [comment]
> could you try to find the `zstd` level that gives same compression as `lzma,6` and compare that `zstd,L` to `auto,zstd,L`? just to check if it is the same problem with zstd.

'auto,zstd,22' was almost identical to 'auto,lzma,6'. I've just finished running 'zstd,22' which is within 1GB of 'lzma,6'. As you'll see, removing auto leads to a dramatic slowdown with zstd also, albeit not as severe as lzma. Here's the full set of auto vs no-auto for maximum compression (it includes the data from my previous post):

**auto,lzma,6** 
backup time: 3h59m20s
backed up size (dedup + compr): 485.73GB

**lzma,6**
backup time: 35h11m47s
backed up size (dedup + compr): 483.72GB

**auto,zstd,22** 
backup time: 3h45m45s
backed up size (dedup + compr): 485.70GB

**zstd,22**
backup time: 19h54m32s
backed up size (dedup + compr): 482.80GB

It seems if one wants to use max settings and 'compress and forget' with a reasonable backup time, auto is essential.

**Comment by knutov** [comment]
auto is very usefull in case when backuping big data with both text files (some scripts for example) and media files.

For example, Kopia has no "auto" and it is really pain, leading to having large list of file extention to exclude from compression.

removing auto will require a lot more time and cpu resources to backup in almost all cases.
