### ISSUE TITLE
Borg info reported size is < actual archive size

### ISSUE THREAD

**Issue by willrabbermann** [borgbackup/borg#7089]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

Minor issue/possible user error

## System information. For client/server mode post info for both machines.

borg 1.2.1

gentoo hardened

30 GB de-duplicated archive size

```
borg info -v os-backups
```

## Describe the problem you're observing.

borg info reported deduplicated size is < actual archive size.

```
# borg info -v os-backups
                       Original size      Compressed size    Deduplicated size
All archives:              502.13 GB            247.54 GB             30.93 GB

# du -sh os-backups/
49G	os-backups/
# ...os-backups/data # du -shc *
21G	0
23G	1
5.4G	2
50G	total
```

Archive is located on an ext4 partitioned hard drive.

**Comment by ThomasWaldmann** [comment]
Did you ever run `borg compact`? Is the repo append-only?

**Comment by willrabbermann** [comment]
```
λ sudo borg compact --progress --verbose os-backups/
segment 2 not found, but listed in compaction data
compaction freed about 21.66 GB repository space.
```
Would an append-only repo not auto compact after prune/deletes? 
```borg compact``` worked great. I may need to set a cron job for it.
```
[repository]
version = 1
segments_per_dir = 1000
max_segment_size = 524288000
storage_quota = 0
additional_free_space = 0
append_only = 0
id = redacted_lol
```

**Comment by willrabbermann** [comment]
my brother's last name is Waldmann, small world

**Comment by ThomasWaldmann** [comment]
The separated `borg compact` is new since borg 1.2 (borg 1.1 did implicitly compact at the end of each command, if possible).

If a repo is in append-only mode, no data is ever removed / compacted, that's the whole point of append-only.
You can still logically delete archives, but their space won't be freed in an a-o repo.
But your repo is not a-o, according to the repo config you showed.

Yeah, small world. But the name Waldmann is not very rare in Germany, I even have people in the same small city where I live with the same name which are not closely related. :-)

**Comment by willrabbermann** [comment]
My brother is a B-52 weapons systems officer, he can find a lot of Waldmann's everywhere he goes. I cant find a single Rabbermann in St. Louis, they're all in Illinois or somewhere else but I've never met them. At least we are all German :)
