### ISSUE TITLE
Experienced high IO delay during a borg backup

### ISSUE THREAD

**Issue by ovizii** [borgbackup/borg#711]
I am running a server with proxmox as hypervisor which in turn runs 2 LXC - the server is barely using any RAM/CPU but a few days ago my monitoring systems told me every hosted domain was offline so I started analysing and found the IO delay was so high due to extremely high HD usage. I attempted to install sysstats and iostat but even installing these 2 tools took about 15 minutes and things were getting critical so I simply restarted the containers interrupting the borg backups and everything went back to normal.

I don't have any proof that it was borg causing this but the problems started exactly when the borg cronjob fired.

This issue lead to me creating my other support thread when I tried upgrading from borg 0.30.0 to 1.0.0rc2

**So the question would be:**
Is it possible borg caused so much HD access that the whole system suffered from IO delays?
And if it is possible, any way to track or mitigate this?

**Comment by ThomasWaldmann** [comment]
Well, of course does a backup tool cause high I/O load (and, depending on your settings and CPU resources maybe also high cpu load) - it must read all the files it shall backup (esp. if it is the first time it runs, later it will only read modified files).

So if multiple accesses compete about the hard disk, it will slow down because its head needs to seek all the time. SSDs have less problems here as seek time is much lower.

You can check these tools / mechanisms to optimize: ionice, disk I/O scheduler and running your backups at a time when the VMs are relatively idle.

This is nothing special about borg btw.

**Comment by ovizii** [comment]
Thanks, I have already lowered the compression to see if that helps. Will look into all the tools you mentioned. I understand what you're saying but it was running fine for about 4 months now without a single issue so I was wondering why it would hang all of a sudden.

Are there any particular points in time it could spike, if using 
`/usr/local/sbin/borg prune $REPOSITORY --prefix `hostname`- --keep-daily=7 --keep-weekly=4 --keep-monthly=6 --keep-yearly=1 -v` 

Just trying to figure out why this happened now and never before.

**Comment by manwegit** [comment]
I use this on some prod systems to lower io problems for actual service while doing backups etc.
But use them with care, because on really heavy systems this might slow down backups etc too much.

```
#!/bin/bash

# -c 3 = idle, $$ = current process
ionice -c 3 -p $$
renice -n 16 -p $$

my-disk-heavy-backupcmd
```

**Comment by ovizii** [comment]
Thanks, I've been looking into ionice since Thomas mentioned it, I think that could be the solution. 
I'll try ionice -c 2 -n 7 first and see how far that gets me.
