### ISSUE TITLE
Question regarding one repo vs multiple

### ISSUE THREAD

**Issue by DarkShadow44** [borgbackup/borg#7184]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
borg 1.2.2

#### Operating system (distribution) and version.
Arch Linux

#### Hardware / network configuration, and filesystems used.

btrfs, ext4, NTFS, FAT32

#### How much data is handled by borg?

~1TB

#### Question

I'm currently having a complete backup from by system to a remote hetzner storagebox.
Currently I'm using something like
```
sudo borg create --exclude={"/home/fabian/.cache/ccache/*","/home/fabian/VirtualBox VMs/*","/home/fabian/.cache/borg/*"} ssh://XYZ@XYZ.your-storagebox.de:23/./Borg_Home::Home1 /home
sudo borg create ssh://XYZ@XYZ.your-storagebox.de:23/./Borg_Z::Z1 /run/media/fabian/DataB/Spiele/Z/Z.dat
sudo borg create --exclude={"/run/media/fabian/DataB/_Linux/*","/run/media/fabian/DataB/Spiele/Z/*"} ssh://XYZ@XYZ.your-storagebox.de:23/./Borg_DataB::DataB1 /run/media/fabian/DataB
sudo borg create --read-special ssh://XYZ@XYZ.your-storagebox.de:23/./Borg_Efi::Efi1 /dev/sdb2
sudo ntfsclone -so - /dev/sdb3 | sudo borg create --stats --compression auto,zstd,7 --checkpoint-interval 300 ssh://XYZ@XYZ.your-storagebox.de:23/./Borg_WinHome::Win1 -
sudo borg create --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/home/*","/.snapshots/*"} ssh://XYZ@XYZ.your-storagebox.de:23/./Borg_LinRoot::Root1  /
```

Currently everything is done into a separate repo. This makes handling kinda simple, but requires inputting the password separately for each repo, and if I move files from a volume to a different one, it's not deduplicated.

Question is, would a monolithic repo be preferred? It does  seem smarter than ~10 different small repos. This would also allow deduplication across volumes.
Problem I see here, I use ntfsclone with stdin, also backup of '/dev/sdb3' directly. Also potentially troublesome, 'Z.dat' is a mountable container that doesn't seem to have its modified date updated when it's changed, so it always needs to be read and deduplicated.

Could I even put that all into a single borg command? Would I want that?

Note: With borg 2.0 at the horizon, I probably will upgrade as soon as it's considered ready. So if there is differences between 1.x and 2.0 here, I'd focus on an answer for 2.0.

**Comment by ThomasWaldmann** [comment]
If these commands are all from same source host: put them all (without sudo) into a script, make the script root.root 700 permissions and do `export BORG_PASSPHRASE=yoursecret` at the beginning of the script. If you run multiple commands against the same repo (e.g. create, prune, compact), then `export BORG_REPO=...` might also save some duplication. Then execute the script using sudo or via cron as root.

One big or multiple smaller repos are a matter of taste and also resource usage (fewer repos might save some disk space due to better dedup, but the repos will then be bigger and contain more chunks, thus use more RAM for borg and also some operations will take longer, like borg check or borg mount).

**Comment by DarkShadow44** [comment]
Thanks for your quick answer. Yes, all from the same host, so I use multiple commands for that, makes sense.
RAM usage and operation time is not so important, so I'm gonna go for a single repo then. Just have to wait for 2.0 to use transfer :smile: 

Regarding the monolithic repo, I thought maybe it's possible to store all that data from different sources inside a single archive, would make handling a bit easier. But I guess it's not that important.

Is there also an option to use put the whole `--verbose --list --stats --progress --compression auto,zstd,7 --checkpoint-interval 300` thing that I left out into a variable?

**Comment by ThomasWaldmann** [comment]
Guess borg2 does not help you with the "multiple repo into one repo" transfer issue:

Each of your exisiting repos has a different chunker seed and also a different MAC (id) key.
That means they would cut chunks differently and also would compute a different id even for the same content.
You can't mix such chunks together into 1 repo. It would not work due to the id computation. And it would not deduplicate due to the different chunk cutting.

The trick borg2 transfer does (for single-old-to-single-new repo transfers):
- it reuses the old chunker seed also for the new repo
- it reuses the old MAC key also for the new repo

But obviously that can be only done for **one** old repo **per** new repo.

In future, that will be more flexible **if** you remember to create **related** repos, then you can transfer stuff between multiple of them and mix together stuff.

But the **related repo** feature did not exist before borg 2.

**Comment by ThomasWaldmann** [comment]
Guess you can put that into a shell variable to reduce repetitiveness in your script.

--list and --progress usually do not mix well, could get rather unpretty. use --list for unattended stuff and --progress if somebody is watching.

--checkpoint-interval 300 is rather short. i'ld only use that if i had a super unstable connection, because there is quite some overhead to do each checkpoint. if your connection is not that bad, go with the default 1800 (or 900).
