### ISSUE TITLE
Borg create aborted - Data integrity error: Invalid segment entry header: unpack requires a buffer of 41 bytes

### ISSUE THREAD

**Issue by xeruf** [borgbackup/borg#7221]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.2.2

#### Operating system (distribution) and version.
Arch

#### Hardware / network configuration, and filesystems used.
FAT

#### How much data is handled by borg?
A few TB

## Describe the problem you're observing.

I am backing up a 400GB SD Card (with mostly duplicated data) onto my borg repo, which has 2TB free space.
But upon being almost done, it aborted with this confusing error.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Restarted the backup now, let's see what happens...

#### Include any warning/errors/backtraces from the system logs

```
Data integrity error: Invalid segment entry header [segment 2197, offset 524190020]: unpack requires a buffer of 41 bytesow oranges in snow.mp4    
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 675, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 608, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 820, in _rec_walk
    self._rec_walk(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 786, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 688, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1434, in process_file
    self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1261, in process_file_chunks
    item.chunks.append(chunk_processor(chunk))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1249, in chunk_processor
    chunk_entry = cache.add_chunk(chunk_id, data, stats, wait=False)
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 951, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1228, in put
    self._delete(id, segment, offset, update_shadow_index=False)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1262, in _delete
    size = self.io.read(segment, offset, id, read_data=False)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1572, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/usr/lib/python3.10/site-packages/borg/repository.py", line 1587, in _read
    raise IntegrityError('Invalid segment entry header [segment {}, offset {}]: {}'.format(
borg.helpers.errors.IntegrityError: Data integrity error: Invalid segment entry header [segment 2197, offset 524190020]: unpack requires a buffer of 41 bytes

Platform: Linux pavilion.arch 6.0.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000 x86_64
Linux: Unknown Linux  
Borg: 1.2.2  Python: CPython 3.10.8 msgpack: 1.0.4 fuse: None [pyfuse3,llfuse]
PID: 17452  CWD: /run/media/janek
sys.argv: ['/usr/bin/borg', 'create', '--exclude-caches', '--progress', '--stats', '::sd_FAT', 'FAT']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Hmm, the chunks cache does not have information about this chunk, so `add_chunk` thinks this is a **new chunk** and calls `put` to write the chunk (for an existing chunk, it would have just increased the refcount and not called `put`).

Inside `put`, it notices that the repo index **does have** information about this chunk (which is unexpected considering the above). Thus, it calls `_delete` to delete the existing chunk in the repo before actually putting the current chunk.

In `_delete` it needs to know the size of the chunk it is deleting (for bookkeeping purposes, like compaction information) and as we have the size only in the segment entry header, it calls `io.read` to read that.

In `io.read` it calls `io._read` to do the actual reading. There it tries to `fmt.unpack(header)` to unpack the segment entry header into a tuple, but that fails with `unpack requires a buffer of 41 bytes`.

The `fmt` used there is `self.put_header_fmt` (which describes the format of a 41 bytes long bytestring), the `header` used there is what came back from `fd.read(self.put_header_fmt.size)` (so that should be 41 bytes, but could be less if there was unexpectedly not enough data to read in the file).

So, considering this, I'ld say your repo is corrupted somehow and you should run a full `borg check --repair` on it.

**Comment by ThomasWaldmann** [comment]
BTW, what fs do you use for the **repo**?

**Comment by ThomasWaldmann** [comment]
Note: `io._read` could fail a little earlier (before trying the struct unpack operation) if it checked whether `fmt.size == len(header)`. If the header is too short, we do not have enough data for the struct unpacking.

**Comment by xeruf** [comment]
It is a 4TB disk formatted as ext4 attached through a USB hub.
Trying the backup again worked, the SD Card was formatted with FAT32 btw.

**Comment by ThomasWaldmann** [comment]
@xeruf Did you find out more about this? What I've seen yet, it looks like corruption in the repo, but I didn't find anything wrong on borg related to this.
