### ISSUE TITLE
lazy eval for list output?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#735]
the current `borg list` implementation has some hardcoded optimization to either compute some "standard" output (show some specific attributes in a specific way) or to support user-defined output format (making it possible to show more attributes in a user-defined way).

maybe this code could be unified again using lazy evaluation - to only compute exactly what's needed.

that would also open the door to do some more heavywheight stuff (that we for sure do not want to do in a non-lazy way): e.g.:
- display the sha256 of the file
- display unique chunks of this file(?)

**Comment by manwegit** [comment]
About the newline 'NEWLINE': os.linesep,  # TODO: difference between LF and NEWLINE?
I could not test and I don't if there is differences based on os for newline.
Other than that, some people might be more comfortable with NEWLINE term than LF

Part of the reason for list-format change was to make way for future more complex chunk information prints. I'm not experienced enough python coder, but lazy eval based on keys sounds great.

**Comment by enkore** [comment]
Hm, I guess if someone wants to emulate the output of a different program closely LF vs. CR vs. NEWLINE could be useful, but that seems a bit far-fetched maybe.

Yesterday I profiled the current master branch and a slightly better version of what I made public in my repository so far. The difference in total run time is miniscule (for the exact same output my version takes about 3 % less wall time: performance for the default output format shouldn't be considered a "driving force").

Find two kcachegrind maps attached. As you can see, the runtime is *dominated* by what *has* to be done. Differences in the runtime for the default format thus stem from tiny differences in overhead.

![newlist-profile](https://cloud.githubusercontent.com/assets/1330164/13748536/7b58d7f8-e9fd-11e5-9ad6-2561d19f4d5f.png)
![oldlist-profile](https://cloud.githubusercontent.com/assets/1330164/13748538/7e658522-e9fd-11e5-9d2d-4434b879044f.png)

For the default output safe_timestamp calls can be reduced a bit, but that will also yield only 2-3 % I expect.

btw. I think I found a (valid) optimization of `unpack_many` which speeds up diff, list and extract by 5-15 %. So far it looks like it doesn't change program behaviour otherwise, but I will perform much additional testing before considering pushing it to my public repo.

**Comment by ThomasWaldmann** [comment]
@enkore interesting stuff, but please stay on topic in this ticket (open new / amend existing other topics if it does not fit).

When looking at these big blocks in your pictures for time-related computations, it seems lazy eval (if it does not cost too much by itself) could give some speedup here (if there are no timestamps in output).

**Comment by ThomasWaldmann** [comment]
Fixed by:
https://github.com/borgbackup/borg/commit/4151db270cd9413f3fac153e173ca13ad77a539a

(only computes stuff needed for the desired output format)
