### ISSUE TITLE
add a mount.borg wrapper

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#743]
it just needs to do:
```
#!/bin/bash
borg mount "$@"
```

it can be used in fstab like:
```
mount.borg#repo_or_archive mountpoint fuse defaults noauto 0 0
```

**Comment by manwegit** [comment]
Create `borgmount`-wrapper:
Add symlink to fuse:
`ln -s /sbin/mount.fuse /sbin/mount.fuse.borgmount`

Now fstab line works without '#'-program
`repo_or_archive mountpoint fuse.borgmount defaults noauto 0 0`

**Comment by ThomasWaldmann** [comment]
If we add mount.borg here https://github.com/borgbackup/borg/blob/master/setup.py#L262 we can have it automatically installed in a directory in the PATH within the usual installation process. Also we save having that extra directory/file.

**Comment by enkore** [comment]
Should this:

    def main_mount():  # pragma: no cover
        sys.argv.insert(1, "mount")
        main()

    'console_scripts': [
        'borg = borg.archiver:main',
        'mount.borg = borg.archiver:main_mount',
    ]

not already suffice for a fstab to work? `borg mount` expects <device> <dir> just like mount.*

**Comment by ThomasWaldmann** [comment]
@enkore looks good, try. :)

**Comment by enkore** [comment]
Well, after being dropped once into "emergency maintenance mode" (systemd's wording :-) because I didn't have llfuse installed system-wide, it works quite well.

    $ borg list testrepo::arch1 
    drwxr-xr-x mabe   mabe          0 Sun, 2016-03-13 15:53:45 testdir
    -rw-r--r-- mabe   mabe          5 Sun, 2016-03-13 15:53:45 testdir/file1
    -rw-r--r-- mabe   mabe          5 Sun, 2016-03-13 15:53:45 testdir/file2
    -rw-r--r-- mabe   mabe          5 Sun, 2016-03-13 15:53:45 testdir/file3
    -rw-r--r-- mabe   mabe   10485760 Sun, 2016-03-13 15:53:45 testdir/kern
    $ cat /etc/fstab | tail -n 1
    /home/mabe/Projekte/_oss/borg/testrepo::arch1 /mnt/test borg rw 0 2
    $ sudo ls -lR /mnt/test  
    /mnt/test:
    total 0
    drwxr-xr-x 1 mabe mabe 0 Mar 13 15:53 testdir

    /mnt/test/testdir:
    total 10240
    -rw-r--r-- 1 mabe mabe        5 Mar 13 15:53 file1
    -rw-r--r-- 1 mabe mabe        5 Mar 13 15:53 file2
    -rw-r--r-- 1 mabe mabe        5 Mar 13 15:53 file3
    -rw-r--r-- 1 mabe mabe 10485760 Mar 13 15:53 kern

(I only need sudo here because I forgot to chown /mnt/test after creating it. chown'ing it now fails, because that would apply to both / in the mounted archive, which isn't supported).

**Comment by manwegit** [comment]
How will this affect standalone builds? Do we then have two "binaries" to download or will it be only borg and leave the rest to documentation?

**Comment by enkore** [comment]
Because they would need to be independent it would double the download size. I think there are two options for making this work with standalone binaries:

1. Tell the user to create bin/mount.borg with something like `borg mount $@`.
2. Tell the user to ln -s bin/mount.borg to borg (which would need a bit of code in borg.archiver:main to look at sys.argv[0] (endswith(/mount.borg) and do `sys.argv.insert(1, "mount")`

**Comment by ThomasWaldmann** [comment]
@manwegit about the binary: there will be just 1 binary, leaving the rest to the docs.

**Comment by manwegit** [comment]
That's what I thought, so examples to FAQ I assume?

**Comment by ThomasWaldmann** [comment]
Maybe rather extend borg mount usage docs.
