### ISSUE TITLE
No new initial backup after restoring whole harddrive

### ISSUE THREAD

**Issue by Oberlurch3000** [borgbackup/borg#7484]
Because of a damaged file system I had to format the whole harddrive of my clouds data directory.
After restoring the backup I noticed that borg is not handling the data as already existing in the repo.
It's making a initial backup of all the already known data. With roughly 2TB data this takes quite a while on my pi4.

Is there any better way to solve this? It's not dramatic but I'm curious.

**Comment by infectormp** [comment]
This is expected behavior, but only at first run, I think.
You can try to play with `--files-cache` option to avoid this. 
Also read this article carefully https://borgbackup.readthedocs.io/en/stable/faq.html#i-am-seeing-a-added-status-for-an-unchanged-file

**Comment by Oberlurch3000** [comment]
Ok, thank you!

**Comment by ThomasWaldmann** [comment]
@Oberlurch3000 it will:
- not be super fast because you lost the "files cache", so it will read, chunk, hash all files (because it can not determine they are unchanged)
- not have to compress/encrypt/store any chunk that already is in the repo, because it will notice after the hashing step that the repo already has the chunk
