### ISSUE TITLE
--match-archives defaulting to id: (not sh:)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7573]
for borg2, `-a` (aka `--match-archives`) defaults to `id:` (identical) as matching style, not `sh:`.

introduced by #7028.

discuss differences / pros / cons.

**Comment by ThomasWaldmann** [comment]
From borg2 help:
```
Shell-style patterns, selector sh:

This is the default style for --pattern and --patterns-from.
Like fnmatch patterns these are similar to shell patterns.
The difference is that the pattern may include **/ for matching zero or more directory levels,
* for matching zero or more arbitrary characters with the exception of any path separator.
A leading path separator is always removed.
```

**Comment by ThomasWaldmann** [comment]
From borg 1.2 help:
```
-a GLOB, --glob-archives GLOB:
only consider archive names matching the glob. sh: rules apply, see “borg help patterns”.
```

**Comment by ThomasWaldmann** [comment]
So, the difference between id and sh is:
- `id:` pattern is just taken as is for an identical string match
- `sh:` pattern uses wildcards: `*`, `**/`
- `sh:` pattern treats path sep (`/`) specially
- `sh:` our `shellpattern.translate()` also processes `[...]`

We do not have path seps in archive names, so these and also the `**/` doesn't make a difference.

Note: when using wildcards in shell scripts, one needs to be careful so that the shell does not expand them before giving them to borg. That behaviour is outside of borg.

**Comment by ThomasWaldmann** [comment]
@m3nu @sophie-h (and everybody else) ^

**Comment by PhrozenByte** [comment]
Pro requiring `sh:`: Since positional arguments for archives were mostly dropped, I'd argue that matching a single archive by its exact name is the most common use case for this option.

Pro requiring `sh:`: Since the option was renamed to *match* archives (not *glob* archives), globbing is unexpected.

Pro requiring `sh:`: Advanced stuff (like globbing) should always require the user to explicitly enable it.

**Comment by bof** [comment]
I was surprised needing the extra sh: for pattern matching, so I'd vote for the convenience of leaving it out / being default.

Any non-novice unix CLI jockey should know that where he gives patterns to commands, they must be quoted - and that `sh:*` _usually_ needs no quoting because by serendipity current working directory has no file named sh:it, is quirky...

The other way round, it would take archive names with verbatim `*` in their names (is that allowed?) to make the id: match prefix be really needed.

**Comment by ThomasWaldmann** [comment]
--match-archives (aka -a) is being extended to not only match on the name, but also on the archive ID (aid:), on the user name (user:), on the host name (host:).

The latter are all non-wildcard matches, so guess it is fine for the match on the name also being a non-wildcard match. Name matching (name:) can now optionally also given as name:myarchivename, but as that is the default, "name:" can be left away.

Since the introduction of the "archive series" feature, names do not need to be unique anymore. To the contrary: it is recommended to use the same name when appropriate (when creating a new archive of the same source data set) and let borg track the timestamp, the user, the host as separate metadata.

**Comment by ThomasWaldmann** [comment]
Considering the above, I am closing this as "nothing to change here".
