### ISSUE TITLE
borg 1.1.x to 1.2.x recommendations questions

### ISSUE THREAD

**Issue by ledufff** [borgbackup/borg#7633]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

1.1.14

## Describe the problem you're observing.
Hello,
I am reading in the docs that it is recommended to run borg create, borg prune, and borg check before upgrading.  And I have some questions about that.

Is this supposed to be done in that order?  Create,  prune, and check?
Why is borg check not enough?
Can borg prune be skipped?  why is it suggested to prune at least once? 
should I run borg check, or borg check --verify data?

Thanks!

**Comment by ThomasWaldmann** [comment]
create, prune, check: the only reason these are part of the upgrade docs is to confirm that the repo is **working normally within your current setup (with borg 1.1.14)** before the upgrade is done.

I just wanted to avoid getting issue reports like "borg 1.2 upgrade broke my repo" for cases when the repo was already broken (or having issues) before the upgrade.

so, if you don't usually run `borg prune`, you can also leave that step away.

if you are sure that `borg create` worked flawlessly until recently (e.g. by checking the logs), you can leave that step away also.

running `borg check REPO` is recommended in any case to make sure the repo is fine **now**.
You can run it without `--verify-data`, that will already do a lot of checks.

`--verify-data` is an option for situations where one wants to make sure that all the chunks actually contain what they are expected to contain and that would even find e.g. chunks maliciously corrupted by a client-side attacker who has access to the borg key. if your repo is rather small, you can use it, but if your repo is big and there are no special circumstances asking for this option, i'ld rather not use it as preparation for the upgrade because it would take much longer than the normal `borg check`.

So, usually it is `borg check -v --progress REPO`.

**Comment by ledufff** [comment]
Wonderfully explained,  thanks!
