### ISSUE TITLE
file list

### ISSUE THREAD

**Issue by iomari** [borgbackup/borg#7718]
greetings,
I'm using v2beta. How can I use a list of files/folders as my input?
ex: --files filelist.txt

**Comment by ThomasWaldmann** [comment]
If you have a complete list of all fs objects you want to back up (all files and all directories and ...), you can use `--paths-from-stdin` (read the docs about it!).

Otherwise you can use `--patterns-from` and you must read the patterns help first.

To try whether it does what you want, use `borg create --list [--dry-run] ...` to get a full list of what it backed up / what it excluded.

**Comment by iomari** [comment]
thanks
