### ISSUE TITLE
Quota with a central repository server

### ISSUE THREAD

**Issue by Ravinou** [borgbackup/borg#7757]
Hi there! 
I'm currently working on improving [BorgWarehouse](https://borgwarehouse.com). In its v1, BorgWarehouse uses a unix user for each new repository. **This works very well.**

**However**, unix user management can quickly become cumbersome and this is an **intrinsic limit** to the possibility of offering BorgWarehouse as a docker container **as many users ask me to do**.

As a result, @apiening [suggests](https://github.com/Ravinou/borgwarehouse/issues/47) that I opt for a model with a single Unix user, [as recommended in the documentation here](https://borgbackup.readthedocs.io/en/stable/deployment/central-backup-server.html). 

But as I started working on this solution, I remembered a problem I'd come across. **I can't figure out how to apply a quota to each repository**.

In fact, with the method proposed in Borg's documentation, an SSH key is unique, and in any case, the first match of the public key will invalidate any other lines containing it later on. You should therefore use the following method: _"You can allow a client to access several separate directories by passing multiple `--restrict-to-path flags` "_.

But what about the quota option? 

It seems that **only the last occurrence of the flag is taken** as quota for all repositories corresponding to this SSH key.

For example, the quota for this `SSH_PUB_KEY` **will always be 1G for all path**. Previous flags are ignored : 
```
command="cd /home/borgwarehouse/repos;borg serve --restrict-to-path /home/borgwarehouse/repos/a7035047 --storage-quota 10G --restrict-to-path /home/borgwarehouse/repos/a7035048 --storage-quota 1G",restrict ssh-ed25519  SSH_PUB_KEY
```

Is there a solution for this ?

Thanks in advance.

**Comment by ThomasWaldmann** [comment]
Guess you'ld need to use a different ssh key per repo (even if it is the same client-side user).

**Comment by Ravinou** [comment]
@ThomasWaldmann thank you for your answer. If there is no solution to this problem then I will have to choose a direction for BorgWarehouse :/ . Thank you for answering me anyway and I think it would be interesting to clarify the documentation about this flag concerning quotas. 

You can close this issue if there is no solution. Thanks.

**Comment by apiening** [comment]
I personally haven't used quotas for my centralized backups before, but I do understand how important this is if the central backup service is provided to external users for example.
However, I'm not sure how much of an issue this really is in most use cases. If someone wants to backup a system, he would probably use the root user for this if he wants to backup system folders as well. Then the public key of the root user of this system would be used. Another system, would have another key. If a normal (non root) user would do backups, then he would naturally have another SSH identity.
As long as SSH identities would be treated as users, everything should be fine and quotas could be applied as well. Or do I miss something?

Since it is supported to backup different folders to one borg repository, from my perspective it is more of an edge use case to give one user (SSH identity) access to more than one borg repository. Is this really a requirement? What would the benefit be?

From my understanding, it is possible to give one SSH identity access to multiple repos (see https://borgbackup.readthedocs.io/en/stable/deployment/hosting-repositories.html). The only restriction I see is that the quota value applies to every repository:

> The storage quotas of repositories are completely independent. If a client is able to access multiple repositories, each repository can be filled to the specified quota.

This might be confusing for users if no appropriate explanation is given. Maybe it is a better option to stick with one repository per identity.

**Comment by ThomasWaldmann** [comment]
> @ThomasWaldmann thank you for your answer. If there is no solution to this problem then...

Well, guess I just gave you a solution to what you described in the first half of the top post, so not sure why you are saying "if there is no solution..."?

About the second half of the top post: guess that is not implemented yet, but guess one maybe could allow giving multiple quota also, resulting in a somewhat fragile construction concerning that the order of quotas given would need to match the order of paths given.

**Comment by Ravinou** [comment]
> Well, guess I just gave you a solution to what you described in the first half of the top post, so not sure why you are saying "if there is no solution..."?

Sorry, I misspoke. By _"if there is no solution..."_, I just wanted to confirm that I had understood how flags work and that I was using them correctly. So there's no solution because that's the way Borg works and that's just what I wanted to be sure of.

> About the second half of the top post: guess that is not implemented yet, but guess one maybe could allow giving multiple quotas also, resulting in a somewhat fragile construction concerning that the order of quotas given would need to match the order of paths given.

I agree with @apiening . However, such a feature would make Borg even more complete and would allow BorgWarehouse to deal with all scenarios. In my case, for BorgWarehouse, I will settle for preventing the reuse of an SSH key in the first instance but if you enable the use of the quota flag for each repo, please keep me informed here, it would be perfect !!
