### ISSUE TITLE
get rid of csize

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#776]
Having csize (compressed size) in the item's chunk list is a problem:
- as found in PR #770: recompressing chunks requires changing csize everywhere
- multithreading branch: waiting for csize requires that strange looping

Now: chunks = [(id1, size1, csize1), (id2, size2, csize2), ...)

Should be: chunks = [(id1, size1), (id2, size2), ...]

id is a direct function (id_hash) of the chunk contents, size is a direct function (len) of chunk contents also.

But: csize depends on the chunk AND the compression algorithm / level, and the latter might change afterwards.

This affects:
- chunk lists in items stored in archives
- maybe: chunks cache/index/hashindex (on-disk format, in-memory format, C/Cython/Python code) - we could either drop it there also or add it there at cache build time.

**Comment by enkore** [comment]
Maybe it's better to leave the field there, but just ignore it. This way we could make this a non-breaking transition.

Removing size from the chunk ID lists... hm, that has turned out quite useful in a few places.

Since csize is a handy figure for stats I think the best approach would be to have the Cache handle it, so no change there. As I mentioned in #770 all the stats-related commands already use the Cache anyway.

---

When we are considering really breaking ways of doing chunk lists, then we should also think about session keys and how these two can work together. So a really simple idea would be to use what's now csize and use that as a SKID (session key ID). This could be as simple as an index into a list of session keys in the repokey/keyfile. Now this has the obvious drawback again that the SKID isn't really a function of the chunk. But we could argue, that this is much less of an issue for an operation like recompress, since it can just use the same session key to encrypt the recompressed chunks as was used for the old chunks.

**Comment by enkore** [comment]
To "summarize" above convoluted post, here's the gist of the proposal (with some changes from above!)

* We introduce **data encryption keys** (DEKs, what I called session key above and then extended to multiple "sessions", so that "session key didn't make much sense").
  * DEKs are stored in the key file (i.e. in the repokey as usual) as a list of tuples which look something like `(algorithm, IV-CTR, key)`
    * Everything after element 0 in the tuple is defined by element 0, the algorithm, including the length of the tuple
  * DEKs are used to encrypt chunks.
  * Which DEK is used for a chunk is encoded *in the chunk itself* as a DEK-ID in plain text
  * Using DEKs changes nothing about chunk identity. Business as usual.
* We slightly redefine the field formerly known as `csize` into ð.
  * ð >= 0 <=> compressed size of chunk (legacy)
  * ð == -1 <=>  the chunk uses DEKs (this is simply to be easily detect this for the point below this one)
* `csize` (for less confusion might rename to compsize or something other) is now only a concept used by the Cache to indicate compressed size of a chunk known to the Cache.
* We can add detection of DEKs to Borg now, so that Borg 1.1 etc. can fail gracefully when trying to read archives that make use of DEKs.
* Multiple DEKs can be used to have fully independent parallel en/decryption
* DEKs are created on-demand, if the demand can be met with existing DEKs they are used. (So we don't create 4 ... 32 [number of cores] *new* DEKs for each `borg create`)

#### Type of ð

After looking at _hashindex.c I'd say that ð is signed (int32_t).

### Practical effects and compatiblity

* [x] Old archives are unaffected
* [x] Chunks deduplicate as usual, independent of whether DEKs are used or not!
* [x] New archives can be recompressed *without* disturbing the supposedly final archive ID
* [x] Multithreading is easier
* [x] Possible to use alternative algorithms for data encryption in the feature without re-encrypting all old data
   * This even works for chunks that are not referenced by chunk id lists, e.g. archive metadata itself*
* [x] Don't make the same mistake twice: ð == -1 merely indicates that it's not csize anymore
  * Only stuff that has a direct relation to the chunk contents go into chunk id lists
    * chunk identity, chunk length
* [x] Can do without new Repository APIs
  * csize handled completely by Cache
  * Cache updated on writes
  * Cache rebuild: just read all chunks for now
    * Can add Repository API to just read chunk size later
    * Cache rebuilds are rare

**Comment by enkore** [comment]
While looking for CTR-related issues I saw #22, which is also fixed by DEKs (since the repokey can't be manipulated by an attacker, because it's secured by a HMAC).

**Comment by ThomasWaldmann** [comment]
btw, I'ld prefer "getting rid of csize" (make csize value unused) and "changing crypto" (repurposing unused csize value maybe) in 2 separate tickets.

**Comment by verygreen** [comment]
Having read this and the 770, I wonder if it really needs to be such a breaking change as it's portrayed?
Essentially csize is already a write-only value in the repo and is never actually used (if not in 1.0.x, that should be an easy change that does not change repo format).

Since it's never used, step 2 - recompress does not need to update it anymore (if the code has recompress in it, it is new enough to also know to never use csize anyway).
Recompress is different enough from recreate that it's worth having it as a separate thing - it would operate on whole repo recompressig chunks and stuff, nothing to do with individual archives. (hm, I guess here's the breakage - serverside recompress would not update client side cache so the numbers become "off" until next cache rebuild).

step 3 - csize field becomes free for other use eventually. In order to maintain back compatibiilty with older repos if recreate is impractical, since original csize is signed and could have never been negative or 0 in the past, the new usage might be strictly in the negative space and then it would be quite easy to tell apart old usage from new.

For the cache out of sync issue - perhaps if server is forced to maintain a cache of chunks (not files) alongside the repo - that would make the issue of cache resync much easier? Since all writes go through server it should be able to do that. Local updates (no server) would update the cache stored in the repo itself. To sync an out of date cache - perhaps something like rsync protocol could be used to only transfer (hopefully not too big) differences between the two - much faster than making server to iterate over entire chunk space.

**Comment by ThomasWaldmann** [comment]
I though about "size" and whether we can remove it from chunks list:
- we have the total file size in item metadata since recently, so we do not need sum(chunk sizes) any more to compute file length
- BUT: if we lose (multiple) chunks in the repo, we need the size information from the chunks list to compute replacement chunks of correct size.

So, we can not remove "size" from the chunks list entries. I am updating the posts above to remove that idea.

**Comment by enkore** [comment]
Just close this and continue in the other ticket, since most stuff here is outdated?

**Comment by ThomasWaldmann** [comment]
You mean #2313? (as I already said there, I'ld like this to be broken into separate steps)

**Comment by ThomasWaldmann** [comment]
Continued / superceded in #2357.
