### ISSUE TITLE
Hash collisions (again) - universal solution for everyone?

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#7765]
Let me share some thoughts.

There has been much discussion (for example #170 #4884) about eliminating the non-zero probability of a SHA hash collision.

The developers here https://github.com/borgbackup/borg/issues/4884#issuecomment-566706071 felt that completely resolving the issue would have too much of an impact on Borg's performance, and implemented a solution to mitigate the risk, but still not definitively addressing the issue #181
Additionally (as far as I understand) comparing chunk size seems useless when using `--chunker-params fixed,4194304`

On the other hand, there are other options in Borg that also affect overall performance, but they do exist (for example, `borg check --verify-data`).

The key to the satisfaction of all parties (proponents and opponents of collision awareness https://github.com/borgbackup/borg/issues/4884#issuecomment-568159478) is **OPTIONALITY**

Additional benefits are here: https://github.com/restic/restic/issues/1620#issuecomment-545924018

Why not add this functionality as an **OPTIONAL TO CHOOSE**? (for example `--verify-hash-collision`). Just a warning that it affects (even heavily affects) performance. Such warnings are already in the documentation and are sufficient for users.

It is enough even [here](https://borgbackup.readthedocs.io/en/stable/faq.html#how-probable-is-it-to-get-a-hash-collision-problem)  to add the information: "Attention! completely eliminate this problem by enabling --verify-hash-collision, but at the cost of performance degradation"

What do you think?

**Comment by ThomasWaldmann** [comment]
Before I'ld feel motivated to continue the hash collision discussion, I'ld like the following answers:
- assuming that data1 and data2 are not identical, but have the same hash, how would you store data1 and data2? the hash is the key to a key/vale store and of constant size, so that is not technically possible IMHO.
- why would we even deal with trying to solve this issue if users have much bigger and much more probable problems?

**Comment by RonnyPfannschmidt** [comment]
@git70 turning hash collision from improbable to impossible is commonly not a worthwhile endeavor as the risks and complications the solution requires may offset the utility in relation to the gain

Modern cryptographic hashes tend to be good for current content addressed storage needs at a wide scale

**Comment by enkore** [comment]
Borg should also check for fixed points in the encryption and add padding to avoid them.

**Comment by ThomasWaldmann** [comment]
@enkore not sure what you mean, but sounds like a different topic - can you make a separate ticket about it?

**Comment by someone-somenet-org** [comment]
@ThomasWaldmann: Imho the only useful thing would be to allow users to select something else than sha256, like sha512, sha3 or something completely different during repo creation.

@git70 - @BTC-Wallet: the chance of colliding borg hashes for the wallet backup is the same as the chance that somebody randomly generates your private key for your btc - its afaik both 1 in 2^256. (Good luck sleeping now ;)

**Comment by ThomasWaldmann** [comment]
@someone-somenet-org The borg hashindex works with a fixed width of the key (256bits), so it is not easy to make that dynamic.

**Comment by ThomasWaldmann** [comment]
Closing this, see https://github.com/borgbackup/borg/issues/7765#issuecomment-1685031045 .

**Comment by mrichtarsky** [comment]
Sorry for commenting in this long-ago closed issue. I was just comparing backup tools and also wondering how they handle the potential hash collision when deduplicating. FYI, your FAQ has me convinced and I'm glad that it is explained there.

However you wrote:

> Before I'ld feel motivated to continue the hash collision discussion, I'ld like the following answers:
> 
> assuming that data1 and data2 are not identical, but have the same hash, how would you store data1 and data2? the hash is the key to a key/value store and of constant size, so that is not technically possible IMHO.

I think the point never was how to solve this technically and store the data. From my (certainly limited) understanding, the collision should be detected and then *the backup process immediately stops* (printing out the two lottery tickets).

> why would we even deal with trying to solve this issue if users have much bigger and much more probable problems?

Not sure what you then meant here by "solving". In my mind, if it's just a bytewise compare of the two chunks and this can be done comfortably within the existing logic, it might be worth adding something like the suggested `--verify-hash-collision`. There might be environments where people want to use Borg and need to see that it handles this case as well, at least with an error on backup. If by solving you meant handling the hash collision and changing all the internal data structures, that's certainly a non-starter. But it's not needed since the chances of collision are so astronomical.

I agree that adding that option would have psychological benefits, just like you always should check your return codes (perhaps even if a call currently has no failing return codes, it can have in the future).

However, in that case I would also add to the docs:

> If `--verify-hash-collision` reports a hash collision, DO NOT open a bug for it. The likelihood that it was caused by a hardware error or file system corruption on your machine are many orders of magnitude higher than a real hash collision we can fix.

**Comment by mrichtarsky** [comment]
P.S.: For completeness, ZFS deduplication also has a `verify` option:

https://docs.oracle.com/cd/E19120-01/open.solaris/817-2271/gjhav/index.html

> If the property is set to verify and two blocks have the same signature, ZFS does a byte-for-byte comparison with the existing block to ensure that the contents are identical.
