### ISSUE TITLE
How to automatize with cronjob? How to pass the passphrase?

### ISSUE THREAD

**Issue by pcuinty** [borgbackup/borg#779]
Sorry for beeing a novice. Running borg maually works fine, but how do I automatize that with Cron where I cannot enter the passphrase? I found nothing about that in the manual, only storing the key inside or outside the repo. I see that this is more a general understanding problem of mine. I would be thankful if you could point into the right direction in order to understand the concept ( maybe a link ).

Thank you.

**Comment by enkore** [comment]
BORG_PASSPHRASE environment variable

http://borgbackup.readthedocs.org/en/stable/faq.html?highlight=BORG_PASSPHRASE#how-can-i-specify-the-encryption-passphrase-programmatically
http://borgbackup.readthedocs.org/en/stable/usage.html?highlight=BORG_PASSPHRASE#environment-variables
http://borgbackup.readthedocs.org/en/stable/quickstart.html?highlight=BORG_PASSPHRASE#repository-encryption

**Comment by pcuinty** [comment]
ok, now I feel a little ashamed....how could I miss that? Thank you very much

**Comment by pcuinty** [comment]
Is storing the actual passphrase in plain text inside the script a good idea? I kind of concerns me. I know I can user the keyfile method without password, but then I have to securely back up my keyfile somewhere. What would be the best practice here?

**Comment by enkore** [comment]
There is no single best practice here. Since it's automated the options to protect the keys are somewhat limited. If you're concerned with offline attacks (someone steals the computer and the backup drive), then you'll want full-disk encryption for the place where the key file is.

I do pull backups and need to store the key only on one machine. It already uses FDE, so I just make the backup scripts etc. r-- --- ---, so no one can read them except root.

**Comment by ThomasWaldmann** [comment]
Note: there is a ticket about using keyrings: #392

**Comment by ThomasWaldmann** [comment]
I am closing this now (this is documented and there also is this keyrings ticket), so nothing to keep here.
