### ISSUE TITLE
Having multiple passphrases for the same repo in borg 1.2 / 2.0

### ISSUE THREAD

**Issue by kalsan** [borgbackup/borg#7812]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

Question asked independently for borg 1.2 and 2.0

## Question

I'm looking for a way to register multiple passphrases for a single borg repo, similar to what is possible with a LUKS encrypted volume. The idea here is to have a random password stored on the client to be backed up, as well as a personal password that I remember well. This way, I don't need to put my personal password on a client machine in plain text. And, I don't need to backup the key stored on the client, because I can use the personal password to recover the data. In short, the random password would be used to backup, and the personal password in case of the loss of the client.

The help article https://borgbackup.readthedocs.io/en/stable/usage/key.html states: "If a key file is found in $BORG_KEYS_DIR, borg key import overwrites it; otherwise, borg key import creates a new key file in $BORG_KEYS_DIR."

This kind of sounds like what I'm looking for, but, honestly, I'm scared to try it without prior confirmation here that this is not a misunderstanding.

Can this be done and if so, what is the recommended procedure? Does this work both under borg 1.2 and 2.0?

Thanks in advance!

**Comment by ThomasWaldmann** [comment]
Having multiple passphrases for the same borg key is not implemented (yet?).

I somehow see your point, but I think you would be (also for other use cases, not just for borg) be better off with a password manager. Only for the borg repository that backs up the password manager's database, you need to solve differently, of course.

But always keep in mind that you need to back up **both** passphrase **and** borg key, that's why we have `borg key export ...`. That problem would not be solved by offering multiple passphrases per key.

If you want to experiment with keys, passphrase and backup/restore of the key, maybe try it first with a fresh repo, not your production one.

**Comment by kalsan** [comment]
Hi Thomas and thank you for your fast answer!

TBH I'm so in love with borg (amazing work btw :heart: ) that I've recommended it to tons of people and back up literally everything with it. This includes my password manager, so I am indeed affected by this situation.

Am I assuming corretly that when using the passphrase mode, only the passphrase would be required if the client computer goes up in flames?

Nice idea with the experimental repo.

Best,
Kalsan

**Comment by ThomasWaldmann** [comment]
No, that's incorrect. One always needs the passphrase-protected key **and** the passphrase to unlock (decrypt) it.

**Comment by kalsan** [comment]
But isn't the keyfile stored at the backup server, not at the client?

**Comment by ThomasWaldmann** [comment]
keyfile mode: key is stored on the client (usually in home dir)
repokey mode: key is stored inside the repo (in repo config)

But it does not matter where it is stored when I say it is needed.

There could be circumstances for both modes leading to the key getting lost / becoming damaged and if you do not have the key any more, you can not decrypt the data in the the repo.

That's why each time you use it `borg init` recommends to make a backup of the key **and** the passphrase.

**Comment by kalsan** [comment]
Excellent, thank you very much. I'll take away that multi-password will not be supported and thus an independent key and keyfile backup is required.

Have a nice day!
