### ISSUE TITLE
Create an archive only if something changed

### ISSUE THREAD

**Issue by debuglevel** [borgbackup/borg#7917]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

As far as I searched, there was no such issue.

## Is this a BUG / ISSUE report or a QUESTION?

Feature Request :)

## Describe the problem you're observing.

Situation:
I'm backupping a machine where only very occasionally something changes (every 2 weeks, 1 TB of virtual machines are dumped).
(The changes are very big and the DSL upstream is rather slow - it actually takes a few days to upload it, so I've got `borg` in some `while true do borg` to handle a daily DSL reconnect).
Once borg finished uploading everything, the while loop goes crazy and creates a lot of archives :D

This works, but lefts me with many useless archives. The easiest thing *for me* would be a `--create-archive-only-if-something-changed` switch. But I'm not sure if this is really something that `borg` should handle.

**Comment by ThomasWaldmann** [comment]
borg always does full backups (which contain all metadata and content data of the source files, no matter whether they have changed or not) and it does not compare against previous archives to detect change.

There is only one place where borg checks for "changed" and that is the files cache's "is the file unchanged" check and that refers only to the content data of the file (to avoid reading/chunking/hashing the content if the file is known-unchanged) and not to the metadata (which are always read and store, no matter what).

So guess it is unlikely that we could implement such a feature.

**Comment by ThomasWaldmann** [comment]
What you can do:
- you can use prune with appropriate settings to get rid of excess backup archives (be careful when playing with that, alway use `borg prune --dry-run --list ...` first, so you see what will get deleted)
- in you while loop, you could break out of the loop when borg terminates with rc 0. that's better than nothing, but not perfect, because misc. circumstances can also lead to rc 1 (which are more difficult to qualify and need looking at the logs).

**Comment by debuglevel** [comment]
Thanks! Already guessed this is a job for a wrapper :)
