### ISSUE TITLE
What happened to the backup "series" feature?

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#7930]
There was an extended discussion on a feature that would allow the use of something more unambiguous than prefixes to identify a series of backups on which commands like `prune` could be applied. It was dubbed "series" at the end of #948. It would seem much more reliable to me to have this feature for handling different series' of backups in apps like Pika and Vorta.

Somehow the issue got closed. Is the feature still on the table for 2.0?

**Comment by sophie-h** [comment]
> So I thought about just using the hash (object ID) as the archive identifier and either not having a name or having it more like a comment in the metadata.

Yes, that's what I imagine for borg2 combined with archives being part of a "series."

**Comment by ThomasWaldmann** [comment]
Did some experiments:
- for the archive NAME, borg now also accepts id:<archive_id> and then loads the archive by-id
- borg list shows the archive id since quite a while anyway
- `-a PATTERN` (which is widely used by commands that are useful for single or multiple archives) is a bit problematic now as the name only refers to the series name now and and as that is the same within a series it isn't suitable to select one or a few archives of a series.
- also, `-a` matching interprets `id:...` in a completely different way (doing an identical match on the name), so guess need to extend/rename that so it can also do a match on archive IDs.
- thus I also added NAME to these commands, so one can use `id:<archive_id>` with that to select a single archive
- need to be a bit careful, as we still need to work with old borg 1.x repos until everyone has borg-transferred their stuff
- guess borg transfer will need some way to create a "series" from a match on the archive name. alternatively, first do the transfer with names as they are and then have a rename command that does the trick.
