### ISSUE TITLE
unchanged files are saved - solved

### ISSUE THREAD

**Issue by e-ferrari** [borgbackup/borg#7931]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
1.2.4

#### Operating system (distribution) and version.
SLES 15 SP5

#### Hardware / network configuration, and filesystems used.
image files from qemu virtual machines reside on an OCFS2 SAN and are saved on a CIFS-mount (NetApp).

#### How much data is handled by borg?
~ 5TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create --list --stats ::{now} /mnt/domains/reflinks

## Describe the problem you're observing.
I have some (~ 15) virtual machines (qemu) on a server. Some run, some don't.

Every evening i create a snapshot of the directory (with ocfs2-tools) where the image files reside, either running or not. Snapshots reside under /mnt/domains/reflinks.

Then borg saves the snapshotted files to the NAS.

After borg is finished snapshots are removed and recreated next evening:

```
M /mnt/domains/reflinks/btrfs.raw
M /mnt/domains/reflinks/vm_amok.raw
M /mnt/domains/reflinks/vm_check-mk.raw
M /mnt/domains/reflinks/vm_crispor.raw
M /mnt/domains/reflinks/vm_crispor-server.raw
M /mnt/domains/reflinks/vm_dietrich.raw
M /mnt/domains/reflinks/vm_docker2.raw
M /mnt/domains/reflinks/vm_docker.raw
M /mnt/domains/reflinks/vm_encore.raw
M /mnt/domains/reflinks/vm_geneious-license-mcd.raw
M /mnt/domains/reflinks/vm_geneious.raw
M /mnt/domains/reflinks/vm_pathway.raw
A /mnt/domains/reflinks/vm_photoshop.raw
d /mnt/domains/reflinks
```

As i decribed some vm's run, some don't. That means that the image files of the not running vm's don't change. So, in my eyes, they don't need to be saved by borg again because they are the same as the day before. But as you see borg said that all files are modified (M), although the vm's didn't run. Why?

I read https://borgbackup.readthedocs.io/en/1.2-maint/faq.html#i-am-seeing-a-added-status-for-an-unchanged-file and https://borgbackup.readthedocs.io/en/1.2-maint/faq.html#it-always-chunks-all-my-files-even-unchanged-ones, but to be honest i don't understand these two links.

What means "the cache entries’ ttl values of files that were not “seen”". What means "seen" ? Borg does not see the file ? Didn't recognize it ?

"So, for example, if you do daily backups of 26 different data sets A, B, C, …, Z on one machine ..." What is a "data set" ? A file ? An archive ? Anything else ?

Is it possible that when the snapshot is created the next evening again the files to be saved in the snapshot get a different inode ? And because of that borg thinks the files have to be saved, although they didn't change ? Shall i use "--files-cache=mtime,size" ?

"It intentionally excludes files that have a timestamp which is the same as the newest timestamp in the created archive." The timestamp of the file to be saved is compared to what ? To the same file in the archive ? Or to all files in the archive ?

Help needed ...

Thanks.

Bernd

**Comment by ThomasWaldmann** [comment]
If you just snapshot the disk file of a running VM, you need to be aware that the best you can expect in the backup is a state as good as if the machine crashed (like power loss or hw reset). If you want a good backup of a guaranteed consistent state, you need to shutdown the VM before taking the snapshot.

"M" means the file has changed compared to the last time borg has seen it (has backed it up) and thus it is read, chunked, hashed again and all different chunks will be added to the borg repo. VM disk files change all the time when the VM is (or was) running since the last backup... - borg uses the ctime, size and inode number to determine a change.

"data set": the source files that are being backed up in one borg run.

You can use `ls` (see man page) to check inode, ctime, size of the files if you suspect there is something wrong. The borg FAQ also lists a borg option to debug the files cache behaviour (to see why borg thinks it is "M").

The newest timestamp is determined by looking at all files in the data set / at all source files.
The FAQ has a workaround in case it frequently drops a big file from the files cache: just touch some dummy file in the data set just before doing the snapshot, so that this file likely will have the newest timestamp (and not some big vm disk file that takes ages to back up).

**Comment by e-ferrari** [comment]
> If you just snapshot the disk file of a running VM, you need to be aware that the best you can expect in the backup is a state as good as if the machine crashed (like power loss or hw reset). If you want a good backup of a guaranteed consistent state, you need to shutdown the VM before taking the snapshot.
I'm aware of that, nevertheless thanks for the hint

> You can use ls (see man page) to check inode, ctime, size of the files if you suspect there is something wrong. The borg FAQ also lists a borg option to debug the files cache behaviour (to see why borg thinks it is "M").
I found it: --debug-topic=files_cache

Thanks for your very quick and clear answer. Awesome. There are only a few forums/mailing lists where i get such high quality answers.

Bernd

**Comment by e-ferrari** [comment]
Hi,
i'm saving now with the following commandline:
``create -v --debug-topic=files_cache --files-cache=mtime,size,inode --list --stats ::{now} $REFLINK_DIR``
Nevertheless image files of not running vm's are treated as being modified and are saved.
E.g.:
``KNOWN-CHANGED: file mtime has changed: b'/mnt/domains/reflinks/vm_encore.raw'
M /mnt/domains/reflinks/vm_encore.raw``
The timestamps of the image files by borg are like that:
``FILES-CACHE-UPDATE: put FileCacheEntry(age=0, inode=858797445, size=536953094144, cmtime=1690555535000000000, chunk_ids='[117827 entries]') [has mtime] <- b'/mnt/domains/reflinks/vm_encore.raw'``
What is "cmtime" ? changed and modified ?
And can i calculate the current date/time from this timestamp ? I tried Unix epoch, but the results were much in the future ...

Bernd

**Comment by ThomasWaldmann** [comment]
It is called cmtime inside borg, because it is one variable and can contain either ctime or mtime - usually it is ctime (default), but in your case it will be mtime.

The timestamps are UNIX timestamps in nanoseconds.
