### ISSUE TITLE
Interleave modifications, additions, and removals in 'borg diff'

### ISSUE THREAD

**Issue by Ape** [borgbackup/borg#797]
I thought about this when implementing #783. The current version of `borg diff` always shows first the file modifications, then file additions, and finally removals. For me it would be easier to follow the list of changes if all of the different change types would be interleaved obeying the archive order.

See the example below. Note that the real-life change lists may be a lot longer with lots of changed in one folder.
```
old:
+234.5 kB -319.7 kB folder1/changed_file
+234.5 kB -319.7 kB folder2/changed_file
+234.5 kB -319.7 kB folder3/changed_file
added     455.61 kB folder1/new_file
added     455.61 kB folder2/new_file
added     455.61 kB folder3/new_file
removed     2.71 kB folder1/removed_file
removed     2.71 kB folder2/removed_file
removed     2.71 kB folder3/removed_file
```

```
new:
+234.5 kB -319.7 kB folder1/changed_file
added     455.61 kB folder1/new_file
removed     2.71 kB folder1/removed_file
+234.5 kB -319.7 kB folder2/changed_file
added     455.61 kB folder2/new_file
removed     2.71 kB folder2/removed_file
+234.5 kB -319.7 kB folder3/changed_file
added     455.61 kB folder3/new_file
removed     2.71 kB folder3/removed_file
```

#783 should be merged before implementing this to avoid conflicts.

**Comment by ThomasWaldmann** [comment]
the problem here might be that borg has no "directory entry list" data in the archive, so while processing items, you do not know in advance what items are coming for a specific directory. Nor can you easily know when you have finished one directory.

there is a hack in the code that assumes a specific traversal method at create time and then detects the directory level change at extract time. this was one of the things breaking after the multithreading changes.

so I'ld prefer not interleaving rather than adding more such hacks that just cause troubles.

**Comment by Ape** [comment]
Perhaps we could process all of the items and only after that start producing output. The diff command runs pretty quickly on my machine even with over 60 GB of data in the snapshots. This feature could be optional with a command line switch.

**Comment by enkore** [comment]
You can work with the assumption that paths are in-order and grouped by parent directory. The approach would look something like this:

```
for item1, item2 in zip(item iters):
  if path1 > path2:
    while path1 > path2:
      output(path1 deleted in path2)
      advance_only_iter1
  # analogous for path1 < path 2
  if path1 == path2:
    # detailed compare
```

IOW instead of using the "matching orphans" approach keep the two item-iterators synchronized; if they become out of sync a file has been deleted or added and can be output this way in the correct order.

**Comment by ThomasWaldmann** [comment]
@enkore when doing multithreading, that grouping and ordering might go away. don't rely on it.

**Comment by enkore** [comment]
When doing MT in a way that doesn't uphold these assumptions, we'll need to rework the data model or a good amount of code anyway (stuff like extract relies on this). E.g. instead of a flat list a nested list that maps the directory structure.

It's maybe better not to increase this "code debt" any further than we must...
