### ISSUE TITLE
make compaction optional?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#809]
some people want a more strict "append only, do not change old repo files" behaviour than we have right now (as borg always tries to compact when it commits).

we could make the compaction optional (like `create --no-compact`, maybe also for `check`) and introduce a separate `borg compact` command.

borg would not modify existing files in the `repo/data` directory then, but just add new files.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/compare/master...oysols:delay_compact_segments

**Comment by enkore** [comment]
Maybe make it (append only repo) an option in the repository config file instead?

**Comment by ThomasWaldmann** [comment]
yes, as this relates to repo behaviour, a setting in the repo config might be best.

**Comment by enkore** [comment]
This works, but how where do we document it? Under the "Additional Notes" heading in docs/usage.rst?

**Comment by Ape** [comment]
How does this affect the ´delete´ command? Is the data freed if I delete old archives?

**Comment by enkore** [comment]
It can't do that. It will mark it as deleted in a new transaction, but it won't delete the data. In append-only mode the data/segments of old transactions are final.

Repository.destroy won't work either (it raises an exception, since it's an RPC method).

A setup where I think this is useful is the typical "central backup server" setup. The machines backup up to there, and if one of the machines get hacked, the attacker can't delete the backups. He can create new ones with wrong data, but those can be rolled back, deleted or simply ignored.

**Comment by ThomasWaldmann** [comment]
Discussion: can this change resolve #36?

**Comment by enkore** [comment]
It can't do that. It will mark it as deleted in a new transaction, but it won't delete the data. In append-only mode the data/segments of old transactions are final. If the transaction is rolled back (e.g. an attacker deleted all backups at 13:45, you look into the `transactions` folder and find the file `N` from 13:45. You go into the data folder and delete all segment files with a number >=N. Voila, everything is back to before 13:45. <--- this could be automated, but I don't think it should be.

Repository.destroy won't work either (it raises an exception, since it's an RPC method).

A setup where I think this is useful is the typical "central backup server" setup. The machines backup up to there, and if one of the machines get hacked, the attacker can't delete the backups.

**Comment by ThomasWaldmann** [comment]
Well, what you say means "it can". Why do you say it can't?

**Comment by enkore** [comment]
I edited my comment to clarify

**Comment by ThomasWaldmann** [comment]
ah :) so you agree it solves #36?

**Comment by enkore** [comment]
Yep. For some setups it's just not possible on a Borg-level (for example a central repo accessed over NFS or something like that).

**Comment by ThomasWaldmann** [comment]
as 1.0 is in ubuntu 16.04 (and debian), shall we tag this as "security" (because #36) and fast-track this to 1.0.1 (which might still get in, 1.1 won't get in I'ld guess).

**Comment by enkore** [comment]
It's all `if`-wrapped with self.append_only, and the default is False, I'd say this is a pretty safe changeset. I can rebase against 1.0-maint and open a PR.

**Comment by ThomasWaldmann** [comment]
fixed by merging https://github.com/borgbackup/borg/pull/817 (currently in 1.0-maint, soon in master)
