### ISSUE TITLE
BORGMATIC UPDATE

### ISSUE THREAD

**Issue by Natii9898** [borgbackup/borg#8121]
Good afternoon,
I wanted to ask the following: I normally install borgmatic with this command pip3 install --user --upgrade borgmatic. I have been realizing that the version is already in 1.8.8 but I have other installations, for example in 1.8.2. I wanted to know how I can update the version of borgmatic, what command can I use? Since the official website does not make the topic clear to me at all. Thank you

**Comment by witten** [comment]
The documentation on upgrading borgmatic is here: https://torsion.org/borgmatic/docs/how-to/upgrade/

And since it sounds like you're not yet using pipx to manage borgmatic, see this as well: https://torsion.org/borgmatic/docs/how-to/set-up-backups/#installation

But if any of that is unclear, I'd be happy to answer specific questions. In the future though, please file tickets about borgmatic at https://torsion.org/borgmatic/#issues rather than on the Borg issue tracker. Thanks!

**Comment by ThomasWaldmann** [comment]
Closing it here.
