### ISSUE TITLE
feature request: support for lzip compression

### ISSUE THREAD

**Issue by jolanouille** [borgbackup/borg#827]
it would be nice to have borgbackup offer lzip compression.

> The lzip file format is designed for data sharing and long-term archiving, taking into account both data integrity and decoder availability
  --  http://www.nongnu.org/lzip/

**Comment by enkore** [comment]
It's description reads like it's aimed at replacing the ".gz" or ".bz2" in ".tar.gz" for backup jobs, i.e. large, unencrypted archives (on unencrypted storage). It would need to be tested whether it has any advantage (compression ratio to speed or similar) over LZ4, zlib or LZMA. The description says it uses an LZMA-scheme so I'd expect similar performance.

The additional integrity checking is unnecessary in Borg, since (HMAC-)SHA-256 is already used for verifying data integrity (with a probability that isn't 100 %, but can't be reasonably written down other than 100 %, to detect errors[1]).

The recovery won't work for encrypted repositories - a flipped bit on-disk has an overwhelmingly large probability of completely garbling the whole block.

[1] Ask a calculator about `1 - 2^-256` ;-)

**Comment by ThomasWaldmann** [comment]
There is already #225 to discuss redundancy / error correction options.

I agree with @enkore that lzip does not seem to offer anything else new than that. And I guess we'll rather want error correction on a separate layer, not mangled into a specific compression method, so it can also be used without compression or with one of the existing compression methods.

Thus, I am closing this.

**Comment by ThomasWaldmann** [comment]
See also #1633.
