### ISSUE TITLE
Cancelled `borg info` invalidates cache, causing expensive sync on next operation

### ISSUE THREAD

**Issue by rrueger** [borgbackup/borg#8330]
**Have you checked borgbackup docs, FAQ, and open GitHub issues?** Yes

**Is this a BUG / ISSUE report or a QUESTION?** Question

**Borg Version** `borg 1.1.15`

**Operating system (distribution) and version.** Ubuntu 20.04

**Hardware / network configuration, and filesystems used.** Btrfs

**How much data is handled by borg?** 750PB (15000 Snapshots of 50GB, 120GB Deduplicated)

Everything is on the same host and disk (a directory is backed up to a borg repository on the same device, no other devices accessing the same repo)

## Describe the problem you're observing.

Cancelling (Ctrl-C'ing) a `borg info` command apparently invalidates the chunks cache, causing an expensive re-build on the next operation (e.g. create)

I don't know what happens under the hood, but `borg info` feels like it should be a read-only operation, and therefore should not be able to invalidate the cache.

Is this a bug, or expected behaviour?

I cancelled the `borg info` call because it was taking a long-ish time (~15 minutes)

Many thanks!

**Comment by ThomasWaldmann** [comment]
If you mean "archives in one repository" when saying snapshots, you should reduce that count to get better speed. Some operations are O(archive count), thus 15000 will make it 100x slower than 150.

You are using a rather old borg version and there were many fixes and improvements since then, maybe upgrade to the latest one in maintainer's ppa.

Important: read the changelog when upgrading, esp. about `borg compact` (>= 1.2.0) and the CVE-related upgrade procedure (>= 1.2.5).

**Comment by rrueger** [comment]
I understand. I will be changing to an OS with Borg version 1.4 soon

I will perform the following upgrade path as outlined in the Upgrade Notes

- Upgrade to newest `1.1.x` version (`1.1.18`)
- Upgrade to newest `1.2.x` version (`1.2.7`)
- Upgrade to newest `1.4.x` version (`1.4.0`)

Can I upgrade directly from `1.1.18` to `1.2.7` without the intermediate step of `1.2.5/1.2.6`?

**Comment by ThomasWaldmann** [comment]
@rrueger sorry for late answer.

Yes, you can directly go from 1.1.18 to 1.2.7/1.2.8 or even 1.4.x, but follow the upgrade steps detailed in the changelog.

**Comment by rrueger** [comment]
No worries!

Thank you very much
