### ISSUE TITLE
Set uid:gid at extraction or archive creation time?

### ISSUE THREAD

**Issue by mittster** [borgbackup/borg#8335]
Is it possible to set uid:gid at archive creation ot extraction time?

on production machine I have a folder with ```/folder/to/backup``` with ```user:apache``` recursive ownership

Running:
```
borg init --encryption=none name@serverip:/backupfolder/repo1
borg create name@serverip:/backupfolder::take1 /folder/to/backup
cd /restored/folder
borg extract name@serverip:/backupfolder::take1
```

changes ownership of the files in ```/restored/folder``` to  ```user:user```.

Is there an option to tell borg what numbers to use for uid:gid properties of files? chown after extraction is an option, but would rather not run in on a few million files.

Thanks

**Comment by infectormp** [comment]
Did you run `borg extract` as root?

**Comment by mittster** [comment]
Nope. Thank you, running as root solves the problem.

Is there also a way to set uid:gid at archive creation or extraction time?

**Comment by infectormp** [comment]
creation: It's possible only for data from stdin. [See ](https://borgbackup.readthedocs.io/en/stable/usage/create.html)`--stdin-user` and `--stdin-group`. 

[extraction](https://borgbackup.readthedocs.io/en/stable/usage/mount.html#description): 
> Borg’s default behavior is to use the archived user and group names of each file and map them to the system’s respective user and group ids. Alternatively, using numeric-ids will instead use the archived user and group ids without any mapping.

> The uid and gid mount options (implemented by Borg) can be used to override the user and group ids of all files (i.e., borg mount -o uid=1000,gid=1000).

**Comment by ThomasWaldmann** [comment]
@mittster it's not like borg is "changing the uid to user at extraction time".

It is rather the case that if you create a file (being logged in as user), the default owner of the file will be user also, automatically.

If something else is desired, that requires a chown/chgrp - but doing that "away from own uid/gid" is not allowed for a normal user. borg tries to do that, but silently ignores it if it doesn't work (as that is a usual thing when it has no root permissions). That's why it will be still user:user afterwards.

So, if you want that chown/chgrp working, run borg with sudo or after logging in as root.

Same thing might apply for other metadata also, e.g. for restoring ACLs.

**Comment by mittster** [comment]
@ThomasWaldmann Thank you for in depth explanation.
