### ISSUE TITLE
add a comment to an archive

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#842]
see: https://github.com/jborg/attic/issues/147

Would need 2 things:
- a --comment option to borg create (to immediately specify a comment)
- a borg comment command to add a comment to an archive later

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/32643831-add-a-comment-to-an-archive)

**Comment by Ape** [comment]
We cannot add the comment field to archive metadata since it would affect the hash. Instead we could add a new directory `comments` to the repository, containing a file for each archive. The files could be named with the archive hash and the content would just be the comment text.

A more extensible approach would be to similarly add a new folder but call it `mutables` (we need a better name) and then store a data structure that allows adding more mutable fields besides the comments. Perhaps one of the fields would be a checksum hash for the file itself.

Any comments on this?

**Comment by enkore** [comment]
If "--comment" is part of "create" than it would kinda make sense to have it in "recreate" to add/change it:

@Ape Mutamble/immutable comment, which one do we want?

**Comment by Ape** [comment]
Okay, I agree. The comment field is very similar to the name.

**Comment by ThomasWaldmann** [comment]
@enkore with borg rename, you can change the archive name, so from the user perspective, it is mutable.

**Comment by enkore** [comment]
... changing the archive ID/fingerprint in the process.

**Comment by infectormp** [comment]
@enkore changing the archive ID/fingerprint is not good idea.

**Comment by Ape** [comment]
@infectormp Actually, I think this kind of immutable data is a very good thing. Compare it to how Git stores its data. Things can still be modified, but under the hood everything is clean and immutable (except the thin mutable layer referencing all that immutable data).

**Comment by enkore** [comment]
Yep, that's the point I was making. You can change it, just like e.g. "git rebase" or soon "borg recreate" allows to change committed / archived things. But the commit / archive ID changes, so you can see that it isn't the *same thing* anymore. I think this is highly desirable.

If I wanted to, I could write my archive IDs down, and even when I didn't encrypt them, nobody could change these archives without me noticing -- either you get a different archive ID, or an IntegrityError.

**Comment by infectormp** [comment]
@enkore with your comments i not have any questions more.
