### ISSUE TITLE
Suggestion for enhancing extract speed on a ssh repo

### ISSUE THREAD

**Issue by knuuuut** [borgbackup/borg#8577]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
1.4.0

#### Operating system (distribution) and version.
Debian 12 client / Ubuntu 20.04 LTS

#### Hardware / network configuration, and filesystems used.
ZFS 1Gb on both sides

#### How much data is handled by borg?
about 15TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
client:
`borg extract --stdout ssh://USER@HOST:22/./REPO::ARCHIVE > FILE`

## Describe the problem you're observing.
Slow on ssh repos

#### Include any warning/errors/backtraces from the system logs

I just want to make a suggestion to enhance restore/extract speed over ssh:

Restoring files with a ssh repo in comparison to backup speed is very slow. It's resulting in a 100% CPU load (1 core) and a bandwith ~30 Mb/s on the client.

But restoring with

` ssh USER@HOST 'borg extract --stdout REPO::ARCHIVE' > FILE`

from the client will saturate a Gigabit line.

I found out this after checking my backups. These are Proxmox VM images. Backup runs fine, but restoring will take hours/days with a ssh repo. Now I'm happy with borg and I want to share my experience with you.

BTW: --chunker-params buzhash,12,16,12,4095 gave me the best results in speed/dedup.

**Comment by ThomasWaldmann** [comment]
Chunker params: sure, these give the best dedup (as ~4KB target block size correspond to the device/fs block size).

BUT you create a lot of chunks by doing that (the default target chunk size is 2MB), resulting in:
- high memory usage (repo index, chunks index) due to the overall amount of chunks in the repo
- a large file consists of a lot of small chunks and there will be more overhead dealing with them.

Maybe this contributes to the extract slowness you observed when using borg client/server.

Can you try 64KB or 512KB chunker target block size as a compromise between dedup efficiency and reducing overhead?

**Comment by knuuuut** [comment]
Yes, with
`--chunker-params buzhash,16,19,16,4095`
restore/extract runs a lot faster with 200-300Mb/s, but dedup is worse at 1/1,2.

It looks like I have to play a little bit more with these values.

Thank you.

**Comment by ThomasWaldmann** [comment]
OK, guess we can close this - it's expected that small chunks have a lot of overhead.
