### ISSUE TITLE
What's the point of the archive name?

### ISSUE THREAD

**Issue by murray** [borgbackup/borg#866]
You need a unique archive name for every backup. If you do backups quite frequently, like every day, then you'll need to come up with a lot of unique archive names. You could just include the date and time in the archive name, but that information is already displayed when you list your archives... I don't see the point.

If the archive name is more of a comment, then it should be optional and not required to be unique.

**Comment by Ape** [comment]
For me the names are really useful. I am doing daily backups with names like `2016-04-08`. It's simple enough for me to write `borg info ::2016-04-08`. They have to be unique, otherwise they could not be used like this. Using pure hash names to refer to my backups would be a lot more difficult.

However, it's true that they could be optional. I'd like to think of them as Git tags. Each backup has its hash ID (like commit hash in Git), but you can make human readable, unique names for them (Git tags, or branches).

**Comment by jungle-boogie** [comment]
> You could just include the date and time in the archive name

Most people would likely do this. 

Others may include hostname & date. And yet, others may just sequentially increase backups starting at 0. 

Having the name be required makes sense to me as I don't want borg to assume what name I want my archives.

**Comment by ThomasWaldmann** [comment]
I have hostname-date-time as archive name, so I can run as many backups per days as I like.
A prune policy takes care of keeping an appropriate amount of them.

**Comment by lfam** [comment]
I mostly use borg to backup my home directory, in which case the archive metadata is sufficient. But in other cases, I use to create "one-off" bit-reproducible archives of other things, and in that case, giving a descriptive name is very useful.

**Comment by ThomasWaldmann** [comment]
As prune --prefix is based on the name, we need the archive name.
