### ISSUE TITLE
exclude big files?

### ISSUE THREAD

**Issue by niksfirefly** [borgbackup/borg#902]
Is there a way to exclude big files (bigger/smaller --than-size) with borg create?

**Comment by ThomasWaldmann** [comment]
No (not yet?).

See also: https://github.com/jborg/attic/issues/330

**Comment by niksfirefly** [comment]
ok I assume it is not on roadmap list?

**Comment by ThomasWaldmann** [comment]
it has not been assigned to a milestone yet.

if you want to help, you could try the workaround suggested in the linked ticket.
if it works well. we maybe do not need the feature.
if it doesn't work well, tell us why - this might be a reason to add this feature.

**Comment by edgewood** [comment]
This would be a good place to use --files-from (on my phone and can't find the ticket #, but it's been discussed recently).
-- 
Ed Blackman
Sent from my OnePlus One. Please excuse my brevity.

**Comment by enkore** [comment]
#841

**Comment by cbothamy** [comment]
The solution linked in the ticket obviously works.

However, I'd rather have all the excluded files directive at one single place, and it's quite uneasy to have to run another process and rely on a temporary file before running borg. (also, the find -size syntax is quite clumsy, for example try find /home -size -1M ...).

I have a small 50 lines patch that extends patterns.py and adds the possibility to exclude files based on filesize and optionnally file extension.

If anybody is interested, I can add tests for this new directive, and forward the diff to the mailing list.

**Comment by n-st** [comment]
Picking this back up because I have another slightly different use case (→ #3097).

The [workaround](https://github.com/jborg/attic/issues/330) will cause a significant performance penalty on anything beyond tiny datasets (anything larger than your RAM, I'd guess).

We're already looking at the files' `stat` during processing, so theoretically we'd only need two new arguments in argparse, an "x MB"-to-"n bytes" conversion and an if condition in `do_create` (near the existing check for `one_file_system`).

I'd vote for using the same option names and syntax as `rsync` (`--min-size=42K` / `--max-size=123M`) as it is easy to understand for the user and easy to parse for the program (easier than `find`'s `-size` or the `--exclude-by-size '>=15M'` from the attic bug report, at any rate).

**Comment by varac** [comment]
Thx for assiging this to a milestone, looking forward to it!

**Comment by ThomasWaldmann** [comment]
superseded by #4102.
