### ISSUE TITLE
use more compatible locking code

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#92]
attic/borg's current locking code uses fcntl.lockf() and this causes some issues on filesystems which do not support this correctly.

see there:
- https://github.com/jborg/attic/issues/317
- https://github.com/jborg/attic/issues/201
- http://0pointer.de/blog/projects/locking.html

The idea is to replace this by using directory creation (mkdir) as atomic operation.

**Comment by ThomasWaldmann** [comment]
I just merged https://github.com/borgbackup/borg/pull/94 into borgbackup/borg master branch.

If some people who have issues with locking could test that, that would be very welcome!

**Comment by ThomasWaldmann** [comment]
tested with a cifs mount on linux (exported on a Win 10 VM) - works.

**Comment by tgharold** [comment]
I'm interested in this feature, but not sure how to test it.  Is there a "pip3 install borgbackup-bleeding-edge" command? :)

Does borg wait for the lock to expire when it wants a write-lock to the repo?  Can it be told how long to wait (with a default of 30 minutes)?  Or does it immediately error out and your backup just doesn't run that day?

Do write-locks take precedence over read-locks?  Can a write-lock kick readers off after the specified  max-wait time?

Is there a way to only lock portions of the repo?  So that readers can coexist with a single writer?

Can "borg create" be written in a way that it only appends new chunks to the repository, allowing for multiple writers?  (I suspect the issue is that the "index" is not multi-threaded.)

**Comment by ThomasWaldmann** [comment]
see there: http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch

about your other questions:

no, there is currently no expiry, it would wait endless for the lock (which is good, if another backup process has the lock and will need some hours to finish).

if a write lock shall be acquired, it will wait (currently: infinitely) until all readers go away and then acquire it (might be problematic if something is reading all the time).

there is only 1 write/exclusive lock and N read/shared locks for the repo, no other locks.

not sure about whether a writer could coexist with readers, this would need a deeper look into the code and mechanisms. currently, the locking principally works like in attic, it's just not using fcntl, but mkdir.

writing chunks (new key/value pairs) to the repo in parallel is maybe not a big issue, but cache consistency, maybe transactions, indexes, ...

**Comment by ThomasWaldmann** [comment]
0.24 release is pending any day soon. any final testers?

**Comment by tgharold** [comment]
My only comment would be that in --verbose mode, borg should be more verbose about telling me that:
- It's about to attempt to grab a read (or write) lock
- Whether it's waiting because it couldn't grab the lock
- And that it's succeeded in grabbing the lock

**Comment by ThomasWaldmann** [comment]
I'm closing this ticket now because the new mkdir-based locking is in master, so this is done.
If somebody finds issues with the new locking code: either reopen this ticket or just open a new one.
